### ISSUE TITLE
Change "Start now" button on LP to all caps

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1007]
### Overview
The LP page currently has one of the start now buttons in sentence case. Please change the "Start now" button in the hero banner to all caps 

Currently on site: 
![Screen Shot 2023-09-08 at 11 25 45 AM](https://github.com/hackforla/expunge-assist/assets/105686896/74992fef-92d0-4f13-a836-74e01d9a370b)

Correct case:
![Screen Shot 2023-09-08 at 11 28 55 AM](https://github.com/hackforla/expunge-assist/assets/105686896/45158b64-d4bf-490f-870d-3e0501e5732a)

### Action Items
- [x] Change "START NOW" button text to all caps

### Resources/Instructions
Ask @SamHyler if you have any questions

**Comment by SamHyler** [comment]
I went to check this button in our master pages and they are already correctly in all caps START NOW everywhere.
