### ISSUE TITLE
FAQ Page 

### ISSUE THREAD

**Issue by mbui31** [hackforla/expunge-assist#1009]
### Overview
The FAQ page has been redesigned. The content has also been adjusted and edited to ease the flooding and overwhelmingness for the users. Reference issues #956, #957, and #1009 for more information. 

### Action Items
- [x] using [figma design](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=12745%3A6933&mode=design&t=E0yc8YVJBfWkPJTW-1), code first draft of the redesigned FAQ page

### Resources/Instructions
- Design: [here](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=12745%3A6933&mode=design&t=E0yc8YVJBfWkPJTW-1)
-  reference the [landing page](https://expungeassist.org/#/) faq section and reuse the chevron icon.
- header image in [comments below](https://github.com/hackforla/expunge-assist/issues/1009#issuecomment-1725848639) (just use the large one and style it responsively

links: 
- [California Records Self-Help Guide: Clean your record](https://selfhelp.courts.ca.gov/clean-your-record)
- [Clearing Your Adult Criminal Record in California: A Step-by-Step Guide](https://www.courts.ca.gov/partners/documents/ExpSBS.pdf)
- [California Senate Bill 731](https://leginfo.legislature.ca.gov/faces/billTextClient.xhtml?bill_id=202120220SB731)
-  [Hack for LA](https://hackforla.org)
- [Civic Tech Structure](https://www.civictechstructure.org/)
- [California Courts Record cleaning: Felony convictions and Proposition 47](https://selfhelp.courts.ca.gov/clean-your-record/felony-prop47)
- [California Courts Marijuana conviction relief (Proposition 64)](https://selfhelp.courts.ca.gov/clean-your-record/marijuana-conviction-relief-prop-64)

**Comment by mbui31** [comment]
Vector image was taken from: https://undraw.co/search (search: knowledge sharing)

**Comment by anitadesigns** [comment]
@mbui31 Dev also needs the svg file for the illustration on the FAQ page. Can you also export it and add it to this issue so it is accessible to the developer who works on this issue?

**Comment by mbui31** [comment]
![undraw_sharing_knowledge_03vp (3)](https://github.com/hackforla/expunge-assist/assets/129242827/907ada49-e34c-4b6e-bb24-9e4d51174bfb)

**Comment by mbui31** [comment]
Please note that we removed the flower and swapped some colors around to match the EA branding

**Comment by sydneywalcoff** [comment]
@mbui31 hey sorry, we'll need the exact version that you want added to the app.

**Comment by mbui31** [comment]
![Union-1](https://github.com/hackforla/expunge-assist/assets/129242827/eb47c16f-b15a-40d4-a8b5-593d77b29bd7)

**Comment by mbui31** [comment]
@sydneywalcoff the first one is for mobile and the second is for desktop! thank you for your patience throughout this process!
