### ISSUE TITLE
IUT3 - Brainstorm & Planning

### ISSUE THREAD

**Issue by sofialaguna** [hackforla/expunge-assist#1011]
### Overview
We are preparing a research plan for IUT3, which will be focused on evaluating the user experience with the Expunge Assist letter writing tool. We want to begin with reflecting on the IUT2 research process and find ways to improve the process for IUT3. We also want to consider our timeline for completing IUT3 and the current capacity of our team to lead and manage IUT3 tasks. 

### Action Items

- [ ] Initial discussion and brainstorm of IUT3 during research meeting on 9/15/23. Team will be introduced to issue and will be asked to [add stickies throughout IUT3 planning Figjam with their ideas/thoughts](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?type=whiteboard&node-id=1910-2671&t=UxE0fOlHeZ2QDqTM-0). Team will also be asked to determine capacity for IUT3 and if they want to lead specific activities. 
- [ ] During week of 9/18, team will be asked to review IUT2 research process and add all ideas/thoughts into FigJam. 
- [ ] At 9/22 meeting, team will discuss lessons learned from IUT2 and team's capacity to manage IUT3. Timeline for IUT3 and team leads for IUT3 activities will be discussed.

### Resources/Instructions

- [Brainstorm FigJam for IUT3](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?type=whiteboard&node-id=1910-2671&t=UxE0fOlHeZ2QDqTM-0)
- [IUT2 Research Documents for review](https://drive.google.com/drive/folders/1a8DiD8njWmdFyJ0DmugzS57HwPLpmJ3s?usp=drive_link) 
- [Expunge Assist Roadmap](https://miro.com/app/board/uXjVMM5kQWY=/)

**Comment by amejiamesinas** [comment]
Our goal is to have Bonnie review all updates to page.
