### ISSUE TITLE
design Credits Page

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1013]
### Overview
In order to apply for the white hat HackerOne project, we need to have a credits page of all of the external assets we use on the project.

### Action Items

**Week 1:**
- [x] Prep workspace under "Credits page" in Figma 
    - [x] Add overview card and fill out background and info 
    - [x] Add title headers and document process on Github comments and Figma

**Week 2:**
- [x] Design a credits page using the hfla example below as inspiration ✨ Use lorem Ipsom for copy placeholder
   - [x] Create a mobile and desktop hi-fi wireframe 
- [x] Reach out to Content to have copy created for page
- [x] Assign @jyehllow or @anitadesigns to review 
- [x] Prepare Design hand off for Dev
- [x] Add figma link to resources section of #1015
- [x] Remove dependency label on #1015 and move from icebox to ready for approvals
- [x] Add mobile and desktop hi-fi wireframes to "Master" section on Figma

### Resources
- Link to H4LA's Credits page: https://www.hackforla.org/credits/
- Find list of icons and illustrations to cite: #1029 
- Work under "Credits page" in Figma

**Comment by mbui31** [comment]
https://storyset.com/illustration/multitasking/cuate for LP image

**Comment by SamHyler** [comment]
Yas will support from Content!

**Comment by anitadesigns** [comment]
Working on preparing dev hand off
