### ISSUE TITLE
Collect a list of the external assets used

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1014]
### Overview
In order to apply for the white hat HackerOne project, we need to have a credits page of all of the external assets we use on the project. 

### Action Items
- [ ] Collect a list of assets including its name, where its used, the artist, and where it came from.

### Resources/Instructions
Link to H4LA's Credits page: https://www.hackforla.org/credits/

**Comment by anitadesigns** [comment]
Didn't notice this issue was already made to collect all external assets. The Design team had started to work on issue #1029. I transferred the title to issue there with other information needed. Going to close this issue
