### ISSUE TITLE
code Credits Page

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1015]
### Dependency
- [x] #1013 

### Overview
In order to apply for the white hat HackerOne project, we need to have a credits page of all of the external assets we use on the project.

### Action Items
- [ ] create a 'credit' component that can be reused for both the icons and tools sections
- [ ] build a 'credits' page
- [ ] Add "credits" to current footer and link to credits page

### Resources
Design: [link](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=15341-47005&mode=design&t=gcnnISDhKNg9qXEG-0)
Link to H4LA's Credits page: https://www.hackforla.org/credits/
Link to the assets and info: https://github.com/hackforla/expunge-assist/issues/1029

Illustrations attached below in comments

**Comment by anitadesigns** [comment]
Mobile (XS) 
![Header illustration](https://github.com/hackforla/expunge-assist/assets/105686896/7d059542-cea4-47eb-b0c3-e896ec33abff)

Desktop (XL)
![At the office-pana 1](https://github.com/hackforla/expunge-assist/assets/105686896/c0b2a3f5-fcc6-48c0-83af-760fb9aea386)

**Comment by troymathis** [comment]
Shooting to be completed by the 23rd!
