### ISSUE TITLE
URL clean up

### ISSUE THREAD

**Issue by whitneywind** [hackforla/expunge-assist#1026]
### Overview
The current HashRouter adds extra characters as the user navigates around the site and through the letter generator. On load,` #` is added. Then upon clicking anything `/./ `is added. We would like the URL to be a little more semantic and cleaned up.

Using a BrowserRouter fixed the character adding problem, but creates a problem where when any page other than homepage is refreshed or directly navigated to, `/~and~/` is added to the URL on an infinite loop. This doesn't occur locally, and is likely related to how the router works with github pages.

Currently, the project is back to using the HashRouter.

### Action Items
- [x] research react router and how its routing works with github pages
- [x] find a solution to remove the extra characters that the HashRouter is adding
- [x] test that all pages are still working properly

### Resources/Instructions
https://reactrouter.com/en/main (expunge-assist is using version 5)

https://stackoverflow.com/questions/49240231/removing-from-hashrouter

**Comment by davidwiese** [comment]
I'll try to take on this issue, but I don't have a ton of experience in this area. I'll reach out with blockers or un-assign if it's appropriate.

Availability: Weekdays 1p-4p PST
ETA: 9.29.23

**Comment by davidwiese** [comment]
I'm digging into the React Router docs. Assuming we need to keep using the HashRouter, is the /#/ remaining in the URL acceptable, we just want to remove the additional /./ that appear?

**Comment by davidwiese** [comment]
I've forked the expunge-assist repo (following the same instructions from the website team: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#13-dev-setup-3-fork-the-repository)  so that I can start working on some issues.

I'm trying to recreate the URL issue here: https://github.com/hackforla/expunge-assist/issues/1026
The issue doesn't show up when using npm run start to launch the site locally, and I don't see a docker-compose.yml file to launch it that way. Any suggestions on how I should be launching the site in order to test this particular issue?

**Comment by whitneywind** [comment]
Hi there! Because the bug only shows up in the production environment, and the EA site is deployed on gh-pages, I believe you'll need to deploy your own fork to gh-pages, too. Just like how the real site is deployed. The issue seems to be due to how the router and gh-pages specifically interact

**Comment by davidwiese** [comment]
Thanks! Yea I came to a similar conclusion and found this guide:

https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/testing-your-github-pages-site-locally-with-jekyll

Setting up all the dependencies and then I'll know whether or not this will work as a testing environment.

**Comment by davidwiese** [comment]
Thanks @whitneywind - I'm having some trouble accomplishing this. When I try to deploy my own fork of the repo to gh pages, it seems to only be loading up the README.md file and not the app/website itself. I've personally only published static pages on github so I'm probably missing some steps.
