### ISSUE TITLE
Collect a list of the external assets used

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1029]
### Overview
In order to apply for the white hat HackerOne project, we need to have a credits page of all of the external assets we use on the project.

All images are to be cited on our credits page. 

This issue is linked to #1013 and #1015 

### Format
```
[Drag image file here]   

**Name:** 
**Used in:** [where on the website]
**Artist:** [only if found]
**Provider:** [website name]
**Alt text:**
 
```

### Resources
[How to add an image on Github Comments](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files)

**Comment by mbui31** [comment]
https://www.freepik.com/free-vector/characters-people-chatting-through-smartphones_3226068.htm#query=people%20chatting&position=11&from_view=search&track=ais#position=11&query=people%20chatting 
![image](https://github.com/hackforla/expunge-assist/assets/129242827/de46ddbb-414a-4e44-88be-7d1df4705e2f)

**Comment by mbui31** [comment]
https://undraw.co/search
![image](https://github.com/hackforla/expunge-assist/assets/129242827/6c54ab80-c0aa-4297-9347-0edc2da9f441)

**Comment by ermbrown** [comment]
Overview

Documentation of all illustrations and icons used on the expunge assist website. All images are to be cited on our credits page.

This issue is linked to #996, #924 and #931 
Format

[ 
![freepik--device-4--inject-3](https://github.com/hackforla/expunge-assist/assets/130421855/4060b66b-6bc3-45c7-a335-80bb370cacb8)
]   

**Name:** Multi-device targeting concept illustration
**Used in:** [Last Page Pop-Up]
**Artist:** [storyset]
**Provider:** [(https://www.freepik.com/)]

**Comment by Ugochukwu-On** [comment]
> https://undraw.co/search



> ![image](https://user-images.githubusercontent.com/129242827/271178710-6c54ab80-c0aa-4297-9347-0edc2da9f441.png)
> 
> **Name:** **Used in:** FAQ **Artist:** n/a **Provider:** https://undraw.co/search

the name of the illustration is called "sharing knowledge"

**Comment by anitadesigns** [comment]
<img src="https://github.com/hackforla/expunge-assist/assets/105686896/f178030f-beb9-4d31-b9ee-cc75c8da2aaf" width="300" height="300">


**Name:** [Mobile EA](https://storyset.com/illustration/mobile-login/cuate#default&hide=&hide=false)
**Used in:** Landing page
**Artist:** n/a
**Provider:** StorySet
**Alt text:**

**Comment by anitadesigns** [comment]
![Data secure image (1)](https://github.com/hackforla/expunge-assist/assets/105686896/ccbef849-7fbd-4d34-89ac-61332f01c519)

----
**Name:** [Data secure ](https://storyset.com/illustration/security/cuate)
**Used in:** Landing page
**Artist:** n/a
**Provider:** StorySet
**Alt text:**

**Comment by Ugochukwu-On** [comment]
![Stuck at Home Home Office](https://github.com/hackforla/expunge-assist/assets/87321473/f7541175-45ea-44be-9d92-5a729250b6ab)


**Name:** Home Office
**Used in:** Credits page
**Artist:** Mariana Gonzalez Vega
**Provider:** [website name]
**Alt text:**

**Comment by anitadesigns** [comment]
![Almost there](https://github.com/hackforla/expunge-assist/assets/105686896/c667517a-6b72-4f3f-a4ec-b958409530df)

-------

**Name:** Collaboration
**Used in:** Almost There Pop-Up
**Artist:** N/A
**Provider:** StorySet
**Alt text:**

**Comment by anitadesigns** [comment]
![Hero image](https://github.com/hackforla/expunge-assist/assets/105686896/0b776377-df91-4c75-a544-258a68a1628a)
------

**Name:** [MultiTasking](https://storyset.com/illustration/multitasking/cuate)
**Used in:** Landing Page
**Artist:** N/A
**Provider:** StorySet
**Alt text:**

**Comment by anitadesigns** [comment]
![Confirmation Image Small](https://github.com/hackforla/expunge-assist/assets/105686896/51e8a964-5197-472a-a595-28859ce5d1e9)
-----
**Name:** Support
**Used in:** Welcome Page
**Artist:** N/A
**Provider:** [Whoooa](https://www.whoooa.rocks/)
**Alt text:**

**Comment by anitadesigns** [comment]
![Why Image](https://github.com/hackforla/expunge-assist/assets/105686896/8f6fb618-b161-4319-8469-b22f199c3610)
----

**Name:** Research
**Used in:** Why Pop-Up
**Artist:** N/A
**Provider:** [StorySet](https://storyset.com/illustration/editorial-commision/rafiki)
**Alt text:**

**Comment by anitadesigns** [comment]
![Future Goals](https://github.com/hackforla/expunge-assist/assets/105686896/a2510bbd-d969-403b-a31f-133fe6bdb007)
-----

**Name:** Report
**Used in:** Future Goals Pop-Up
**Artist:** N/a
**Provider:** [StorySet](https://storyset.com/illustration/report/pana)
**Alt text:**

**Comment by Ugochukwu-On** [comment]
![At the office-pana](https://github.com/hackforla/expunge-assist/assets/87321473/05494cf6-a86d-48b6-9d1f-a8fa0f20978e)
**Name:** At the office
**Used in:** Credits Page
**Artist:** N/A
**Provider:** [Storyset](https://storyset.com/illustration/on-the-office/pana)
**Alt text:**

**Comment by anitadesigns** [comment]
![Icons](https://github.com/hackforla/expunge-assist/assets/105686896/d931bd72-277d-4f4e-a0b0-8b6d1438b50c)
----

Name: Material Design Edit Icons
Used in: EA Website
Artist: n/a 
Provider: [Pictogrammers](https://pictogrammers.com/library/mdi/) 
Alt text:

**Comment by SamHyler** [comment]
Content will add alt-text! Follow up with us if we are not on it!

**Comment by ykleinbart** [comment]
Where should content be putting the alt-text?

**Comment by anitadesigns** [comment]
> Where should content be putting the alt-text?

@ykleinbart each illustration has it's own comment box that you can edit and add the Alt text :)

**Comment by ykleinbart** [comment]
Okay thank you!

**Comment by anitadesigns** [comment]
![Cancel](https://github.com/hackforla/expunge-assist/assets/105686896/124bd082-91fa-4417-9cb9-28ffc31b4655)
-------
**Name:** Cancel 
**Used in:** Advice Page
**Artist:** n/a
**Provider:** [Pictogrammers](https://pictogrammers.com/library/mdi/)
**Alt text:**

**Comment by anitadesigns** [comment]
![Check](https://github.com/hackforla/expunge-assist/assets/105686896/aaab2505-2cca-4cd5-871e-9077388ebcb2)
-----
**Name:** Success
Used in: Advice Page and Letter Generator 
Artist: n/a
Provider: [Pictogrammers](https://pictogrammers.com/library/mdi/)
Alt text:

**Comment by anitadesigns** [comment]
![close](https://github.com/hackforla/expunge-assist/assets/105686896/c892dc96-0bf7-4286-8e93-1b8b78986d93)
------

**Name:** Close
**Used in:** [where on the website]
**Artist:** Material Design 
**Provider:** [website name]
**Alt text:**

**Comment by anitadesigns** [comment]
![Pencil](https://github.com/hackforla/expunge-assist/assets/105686896/c61d3415-a480-4a36-81af-5a3a81b6986b)
-------

[Drag image file here]   

**Name:** Pencil
**Used in:** Letter Generator Edit pages
**Artist:** Material Design 
**Provider:** [Pictogrammers](https://pictogrammers.com/library/mdi/)
**Alt text:**

**Comment by anitadesigns** [comment]
![Vector](https://github.com/hackforla/expunge-assist/assets/105686896/b4de688d-65e6-400c-9027-eae94012603a)
----------

**Name:** Arrow 
**Used in:** Buttons 
**Artist:** Material Design 
**Provider:** [Pictogrammers](https://pictogrammers.com/library/mdi/)
**Alt text:**

**Comment by anitadesigns** [comment]
![Vector](https://github.com/hackforla/expunge-assist/assets/105686896/45c20b95-899e-438c-a59a-1f0395a569ba)
--------

**Name:** Back Arrow
**Used in:** Back buttons
**Artist:** Material Design 
**Provider:** [Pictogrammers](https://pictogrammers.com/library/mdi/)
**Alt text:**

**Comment by anitadesigns** [comment]
![Eye](https://github.com/hackforla/expunge-assist/assets/105686896/0c86ad8a-6365-40f7-a225-e9574630202a)
--------
**Name:** Eye 
  **Used in:** Preview pages in letter generator 
**Artist:** Material Design 
**Provider:** [Pictogrammers](https://pictogrammers.com/library/mdi/)
**Alt text:**

**Comment by anitadesigns** [comment]
![Icon](https://github.com/hackforla/expunge-assist/assets/105686896/5aeb59bc-ac82-40a9-bbd4-920f9c8f3817)
---------

**Name:** Information Alert
**Used in:** Download page
**Artist:** Material Design 
**Provider:** [Pictogrammers](https://pictogrammers.com/library/mdi/)
**Alt text:**

**Comment by anitadesigns** [comment]
![docx](https://github.com/hackforla/expunge-assist/assets/105686896/829f7bad-0701-4832-a4f0-e15f85ca8f91)
---------
**Name:** DOCX File 
**Used in:** Download page
**Artist:** Unknown 
**Provider:** Unkown 
**Alt text:**

**Comment by anitadesigns** [comment]
![Download](https://github.com/hackforla/expunge-assist/assets/105686896/d91b7de1-fa6b-409e-8d74-471453ce3270)
---------------

**Name:** Download
**Used in:** Download page
**Artist:** Material Design 
**Provider:** [Pictogrammers](https://pictogrammers.com/library/mdi/)
**Alt text:**

**Comment by anitadesigns** [comment]
![Vector](https://github.com/hackforla/expunge-assist/assets/105686896/6c3bc8b0-499d-479a-870f-85c7154ea506)
-----------------

**Name:** Copy
**Used in:** Download page
**Artist:** Material Design 
**Provider:** [Pictogrammers](https://pictogrammers.com/library/mdi/)
**Alt text:**

**Comment by eruan8888** [comment]
[Drag image file here]   
![chevron_right_24dp_5F6368_FILL0_wght400_GRAD0_opsz24](https://github.com/user-attachments/assets/8675f3a7-0596-4c37-953f-cb06e8fca2a1)


**Name:** Right Chevron
**Used in:** [where on the website] FAQ section on the home page
**Artist:** [only if found] Material Design
**Provider:** [website name] [Google Fonts](https://fonts.google.com/icons)
**Alt text:** View Answer

**Comment by eruan8888** [comment]
![chevron_right_40dp_000000_FILL0_wght400_GRAD0_opsz40](https://github.com/user-attachments/assets/82c04ec2-c205-4424-be2f-2b882b0310e6)


**Name:** Info
**Used in:** Before You Begin page, Letter Generator Preview/Download page
**Artist:** Material Design
**Provider:** [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Notice
![info_24dp_2F6FED_FILL1_wght400_GRAD0_opsz24](https://github.com/user-attachments/assets/4ee84591-8fd4-4c65-a7a0-023011464913)

**Comment by eruan8888** [comment]
**Name**: Right Arrow
**Used in**: Next/Back/Return Home Buttons
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** (Whatever the button says)

**Name**: Cancel
**Used in**: Advice for a successful declaration page
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Avoid writing things like...(whatever the bad example is)

**Name**: Check Circle
**Used in**: Advice for a successful declaration page, every page in the letter generator where the user needs to fill in a textbox.
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Either "This is a good example for (either using formal language, answering in complete sentences with punctuation, or using the first person when answering questions)" or "Good Job"

**Name**: Radio Button Unchecked
**Used in**: Introduce Yourself page
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Unselected

**Name**: Radio Button Checked
**Used in**: Introduce Yourself page
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Selected

**Name**: Edit
**Used in**: Preview/Edit pages in Letter Generator 
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Edit

**Name**: Check Box Outline Blank
**Used in**: Involvement Page, Preview/Download/Active Page
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Unselected

**Name**: Check Box 
**Used in**: Involvement Page, Preview/Download/Active Page
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Selected

**Name**: Visibility
**Used in**: Edit Final Letter page, Preview/Download Final Letter page
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Preview

**Name**: Microsoft Word
**Used in**: Preview/Download Final Letter page
**Artist**: Material Design
**Provider**: [icons8](https://icons8.com/icon/set/word/material-rounded)
**Alt text:** Download a Microsoft Word copy of your letter

**Name**: Download
**Used in**: Preview/Download Final Letter page
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Download a (PDF or .txt) file of your letter

**Name**: Mail
**Used in**: Preview/Download Final Letter page
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Send your letter in an email

**Name**: Content Copy
**Used in**: Preview/Download Final Letter page
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** Copy your final letter to clipboard

**Name**: Keyboard Arrow Down
**Used in**: FAQ pages + FAQ section on home page
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** See less

**Name**: Menu
**Used in**: All mobile pages
**Artist**: Material Design
**Provider**: [Google Fonts](https://fonts.google.com/icons)
**Alt text:** See menu

**Comment by vyndesign104** [comment]
<img width="2000" height="1174" alt="Image" src="https://github.com/user-attachments/assets/914d430a-1160-4dec-815a-ffc5f0b2eb16" />

**Name:** Welcome
**Used in:** All Mobile (XS) and Desktop (XL) frames
**Artist:** PikiSuperstar
**Provider:** [Freepik](https://www.freepik.com/free-vector/meet-our-team-concept-landing-page_4655332.htm#fromView=search&page=2&position=24&uuid=0880da02-74b9-4b94-b5f5-e5b3e45c1087&query=meet+the+team+on+computer+illustration)
**Alt text:**
