### ISSUE TITLE
Add "Credits" page to footer

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1030]
### Overview
In preparation for our Partnership launch, we are adding a "Credits" page that includes open-source images and icons used in the EA website. The credits page would be accessed in the footer 

### Action Items
- [x] Using the current footer in the design system on Figma , add "Credits" 
- [x] Tag @anitadesigns and @jyehllow for Review 
- [x] Ensure change has been made in all master pages on Desktop and mobile wireframes 
- [x] Prepare hand over to Dev 
- [x] Add figma link to resources section of #1031 
- [x] Remove hold label on #1031 
- [x] Close issue 

### Resources/Instructions
Linked to #1013 and #1015

**Comment by mbui31** [comment]
@anitadesigns @jyehllow is it best practice for the ux designer assigned to the issue to close it out or to push to "ready for review" and have the design lead close out the issue?

**Comment by anitadesigns** [comment]
@mbui31 Since preparing for Hand off would proceed with the Leads reviewing the issue, the best practice would be for the designer leading the issue to close!
