### ISSUE TITLE
code "Credits" page to footer

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1031]
### Overview
Design team is adjusting the Footer to add Credits page to footer. Issue is attached to #1013 and #1015 

### Action Items
- [ ] Add "credits" page to footer 
- [ ] Link to Credits page 

### Resources/Instructions
Design: [[link](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=13182-12307&mode=dev)]

**Comment by mbui31** [comment]
@sydneywalcoff issue is ready for dev!

**Comment by sydneywalcoff** [comment]
@mbui31 @anitadesigns Hey y'all! This can be added as an action item in #1015. That way we can make sure that it's released at the same time as the Credits page, so there isn't just a broken link in the footer.

**Comment by anitadesigns** [comment]
@sydneywalcoff thanks syndey! I went ahead and added it to #1015 and closing this one
