### ISSUE TITLE
Content About Us HfLA/CfA changes

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1049]
### Overview
The About us page does not currently have the same text that the FAQ and LP have. It does however have one line that is about "who we are." Decisions need to be made to create modular copy that goes on all three pages, or if the About page should have a different solution. 

However, the one sentence that addresses HfLA and EA's relationship needs to be addressed.

---

This issue is linked to #684 

Hack for LA (HFLA) changed its relationship from CfA (Code for America). This information needs to be updated across the site to the new and correct information. Copy needs to be updated under "What is Expunge Assist?" section on the LP to reflect changes. 

See https://github.com/hackforla/expunge-assist/issues/902 for detailed information and where to find information about the relationship change. 

The copy only needs to be written once and coordinated across the LP, FAQ, and About pages. See the other issues: https://github.com/hackforla/expunge-assist/issues/1056, https://github.com/hackforla/expunge-assist/issues/1049, and https://github.com/hackforla/expunge-assist/issues/1053

### Action Items
- [x] Create appropriate texts/content for the About us page that reflects the new structure and where EA fits into the various organizations 
- [x] Be sure Content is consistent in 3 places places (About, LP, and FAQ)
- [x] Collaborate with Design on any parts that change

### Resources/Instructions
related to this design issue https://github.com/hackforla/expunge-assist/issues/684

news about the change https://statescoop.com/code-for-america-local-brigades-ending/

Our new nonprofit is https://www.civictechstructure.org/

https://socialimpact.github.com/insights/merl-center-move/

Bonnie's advice video https://drive.google.com/drive/folders/1TGl0s76LtxqIJcNPtwmg_4F2rE0tLtol

[Revised Figma frames](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2%3A45&mode=design&t=RsrNQ5dPybJSAitU-1)

**Comment by anitadesigns** [comment]
@SamHyler I am working on transitioning the backlog issues into the new format we discussed (parent issues linked to child issues that belong to specific teams). I tagged you in this issue to adjust this items as you see fit for Content

**Comment by SamHyler** [comment]
Discussed About page getting a major redesign rather than only small changes. Together with that, there is room to update by adding new headers and categories. Cheryl is leading that issue. For this issue, we discussed possibly expanding by adding a new heading or a series of headers and possibly modular copy. More updates to come, only iterations made so far

**Comment by SamHyler** [comment]
Content is finished. Content will be under the master pages and in the Content SOT copydoc. Design has OKed handover without check on padding. Handing over to Dev on [Design handover space in Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-38&mode=design).
