### ISSUE TITLE
code About Us HfLA/CfA changes

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1051]
### Overview
Hack for LA (HFLA) changed its relationship from CfA (Code for America). This information needs to be updated across the site to the new and correct information.

### Action Items
- [x] Update copy on the About Us page

### Resources/Instructions

[Design](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?m=dev&node-id=15888-6216)

**Comment by eburdekin** [comment]
Hey @anitadesigns, noticed in the Figma file that the "Who we are" and "What is Expunge Assist" sections are in different orders on desktop vs mobile. Wanted to confirm whether this is intentional? Thanks!

**Comment by sydneywalcoff** [comment]
@eburdekin for this issue, just do the copy change. Disregard any structural changes. The CfA changes are high priority and urgent. 

If we have any structural changes, we'll need to open a new issue.
