### ISSUE TITLE
Update HfLA/CfA relationship - FAQ Page

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1052]
### Overview
With the new changes regarding HfLA, we are updating information across the EA website. Update information on FAQ page regarding HfLA 

### Action Items
- [x] #1053 
- [x] #1054
- [x] #1055 

### Resources/Instructions
Figma workspace [here]

**Comment by sydneywalcoff** [comment]
replacing the 'parent' language with `main issue` labels

**Comment by SamHyler** [comment]
Content is finished. Content will be under the master pages and in the Content SOT copydoc. Design has OKed handover without check on padding. Handing over to Dev on [Design handover space in Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-38&mode=design).

**Comment by sydneywalcoff** [comment]
<img width="874" alt="Screenshot 2024-06-03 at 7 09 42 PM" src="https://github.com/hackforla/expunge-assist/assets/75542938/16a8ff1d-7fff-49b7-99d2-69202897295f">
