### ISSUE TITLE
Content Landing Page HfLA/CfA changes

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1056]
### Overview
Hack for LA (HFLA) changed its relationship from CfA (Code for America). This information needs to be updated across the site to the new and correct information. Copy needs to be updated under "What is Expunge Assist?" section on the LP to reflect changes. 
See https://github.com/hackforla/expunge-assist/issues/902 for detailed information and where to find information about the relationship change.

See also parent issue #684 

The copy only needs to be written once and coordinated across the LP, FAQ, and About pages. See the other issues: https://github.com/hackforla/expunge-assist/issues/1056, https://github.com/hackforla/expunge-assist/issues/1049, and https://github.com/hackforla/expunge-assist/issues/1053

### Action Items

- [x] Create appropriate texts/content for the Landing page that reflects the new structure and where EA fits into the various organizations 
- [x] Be sure Content is consistent in 3 places places (About, LP, and FAQ)
- [ ] Collaborate with Design on any parts that change
- [x] Share with Design 

### Resources/Instructions
Figma workspace is [here]

related to this design issue https://github.com/hackforla/expunge-assist/issues/684

news about the change https://statescoop.com/code-for-america-local-brigades-ending/

Our new nonprofit is https://www.civictechstructure.org/

https://socialimpact.github.com/insights/merl-center-move/

Bonnie's advice video https://drive.google.com/drive/folders/1TGl0s76LtxqIJcNPtwmg_4F2rE0tLtol

[Revised Figma frames](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2%3A45&mode=design&t=RsrNQ5dPybJSAitU-1)

**Comment by anitadesigns** [comment]
@SamHyler Issue needs to be adjusted

**Comment by SamHyler** [comment]
Discussion around modular copy contra presenting the information in different ways across LP, FAQ, and About. Iterations initiated.

**Comment by SamHyler** [comment]
Content is finished. Content will be under the master pages and in the Content SOT copydoc. Design has OKed handover without check on padding. Handing over to Dev on [Design handover space in Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-38&mode=design).
