### ISSUE TITLE
Design Landing Page HfLA/CfA changes

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1057]
### Dependency 
- [x] #1056

### Overview
linked to #1058

### Action Items
- [ ] Make sure padding/spacing is correct 
- [ ] Update mobile and desktop wireframes on Figma's Master page section 
- [ ] #1059 
   - [ ] add figma
   - [ ] remove https://github.com/hackforla/expunge-assist/labels/dependency
   - [ ] add https://github.com/hackforla/expunge-assist/labels/ready%20for%20dev%20lead
   - [ ] move to `new issues` column

### Resources/Instructions
Figma wireframes are [here]

**Comment by sydneywalcoff** [comment]
<img width="874" alt="Screenshot 2024-06-03 at 7 09 42 PM" src="https://github.com/hackforla/expunge-assist/assets/75542938/861da0db-505d-4b63-8935-834d6f03ff28">
