### ISSUE TITLE
Update HfLA/CfA relationship - Landing Page

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1058]
### Overview
Hack for LA (HFLA) changed its relationship from CfA (Code for America). This information needs to be updated across the site to the new and correct information. 

LP needs copy updates for "What is Expunge Assist?" section 

<img width="512" alt="Screenshot 2023-08-04 at 21 21 50" src="https://github.com/hackforla/expunge-assist/assets/87077650/3aec680a-5533-436c-ad29-6770003d3765">

### Action Items
- [x] #1056 
- [x] #1057 
- [x] #1059

### Resources/Instructions
Figma workspace is [here]

**Comment by sydneywalcoff** [comment]
Replacing the 'Parent' language in the title with a `main issue` label

**Comment by SamHyler** [comment]
Content is finished. Content will be under the master pages and in the Content SOT copydoc. Design has OKed handover without check on padding. Handing over to Dev on [Design handover space in Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-38&mode=design).
