### ISSUE TITLE
Capturing Responses from Those Using the Generator 

### ISSUE THREAD

**Issue by j100892** [hackforla/expunge-assist#106]
### Overview
NDICA mentioned that data is important to them and that they currently have those going through the expungement clinics fill out an intake form before the process starts. 

We're currently not capturing any of the responses through our generator but if there is a way for us to capture the responses  and have it sent to recordclearance@hackforla.org or to a Google Sheet without building out an entire backend architecture then we should investigate.

**Comment by cayd** [comment]
We have this capability by default. We would simply leverage the existing "email pdf of statement" feature to send a copy of the statement to recordclearance@hackforla.org. The bigger question is the design that would be involved. We should obviously not be doing this without the user's knowledge and consent, as it exposes personal information.

Adding design label. We'll address this in dev when the email functionality and the form to get user consent are ready. It should be a quick change.

**Comment by brandohayes** [comment]
This product will not have a backend to avoid potential privacy issues. This issue will be closed.
