### ISSUE TITLE
Documenting Process for Icebox and Dependencies

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/expunge-assist#1061]
### Overview
The EA Team is working to align management of Icebox and Dependency issues with HackforLA processes. The team has developed a working draft to document this process and communicate with all teams. 

### Action Items
Review [DRAFT](https://docs.google.com/document/d/1LlFnc-rXG_gOS5tw9xWDfgSk05Lva7LHNusXheXTYdA/edit) and add edits/comments. 

Once finalized, documented will be presented to Bonnie for approval.

**Comment by amejiamesinas** [comment]
@sydneywalcoff will make first round of comments, which will then be reviewed/discussed at 11/10 design content meeting. We will continue to follow up if there are any questions.

**Comment by sydneywalcoff** [comment]
I added my thoughts below the original draft in the doc.
