### ISSUE TITLE
Dev Team 2023 Reflection

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1072]
Overview
The purpose of this activity is to gain insight into each person's experience working on the team this year. Our hope is to examine these and integrate insights into 2024 workflows.

Action Items
- [Go to FigJam Board](https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?type=whiteboard&node-id=3303-9784&t=nzPvhXv49gHiASuk-0)
- Add your insights to each section (use a sticky)
- unassign yourself when you've added your insights

**Comment by davidwiese** [comment]
Requested access to the FigJam 🙃

**Comment by davidwiese** [comment]
I have read only access to the FigJam at this point. I requested edit access, just needs to be approved by someone I believe. @sydneywalcoff
