### ISSUE TITLE
Fix height to Progress Bar 

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1076]
### Overview
The light purple background to the progress bar is thinner on the website compared to what is on the wireframes. 

**Website**
![Screen Shot 2023-11-15 at 5 43 11 PM](https://github.com/hackforla/expunge-assist/assets/105686896/bb74c65b-e1a7-4e2b-8eb4-df5eb63f1a74)

**Wireframe**
![LG_ Involvement](https://github.com/hackforla/expunge-assist/assets/105686896/0159f4bb-f3ba-4661-8618-53896e53c22b)

### Action Items
- [ ] Fix height of the background of the progress bar 
- [ ] Center text and progress bar 

### Resources/Instructions
Design on Figma is located [here](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=13787-40226&mode=design&t=b8h1KpHL3kzyvpAD-4)

**Comment by sydneywalcoff** [comment]
@anitadesigns I actually noticed this and have an issue in progress already. I'll add the figma to #955 to give more details

**Comment by sydneywalcoff** [comment]
Added the figma to #955 so I'm closing as a duplicate
