### ISSUE TITLE
Before you begin

### ISSUE THREAD

**Issue by ermbrown** [hackforla/expunge-assist#1077]
### Overview
We have updated the Before you begin page per Bonnie's requests. Reference #990 for more information.

### Action Items

- [x] Update Take your time title and paragraph text (mobile/desktop)
- [x] Added Keep your browser open alert (mobile/desktop)
- [x] Update spacing between alert and buttons in mobile

### Resources/Instructions
Reference issue: [1077 under Dev Team in Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=13877%3A4545&mode=design&t=k7oUNGQnNzUbM09b-1)
`

**Comment by davidwiese** [comment]
ETA: before 1/18/24 meeting
