### ISSUE TITLE
Write `How to Review Pull Requests` Wiki Page

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1081]
### Overview
We would like to document our Pull Request review process. This is going to be a collab with @sydneywalcoff.

### Action Items

- [x] Create a new Wiki page called `How to Review Pull Requests` in the [EA wiki](https://github.com/hackforla/expunge-assist/wiki)
- [x] To the best of your understanding, write how to review pull requests (either from what you've seen on PRs you've submitted or reviewed yourself)
- [x] add new wiki page link to [Web Developer Wiki Page](https://github.com/hackforla/expunge-assist/wiki/Web-Developer) `How to Review Pull Requests` and remove `- Does not exist` text
- [x] assign @sydneywalcoff to add thoughts, leave yourself assigned :)

### Resources/Instructions
[Web Developer Wiki Page](https://github.com/hackforla/expunge-assist/wiki/Web-Developer)
[CONTRIBUTING.md](https://github.com/hackforla/expunge-assist/blob/main/CONTRIBUTING.md)
[HfLA website team Wiki Page](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) - this is excessive, but definitely could give a good idea of where to start

**Comment by davidwiese** [comment]
@sydneywalcoff First draft is up!
