### ISSUE TITLE
Write `How to Create Pull Requests` Wiki Page

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1082]
### Overview
We would like to document our Pull Request review process. This is going to be a collab with @sydneywalcoff.

### Action Items
- [x] Create a new Wiki page called `How to Create Pull Requests` in the [EA wiki](https://github.com/hackforla/expunge-assist/wiki)
- [x] To the best of your understanding, write about how to create pull requests (either from what you've seen on PRs you've submitted or reviewed yourself).
- [x] add new wiki page link to [Web Developer Wiki Page](https://github.com/hackforla/expunge-assist/wiki/Web-Developer) How to Create Pull Requests and remove - Does not exist text
- [x] assign @sydneywalcoff to add thoughts, leave yourself assigned :)

### Resources/Instructions
[Web Developer Wiki Page](https://github.com/hackforla/expunge-assist/wiki/Web-Developer)
[CONTRIBUTING.md](https://github.com/hackforla/expunge-assist/blob/main/CONTRIBUTING.md)

**Comment by hasham-qaiser** [comment]
Overview
Introduces a new wiki page, on steps for how to create a new pull request.

Action Items
Link to wiki page: https://github.com/hackforla/expunge-assist/wiki/How-to-Create-Pull-Requests

Resources/Notes
Resources used: [Contributing page](https://github.com/hackforla/expunge-assist/blob/main/CONTRIBUTING.md)
