### ISSUE TITLE
Reuse Social Media Accounts

### ISSUE THREAD

**Issue by j100892** [hackforla/expunge-assist#109]
### Overview
Can we rename ClearCali for our Linkedin, Twitter and Facebook Groups to a different name once we get confirmation form Bonnie on Friday?

**Comment by ggrrettcchhenn** [comment]
https://twitter.com/expungeassist
https://www.instagram.com/expungeassist/
https://www.facebook.com/Expunge-Assist-100934455366755 (we can choose our own URL when we get at least 25 likes)
https://www.linkedin.com/company/expungeassist/
