### ISSUE TITLE
Create a `Dependency` Template

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1091]
### Overview
We're re-organizing how we write issues to include dependencies. To make writing issues more efficient, we want to create a template for issues with dependencies.

### Action Items
- [x] create new issue template with below info:
file name: blank-issue-dependency.md
name: Blank Issue w/ Dependency
labels: feature: missing, priority: missing, role: missing, size: missing, dependency, issue level: missing

```
### Dependency
- [ ] add number of issue blocking this one ex`#...`

### Overview
REPLACE THIS TEXT - Text here that clearly states the purpose and context of this issue 

### Action Items
- [ ] REPLACE THIS TEXT - If this is the beginning of the task this is most likely something to be researched and documented.
- [ ] REPLACE THIS TEXT - If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

IF BLOCKING ANOTHER ISSUE:
- [ ] remove dependency on #BLOCKED_ISSUE and move it to `New Issues waiting for approval` on the project board

### Resources/Notes
REPLACE THIS TEXT - If there is a website which has documentation that helps with this issue provide the link(s) here.`

```

### Resources/Instructions
- [Issue templates](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by davidwiese** [comment]
ETC before tonight's meeting

**Comment by davidwiese** [comment]
PR here:

https://github.com/hackforla/expunge-assist/pull/1372
