### ISSUE TITLE
Add GHA that comments when issues are assigned

### ISSUE THREAD

**Issue by CBx3000** [hackforla/expunge-assist#1092]
### Overview
The website team has an automation that comments when an assignee is added to an issue:
![Screen Shot 2024-01-12 at 11 25 37 AM](https://github.com/hackforla/expunge-assist/assets/75542938/cecb23db-10ac-4c43-8c47-45039a3d87e7)

We would like to implement a similar action.

### Action Items
- [x] Review the Website Team's code to implement 
Add a GH Action that 
- [x] detects when someone is assigned
- [x] comments the following
```
Hey [ASSIGNEE]! Thanks for taking this issue. 

To help keep everyone in the loop, please comment your Estimated Time to Completion (ETC) below!

Thanks again!
```

### Resources/Instructions
[website repo](https://github.com/hackforla/website) - looks like a GH Action

**Comment by sydneywalcoff** [comment]
@whitneywind I know you're on vacation and this might not end up being a problem. But just in case, can you hold off on this until #1266 is completed?

**Comment by whitneywind** [comment]
Update:
**Progress:**  currently learning about how github actions and looking through the repo's existing ones
**Estimated Time to Completion (ETC):** this week
**Blockers:**  none
