### ISSUE TITLE
Create a `Bug` issue template

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1106]
### Overview
As the EA team grows and new developers are introduced, bugs become more likely. To simplify the process of reporting and solving a bug, we want to include 
* what the bug is
* where it was seen
* what time it is
* what system the user is running
* what browser the user is running
* images/videos if relevant

The bug issue should be assigned high priority and be assigned to the dev lead.

### Action Items
- [x] create a new issue template for reporting bugs using the below info:

file name: bug-report.md
name: Bug Report
title: [BUG]
assignees: @sydneywalcoff
labels: feature: missing, priority: high, role: missing, size: missing, bug

```
### What is the bug you're reporting?
REPLACE THIS TEXT - Describe the bug to the best of your ability.

### Where did you find the bug?
REPLACE THIS TEXT - Describe the location or paste a link.

### When did you first notice this bug?
REPLACE THIS TEXT - Your best guess is fine

### What browser do you use?
REPLACE THIS TEXT - Safari/Chrome/Firefox/Opera/etc

### What kind of device did you notice this bug on?
REPLACE THIS TEXT - ex) iPhone 11 or Windows PC

### What operating system are you running?
REPLACE THIS TEXT - ex) macOS Monterey

### Do you have any screenshots or videos of the bug?

### Action Items
- [ ] ... to be filled out by the Dev Lead

### Resources/Notes
REPLACE THIS TEXT - If there is documentation or tutorials that may help with this issue, provide the link(s) here. 

```

### Resources/Notes
[issue template docs](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

**Comment by eburdekin** [comment]
ETC: Friday 5/24
