### ISSUE TITLE
Formula to Combine Responses from Web Form 

### ISSUE THREAD

**Issue by j100892** [hackforla/expunge-assist#111]
### Overview
We need to make a functional prototype of the statement generator that we can share with stakeholders for testing out the statement formula with stakeholders. This will make it easier to test out different formulas to get the statement to sound natural and valuable (instead of hard coding each change into the web application).

### Action Items

- [x] Create [web form](https://form.jotform.com/210456150734146) for users to fill out
- [x] Collect responses in [Google Sheets](https://docs.google.com/spreadsheets/d/1o1iHthALkwtvptA-NevAZUDgRb7f4kCxr-rTSr9Z0Ek/edit?usp=sharing)
- [x] Create generated statement document in [Google Docs](https://drive.google.com/drive/folders/1MKNGKR1yc1PVm6IdFJBtdOhDTIHIgc1M?usp=sharing)
- [ ] Refine generated statement so that it only includes relevant information

### History

- First, we used a Google Form that output to Google Sheets, and if-then and concatenate formulas in Google Sheets to combine the form responses into an auto-generated statement.
    - Problem: Google Forms does not allow the type of conditional logic we needed. (Based on which activities the user has been involved with since their conviction, we ask them & require different questions.)
    - ~~[Editable Version of Google Form](https://docs.google.com/forms/d/1Iy8E_zTRtGPaA3axjgPkn2fG5wG8dTlwpTLSfxozs88/edit?ts=5fcad979)~~
    - ~~[View form](https://docs.google.com/forms/d/e/1FAIpQLSfq53fzh1Y8d5x0hhn3PDFBvV5CGFAiMDHuqr9T7xCiPVQ7iQ/viewform)~~
    - ~~[Responses Spreadsheet with Statement Maker formula](https://docs.google.com/spreadsheets/d/12JKjQ7l1gGL_bYwcstDW1i5OoHKBLRZzM8HxDMN86-Q/edit#gid=112762119)~~
    - ~~https://docs.google.com/document/d/1bYv32qHQZjpU1vVuHAvNDeopNXgEKKjWix5fSyUpTLI/edit~~
- Then, we used JotForm to collect responses because its free version offers more complex conditional logic, and it can output to Google Sheets.
    - Problem: Google Sheets is not an elegant way to share the final statements with our stakeholders, and the formulas are challenging to put together and get to work correctly.
- Now we are trying to use Zapier to take the responses from JotForm and create a new Google Doc in a specified folder for each generated statement
    - Problem: We can't hide the irrelevant sections about the activities they did not fill in responses about.

### Resources/Instructions

- [Editable Version of JotForm, Feb 2021](https://www.jotform.com/build/210456150734146?iak=ce803cdc2e1810b6510901ed9b1f1edd-b47ce1a133a4399e)
- [View form – JotForm update, Feb 2021](https://form.jotform.com/210456150734146)
- [Responses Spreadsheet with Statement Maker formula – JotForm update, Feb 2021](https://docs.google.com/spreadsheets/d/1o1iHthALkwtvptA-NevAZUDgRb7f4kCxr-rTSr9Z0Ek/edit?usp=sharing)
- [Personal Statement Sample](https://drive.google.com/file/d/1-eSDTOJHRtmFcu2uvLvuZslgP8EieEDw/view?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
I am doing a cleanup of my desktop and found think link.  please provide context for it https://docs.google.com/document/d/1JuKKIwe8EqBD110j40Va0SWS6_TxFjsk9YBsICF98Uk/edit

**Comment by j100892** [comment]
@ExperimentsInHonesty @cayd Setting up some time for you both next week to speak

**Comment by ExperimentsInHonesty** [comment]
@alexchoiweb @j100892 found this at ticle which proposes a solution for our issue https://superuser.com/questions/1058486/multiple-if-statements-and-concatenation-in-excel

**Comment by ggrrettcchhenn** [comment]
I believe the lo-fi statement generator is now working.

Input on JotForm: https://form.jotform.com/210456150734146
Output to Google Sheets: https://docs.google.com/spreadsheets/d/1o1iHthALkwtvptA-NevAZUDgRb7f4kCxr-rTSr9Z0Ek/edit?usp=sharing

The first sheet is the responses, the second has the Excel formula. Those two sheets are locked, and the third sheet is an unlocked copy of the statements to share with our stakeholders to test out the form.

**Comment by ggrrettcchhenn** [comment]
The formula still needs some work because it doesn't incorporate the answers to the yes/no questions. Need to figure out how to do something like `if YES, concatenate "I am a veteran of the United States of America."' and same for the answer at the end of the involvement flow, "Do you believe that having your record cleared would help you find a job and be more involved in your community?"

**Comment by ggrrettcchhenn** [comment]
Look into using [Zapier](https://zapier.com/) to convert responses in Google Sheet to a Google Doc – Bonnie's recommendation. Should be simpler than the excel formula.

**Comment by ggrrettcchhenn** [comment]
I got Zapier to create a Google Doc from the JotForm submission. https://zapier.com/shared/9109909b7e1356e5b1f1364cd08554e9e9510ca9

The statements end up in this folder (Expunge Assist > Research > Personal Statement Generator > [Generated Statements from Zapier](https://drive.google.com/drive/folders/1MKNGKR1yc1PVm6IdFJBtdOhDTIHIgc1M?usp=sharing)

The problem that I still need to solve is that currently the zapier function doesn't have logic to delete the irrelevant paragraphs. For example, if they only selected that they've been parenting since their conviction, it will still show the formula for the job, school, community service, recovery program, and unemployment flows. Need to look into what we can do to solve for this.

**Comment by ggrrettcchhenn** [comment]
At this point, the actual product is so close to being ready and the functional prototype got so complicated that I don't think it's very helpful to continue to try to make this work.
