### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1136]
### Overview
Our 404 (something went wrong) uses the old app styles. We should update it to use the current design. 

### Action Items
- [x] #1137
- [x] #1171 
- [x] #1138

### Resources/Notes

<img width="1440" alt="Screen Shot 2024-02-02 at 3 10 32 PM" src="https://github.com/hackforla/expunge-assist/assets/75542938/c57baf6f-db52-44ca-af4f-292b824b8e95">

**Comment by anitadesigns** [comment]
**Progress:** Content and design has been handed over to Dev
**Estimated Time to Completion (ETC):** Dependent on Dev
**Blockers:** n/a
