### ISSUE TITLE
Code 404 page

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1138]
### Dependency
- [x] #1137 

### Overview
Our 404 page is ugly lol. Design will be updating it.

Current 404 
<img width="1440" alt="301992562-c57baf6f-db52-44ca-af4f-292b824b8e95" src="https://github.com/hackforla/expunge-assist/assets/75542938/9ac0d2bd-aea1-4124-8866-a57c4d47371b">

### Action Items
- [x] update the 404 page design

### Resources/Notes

- [DESIGN](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=15259-17293&mode=design&t=U0jgKAvN9oRfGysn-4)

Illustrations can be found in the comment below

**Comment by anitadesigns** [comment]
Desktop 
![404 Illustration](https://github.com/hackforla/expunge-assist/assets/105686896/c2ff008e-e621-47fe-aae2-38835be73199)

Mobile
![404 Illustration](https://github.com/hackforla/expunge-assist/assets/105686896/89d61311-1fe8-4b3e-95e6-a9e478274deb)

**Comment by anitadesigns** [comment]
desktop background
![BG](https://github.com/hackforla/expunge-assist/assets/105686896/a9d963ee-5306-4dc8-afdf-9e663050d624)

mobile background
![BG](https://github.com/hackforla/expunge-assist/assets/105686896/6c9ed560-503a-4102-9b9d-e92d5a67f5cf)
