### ISSUE TITLE
Design Oops Reminder

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1141]
### Overview
If you use browser navigation like (refresh, forward and backward) while in the letter generator, the app forgets all your previous answers. And because it uses your previous answers to determine the flow and eventually to form the letter, the app breaks and shows a blank white page.

We should
a) warn users not to use browser navigation like (refresh, forward and backward) while in the letter generator before they start #1152 
b) if a user does refresh, we should show a little Oops reminder (similar to the https://github.com/hackforla/expunge-assist/issues/1136, but smaller) reminding the user not to use browser navigation

### Action Items
- [x] Design Oops Reminder
   - [x] find illustration
   - [x] edit illustration
   - [x] create mobile and web version for the oops reminder
   - [x] edit colors to be purple for now
   - [x] ping claudia to let her know when i'm done
   - [x] create a [user flow](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=15876-481&mode=design&t=BXi8FQqyKf4508rr-4) for possible decisions that the user would take 
      - [x] returning home
      - [x] returning to onboarding
      - [x] returning to the start of the letter generator
      - [x] two buttons: home/letter generator
- [x] hand off
- [x] place screens onto the "desktop" and "mobile" pages
- [x] add the wireframes to the design hand off page [in progress]
- [x] add comments wherever needed
- [x] link the issue in the page
- [x] add design to #1142  
   - [x] remove `dependency` label
   - [x] move to `new issue approval` column
   - [x] add `ready for dev lead` label

### Resources/Notes
[CONTENT]()

**Comment by jyehllow** [comment]
Hey @sydneywalcoff , would it be possible to just use browser popups in this situation?

[Example 1](https://i.stack.imgur.com/X16CV.png)
[Example 2](https://www.bleepstatic.com/swr-guides/y/you-should-install-the-extension/you-should-install-the-extension.png)

Also, the current advice page instructs users to keep their browser open - maybe we can also add " do not refresh the page"?

Tagging @SamHyler and @emmathrash for visibility as well.

**Comment by sydneywalcoff** [comment]
@jyehllow we can, but I would prefer to at least have a branded popup. Using the browser popups isn't a good look. 

As for your other point, that is already covered in another issue #1152

**Comment by anitadesigns** [comment]
This issue is not ready to be worked on. Design and Content will strategize the best approach for this on Friday

**Comment by eruan8888** [comment]
Hey all, I [prototyped a desktop and mobile version for the Oops page](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-4&mode=design). I customized an illustration from Storyset and used it for these pages. Let me know what you think. Attached are screenshots of what the design looks like. 
<img width="744" alt="image" src="https://github.com/hackforla/expunge-assist/assets/82855068/ccb68ebe-2496-4bdf-a2ce-e6a33da3bbd5">

**Comment by anitadesigns** [comment]
@eruan8888 next week we can go over the hand off just remind @vanessaavviles to add it to the agenda

**Comment by eruan8888** [comment]
Can I just close this one? It's pretty much done.

**Comment by eruan8888** [comment]
Updated the spacing, design is ready for dev

**Comment by SamHyler** [comment]
Final designs were never added to master pages. I did that now.
