### ISSUE TITLE
Offboarding PM: Lane

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1144]
### Overview
Lane got a job 🎉  but is leaving EA 😢  we have to offboard him.

### Action Items
- [x] reassign issues to @sydneywalcoff 
- [x] update
   - [x] team roster
   - [x] github wiki
   - [x] submit website team ticket to update project page 'current team'
- [x] remove access
   - [x] 1password
   - [x] figma
   - [x] google drive/calendar
   - [x] github

### Resources/Links
[Link to Submit Website Team Ticket](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2CComplexity%3A+Small%2Csize%3A+0.5pt%2Ctime+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D)
[Drive Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit#gid=897455484)
[Wiki Team Roster](https://github.com/hackforla/expunge-assist/wiki/The-Current-Team)

**Comment by amejiamesinas** [comment]
Messaged admin to remove from 1 passwork. Will update github wiki and issue for  website team project during 2-5-2024 PM meeting

**Comment by sydneywalcoff** [comment]
Hey @sydneywalcoff, @amejiamesinas! Thanks again for taking this issue.

    Time for an update! Please comment the following update:
    **Progress:** What's the status of the project? What have you done and what still needs to be done?
    **Estimated Time to Completion (ETC):** When do you estimate to be finished?
    **Blockers:** Anything preventing you from finishing?

    Thanks again!

**Comment by amejiamesinas** [comment]
@sydneywalcoff just need to update team page. Will be submitted Monday before PM Meeting (and form will reviewed at meeting). At meeting we should be able to close issue.

**Comment by amejiamesinas** [comment]
All action items have been completed. Issue submitted to update project profile: https://github.com/hackforla/website/issues/6475
