### ISSUE TITLE
Apply remaining Localization

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#117]
### Dependency
This is waiting on the MVP to be completed so we know which text needs to be localized. 

### Description
The product will eventually need localization to be applied so that it will adapt to other languages.

We have set up `translation.json` which contains key-value maps of text that is used in the app. It currently doesn't cover everything.

Notable elements to cover:
- buttons
- links
- headers
- choices
- paragraphs

**Comment by alexchoiweb** [comment]
Linking the initial PR #197 for future referencing

**Comment by sydneywalcoff** [comment]
Closing as this isn't realistic at our current stage
