### ISSUE TITLE
Enhance Friday syncs 

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1198]
### Overview
As a remote volunteer-run project, our Friday sync meetings have traditionally served as a platform for the Design and Content team to provide updates and collaborate on issues. However, recent observations have highlighted a shift towards administrative discussion and a noticeable decrease in attendance. This trend has led to increased miscommunication, difficulty in asynchronous collaboration, and a limited representation of voices.

As a team, we aim to improve our Friday syncs so that they are beneficial for all volunteers. 

### Action Items
- [x] Speak to UX writers and designers to gather pain points and opinions on current Friday sync format 
   - [x] Ask about whether time is doable or adjust
   - [x] Gather pain points 
   - [x] Ask what they would like to see from Friday syncs 
- [x] Draft up a [proposal ](https://docs.google.com/document/d/1Nb6dHrHbdZ4ZSSAWSUKSTFie30awP1xTTQNA6iFUpRE/edit)
- [x] Present proposal and gather team feedback 
- [ ] Conduct [Brainstorming session on FigJam](https://www.figma.com/board/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?node-id=4076-10238&t=9ZzwSr5dsYuW6nK7-4)
- [ ] Implement changes and present them to individual teams

### Resources/Notes
Discussion on this issue has been ongoing in Friday syncs. 
[Brainstorming on FigJam](https://www.figma.com/board/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?node-id=4076-10238&t=9ZzwSr5dsYuW6nK7-4)

**Comment by anitadesigns** [comment]
**Progress:** What's the status of the project? What have you done and what still needs to be done?

- This task is still a WIP. The proposal had been presented and we decided to roll out the changes beginning in April. 

**Estimated Time to Completion (ETC):** Hope to have this completed by the end of April. Each team will decide how to best improve their onboarding process for new volunteers. Design is already working on improving their process. #1180
**Blockers:** Anything preventing you from finishing? Just need to follow up with the team on this. Things to cement:
- Will UXR be implemented into our Friday syncs?
- Reviewing current agenda format and adjusting
- Present updates to team

Thanks again!

**Comment by anitadesigns** [comment]
**Progress:** Discussion is set in place on Slack to review the sync agenda and name. A proposal to change the name to "open sync" has also been in place. 
**Estimated Time to Completion (ETC):** Hope to have this closed by next week
**Blockers:** Reaching out to leads

**Comment by SamHyler** [comment]
@anitadesigns and I have discussed finalizing the doc soon. 

**Progress:** Finalization stage needed
**Estimated Time to Completion (ETC):** 1 or 2 weeks 
**Blockers:** Overwhelm of the amount of tasks.

**Comment by anitadesigns** [comment]
**Progress:** I've created a [revised proposal](https://docs.google.com/document/d/1J9mbG3nh-sSbBX5bFCT8jnSVaDYN95b-8d1m5D6RB1Y/edit) but would like to workshop the solutions with the rest of the team during an open sync
**Estimated Time to Completion (ETC):** two weeks (i hope)
**Blockers:** scheduling a time to workshop solutions

**Comment by anitadesigns** [comment]
I was able to introduce the Brainstorming Workshop to the team during our Open Sync on May 10th, 2024. Due to limited time, we decided to proceed with adding solutions async during the week and then revisiting it at our next Open Sync that @SamHyler will lead. 

Today we were only able to address Pain Point #5: Facilitating and brought up the following solutions:
- Leads and PMs can "buddy" with team members new to facilitating to support them in building this skill. They can either 1. meet before a meeting and go over best practices 2) Begin practicing facilitating in "local" smaller meetings like their own team meetings and/or 3) Split the facilitator role with someone else during an Open Sync 
- Create a Facilitator Role Guide 
- Review Open Syncs agenda template and adjust to that new facilitators have a better feel of what to cover 

We also discussed not having a facilitator for the first 30min of a meeting so that it becomes an open space for folks to share updates and ask for feedback 


The FigJam board can be found [here](https://www.figma.com/board/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?node-id=4076-10238&t=9ZzwSr5dsYuW6nK7-4)

**Comment by sylvia-nam** [comment]
PM and Leads suspended Open Sync at the end of June 2024 for time being until: 1) function, roles, etc, 2) participation, 3) collaborative framework can be worked out

**Comment by sylvia-nam** [comment]
-

**Comment by sylvia-nam** [comment]
Revised from closed as not completed
