### ISSUE TITLE
Fix page breaking when clicking from LG page to FAQ page 

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1199]
### Overview
When user is navigating from the Letter generator and then decides to visit the FAQ page by click "FAQ" on the header, the page breaks. It directs users to the FAQ page but includes a snippet of the progress bar found in the letter generator. 

Also noticed when clicking on "Privacy Policy" and "Terms of Use" on Footer

Examples:
<img src="https://github.com/hackforla/expunge-assist/assets/105686896/58d58a9a-79d7-42a8-9a7c-20febb2349f6">

Privacy Policy 
![Screen Shot 2024-03-06 at 10 52 17 PM](https://github.com/hackforla/expunge-assist/assets/105686896/ea342deb-447c-4ae9-a5a2-69b1c984ef2b)

Terms of Use 
![Screen Shot 2024-03-06 at 10 53 28 PM](https://github.com/hackforla/expunge-assist/assets/105686896/22052e6a-e27a-42c4-aff6-9f6a809d0a5e)

### Action Items
- [ ] Fix bug

### Resources/Notes
Screen recording of behavior 
https://github.com/hackforla/expunge-assist/assets/105686896/cf8fdedc-cebd-4bd7-a96f-f44091dc3fe3

**Comment by sydneywalcoff** [comment]
Duplicate to #1151 that was merged today.
