### ISSUE TITLE
style Next button to be at same position

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#120]
Going to talk to Design about this UX since typically it's better to have the position in the same location so the user isn't looking for the next place to click as they fill it out. I mean, aren't you annoyed at how the button position keeps changing at the moment??

On desktop, it'd probably be on the bottom left but we don't want it to the extreme left - so we want to make sure we have a max-width of the page implemented.

**Comment by sarahyaepark** [comment]
Next and back button in the same place
