### ISSUE TITLE
Establish email for Contact Form

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1212]
### Overview
The Contact form requires an email that inquiries can be sent to. Confirm an email the Dev team can link to the contact form.

### Action Items 
- [x] Confirm with Bonnie the email the contact form should link to 
- [x] Share email with Dev for #1213 

### Resources/Notes 
- Main Issue: #1209

**Comment by CBx3000** [comment]
I posted in the Dev issue that the contact form can use this email : expungeassist@hackforla.org
