### ISSUE TITLE
implement Textarea component

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#122]
https://www.figma.com/proto/t1lW4Tm0Lp3jFdeOCd98b1/Record-Clearance-Personal-Statement?node-id=805%3A6018&scaling=scale-down

This is different from an Input component because it's more than one line. Product has asked that the field expands as the user types.

**Comment by sarahyaepark** [comment]
I'd like to take this issue!

**Comment by aahvocado** [comment]
Awesome! Please assign yourself to the issue so we know, much appreciated!
