### ISSUE TITLE
Button Unit Testing

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1243]
### Dependency
- [x] #1267 

### Overview
Testing is an important part of the development process that has been ignored in the Expunge Assist process thus far. To create a better protected codebase, we want to retroactively implement tests.

Create tests for the below scenarios. Feel free to include additional tests if you find opportunities for more coverage.

### Action Items

- [x] Button sets up correctly
   - [x] Button element renders
   - [x] Button displays text correctly
- [x] Props pass correctly
   - [x] forward arrow 
   - [x] backward arrow
   - [x] if disabled, no pointer events and gray coloring
- [x] Button disables correctly
   - [x] disable - no pointer events and gray coloring
   - [x] un-disabling something reinstates pointer events and purple coloring
- [ ] button is accessible
   - [x] is focusable
   - [x] does not trap focus (pressing tab with more than one focus-able element present will move focus to next available element)
   - [ ] ~~are at least 44px wide~~

### Resources/Notes
[Jest](https://jestjs.io/docs/getting-started)
[React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

**Comment by whitneywind** [comment]
<img width="633" alt="Screenshot 2024-05-06 at 12 30 56 PM" src="https://github.com/hackforla/expunge-assist/assets/78887901/fb83fa3e-1f20-4960-91af-0bc98a1e1c44">
