### ISSUE TITLE
Checkbox Testing

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1244]
### Dependency 
- [x] #1267 

### Overview
Testing is an important part of the development process that has been ignored in the Expunge Assist process thus far. To create a better-protected codebase, we want to retroactively implement tests.

### Action Items

- [x]  Checkbox sets up correctly
   - [x] Checkbox renders
   - [x] renders correct initial state 
- [x] Checkbox functions correctly
   - [x] clicking checkbox changes state
   - [x] clicking checkbox does NOT change state of other checkboxes (multi-select is possible)
- [x] Checkbox passes props correctly
   - [x] id passes correctly
   - [x] label passes correctly
- [x] Checkbox is accessible
   - [x] using spacebar changes state
   - [x] checkbox is focus-able
   - [x] does not trap focus (pressing tab with more than one focus-able element present will move focus to next available element)

### Resources/Notes
[Jest](https://jestjs.io/docs/getting-started)
[React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

**Comment by davidwiese** [comment]
ETC Weds 6/12/24
