### ISSUE TITLE
LG Routing Testing

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1249]
### Dependency
- [x] #1267

### Overview
Testing is an important part of the development process that has been ignored in the Expunge Assist process thus far. To create a better protected codebase, we want to retroactively implement tests.

Create tests for the below scenarios. Feel free to include additional tests if you find opportunities for more coverage to test our routing in the letter generator.

### Action Items
- [x] Static pre-form pages route correctly
   - [x] Start Now -> Welcome
   - [x] Welcome -> Before you Begin
   - [x] BYB -> advice
   - [x] advice - > Form  
- [ ] Static form pages route correctly
   - [x] Introduction -> Intro Preview
   - [x] Intro preview -> Involvement
   - [x] Future Goals -> FG preview
   - [x] FG preview -> Why
   - [x] Why -> Why preview
   - [x] Why preview -> Finalize
   - [x] finalize -> finalize preview
- [ ] Dynamic form pages route correctly
   - [ ] form uses formState to determine route
   - [ ] pages are ordered: employment, unemployment, self-improvement, education, parenting, community service, something else

### Resources/Notes
[Jest](https://jestjs.io/docs/getting-started)
[React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

**Comment by whitneywind** [comment]
Still working on this! I have written tests that test the static pre-form page routing. Now I'm determing how to test the form routing specifically without having the test also access and fill out the entire form.

**Comment by whitneywind** [comment]
The tests are finished, but I am still working on fixing some bugs that are caused by using certain versions of node. As of now, node versions 16 and 18 work without problems.
