### ISSUE TITLE
Conduct and present background research on colors and typography

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1263]
### Overview
The Design team is working on improving our visual style and requires more background research on color theory and typography. 

The current typography is: Roboto
The current color scheme is: purple

The main recommendation from IUT 2 was to find balance between “legal” and “modern." The question asked at the time behind the recommendation: How is our mission achieved through color [and typography]?

### Action Items 
- [x] Conduct background research
- [x] Prepare findings
- [x] Share with Design team

### Resources/ Notes
Main: #1226

**Comment by saraisabelcf** [comment]
[Google Doc with findings summary and resources](https://docs.google.com/document/d/16e3smfFPbzIXQlyj7U5XUSzKGgepJvJuPYlHbLiOZFY/edit)

**Comment by sylvia-nam** [comment]
For actionable next steps, see https://github.com/hackforla/expunge-assist/issues/1339

**Comment by anitadesigns** [comment]
Closing this issue since it has been completed
