### ISSUE TITLE
LG: Input/Button Interactions

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1270]
### Dependency
- [x] #1267

### Overview
Testing is an important part of the development process that has been ignored in the Expunge Assist process thus far. To create a better protected codebase, we want to retroactively implement tests.

Create tests for the below scenarios. Feel free to include additional tests if you find opportunities for more coverage of the input/button interactions.

### Action Items
- [ ] Inputs control button availability
   - [ ] button starts disabled
   - [ ] filling some (but not all) inputs keeps it disabled
   - [ ] filling all the inputs makes the button available
   - [ ] filling all the inputs, then removing an answer, disables the button

### Resources/Notes
[Jest](https://jestjs.io/docs/getting-started)
[React Testing Library](https://testing-library.com/docs/react-testing-library/intro/)

**Comment by eburdekin** [comment]
Estimated ETA is end of this week

**Comment by eburdekin** [comment]
ETA is ~6/28! Haven’t had time to get started but I will this week

**Comment by eburdekin** [comment]
I bit off more than I could chew with this one, so working on the individual component testing issues first. Not sure on my ETA yet
