### ISSUE TITLE
Content - New Member Orientation

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#1288]
This is a (draft) for the content team pre-work onboarding, this is currently being written with the possibility that there will be a separate issue for PM type onboarding. 

### Overview
Hello and welcome to the UX Writing/Content Design team at Expunge Assist! 

This is to help introduce new team members to all important documents, work processes, and other information that will help them orient and get started at EA. 
This onboarding process is here to help familiarize you with the project and begin to work with GitHub. Take your time as you work through each step and don't hesitate to comment with questions and tag/slack @SamHyler and/or @emmathrash (content co-leads). You can also find and message members in the EA [slack channel](https://hackforla.slack.com/archives/CN8NXTPK5)

### Set Up This New Issue

- [ ] At the top of the issue, under "add a title" replace [YOUR NAME] with your name
- [ ] Assign yourself to this issue using the gear in the sidebar on the right
- [ ] Under `Labels`, replace `role: missing` label with `role: content`
- [ ] Under `Projects`, add issue to `Expunge Assist Project Tracking` using the gear in the sidebar
- [ ]  Under `Milestones` add issue to `Team Workflow` using the gear in the sidebar
- [ ] Submit this issue and then find it on the Project Board and move into the `In Progress (active)` column

### Slack

Add yourself to the following slack channels
 - [ ] [#expunge-assist](https://hackforla.slack.com/archives/CN8NXTPK5)
  - [ ] [#expunge-assist-design-content](https://hackforla.slack.com/archives/C02T3EB0N77)
  - [ ] [#expunge-assist-research-team](https://hackforla.slack.com/archives/C02M2CV2J9E)
  - [ ] [#expunge-assist-dev](https://hackforla.slack.com/archives/C04EG4A284F)

### Project Resources

Read through and bookmark the following:

**Your workspaces:** 

- [ ] [Github project board ](https://github.com/hackforla/expunge-assist/wiki/Team-Weekly-Monthly-Meetings)
 - [ ] [Figjam board ](https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?type=whiteboard&node-id=4041-9898&t=Bhtt87T8WaELjpwj-4)for collaboration between Content and Design. There is also a Figjam board for UXR, and one for PMs/planning. 
EA has access to 3 collaborative Figjam boards, the main Figma, Slack, and Google Drive. We don't use Miro, Notion, or other tools. Please use these boards only (and not your personal boards, for example), so that all work is saved for future EA volunteers! If we need additional resources, raise it at a meeting and with the leads/PMs so that it can be discussed and created through EA resources if deemed a necessary new tool.
- [ ] [Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=0-1&mode=design) 

**Specific Figma pages**

 - [ ] Read ["Start Here"](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2%3A21&mode=design&t=g8j5PA8CesPhD7N5-1) page on Figma. Read the Team Workflow "Practical steps to getting the work done" on the Start Here page. This is a general guide to how we collaborate between crossfunctional teams and take an issue through to completion.
- [ ] Familiarize with Figma - [master pages](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-37&mode=design) "desktop" and "mobile" we are working in responsive web, no app. These are the source of truth sections 
- [ ] Familiarize with [Work in Progress](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2349-24717&mode=design) pages. This is where we work and collaborate between Design and Content. 
- [ ] Familiarize with the [Design hand off space to Dev](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-38&mode=design), this happens at the end of an issue
- [ ] There is a [Figma Archive](https://www.figma.com/file/jaYLRw4dCTYhGYOI9aMehr/Expunge-Assist---Figma-Archive?type=design&node-id=4875-45387&mode=design) with work prior to 2024. This is because the free version ran out of storage space. This is a resource to see previous design decisions.

**General resources:**
- [ ] ["How to Create Github Issues"](https://github.com/hackforla/expunge-assist/wiki/How-to-Create-Issues) Github is our project management tool, everyone on the team should know how to use it
- [ ] Expunge Assist [website](https://expungeassist.org/#/). VIsit the website, look at all the pages (there are not that many). Go through the tool, enter in anything to observe how the tool behaves.
- [ ] [Understanding Expungement in CA](https://docs.google.com/presentation/d/1MGeAWeTl3C_Eg6rsrmzdzsc_vX2aY3YX-ODdVlDe21o/edit#slide=id.p) a presentation about the nuances and key terms of expungement processes in CA.
- [ ] [Internal Usability Testing 1 ](https://docs.google.com/document/d/1N0u7c1RwbxglQpLk_lIgbhDnAenMhCwNPazcNHI9aJI/edit?tab=t.0#heading=h.gpri51glck6b)
- [ ] [Internal Usability Testing 2 ](https://docs.google.com/presentation/d/1PH0c-MvX4HKfiEI9xZHUMM9YJFjGNsplaMNsCNbWqzI/edit#slide=id.geed4b67c62_0_0)
 - [ ] [Personas/Target audience demographics](https://docs.google.com/presentation/d/1Bwl-tzVmd3xIZX5vLFmNKkwjylSExFImo2RMIqvsS0g/edit#slide=id.p)
 - [ ] Read our project's [One Page](https://docs.google.com/document/d/1SVgk4vH02oH7kUVbphKebrWMQNOMtzkIkpcksnHAULo/edit)

**Content specific resources:**
- [ ] [Content Guidelines](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-19&mode=design) on Figma
- [ ] [Wiki](https://github.com/hackforla/expunge-assist/wiki) pages and specifically the resources under [this wiki page](https://github.com/hackforla/expunge-assist/wiki/Content-Writer)
- [ ] [Content Timeline](https://docs.google.com/document/d/1W2zFZxBvFfzLaPlv51LEzQx3J_0fCiy_XlBYjN59IUA/edit#heading=h.pnf9fi7gvgab) doc, which documents all major highlights since the Content Design/UX Writing team was started (2021)
- [ ] [Source of truth document](https://docs.google.com/spreadsheets/d/1c_Kv_T1yER-hHckNl5zkGrlGaLNCE_AeZE6Jjmn8IK0/edit#gid=368137937), tracks all current content on the site (careful not to edit anything here!)
- [ ] Google Drive [Content Folder](https://drive.google.com/drive/u/1/folders/1gBWIqDBDvNxKaqQo39ebpQeWu54ddDYR)

**Meetings**
- [ ] [Content and Sync Meeting times](https://github.com/hackforla/expunge-assist/wiki/Team-Weekly-Monthly-Meetings)

## Your first issue

Now that you are familiar with our project and learned a bit about using our tools, it's time to work on your first Issue. It's important to note to practice the following:

- Most of our issues are 1pt (1pt should = 1 week of work), but do occasionally get higher than that. Start small and work your way up. We discuss upcoming issues during Content meetings, you can express interest for any issue during the meetings 
- Frequently add updates to all issues you are assigned to or providing input to
  - updates are required once a week and should use the following format:

```
1. Progress
2. Blockers
3. Availability
4. ETA
```

- Make sure to check off 'Action Items' as they are completed
- Make sure to close issues as you finish them

### Resources/Notes
https://github.com/hackforla/expunge-assist/issues/819 - Content PM onboarding issue

**Comment by emmathrash** [comment]
**Progress:** What's the status of the project? What have you done and what still needs to be done? Still wanting to make sure we haven't missed anything
**Estimated Time to Completion (ETC):** When do you estimate to be finished? 2-3 weeks
**Blockers:** Anything preventing you from finishing? Nope

**Comment by emmathrash** [comment]
@SamHyler I just spent some time working on this. Based on the PM/lead meeting earlier this week, it seems like the PM type onboarding with be different from this type of orientation, I looked at Design's template for guidance (PS, this will be turned into an issue template and we can tag 'ready for dev lead' when we're ready for Sydney to do that). I've left comments and questions through the set up, feel free to make any changes or additions. I know the headings are also a mess right now, all WIP :D

**Comment by SamHyler** [comment]
Amazing, thank you @emmathrash ! I did some restructuring of the things to read section. Go ahead and change any if needed. I added links to all the sections, so should be good to go on this part. Unless there is something else we want them to put eyes on? I _think_ we got it all? 

I just made some minor changes to the Design template. Curious about what you mean by the template and what happens here?

My other question is around their "first issue." Is creating a Github issue with this task list their "first issue" or did we want to have a different strategy?

**Comment by SamHyler** [comment]
Another thought, we should consider what resources from the other teams new writers should be aware of, that can help them in their work.

**Comment by emmathrash** [comment]
@sydneywalcoff hello! Sam and I have finalized this for content orientation, please  can you"templatize" this? Thank you!

**Comment by sydneywalcoff** [comment]
ETA: today
