### ISSUE TITLE
Content Guidelines - 3 principles (step 1)

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#1292]
### Overview
Updating CGs.
Add our new Voice Principles to the Guidelines. 

### Action Items
- [x] Copy each Voice principle from the [FigJam](https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?type=whiteboard&node-id=2482%3A6581&t=TNonPY2Am0gVUBIe-1) to the CGs in [Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-19&mode=design)
- [x] Add detail to each using the same chart format (or discuss within content to create a new format), using the 'this not that' qualifiers and descriptions for each principle
- [x] Raise discussion around TONE after this task is finished. How does the tone change for each principle in different situations users encounter site wide?
- [x] Add any relevant resources to the resource section
- [x] Reach out for feedback from the Content team

### Resources/Notes
Figma Content Guidelines Board: https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-19&mode=design
Figjam V&T Work: https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?type=whiteboard&node-id=2482%3A6581&t=TNonPY2Am0gVUBIe-1

**Comment by emmathrash** [comment]
@SamHyler do you feel this one is ready?

**Comment by SamHyler** [comment]
@emmathrash yes!

**Comment by SamHyler** [comment]
Added, ready to continue with the rest of the CGs and develop tone
