### ISSUE TITLE
Evaluate automating the weekly label check

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1316]
### Overview
Currently the weekly label check is really onerous. You have to go link by link to update add 'missing' labels to all the issues missing any of the required labels.

Requirements:
- On a weekly basis, 
- bot searches size, priority, feature, and role labels
   - creates dynamic filters for each
- bot filters for all issues
   - not containing a size label
      - add https://github.com/hackforla/expunge-assist/labels/size%3A%20missing
   - not containing a priority label
      - add https://github.com/hackforla/expunge-assist/labels/priority%3A%20missing
   - not containing a feature label
      - add https://github.com/hackforla/expunge-assist/labels/feature%3A%20missing 
   - not containing a role label
      - add https://github.com/hackforla/expunge-assist/labels/role%3A%20missing

### Action Items
- [x] evaluate the possibility of automating the weekly label check
   - [ ] if not, message dev lead with explanation why
   - [x] otherwise code GHA to meet the above requirements

### Resources/Notes
reference #369 to see current process

**Comment by eburdekin** [comment]
ETC: Friday 4/19
