### ISSUE TITLE
Implementing New Visual Style Based on UXR Findings 

### ISSUE THREAD

**Issue by saraisabelcf** [hackforla/expunge-assist#1338]
Based on findings on color system from UXR, lower levels of color saturation and image increase user trust on website. Current saturation is very high, so UXR recommendation is to decrease saturation. 

### Action Items
- [ ] Draft new saturation level 
- [ ] Propose in a collaborative meeting 
- [ ] Usability testing 
- [ ] Implement 

### Resources/Notes
Slide Deck: slides 7-10 

https://docs.google.com/presentation/d/1NtmEOO7AbcHypaEkxXqvOrUYfisrkE3ly2-Js-J8G38/edit#slide=id.gc6f90357f_0_0

**Comment by anitadesigns** [comment]
Saturation is also being explored in #1228 when design standardized our new color system. Closing this issue as not planned
