### ISSUE TITLE
Implement findings for new colors 

### ISSUE THREAD

**Issue by saraisabelcf** [hackforla/expunge-assist#1339]
### Overview
Based on UXR research, it recommends: 1) blue as the new color and 2) less color saturation.

COLOR (refer to slides 7-11)
Blue is associated with trustworthiness and communicates reliability and safety, and matches Voice and Tone (supportive, straightforward, trustworthy). Most, if not, all government websites and "high risk" websites use blue. Expunge Assist website color scheme is currently purple (a shade close to pink). 

An alternative is to change the current color of purple to a shade closer to dark blue. 

SATURATION (refer to slide 11)
Less saturation. UXR findings: less saturation corresponds to increased trust.

The site relies on highly saturated colors.

### Action Items for Design
- [ ] Review, discuss, decide on new color https://github.com/hackforla/expunge-assist/issues/823 
- [ ] Review, discuss, decide on new saturation 
- [ ] Make changes to Figma
- [ ] Implement changes on the website
- [ ] Discuss next steps: A/B testing, usability testing, etc.

### Resources/Notes
- https://github.com/hackforla/expunge-assist/issues/1263 on UXR findings on colors and typography
- UXR [summary](https://docs.google.com/document/d/16e3smfFPbzIXQlyj7U5XUSzKGgepJvJuPYlHbLiOZFY/edit) of findings on color and typography
- UXR [slide deck](https://docs.google.com/presentation/d/1NtmEOO7AbcHypaEkxXqvOrUYfisrkE3ly2-Js-J8G38/edit#slide=id.gc6f90357f_0_0)  on research findings

**Comment by anitadesigns** [comment]
Closing due to duplication. Design team created an issue for this : #1228
