### ISSUE TITLE
Code auto-correct missing periods and capitalizations

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#1363]
### Overview
The LG has some instances where the user should write sentences. The user may or may not add a period at the end of the sentence. In all the spaces users enter words, they may or may not capitalize the first word of a sentence (or possibly proper nouns). 

This issue is to build automatic detection for these instances, and to automatically correct them. 

### Action Items
- [x] Code a solution that identifies and fixes sentences missing capitalization or ending periods.

### Resources/Notes
- In the LG flow, we'd want this to execute after the user enters the answer, but before the text preview.

**Comment by davidwiese** [comment]
ETC Weds 5/15

**Comment by davidwiese** [comment]
PR here-

https://github.com/hackforla/expunge-assist/pull/1407

**Comment by davidwiese** [comment]
Updated PR
