### ISSUE TITLE
(draft) Design new about us page

### ISSUE THREAD

**Issue by emmathrash** [hackforla/expunge-assist#1367]
### Overview
The about us page is not consistent with the other main pages of the websites - it is missing the header graphic that the other pages have. Content is also completing a redesign of the copy on the page and the alignment will need to be adjusted once that is complete.

### Action Items
- [ ] 

### Resources/Notes
#965 
#1366

**Comment by emmathrash** [comment]
@anitadesigns @jyehllow I started the issue and added what I knew about what design wants to do with this page, but I'm not sure of all the details or your preference for task lists

**Comment by anitadesigns** [comment]
Thanks @emmathrash !Thinking we can amend the other issue we had for Design to redesign the About Us page and just close this issue. Ill go ahead and link the main issue and the new content issue
