### ISSUE TITLE
Identifying target user

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/expunge-assist#1387]
### Overview
PM /Leads team needs to promote discussion in order to make decision around question: who is our target user. 

### Action Items
- [ ] Add this issue to discussion item for PM-Leads Meeting
- [ ] Discussion should focus on what is in the best interest of the product?
- [ ] Present target user and rationale at all teams.

**Comment by mariaweissman** [comment]
Conclusion reached via PM-Org Meeting with Bonnie. Product is geared toward being used in conjunction with a legal aid group, not directly with a user finding it online on their own. User would be the person seeking expungement, but they wouldn't be finding this on their own.
