### ISSUE TITLE
Fix spacing in Partnership Opportunities section of landing page on mobile

### ISSUE THREAD

**Issue by eburdekin** [hackforla/expunge-assist#1421]
### Overview
On mobile, a hardcoded line break in the Partnership Opportunities section is causing awkward spacing on mobile:

![Screen Shot 2024-06-03 at 11 20 59 PM](https://github.com/hackforla/expunge-assist/assets/146603843/1e6a5743-cbdc-43a0-896c-3bd8c1f9ec3b)

### Action Items
- [x] Fix spacing on mobile

### Resources 
[Design ](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=16635-23923&t=giLjpRRlmhXINWz0-4)

**Comment by anitadesigns** [comment]
@sydneywalcoff Green light from Design! I also added a link to the mobile design and moving this over to "New issue awaiting approval

**Comment by sydneywalcoff** [comment]
@anitadesigns thank you!!
