### ISSUE TITLE
FAQ link color doesn't match Figma designs

### ISSUE THREAD

**Issue by eburdekin** [hackforla/expunge-assist#1434]
### Overview
The links on our FAQ page should be in `#25003F` per the Figma designs. Right now they're in default `a` colors:

#### screenshots from the live site
![Screen Shot 2024-06-05 at 6 11 55 PM](https://github.com/hackforla/expunge-assist/assets/146603843/b0ce6a39-d41d-40d3-a7d3-718395a20950)
![Screen Shot 2024-06-05 at 6 12 15 PM](https://github.com/hackforla/expunge-assist/assets/146603843/16f011bf-64cd-4a7e-8006-c412ede8c547)

#### screenshots from the figma
![Screenshot 2024-09-26 at 2 28 03 PM](https://github.com/user-attachments/assets/67a5eaeb-7f41-48cd-8fd3-c8927bb61910)

### Action Items
- [ ] Update FAQ link styling 

### Resources/Notes
[Figma designs](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=15920-16184&t=1s4FIQmGGZaaH5aC-4)

**Comment by anitadesigns** [comment]
@sydneywalcoff thinking this one can be paired up with the feedback Bonnie provided on external links

**Comment by sydneywalcoff** [comment]
hey @anitadesigns ! We can get this knocked out pretty quickly if I can get a Figma link specifically to the Figma FAQ page. Right now it has all the master docs linked, and I think it might be hard to find for devs.

**Comment by anitadesigns** [comment]
> hey [@anitadesigns](https://github.com/anitadesigns) ! We can get this knocked out pretty quickly if I can get a Figma link specifically to the Figma FAQ page. Right now it has all the master docs linked, and I think it might be hard to find for devs.

@sydneywalcoff updated the design link so that the new link will directly show the FAQ frame in the Master page.
