### ISSUE TITLE
Bonnie Expunge Assist Review (for PM/Org Meeting)

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/expunge-assist#1442]
### Overview
During our [monthly PM/Org meeting](https://github.com/hackforla/expunge-assist/issues/379#issuecomment-2166946457), Bonnie will conduct a recorded review of our Expunge Assist Site and Letter Generator.  

In July 2023 Bonnie provided EA team a recorded review of the landing page and letter generator. Updates since last review by team
- **Content:** Updated all CFA/HfLA changes, Rewrote the example letters on the Landing Page to be unique and match the LG, updated the "Before you Begin Page" Instructions, Created Alt Text for relevant images
- **Dev:** audited and refactored site for accessibility (the site is now easily navigable using a keyboard or screen reader), published the credits page, implemented redesigned 404 page, implemented redesigned FAQ page
- **Research:** audited site for accessibility, completed content terminology research, developed expungement in CA huide for all teams
- **Design:** Designed the Credits page, 404 page, and loading page design, Adjusted illustrations on the landing page to improve readability and quality of the pictures, Redesigned the FAQ page, Added an error prevention modal at the of end of letter generator to allow user flexibility in downloading the letter or returning home and erasing data.

### Action Items
- [x] Using Zoom, Begin Recording 
- [x] Go to: https://expungeassist.org
- [x] Please review the site (including the letter generator, about us, and FAQ page)
- [x] Please share out load any thoughts, first impressions, concerns, or issues that need to be addressed
- [x] Additional Questions from team: 
- What is your experience/first impressions of the last modal before the user officially exits the letter generator?
- For the FAQ page, how easy is it finding information? What was your experience using the accordions?
- [x] Upon Completion, Please Add Recording [HERE](https://drive.google.com/drive/folders/1LD9ijjdQvX2pmdPkuyMbq9AKKOPymnfr)

### Additional Feedback
Any updates on Privacy Policy? 

### Resources
Upload completed to [Usability Test Bonnie - June 2024](https://drive.google.com/drive/folders/1LD9ijjdQvX2pmdPkuyMbq9AKKOPymnfr)

**Comment by ExperimentsInHonesty** [comment]
I plan to do this now, should be done in a few hours at most

**Comment by ExperimentsInHonesty** [comment]
https://languagetool.org/

**Comment by ExperimentsInHonesty** [comment]
https://tdm.ladot.lacity.org/about

**Comment by ExperimentsInHonesty** [comment]
info@expungeassist.org can be customized so that clicking on it in specific places gives different results.  For example

HTML
```
‹a href="mailto:info@expungeassist.org?subject=Incorrect Information">info@expungeassist.org‹/a> with the subject: Incorrect Information
```

‹a href="mailto:info@expungeassist.org?subject=Incorrect Information">info@expungeassist.org‹/a> with the subject: Incorrect Information

**Comment by ExperimentsInHonesty** [comment]
Notes about the future of this tool given that it is only servicing people who missed the deadline for Proposition 47

**Comment by ExperimentsInHonesty** [comment]
The author for this image 
![image](https://github.com/hackforla/expunge-assist/assets/37763229/4361575f-54ea-430c-b79e-559fe296f232)
is listed as 
![image](https://github.com/hackforla/expunge-assist/assets/37763229/0d4b3da1-2921-4762-b47c-dfd1cc74a0a8)
which links to 
https://www.freepik.com/author/rawpixel-com

**Comment by ExperimentsInHonesty** [comment]
Credit page needs to link each credit to the url where it came from
See https://www.hackforla.org/credits/ for examples

On this image
![image](https://github.com/hackforla/expunge-assist/assets/37763229/a1dc8161-e729-46c0-8073-287e5ae1ed1a)

The word pencil would be linked to 
https://pictogrammers.com/library/mdi/icon/pencil/

Or you could add the word source and link that, or something.

**Comment by ExperimentsInHonesty** [comment]
User stories for since your conviction where the user has both unemployment and employment checked
A person who had a job and now does not
A person who was unemployed and now is not

**Comment by ExperimentsInHonesty** [comment]
Converting recording now.

**Comment by ExperimentsInHonesty** [comment]
Upload completed to [Usability Test Bonnie - June 2024](https://drive.google.com/drive/folders/1LD9ijjdQvX2pmdPkuyMbq9AKKOPymnfr)

**Comment by ExperimentsInHonesty** [comment]
## Key moments in video

### Homepage: 
Starts at 0:50
- What is Expunge Assist
  - concern S: missing commas
  - concern S: multiple use of the word this
- Committed to data safety
  - concern M: that we are giving a blanket promise.  And there are applications out there that might be installed on the computer, such as a keystroke logger, and screen recorder that employers sometimes use, that would record their visit to the site and everything that they typed.
  - concern C: iPhone and image inside are both dark, the external could be lighter
- A complete letter
  - concern C: communicate that they are creating the letter
  - concern A: how we communicate that they need legal representation
     - The sentence "This is not a replacement for legal advice." can be changed to "ExpungeAssist.org is not a replacement for legal advice."
- Frequently Asked Questions
  - concern S: we use the word gun on a faq question on the first page and firearm on a different faq questions on the FAQ page, we should standardize and probably should use the word weapon
  - concern C: contradiction in the explanation if something is expunged or just updated
  - concern C: The Button Read our FAQ, might be better if it said "All FAQs" or "More FAQs" (is actually mentioned in the FAQ review part of the video)

### About Us: 
Starts at 9:28
- What is Expunge Assist
   - concern S: missing commas
   - concern S: multiple use of the word this
  - concern M: how we communicate that they need legal representation
     - The sentence "This is not a replacement for legal advice." can be changed to "ExpungeAssist.org is not a replacement for legal advice."
- Why Record Clearance Matters
   - concern C: 144,000 might age badly, we can fix that by adding a date or at least a plus sign
- Partner with us:
   - concern S: add free of charge to the partner with us section

### FAQ
Starts at 12:35
- concern C: Formatting of the FAQ page is different from the FAQs on the homepage
- concern S: commas missing
- concern C: "it is often about one page" could be changed to "It is usually one page"
- concern S: we use the word gun on a faq question on the first page and firearm on a different faq questions on the FAQ page, we should standardize and probably should use the word weapon
- concern M: external links should let the user know where they are going by saying who the publisher is (example: [Clearing Your Adult Criminal Record in California: A Step-by-Step Guide](https://www.courts.ca.gov/partners/documents/ExpSBS.pdf) (publisher: Los Angeles County Neighborhood Legal Services or 
- concern M: external links need to have an external link. See the comment above [External Link Indicator](https://github.com/hackforla/expunge-assist/issues/1442#issuecomment-2168820868) with details and examples


I rated the concerns in order of priority
Concern M = Must change
Concern S = Should change
Concern C = Could change

**Comment by ExperimentsInHonesty** [comment]
## Please add this to the PM/Org agenda

We need to discuss the future of this tool, given that it is only servicing people who missed the deadline for Proposition 47
