### ISSUE TITLE
Research illustrations vs images

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1481]
### Overview 
The goal is to identify best practices for illustrations, images, and other visual communication on the website.

The revised visuals must reflect Content's voice and tone key terms (trustworthy, supportive, and straightforward). 

### Action Items 
- [x] Conduct background research on visual communication 
- [x] Conduct background research on illustrations relevant to EA  
- [x] Communicate findings

### Resources 
- Main: #1480 
- Example: #512 
- Example: #1173
- #1226

**Comment by sylvia-nam** [comment]
@saraisabelcf when you write out this issue, this issue is worth referencing https://github.com/hackforla/expunge-assist/issues/512
It is an example to think through: visibility and utility

**Comment by sylvia-nam** [comment]
Also this one too @saraisabelcf: https://github.com/hackforla/expunge-assist/issues/1173
On the importance of creating a graphic with high utility in terms of info delivered

**Comment by vanessaavviles** [comment]
Design wants to know if there is a difference in comparison between photos vs stock photos?

**Comment by sylvia-nam** [comment]
@vanessaavviles can you clarify what you mean by the question? Do you want Research to analyze the differences between photos and stock photos in terms of best practices? Or did you mean something else?

**Comment by vanessaavviles** [comment]
We were curious of the status of the research on best practices including illustrations vs stock photos?

**Comment by sylvia-nam** [comment]
@vanessaavviles from my understanding, you're asking a different question from the previous one. I can give a status update tomorrow if my understanding is correct

**Comment by vanessaavviles** [comment]
Yes, you are correct. There was a misunderstanding within our team. We are just curious of the status on the research. Thanks for finding that information for us.

**Comment by saraisabelcf** [comment]
@vanessaavviles 09/27 status update: we're doing a final revision of the research and will share the final product by October 11.

**Comment by vanessaavviles** [comment]
Thank you for the update. @saraisabelcf

**Comment by saraisabelcf** [comment]
Leaving here the Illustrations Research Findings Google Doc and Slide Deck: 

Google Doc:
[https://docs.google.com/document/d/19m3Oo9JB59ncJCTiRkB7Grd5sIR769BHwb7yB-OygE4/edit?tab=t.0#heading=h.4pjfbu7guqdb]

Slide Deck: 
[(https://docs.google.com/presentation/d/1bDqD0IIWIiataYKV0kIJi1_xGxqHda0LWP5HT6ZbVKU/edit#slide=id.gc6f90357f_0_0)]

**Comment by sylvia-nam** [comment]
Closing issue for Research
