### ISSUE TITLE
Identify data accessible from court record APIs

### ISSUE THREAD

**Issue by ggrrettcchhenn** [hackforla/expunge-assist#149]
### Overview
Bo asked if we could create a tool to get access to all criminal record cases that qualify for record clearance so that expungement clinics can do mass outreach to people who might not know they can get their record cleared.

### Action Items
Look into these court record APIs to see what data we can access.

- [ ]  Microbilt Criminal Records Search - https://developer.microbilt.com/criminalsearch/apis
- [ ]  US Legal Pro CA Courts - APIs https://documenter.getpostman.com/view/5415285/SzezbWZc
- [ ] Court Listener - Free Law Project - https://www.courtlistener.com/api/rest-info/

### Resources/Instructions
Gretchen started a google doc for API notes here: https://docs.google.com/document/d/1EypuJ5DIU-GjCLET3uu63aQFbtc7WzwflYX6oDNJKko/edit?usp=sharing

**Comment by ggrrettcchhenn** [comment]
More questions/ideas about possible uses of API on Running List of Questions doc here: https://docs.google.com/document/d/1CxH8-UXMEDGDiPQncpBOlUNgxtcDhzNEFF9SHhaPaH4/edit?usp=sharing

**Comment by sylvia-nam** [comment]
This is a level of expertise in data analysis and access that we don't have, in contrast to California Policy Lab and Code for America.
