### ISSUE TITLE
create Slide Deck

### ISSUE THREAD

**Issue by myrandi** [hackforla/expunge-assist#151]
- [x] Assign slides to team members
- [ ] Gretchen to work on people slides, key insights from phase 1 & prior research
- [ ] Myranda to work on Background/Scope slides
- [x] Tierney to work on Ecosystem slide, add visuals after assigned slides are completed
- [x] Gilles to work on current PSG tool, next steps slides
- [ ] Tina will work on graphics (when we have new domain secured)
- [ ] Andan to work on Eligibility criteria
- [ ] Sahiba to look into measurables for an impact page, assist with next steps
- [ ] Tierney to work on updating Service Design Blueprint

References added: https://www.femke.design/researchreport 
Slide deck: https://drive.google.com/file/d/13BQa_5pf-BWakmKN0ve7aa0ZHH6J3xfm/view?usp=sharing

Research Report outline doc: [fill this in directly](https://docs.google.com/document/d/1MhO3A1YTDPpTDULUtaWZ-Edk6ijI4V53ix_9AE_Jbis/edit)

**Comment by kande81** [comment]
The following slides have been filled:

- Personal statement generator tool
- Next Steps
- Anticipated future iterations
- Potential new trajectory for record clearance projects

**Comment by TierneySadowski** [comment]
Ecosystem slides are mostly done pending any changes or additions from previous C+C analyses (if we can find them)

I'll be working on updating the service design guide to match our style.

**Comment by myrandi** [comment]
4 sections remain (plus visuals for an updated service blueprint).

Next steps after remaining sections are completed (text added), we will assign tasks to merge text with visuals onto slide deck.
