### ISSUE TITLE
Offboarding PM: Analicia

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1513]
### Overview

We need to have a checklist of items to do when a product manager onboard and offboards so that the process can be consistent and fast.

### Member Info

name: Analicia Mejia Mesinas
role: Research PM
github: amejiamesinas

#### Offboard
  - [x] 1password setup
    - [x] remove from team vaults
       - [x] Expunge-Assist
       - [x] Zoom vault
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [x] GitHub
     - [x] demote member to read only team and remove from write team
     - [x] if previously maintainer, change role in read only team to member only
- [x] Figma
  - [x] remove from team
- [x] Help them delete the desktop shortcut to email address if they made one.
- [x] Remove from email address(s)
   - [x] expungeassist@hackforla.org
- [x] Go over the person's assigned Github issues and Close or Reassign them
- [x] submit ticket to website team to amend EA project leadership 
   - https://github.com/hackforla/website/issues/7321
- [x] Remove PM Admin Access on VRMS

### Resources/Instructions

- 1password.com
- [Expunge Assist Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n?usp=sharing)
- [Expunge Assist Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
- Check public and 2FA at [people page](https://github.com/orgs/hackforla/people)
- [Expunge Assist GitHub Team URL](https://github.com/orgs/hackforla/teams?query=expunge)
  - [base (read)](https://github.com/orgs/hackforla/teams/expunge-assist/members)
  - [write](https://github.com/orgs/hackforla/teams/expunge-assist-write/members)
  - [maintain](https://github.com/orgs/hackforla/teams/expunge-assist-maintainers)
  - [admin](https://github.com/orgs/hackforla/teams/expunge-assist-admins/members)
- [Website Team Project Update Request](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2Crole%3A+back+end%2FdevOps%2Crole%3A+front+end%2CComplexity%3A+Small%2Csize%3A+0.5pt%2Ctime+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- Tutorials
  - [Forward emails to team members](https://github.com/hackforla/product-management/wiki/Forward-emails-to-team-members)

**Comment by sydneywalcoff** [comment]
**Progress:** Waiting for the Website team to complete their issue
**Estimated Time to Completion (ETC):** Unsure. Currently in prioritized backlog.
**Blockers:** Website team capacity.

**Comment by mariaweissman** [comment]
Marking as closed, as we completed all of the steps
