### ISSUE TITLE
Make Welcome page background white

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#1525]
### Overview
The Welcome page on expungeassist.org is '#F7EBFF' whereas on Figma it is '#FFFFFF'. Please update the background of the Welcome page to '#FFFFFF'

|.         Website(incorrect)        |        Figma Wireframes(correct)      |
| --------------------------| ---------------------------------|
| <img src="https://github.com/user-attachments/assets/dfde3afa-675d-4569-ac13-208ecfe4ea5c" width="350" height="200"> | <img src="https://github.com/user-attachments/assets/4a6c81fe-a824-41bb-b6e7-c70701e81281" width="300" height="200">

### Action Items
- [x] Change the background color to #FFFFFF

### Resources/Notes
[Figma Design](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=8543-105399&t=91qpXWSorh218F6b-4)

**Comment by eburdekin** [comment]
@sydneywalcoff @anitadesigns looking at the  [mobile wireframes](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=10591-106214&t=dk55lbF6oMnMEnZf-4) for #1558, I noticed the Welcome background is meant to be pink on mobile
