### ISSUE TITLE
fix Affirmation timing

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#154]

**Comment by sarahyaepark** [comment]
Can we groom this ticket a little more?

**Comment by aahvocado** [comment]
@sarahyaepark Hah, yeah. This is just something that @alexchoiweb noticed where because of the timing of the state change, the affirmation popup could sometimes show up _after_ the page changed already.

**Comment by alexchoiweb** [comment]
Oh actually I think I just understood what this ticket was actually about - the ghost flicker of the Step page before the Affirmation popup shows up. Will try to work on this before this week's meeting
