### ISSUE TITLE
resolve Material UI errors

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1546]
### Overview
Since Github changed the Node version they use to run Github actions from Node18 to Node20, we're getting some warnings and errors across the app.

It looks like Material UI has deprecated 'globals'. 

### Action Items
- [ ] make sure you are running Node v20.16
- [ ] identify the cause of the error
- [ ] resolve error
- [ ] test against live site to make sure styles are still correctly applied
   - [ ] landing page
   - [ ] FAQs
   - [ ] 404
   - [ ] About Us
   - [ ] Credits
   - [ ] Privacy Policy
   - [ ] Terms of Use
   - [ ] The Letter Generator
      - [ ] Welcome
      - [ ] Before you Begin
      - [ ] Advice
      - [ ] The LG (these all use the same layout)

**Comment by eburdekin** [comment]
@sydneywalcoff noting here too - for this error we're seeing on the routing tests PR #1466 

![Screenshot 2024-09-23 at 7 01 43 PM](https://github.com/user-attachments/assets/83390546-6b0c-462d-9da6-68c5c4d50f83)

we can resolve by updating customMuiTheme.ts from this:
![Screen Shot 2024-09-29 at 5 03 47 PM](https://github.com/user-attachments/assets/22e1f12a-750c-42da-a120-b676d6f3db2c)
to this:
![Screen Shot 2024-09-29 at 5 03 28 PM](https://github.com/user-attachments/assets/d9fb1449-98cc-4562-b35d-6f158000d223)

that's already the case on `dev` so I'll close this issue
