### ISSUE TITLE
resolve eslint warnings

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1547]
### Overview
Since Github changed the Node version they use to run Github actions from Node18 to Node20, we're getting some warnings and errors across the app.

esLint is giving us warnings we weren't getting previously.

### Action Items
- [ ] make sure you are running Node v20.16
- [ ] identify the cause of the error
- [ ] resolve error

**Comment by hasham-qaiser** [comment]
Sydney nor I could recreate the esLint errors that were appearing so this issue is closed
