### ISSUE TITLE
spike: research google analytics

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#155]
Product has asked to see if we can get Google Analytics into the app. Seems like the first pass will be to see how far users reach while filling out the form.

## Acceptance Criteria
Document Privacy concerns and what goes into implementation

**Comment by yumengluo** [comment]
Dependency: need users's data to conduct this task

**Comment by brandohayes** [comment]
We are interested in seeing how far the user reached in the form vs their personal data.
