### ISSUE TITLE
Optimizing Weekly Label Check GHA

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#1555]
### Overview
While fixing a bug related to the Weekly Label Check, some opportunities for improvement have been identified. 

1) When the action fails, it just prints the error in the console and continues on and will 'pass' when it's finished. Rather than have it continue, the action should fail.

2) The action doesn't currently inform anyone debugging how many issues have successfully been labeled after the action runs. Let's add a counter that prints how many issues were updated at the end of the script. 

3) [Lines 91-93](https://github.com/hackforla/expunge-assist/blob/169113b4b18c52e3a2e76193de0e68f54290fc68/.github/workflows/scripts/weekly-label-check.js#L91) are incorrect. Currently it shows the 'successful' text regardless of if the POST action to OctoKit was successful, and instead based on if there were any labels to be added to an issue. Update this logic to be dependent on the successful POST request to OctoKit.

### Action Items
- [x] action should fail if there are errors
- [x] add affected Issues counter
- [x] update 'Success' logic on lines 91-93

### Resources/Notes
[Testing GHAs Locally](https://github.com/hackforla/expunge-assist/wiki/Testing-Github-Actions-Locally)
[Weekly Label Check file](https://github.com/hackforla/expunge-assist/blob/main/.github/workflows/scripts/weekly-label-check.js)

**Comment by whitneywind** [comment]
I have finished the second and third action items and will finish as soon as I clarify the details of the first one
