### ISSUE TITLE
Landing page h2 font size on mobile doesn't match Figma designs

### ISSUE THREAD

**Issue by eburdekin** [hackforla/expunge-assist#1558]
### Overview
Our landing page section header (`h2`) font size on mobile is larger than it is in the Figma designs.

### Action Items
- [ ] Update header styling to match Figma designs

### Resources/Notes
[Figma designs](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=10591-106214&t=dk55lbF6oMnMEnZf-4)

**Comment by anitadesigns** [comment]
@sydneywalcoff Def something to fix. I added the link to the design
