### ISSUE TITLE
Lead Dev Role for Expunge Assist

### ISSUE THREAD

**Issue by thomasdemoner** [hackforla/expunge-assist#1559]
<img src="https://user-images.githubusercontent.com/78319934/129253133-b41b4aa6-accc-4521-b769-000c1e39a46b.png" />

**Project Name**: Expunge Assist

**Volunteer Opportunity**: Lead Developer. React fluency required, tech lead experience preferred.

Our web application is nearly ready to launch, and we need some assistance working through the final tasks before launch and someone who is ready to take leadership of the team post-launch as we proceed with incremental iterations. Our application is written with Typescript and uses react-router. It's not a problem if you're not fluent in these libraries, we will work with you to make you comfortable with your implementation.

**Duration**: Open-ended

**Meeting times**: Mondays at 5pm, Thursdays at 6 pm PST

**Who to communicate your interest to**
 - Slack channel link: [#expunge-assist](https://hackforla.slack.com/archives/CN8NXTPK5)
 - Slack name of person to contact in the channel: Daniel Xiao, Thomas Demoner

[Read more about the project](https://www.hackforla.org/projects/expunge-assist)
[Github Page](https://github.com/hackforla/expunge-assist)

**Comment by ExperimentsInHonesty** [comment]
Not sure why this issue got opened over at the engineering community of practice but I am moving it to EA where it  belongs.
