### ISSUE TITLE
Change Welcome page background back to #F7EBFF on mobile

### ISSUE THREAD

**Issue by eburdekin** [hackforla/expunge-assist#1564]
### Overview
We [recently updated](https://github.com/hackforla/expunge-assist/issues/1525) the background for the Welcome page from '#F7EBFF' to '#FFFFFF' across devices, but upon reviewing the Figma designs, it should have stayed '#F7EBFF' on mobile.

|    | **Currently live**       | **Figma wireframes**        |
| ------------- | ------------- | ------------- |
| **Desktop (correct)** | ![Screen Shot 2024-09-23 at 7 28 15 PM](https://github.com/user-attachments/assets/3b6f21de-8aa2-4c3c-a7fe-563dfcaa2347) | ![Screen Shot 2024-09-23 at 7 25 31 PM](https://github.com/user-attachments/assets/96e69254-b08a-4f0e-a425-fdea4cdd0720) |
| **Mobile (incorrect)**| ![Screen Shot 2024-09-23 at 7 30 23 PM](https://github.com/user-attachments/assets/3b389d56-396b-4f3d-a20d-bad49973e879) | ![Screen Shot 2024-09-23 at 7 27 12 PM](https://github.com/user-attachments/assets/b1080442-ab4e-4ff4-9fad-5ec772f66d53) |

### Action Items
- [x] Update styling for Welcome page on mobile - can probably reuse/update the useEffect that was removed with the previous branch [here](https://github.com/hackforla/expunge-assist/pull/1548/files)

### Resources/Notes
- [Figma wireframe - desktop](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=8543-105399)
- [Figma wireframe - mobile](https://www.figma.com/design/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=10591-106214&node-type=frame)

**Comment by anitadesigns** [comment]
Thanks for catching this @eburdekin ! This is a detail that fell through the cracks where Design forgot to update the background on the mobile wireframes. Everything on the website is correct! 

@sydneywalcoff Im going to change the role to Design so we can take care of it

**Comment by anitadesigns** [comment]
Design updated the mobile wireframe's background color to white!
