### ISSUE TITLE
UXR exercise - input for FAQ legal advice

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#1598]
### Overview
UXR has indicated that some parts of the FAQ can be construed as legal advice. It is important we do not have legal advice on our website. This is the first step in improving the FAQs.

### Action Items
- [x] Discuss in UXR and make a plan/divide tasks
- [x] Fill in exercise on FigJam https://www.figma.com/board/DQcMAN49OUsCieINIZbAh0/UXR-FigJam-board---Expunge-Assist?node-id=1177-5860&t=l6sQxDWz8GCG5TVr-4
- [x] Hand over to Content

### Resources/Notes
FigJam exercise https://www.figma.com/board/DQcMAN49OUsCieINIZbAh0/UXR-FigJam-board---Expunge-Assist?node-id=1177-5860&t=l6sQxDWz8GCG5TVr-4

**Comment by raeraeicky** [comment]
Hey @SamHyler! What's been flagged as legal advice already exists in [this doc](https://docs.google.com/spreadsheets/d/1U4gCR8a0MyRcI232Q2Yxi3Gxp9AstXQ2ZkEsxC4hZDE/edit?gid=0#gid=0). the FAQ content starts at row 26 / Page ID 2.0 and continues through row 40 / Page ID 2.3.4. The specific FAQ called out as legal advice are row 36 (Page ID 2.3.0, How does Proposition 47 help me?) and row 39 (Page ID 2.3.3, How is Proposition 47 different from Proposition 64?), and comments are in column K as to why. 

As far as handoff, let me know if a comment here with the specifics works, or if a different format is preferred.

**Comment by SamHyler** [comment]
> Hey @SamHyler! What's been flagged as legal advice already exists in [this doc](https://docs.google.com/spreadsheets/d/1U4gCR8a0MyRcI232Q2Yxi3Gxp9AstXQ2ZkEsxC4hZDE/edit?gid=0#gid=0). the FAQ content starts at row 26 / Page ID 2.0 and continues through row 40 / Page ID 2.3.4. The specific FAQ called out as legal advice are row 36 (Page ID 2.3.0, How does Proposition 47 help me?) and row 39 (Page ID 2.3.3, How is Proposition 47 different from Proposition 64?), and comments are in column K as to why.
> 
> As far as handoff, let me know if a comment here with the specifics works, or if a different format is preferred.

Thanks @raeraeicky ! If you could just fill it in the Figjam, then we can make quick work of the handover. Thanks!

**Comment by raeraeicky** [comment]
@SamHyler Done! To keep this simple and not re-do work, I added the info on why this could be construed as legal advice to FigJam, and only focused on the FAQ where this was an issue.

**Comment by raeraeicky** [comment]
@SamHyler Done! To keep this simple and not re-do work, I added the info on why this could be construed as legal advice to FigJam, and only focused on the FAQ where this was an issue.
