### ISSUE TITLE
Update project name across accounts & materials

### ISSUE THREAD

**Issue by ggrrettcchhenn** [hackforla/expunge-assist#164]
### Overview
We are changing the name of Hack for LA's Record Clearance Project to something that is unique to our brigade. Once we determine the final name and buy a new domain, we will have to change our materials to reflect the new name.

### Action Items
- [x] Gmail account - Admin
    - [x] Set up email forwarding from recordclearance@hfla to expungeassist@hfla - PM
- [x] 1Password - Admin
- [x] Slack - Admin
- [x] GitHub repo - Admin
    - [x] README - PM
    - [x] Wiki - PM
- [x] Google Drive folder - PM
   - [x] One Sheet - PM
   - [x] Onboarding - PM
   - [x] Team Roster - PM
   - [x] Research Report - PM
- [x] Twitter
    - [ ] change login email
- [x] Instagram
    - [ ] change login email
- [x] LinkedIn
    - [ ] change login email
- [x] Facebook
    - [ ] change login email
- [x] Miro - PM
    - [ ] change login email
- [x] [Figma ](https://www.figma.com/file/t1lW4Tm0Lp3jFdeOCd98b1/Expunge-Assist?node-id=214%3A33)
- [x] Logo - Designer
- [x] Website - [Github request](https://github.com/hackforla/website/issues/1249)
- [ ] VRMS - Github request

### Resources/Instructions
Links to most of these at project inventory: https://github.com/hackforla/product-management/issues/79

**Comment by ggrrettcchhenn** [comment]
Our new project name is **Expunge Assist**.

We polled the HFLA community and asked them to rank 6 names in March 2021 and received 63 survey responses. Expunge Assist got the most votes for rank 1 (18 votes), and after conducting instant runoff analysis, Expunge Assist and Record Assist nearly tied. We then connected on 3/14/21 with our primary stakeholder, Bo Money of NDICA, who preferred Expunge Assist because of its clarity – our tools assist with expungement.

**Comment by ggrrettcchhenn** [comment]
@ExperimentsInHonesty @Olivia-Chiong could you please help us change our project name from Record Clearance Project to Expunge Assist on the following platforms?

- [ ] **Gmail** - expungeassist@hackforla.org
- [ ] **GitHub repo** - expunge-assist
- [ ] **1Password** - Expunge Assist
- [ ] **Slack channel** - #expunge-assist

**Comment by myrandi** [comment]
Figma updated

**Comment by ggrrettcchhenn** [comment]
![LOGO](https://user-images.githubusercontent.com/27507664/113653805-61a74d80-964b-11eb-8605-74ed45e5c655.png)
logo from Figma: https://www.figma.com/file/t1lW4Tm0Lp3jFdeOCd98b1/Expunge-Assist?node-id=2289%3A10357

**Comment by ggrrettcchhenn** [comment]
The VRMS team has not responded to our requests to update our name & meeting times – I think that they are on hiatus. We can consider this issue resolved, even though it's not updated on VRMS, because that is outside of our control.
