### ISSUE TITLE
Conduct comparative analysis

### ISSUE THREAD

**Issue by ggrrettcchhenn** [hackforla/expunge-assist#166]
### Overview
Take an inventory of comparative / competitive products so that we have a clear idea of what other products exist in our ecosystem and what features they have to offer.

### Action Items
- [ ] Use [template](https://docs.google.com/spreadsheets/d/1F1UpeIzlhsY23ETjNPi1yzov45XijP79c5LPAITwBho/edit?usp=sharing) to list out the Record Clearance Project's personal statement generator's features and compare it to other products in the same category

### Resources/Instructions
Slides 15 & 16 of the [PSG Research Report](https://drive.google.com/file/d/13BQa_5pf-BWakmKN0ve7aa0ZHH6J3xfm/view?usp=sharing) include Criminal Justice & Personal Statement Generator comparative analyses

**Comment by yumengluo** [comment]
This tasked was completed.
