### ISSUE TITLE
Research Summary - Sticky-notes from NDICA

### ISSUE THREAD

**Issue by H1Angela** [hackforla/expunge-assist#17]
### Overview
Given the amount of data available we need a summary of the Sticky-notes from NDICA document and research on the record clearance project. 

### Action Items
Review the following doc:
- [ ] [Sticky-notes from NDICA](https://docs.google.com/spreadsheets/d/1TEA98jfHOedm86WIXG9HrOwXVZMh5heqsUX18GDBzpI/edit?usp=sharing)

#### Follow the format:
   - Who/What?
     - Who wrote this, in what context when?
   - General Contents
      - What is the main theme or sense of the content?
   - Key insights
      - What did you learn that you haven't seen before? Where there any unique points? Did you find any commonalities or trends?

### Resources/Instructions
[The Google drive link](https://drive.google.com/drive/u/0/folders/1hBhOeNyjjEaHcWAKSu9eW--FF9HnKNqe)

Research Summary [Link](https://docs.google.com/document/d/1oUgN7vT0M-nkMBj68ugPOvvZSgngkL8aRMfX2zF9olk/edit?usp=sharing)
- Your summary should be in the link above

**Comment by sylvia-nam** [comment]
From earlier team with previous partner; part of archive to reference but no actionable steps now
