### ISSUE TITLE
Create scripted contextual inquiry + interview guide for expungement clinic workers

### ISSUE THREAD

**Issue by myrandi** [hackforla/expunge-assist#173]
### Dependencies
#189 

### Overview & Background Information
UX team members assigned to specific sections of the guide. [Find CI - Interview Guide doc here](https://docs.google.com/document/d/1LTquUA-l_YNo7-yq-bfjOEFBdRTpcTlUnjAsCCk8k5o/edit).

See also: Sahiba's [doc on Contextual Inquiry & remote research during COVID](https://docs.google.com/document/d/1SaHFgTJuwp8SieKOJdz2JT0siDXVD6zS7ms03_slBkA/edit)

This folder with [Strategies for Qualitative Interviews PDF](https://drive.google.com/drive/folders/1kqcBQsema5i5lsw2Ag9Tb0-CwhoWwaqQ) is also a great interview scripting resource.

### Actions
Task: write scripts to open each section as well as bulleted guiding and probing questions that help us achieve learning goals at each step of the interview.

As discussed, leave room for flexibility so that we can get to know their process (we want them to talk openly!), but always bring the participant back to our learning goals.

When you have completed the script for your section(s), please add a comment on github with your progress and check off your section box below:

- [x] Overview: CI - [[Phase 2 Research Overview doc](https://docs.google.com/document/d/1DpyHXaQ43DRzfpsiFU2IroPNkjZDh94Mss-uTU_pIqA/edit#)] - updated

- [x] Section II. Introductions - Andan

- [x] Section III. Demographics - Andan

- [x] Section IV. Interview portion (global/general questions) - Gretchen

- [x] Section V. Task walk-thru - Myranda

- [x] Section VI. Closing - Gilles 

- [x] Transition + Prototype Demo (+5 second test) - Gilles

-----

Next steps:

- [x] Consolidate questions & clean up text by Wednesday March 10 at 11:59pm - @myrandi 
- [x] Make comments on ways we can shorten the interview sections @emmacosluo 
- [x] Make comments on ways we can shorten the interview sections @apurvabarve

**Comment by kande81** [comment]
Completed the closing section

**Comment by Andan-Eddy** [comment]
completed section II question about section III

**Comment by kande81** [comment]
added a possible transition to prototype demo. Open for feedback.

**Comment by myrandi** [comment]
Consolidated and transferred questions onto a new doc: [Interview Guide: overview and script](https://docs.google.com/document/d/1ui4TolyYjHp67H_Z1mkjvW9-tTFrSPe6F96am0SszaY/edit#)

Next step: Apurva will use this to transfer Interview Guide onto a Google Form.

**Comment by emmacosluo** [comment]
Hi,
I found a useful interview guide for the research. 
[interview_strategies.pdf](https://github.com/hackforla/record-clearance/files/6135876/interview_strategies.pdf)
