### ISSUE TITLE
Consolidate & Update Google Drives

### ISSUE THREAD

**Issue by ggrrettcchhenn** [hackforla/expunge-assist#185]
### Overview
There are two Google Drives for the Record Clearance Project, but we should have just one that is connected to the greater Hack for LA Drive so that the org doesn't risk losing our project information.

### Action Items

- [x] Add all current team members to primary drive
- [x] Take [inventory](https://docs.google.com/spreadsheets/d/1zrHuEa3q_Fyb2KiWxTBi5LxP-WN4pzLTiZprt0B77Z4/edit?usp=sharing) of what folders exist in both drives
- [x] Identify appropriate file structure for primary drive
- [x] Archive and/or delete targeted/repeating/redundant files from secondary drive
- [x] Move unique files from secondary drive into primary drive
- [x] Rename files as appropriate to meet [Communication Style Guide](https://github.com/hackforla/record-clearance/issues/167) file naming standards (style guide in progress)
- [x] Rename primary drive to current project name - **Expunge Assist**

### Resources/Instructions

- [Primary Drive – currently called record-clearance](https://drive.google.com/drive/folders/1hBhOeNyjjEaHcWAKSu9eW--FF9HnKNqe?usp=sharing)
- [Secondary Drive - called The Record Clearance Project](https://drive.google.com/drive/folders/1oYfLSlWZNZ4ezpNJV2N1eXnC_nDcQ0QX?usp=sharing)
- [Communication Style Guide issue #167 ](https://github.com/hackforla/record-clearance/issues/167)
- [Google Drive Inventory](https://docs.google.com/spreadsheets/d/1zrHuEa3q_Fyb2KiWxTBi5LxP-WN4pzLTiZprt0B77Z4/edit?usp=sharing)

**Comment by ggrrettcchhenn** [comment]
**Proposed file naming conventions:**

- **Start each file with the creation date in YYYYMMDD format.** This format makes sure all of your files stay in chronological order, even over the span of many years.
- **When using a sequential numbering system, use a leading zero** for clarity and to make sure files sort in sequential order. For example, use "01, 02, ...10, 11, etc." instead of "1, 2, ...10, 11, etc."
- **Add version information to the end of the file name** to track versions of a file, e.g. filename_v02.xxx
- References:
    - https://library.stanford.edu/research/data-management-services/data-best-practices/best-practices-file-naming
    - https://datamanagement.hms.harvard.edu/collect/file-naming-conventions

**Comment by myrandi** [comment]
Made comments and recommendations onto onto [Secondary Drive](https://docs.google.com/spreadsheets/d/1zrHuEa3q_Fyb2KiWxTBi5LxP-WN4pzLTiZprt0B77Z4/edit#gid=957474680)

Please review and add a comment with questions/suggestions below:

- [ ] @Andan-Eddy 
- [ ] @ggrrettcchhenn 

I will make adjustments to Research files on the secondary drive accordingly once the comments are reviewed.

**Comment by ggrrettcchhenn** [comment]
Thank you @myrandi ! I replied to some of your comments in the sheet but I agree with your assessments.

**Comment by myrandi** [comment]
Update: 

- [ ] Adjustments made to research files; reorganized and consolidated further

Next: 

- [ ] I am in the process of updating the Secondary tab on the [inventory Google Sheet.](https://docs.google.com/spreadsheets/d/1zrHuEa3q_Fyb2KiWxTBi5LxP-WN4pzLTiZprt0B77Z4/edit?usp=sharing)

**Comment by myrandi** [comment]
Finished updating Secondary tab. Files should now be ready for transfer onto the correct Drive.

**Comment by ggrrettcchhenn** [comment]
Went through secondary drive and renamed and organized folders and files according to the [inventory sheet](https://docs.google.com/spreadsheets/d/1zrHuEa3q_Fyb2KiWxTBi5LxP-WN4pzLTiZprt0B77Z4/edit?usp=sharing). When I finished that, I invited all active team members to the primary drive and moved all of the folders from the secondary drive into the primary. I then consolidated the folders from both drives according to the inventory sheet and deleted any duplicate files.

I gave dates to as many files as I felt made sense. Some living documents are continually used for years, like the Team Roster, Onboarding Doc, etc. and date created does not apply. Other documents may have a YYYY or YYYY-MM date if it was used & edited over weeks or months (or I just didn't know the exact date it was made). This naming structure sorts the docs well, and it makes it easier to find docs from a given time because you can search "2021-02" to find all dated docs from that month, for example.

I updated the Google Drive links in the README and project wiki.
