### ISSUE TITLE
Discovery research on potential partner organizations

### ISSUE THREAD

**Issue by myrandi** [hackforla/expunge-assist#186]
### Overview
We need to understand our potential partners in order to find ways to initiate connections and develop plans for sustainable relationships. We will use the information collected through online searches to inform our outreach strategy.

### Action Items
Fill out [THIS OUTLINE](https://docs.google.com/document/d/1NsZbG3GcDsK3TRLP5SFbGgjRFoQcw5fUAvXoorH3D80/edit) with relevant information (add additional sections as needed). Use search engines and social media to get background information, look up key contacts, the org's vision and projects, and so on.

- [x] @TierneySadowski - 1. Youth Justice Coalition
- [x] @emmacosluo - 1. Neighborhood legal services of Los Angeles (NLSLA)
- [x] @apurvabarve - 1. Justice LA
- [x] @kande81 - 1. Legal Aid Foundation (LA); 2. Homeboy Industries
- [x] @Andan-Eddy - 1. Californians United for a Responsible Budget (CURB
- [x] @yumengluo 1. UCLA School of Law [Critical Race Studies Program](https://law.ucla.edu/academics/centers/critical-race-studies/race-and-re-entry-initiative) (Race & Reentry); 2. [El Centro reentry (expungement) legal clinic](https://law.ucla.edu/life-ucla-law/student-organizations/el-centro-legal-clinics#) 

### Resources/Instructions
Use [this contact list](https://docs.google.com/spreadsheets/d/19bmYK3PpNIiVI_YzSplRf3C0dl6dbjDnmRjvqXG5vWg/edit?usp=drive_web&ouid=109979492177025079714) to see the information we have, but check the existing information. If different from information in this sheet, please do not change this sheet. Instead, fill out the outline with the correct informaiton.

**Comment by kande81** [comment]
Legal aid foundation, and homeboy industries partnership information data entry is completed.
