### ISSUE TITLE
Discovery research on potential government partners

### ISSUE THREAD

**Issue by myrandi** [hackforla/expunge-assist#190]
### Overview 
Preliminary research will be conducted using websites, social media (etc) to map out best ways of contacting public figures and offices, along with how they might be able to partner with Expunge Assist. Findings will be used to inform our <in progress> partnership outreach plan.

### Background
On March 23, 2021, we held a discussion on how to translate our previous outline (used to research potential partner organizations) to collect necessary information at the local govt level.

### Action Items 
- [x] Gretchen will [format new outline](https://docs.google.com/document/d/1qg1SyaXdql8sdC_ejlmdhHb-rcqwpORVgcRFH-S9TcY/edit) according to discussion
- [x] Identify offices and persons with whom we should research for potential contacts
 - - [ ] Los Angeles DA (Gascon) - @yumengluo [details](https://docs.google.com/document/d/1qg1SyaXdql8sdC_ejlmdhHb-rcqwpORVgcRFH-S9TcY/edit#bookmark=id.sd9zczf25nag)
 - - [ ] LA County Pub Def Office - @apurvabarve 
 - - [ ] Los Angeles (City) Mayor - focus on reasons for non-support
 - - [ ] Los Angeles City Attorney: Mike Feuer

**Comment by yumengluo** [comment]
The research on Los Angeles DA (Gascon) is finished.

**Comment by ExperimentsInHonesty** [comment]
yumeng estimates it took her about 4 hours.

**Comment by sylvia-nam** [comment]
Revisit outreach to potential partners following Stakeholder Review
