### ISSUE TITLE
Review revised one sheet

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#204]
### Overview
The ExpungeAssist one sheet needs to updated with new logo. However, prior to that there needs to be a quick review of edited ExpungeAssist one sheet. 

### Action Items
Expunge Assist one sheet edits needs approval or rejection edits.  

### Resources/Instructions
https://docs.google.com/document/d/1JFZGKxeEBWVak_GATgIt0Knyr9_gJ15CBirynebb4tg/edit

**Comment by myrandi** [comment]
all set @Andan-Eddy
