### ISSUE TITLE
Update desktop frames

### ISSUE THREAD

**Issue by myrandi** [hackforla/expunge-assist#213]
### Overview
Update and make Figma desktop design frames consistent

### Action Items
- [x] Adjust spacing
- [x] Adjust button placement
- [x] Check that format is correct 

### Resources/Instructions
[Figma: Desktop new components](https://www.figma.com/file/t1lW4Tm0Lp3jFdeOCd98b1/Expunge-Assist?node-id=2417%3A10379)

**Comment by daniellerubio** [comment]
just worked on updating the frames for the first 2 steps, need to do the rest

- created columns and rows
- established consistent navigation, header, secondary navigation

There are some small details re: typography, button height, etc. that are not cleaned up
However, for the purpose of this project, I'll leave them as is - they'll work for this initial goal
Once we have more established designs, I'll clean them up to be "regulation"

Also, I'd recommend doing simple grey scale wireframes if we're using these for usability tests - but understand that the developers are currently coding the high fidelity version, so I'll clean up these screens for now

@myrandi

**Comment by daniellerubio** [comment]
all set for the desktop frames! there are some minor spacing issues that I didn't have time to clean up, but the overall, larger spacing issues are nailed down. biggest thing was developing a standard grid and resizing some elements to be desktop friendly. can talk more on our 1:1. sorry i can't join the team ux meeting this week.

**Comment by daniellerubio** [comment]
@myrandi ready for review
