### ISSUE TITLE
Organize Figma file

### ISSUE THREAD

**Issue by daniellerubio** [hackforla/expunge-assist#219]
### Dependencies
#242 

###Overview
Organize the Figma file so that it's easy to navigate

### Action Items

- [x] Time-sensitive: Look into upcoming Figma update and how those changes can affect team's access
- [x] Audit the figma file
- [x] Research best practices for organizing figma files
- [x] Reorganize and provide help text documenting what each page should be used for
- [x] Add multiple pages to Figma file (based on what I find out about the incoming Figma update)

**Comment by anitadesigns** [comment]
new issue --- > #639
