### ISSUE TITLE
utilize the new expunge assist domain name

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#220]
expungeassist.org
expungeassist.net
expungeassist.com

Have all been acquired to be used for the project (with the .org one being the primary). I want to know if the github hosted page at https://hackforla.github.io/expunge-assist/ can used with our domain name.

If not, let's have the domain url redirect to the github.io page.

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages

**Comment by alexchoiweb** [comment]
This article seems promising: https://hossainkhan.medium.com/using-custom-domain-for-github-pages-86b303d3918a#:~:text=Go%20to%20your%20GitHub%20Pages,Don't%20delete%20it.

Requested domain name register access

**Comment by ggrrettcchhenn** [comment]
Bonnie updated the domains to point to our github pages site this afternoon, around 1 pm PST. It should take about 24 hours to resolve. She just did the expungeassist.org and the other two are forwarded to it. That way, no matter what someone types they still end up at the .org

**Comment by ggrrettcchhenn** [comment]
The custom domain hasn't resolved to the github pages site. We should use this guide to troubleshoot it: https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages
