### ISSUE TITLE
edits to figma latest designs > mobile presentation slides

### ISSUE THREAD

**Issue by myrandi** [hackforla/expunge-assist#232]
### Overview
Edit Figma slides to clean up demos and presentation to be more concise and content-focused.

### Action Items

- [x] Edit landing page to say "4 steps" instead of 20 minutes
- [x] Move pop-up on slide 4 to the previous screen (slide 3) so that it does not interrupt written tasks; also look for other instances, and move those as well.
- [x] Remove slides x, y, z from  demo; may need to make a copy of entire flow and create a new page for slides - I'll leave this decision up to you
- [x] Look for other opportunities to make the presentation cleaner
- [x]  Removed the connection to the "none of the above" slide, removed it from the flow

### Resources/Instructions
[Figma latest designs > mobile presentation slides](https://www.figma.com/proto/t1lW4Tm0Lp3jFdeOCd98b1/Expunge-Assist?node-id=805%3A5401&scaling=scale-down&page-id=805%3A5266)

**Comment by daniellerubio** [comment]
Changes:

- slide 12: removed delayed forced advance to next screen to improve accessibility; replaced w/ delayed "continue" button that user will click to advance to the next screen
