### ISSUE TITLE
Map out research goals and instruments with UCLA law students

### ISSUE THREAD

**Issue by myrandi** [hackforla/expunge-assist#246]
### Overview
Work on refining the two ways UCLA law students will help us achieve our research goals:

1. Help us validate the existing product’s content: metrics, legal standing, language used… 
2. Help us conduct usability testing during the clinics by performing simple tests and observations related to product use

### Action Items
- [x] **Product validation:** write out all of the ways their experiences as legal experts with direct experience in expungement clinics can help us to refine the existing product (research goals + how we will strategically get this information)
- [x] **Usability testing:** Identify 2-3 usability tests that would likely be useful to teach law students to obtain the data we need (they do not need to be what we will ultimately use, but will get us to start thinking about the data we need to collect and how we will get them to obtain the data through observations and simple tests).
 - - [x] Map out research goals (what these tests will help us understand/test), and figure out the logistics of teaching these tests to law students.

### Resources/Instructions
Add documentation here from the Expunge Assist Google Drive research folder(s)

**Comment by pyachauhan** [comment]
Not working on phone 📱

Could you please UNSUBSCRIBE me?

Thank you 🙏🏻

**Comment by myrandi** [comment]
Hi @pyachauhan, it looks like [you are subscribed because you follow the earlier version of this](https://github.com/hackforla/expunge-assist/watchers), which was The Record Clearance Project. Please click on your Watchlist and try to unfollow the project. Let me know if that helps. Thanks!

**Comment by pyachauhan** [comment]
i am very confused. we can let it be -- ever since pandemic been MIA for
HFLA.

please help clarify.

why does this include UCLA law students

[image: 155917317_903005977176619_6306337101472968303_n.jpg]
