### ISSUE TITLE
Contact potential partners

### ISSUE THREAD

**Issue by apurvabarve** [hackforla/expunge-assist#251]
### Overview
We need to start reaching out to expungement clinics in Los Angeles for the purpose of securing research-focused partnerships.

### Action Items

- [x] Select two partners/clinics to contact
- [x] Send initial contact email
- [ ] Send follow-up contact email (if there are no responses after 3-4 business days)

### Resources/Instructions
The outreach email and follow-up email is can be found [https://docs.google.com/document/d/1rS8Dr5-HHSud5e7W3R-RDVVw-PKaM-WOWDUrx2-vyng/edit#](here)

**Comment by yumengluo** [comment]
This task is finished.
