### ISSUE TITLE
Update logo on Figma desktop designs

### ISSUE THREAD

**Issue by ggrrettcchhenn** [hackforla/expunge-assist#255]
### Overview
The desktop designs in Figma still have the Record Clearance Project logo. Please update the logo to reflect our project's new name, Expunge Assist.

### Action Items

- [x] Update white text logo (already updated on mobile design)
- [x] Update black text logo

### Resources/Instructions
[Figma prototype](https://www.figma.com/file/t1lW4Tm0Lp3jFdeOCd98b1/Expunge-Assist?node-id=214%3A33)

**Comment by TierneySadowski** [comment]
Updated header component and fixed alignment issues. Moved the desktop FAQ screens to the appropriate part of the figma file, and added new active states. TBD if the new states are feasible for this release.
