### ISSUE TITLE
Fix project website image

### ISSUE THREAD

**Issue by ggrrettcchhenn** [hackforla/expunge-assist#268]
### Overview
The image for Expunge Assist on the HFLA website is the wrong size. Please update the image with something more cohesive with our branding, that does not include the name of our project in the image.

### Action Items

- [x] Create a cover image for Expunge Assist, 600x400 pixels
- [x] Comment image on the [relevant ticket in the website repo](https://github.com/hackforla/website/issues/1500), or Slack the image to Gretchen Howard on Slack to comment on the relevant ticket

### Resources/Instructions

- https://github.com/hackforla/website/issues/1500
- [Expunge Assist Page](https://www.hackforla.org/projects/expunge-assist) – See how having the project name in our image creates a double title effect on the project page
- [Project Page](https://www.hackforla.org/#projects) – Take a look at the types of images that other projects use

![image](https://user-images.githubusercontent.com/27507664/119534362-a9894d80-bd3b-11eb-9630-721b821cfd0f.png)

**Comment by Sihemgourou** [comment]
Hello ! 
@nansah nansah

@TierneySadowski TierneySadowski

@rcurtis2 rcurtis2

Please add update
1. Progress
2. Blockers
3. Availability
4. ETA
