### ISSUE TITLE
Create an interview guide for process mapping (A New Way of Life)

### ISSUE THREAD

**Issue by apurvabarve** [hackforla/expunge-assist#288]
### Overview
We have a meeting with A New Way of Life on Thursday, July 15, 2021. We need to have an interview guide ready so we can ask specific questions related to their processes and gather good data. Each UX Researcher will work to create a set of questions to ask at the meeting.

### Action Items

- [x] Create interview questions [Interview Guide for Creating a Process Map with Stakeholders](https://docs.google.com/document/d/1nRXV5dT0mX5EuvF4P4U9utT1F1Fj_jsdm0SR5KtgsxU/edit#) @yumengluo @myrandi @LarisaGav @apurvabarve 
- [x] Create probes for complicated or confusing questions @yumengluo @myrandi @LarisaGav @apurvabarve 

### Resources/Instructions
1. [Interview Guide for Creating a Process Map with Stakeholders](https://docs.google.com/document/d/1nRXV5dT0mX5EuvF4P4U9utT1F1Fj_jsdm0SR5KtgsxU/edit#)
2. [Notes from UXR Friday Meeting](https://docs.google.com/document/d/1GULkXVpqzU2wzik_pttCGRP7AxyklHfDJ-KeK-go5CE/edit#)

**Comment by myrandi** [comment]
@apurvabarve I think we've all added questions and probes. do you want to go over it and consolidate to eliminate repetition? let us know what makes sense for next steps so we can prep for Thursday!

**Comment by apurvabarve** [comment]
> @apurvabarve I think we've all added questions and probes. do you want to go over it and consolidate to eliminate repetition? let us know what makes sense for next steps so we can prep for Thursday!

Awesome! Thanks, everyone!! I'll take a look this evening.
