### ISSUE TITLE
Create content for a "What is a Declaration Letter" Page

### ISSUE THREAD

**Issue by rcurtis2** [hackforla/expunge-assist#290]
### Overview

Create content for a "What is a Declaration Letter" page in order to let our users understand what makes a good letter and why it will assist in the expungement process

### Action Items

- [x] Brainstorm for what content can be included on this page
- [x] Create a draft of the content 

### Resources/Instructions

- A declaration letter is ….
      - Describe in one sentence what the letter is
      - How long it is
- A strong declaration letter explains following things
      - A story-arch 
      - Persuasive - make a claim and give reasons to support this claim
      - Explains why you need expungement"
     
See the working draft [document](https://docs.google.com/document/d/1iuwvG0jAWedlo60nX2a2uwQ-XTXSyEyw3yoIcopc7E0/edit#) and also [FAQ](https://docs.google.com/document/d/1O3y2oE_5VdEYDcwdjtdrlPq0d-Rcu_igmzPBcbjli-E/edit#) document. This is a section of the FAQs.

**Comment by Andan-Eddy** [comment]
I added a size: medium - is that the correct size for this issue?

**Comment by SamHyler** [comment]
> I added a size: medium - is that the correct size for this issue?

yes, seems appropriate

**Comment by SamHyler** [comment]
This is a section of the FAQs and has been merged into that issue/task/document. Closing the issue.
