### ISSUE TITLE
Process Map - A New Way of Life 

### ISSUE THREAD

**Issue by apurvabarve** [hackforla/expunge-assist#293]
### Overview
We met with staff attorneys from A New Way of Life on Thursday (July 15). We need to create a Process Map for A New Way of Life - Expungement Clinics

### Action Items

- [ ] Please compile your notes from our interview [here](https://docs.google.com/spreadsheets/d/1-lWU-H_Lq_6ZeEqsc3Sj4le1uySsNN9S8VKT4EvwJf8/edit#gid=0). 
- [x]          @apurvabarve 
- [x]         @myrandi 
- [x]         @yumengluo 

- [ ] Put any possible templates for the process map and take a look [here](https://docs.google.com/spreadsheets/d/1qG42DAybzftPaYjJCpOhQI7Shrrf7ylBjc58JSWy9j4/edit#gid=0)
- [x] @apurvabarve 
- [x] @yumengluo 
- [ ] @LarisaGav 
- [ ] @myrandi 

- [ ] Decide on a template for our process map @yumengluo @apurvabarve @myrandi @LarisaGav 

Resources:
1. [Notes from the meeting](https://docs.google.com/spreadsheets/d/1-lWU-H_Lq_6ZeEqsc3Sj4le1uySsNN9S8VKT4EvwJf8/edit#gid=0)
2. [Templates for process map ](https://docs.google.com/spreadsheets/u/2/d/1qG42DAybzftPaYjJCpOhQI7Shrrf7ylBjc58JSWy9j4/edit?usp=drive_web&ouid=111226151859288956886)

**Comment by yumengluo** [comment]
This task is completed.
