### ISSUE TITLE
Create Process Map for A New Way of Life

### ISSUE THREAD

**Issue by apurvabarve** [hackforla/expunge-assist#298]
### Overview
We have decided to use Miro to create a process map for our stakeholders "A New Way of Life".  Each UX Researcher will create a part of the process in Miro. 

### Action Items

- [ ] Sign-up @myrandi 
- [ ] Check-in at the Clinic @LarisaGav 
- [ ] Waiting at the clinic @LarisaGav 
- [x] RAP sheet @yumengluo 
- [ ] Overview map/review/overall formatting @apurvabarve 

### Resources/Instructions
Please [use this board](https://miro.com/app/board/o9J_l4K7WZ8=/) to edit and create your parts. 

This is the [Miro board](https://miro.com/app/board/o9J_l7_CQ2I=/) Apurva created a few weeks ago. Feel free to use it as a guide.

**Comment by yumengluo** [comment]
This task was completed.
