### ISSUE TITLE
'Previewing Final Statement' page doesn't match Figma

### ISSUE THREAD

**Issue by qooqu** [hackforla/expunge-assist#301]
### Overview
'Previewing Final Statement' page doesn't match Figma

-   shows full text with 'back' and 'next' buttons
    -   per Figma, 'back' should be 'edit'
    -   'next' leads to a broken page called 'Previewing Final Statement' with 'edit' and 'next' buttons
        -   'edit' sends you back to the real Previewing Final Statement page
        -   'next' sends you to base_url/form/ and it's blank

### Action Items
Conform to Figma

**Comment by aahvocado** [comment]
will be handled in https://github.com/hackforla/expunge-assist/issues/319
