### ISSUE TITLE
Github Label Cleanup

### ISSUE THREAD

**Issue by brandohayes** [hackforla/expunge-assist#318]
### Overview
We need to clean the labels so that it is easy to manage the project.

### Action Items
- [x] Product Manager
   - [x] Rename 
      - [x] roll labels to role labels
      - [x] priority labels to have the first word be priority (e.g. medium priority should be changed to priority: medium)
   - [x] Make new labels
     - [x] Name: Dependency 
        - [x] Description: "The issue or reason why this issue is in the icebox" 
        - [x] Color: primary yellow
     - [x] Name: dependency missing
        - [x] Description: "The issue is in the icebox and missing a dependency detail"
        - [x] Color: dark red
   - [x] Add the label dependency missing to all issues in the icebox that don't have a dependency label
   - [x] Move this issue into the Ready for review column and bring it up at the next PM/Team Lead/Org meeting (Thursdays at 11am pdt)
   - [x] Schedule PM meeting to review each item in the icebox
- [ ] Agile Coach
  - [ ] Once the above is done show PM how to update the "Sort By" updates in the start here column on the board.
     
### Resources/Instructions
https://github.com/hackforla/expunge-assist/labels?q=roll
[Check to see if any issues need a size missing label](https://github.com/hackforla/expunge-assist/issues?q=is%3Aopen+is%3Aissue+-label%3A%22size%3A+1pt%22+-label%3A%22size%3A+missing%22+-label%3A%22size%3A+medium%22+-label%3A%22size%3A+large%22+-label%3A%22size%3A+good+second+issue%22+-label%3A%22size%3A+good+first+issue%22)

**Comment by ExperimentsInHonesty** [comment]
Example of a project that uses points system for size labels 
https://github.com/civictechindex/CTI-website-frontend/labels?q=size

**Comment by ExperimentsInHonesty** [comment]
labels or missing
size
feature
[role](https://github.com/hackforla/expunge-assist/issues?q=is%3Aopen+is%3Aissue+-label%3A%22role%3A+communications%22+-label%3A%22role%3A+design%22+-label%3A%22role%3A+development%22+-label%3A%22role%3A+missing%22+-label%3A%22role%3A+product+management%22+-label%3A%22role%3A+research%22+-label%3A%22role%3A+UX+content+writing%22)
milestone
project

labels missing
[role](https://github.com/hackforla/expunge-assist/issues?q=is%3Aopen+is%3Aissue+label%3A%22role%3A+missing%22)

**Comment by ExperimentsInHonesty** [comment]
step after that is to do a weekly audit

example from this week: 2021-12-2
labels missing
priority: 47
[size]
feature: 99
role: 5
milestone: 78


issues that are no on the project board: 17

**Comment by ExperimentsInHonesty** [comment]
- [ ] next steps add labels that are still missing
   - [ ] size (see [spreadsheet](https://docs.google.com/spreadsheets/d/1q0g4049PVFAK2Nc6gglapnlFouqSfne1AiSP_gDeyLY/edit#gid=0))
   - [ ] p-features
     - [ ] p-feature: Privacy Policy
     - [ ] p-feature: Terms of Use
     - [ ] p-feature: About Us
     - [ ] p-feature: Introduce Yourself
     - [ ] p-feature: Life Changes
     - [ ] p-feature: Community Service
     - [ ] p-feature: Goals
     - [ ] p-feature: Completion

**Comment by ExperimentsInHonesty** [comment]
@brandohayes @thomasdemoner please see the comments I have left above today and update this issue after the feature and size labels have been made.

**Comment by ExperimentsInHonesty** [comment]
@thomasdemoner @brandohayes 
Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by brandohayes** [comment]
1. Progress: New labels have been added and now we need to review and educate the whole team on the new label system.
2. Blockers: Currently, establishing new team meeting before informing the whole team of the changes.
3. Availability: N/A
4. ETA: N/A

**Comment by ExperimentsInHonesty** [comment]
priority 47
size 61
feature 98
role 5
milestone 84
no project: 17/22 add them to board https://github.com/hackforla/expunge-assist/issues?q=is%3Aissue+is%3Aopen+no%3Aproject

**Comment by thomasdemoner** [comment]
There are a few feature labels that seem to be missing from the "labels or missing" feature filters. Will inspect that today.

**Comment by thomasdemoner** [comment]
All these remaining (except for feature) are old issues that I need to get input from to finish properly solving

priority 32
size 44
feature 0 with no missing labels. I need to update the filters for the second category
role 0
milestone 82
no project: 5
