### ISSUE TITLE
implement copy to clipboard in the "Download" page

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#320]

**Comment by brandohayes** [comment]
@aahvocado Technically, this has been completed right? I believe the button is completed but the function just has to be moved from the sandbox to the actual product.

**Comment by aahvocado** [comment]
Archiving this because it will be covered by https://github.com/hackforla/expunge-assist/issues/262

**Comment by thomasdemoner** [comment]
done!
