### ISSUE TITLE
Get Help with Figma warning label

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#325]
### Overview
There is a new Figma warning label I do not understand re:"moving content to new Figma".

### Action Items
Get assistance with Figma warning label. Warning label began after meeting with Bonnie where some modifications were made to Figma. I don't want to leave the label unaddressed. 

### Resources/Instructions
https://www.figma.com/file/t1lW4Tm0Lp3jFdeOCd98b1/Expunge-Assist?node-id=5830%3A13497

**Comment by brandohayes** [comment]
Is this still an issue as I believe Yumeng was correct about this being related to moving all of the old designs to a new account? If she is correct, has all the designs been moved over yet?

**Comment by ExperimentsInHonesty** [comment]
@yumengluo 
Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by yumengluo** [comment]
This is completed.
