### ISSUE TITLE
Finalizing service blueprint for A New Way of Life

### ISSUE THREAD

**Issue by yumengluo** [hackforla/expunge-assist#329]
### Overview
We need to create a Service Blueprint for a New Way of Life so that they can use it to plan changes to their service.

#### Details:
1. We had two meetings with staff attorneys from A New Way of Life. 
2. First meeting: introduction; Second meeting: interview
3. We agreed to make a service blueprint for their virtual clinic and will make another service blueprint for their in-person clinic later this year (end of 2021)

### Action Items
- [x] Create Interview questions 10 hours
- [x] Interviewed Stakeholder 1 hr
- [x] Transcribed Interview 3 hr
- [x] Review Transcript 2 hr
- [x] Identify content for Blueprint 1 hr
- [x] Review optional formats & Select Format  6 hr
- [x] Draft content 3 x 3 = 9 hr
- [x] Team Review each others drafts 3 x 3 = 9 hr
- [ ] Finalizing the service blueprint
- [ ] Make a copy on the Miro board
- [ ] Send it to A New Way of Life

### Resources/Instructions
[A new way of life service blueprint ](https://miro.com/app/board/o9J_l3JLo0U=/) 
[Interview script and notes](https://drive.google.com/drive/u/0/folders/1usuYYYcnpgbtiM0LtCHvuLQmqFFReGYD)

**Comment by ExperimentsInHonesty** [comment]
yumeng, myranda, larissa worked on 
- [x ] Create Interview questions 10 hours
- [x] Interviewed Stakeholder 1 hr
- [x] Transcribed Interview 3 hr
- [x] Review Transcript 2 hr
- [x] Identify content for Blueprint 1 hr
- [x] Review optional formats & Select Format  6 hr
- [x] Draft content 3 x 3 = 9 hr
- [x] Team Review each others drafts 3 x 3 = 9 hr
yumeng estimates this part took total hours 41 hours
