### ISSUE TITLE
Create a Google Form for partnership and volunteer outreach for landing page 

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#331]
### Overview
Create a google form that partners and volunteers will complete that will be embedded into landing page. Then, create a process map / instruction for development on both how to and WHERE to embed the form into the webpage

### Action Items
Create Google forms for partnership and volunteer outreach. 

for Partnership include request for:
- [ ] name
- [ ] email
- [ ] company name
- [ ] are you currently running expungement clinics
- [ ] some pain point/ struggles you have with your expungement clinics

for volunteers include request for: 
- [ ] name
- [ ] email
- [ ] what are you looking to learn / achieve/ get out of volunteering with Expunge Assist

Create process map / instruction for development instruct:
- [ ] how to embed form into webpage
- [ ] WHERE to embed the form into the webpage

**Comment by nansah** [comment]
https://forms.gle/MG4AoCxv9eCWF71n9
