### ISSUE TITLE
Integrate Google Forms built for Partnership and Volunteer outreach into webpage

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#332]
### Overview
Integrate Google Forms built for Partnership and Volunteer outreach into a webpage

### Action Items
- [ ] *following instructions form #331 
Integrate Google Forms built for Partnership and Volunteer outreach into a webpage

*The form created in the issue linked is old and built on possibly outdated goals. Needs to be revisited.

**Comment by aahvocado** [comment]
Moving to Icebox. No idea what is happening with this currently.

**Comment by SamHyler** [comment]
> #331

same. I created this issue (https://github.com/hackforla/expunge-assist/issues/542) as we were asked to do a content check. Let me know when you have time @thomasdemoner so we can figure out what kind of check you're looking for. We don't have any logins over in Content to get in there and make any changes either.

**Comment by sylvia-nam** [comment]
Closing - revisit when we reach demo stage
