### ISSUE TITLE
Small content changes for consistency 

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#336]
### Overview
The content team is keeping track of accuracy and consistency in the content. There are a few small changes/quick fixes to be made so that the vocabulary is consistent/accurate.  

### Action Items
- [ ] Use 'Declaration letter' instead of 'personal letter' or 'personal statement' or 'expungement letter' or 'declaration statement.' Replace all instances of the incorrect term. Declaration letter is the official court term and should be used to reduce potential confusion for the user. 

- [ ] Remove any copy that states how long it will take to complete the letter using the app (some places say 10 minutes, some say 20 - inconsistent + we can't determine that for a task that can cause stress for the user)

**Comment by Andan-Eddy** [comment]
on declaration letter term change is this a common use change? can you slack with design on this topic

**Comment by nansah** [comment]
in the brief research I've done, I've across terms such as "dismissal", petition, expungement letter or petition for dismissal. Wanted to be clear on this before making changes. 

Sources: [lawprojectla.org ](https://www.lawprojectla.org/clean-slate-faqs )

[FindLaw](https://statelaws.findlaw.com/california-law/how-to-expunge-a-criminal-record-in-los-angeles.html)

[Courts.ca.gov](https://www.courts.ca.gov/1330.htm) 

[Petition for Dismissal](https://www.courts.ca.gov/documents/cr180.pdf)

**Comment by SamHyler** [comment]
Hi! I will send Design a slack message.

**Comment by SamHyler** [comment]
updated to add note about time copy

**Comment by SamHyler** [comment]
Hi @daisyyiudesign , just cleaning up old issues so I reassigned you instead of the former design team. You can close this issue whenever you've noted the changes.
