### ISSUE TITLE
Document Expunge Assist team meeting times and who Must/Should/Can attend

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/expunge-assist#340]
### Overview 
The Civic Tech Jobs team needs accurate meeting time information from the Expunge Assist team to help match your project with available volunteers.

### Action Items
- [x] provide details about the each meeting in a comment by using a copy of the check boxes below
- [x]  Confirm Meeting Details with each team
- [x] Confirm all Meetings are listed, not all have been documented on the Expunge Google Calendar
- [x] post a link to this issue on https://github.com/hackforla/CivicTechJobs/issues/35 in a comment letting the civic tech jobs team know you are done.
```
  - [ ] day
   - [ ] start_time
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min
   - [ ] name_of_meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
```
### Resources
- URL of the project's homepage on the HfLA website:  https://www.hackforla.org/projects/expunge-assist
- Times that VRMS shows for your meetings: 
Mon 6:00 pm, 1 hour, Team meeting on 1st & 3rd Mondays/PM on all other Mondays
Tue 6:00 pm, 1 hour, Research & Design meeting
Thu 6:00 pm, 1 hour, Dev meeting

**Comment by ExperimentsInHonesty** [comment]
Monday, 12pm, 1 hour, PM meeting 
Mon 6:00 pm, 1 hour, Team meeting on 1st & 3rd Mondays
Tue 5:00 pm, 1 hour, Research & Design meeting
Wed 5:00pm, 1 hour, Design meeting
Thursday 11am, 1 hour, PM/org meeting
Thu 6:00 pm, 1 hour, Dev meeting
Friday ???, ????, ???Some kind of Research meeting

**Comment by ExperimentsInHonesty** [comment]
Monday, 12pm, 1 hour, PM meeting

  - [ ] day
   - [ ] start_time
      - [ ] AM
      - [ ] PM
   - [ ] duration_in_min
   - [ ] name_of_meeting
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain

**Comment by SamHyler** [comment]
- [ ] day Wednesdays 
   - [ ] start_time
      - [ ] AM 10 PST 
      - [ ] PM
   - [ ] duration_in_min 30-60 minutes, depending on need
   - [ ] name_of_meeting UX Writing/Content 
   - [ ] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ X ] other: please explain   UX Writing/Content
   - [ ] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [ ] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ X ] other: please explain anyone is welcome

**Comment by thomasdemoner** [comment]
Design & Research Meeting - Tuesdays - 5pm

  - [x] day: Tuesday
   - [x] start_time: 5pm PT
      - [ ] AM
      - [x] PM
   - [x] duration_in_min: 30
   - [x] name_of_meeting: Design & Research
   - [x] who_must_attend
      - [x] pm
      - [ ] all_leads
      - [x] design_lead
      - [x] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [x] design
      - [x] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [x] other: anyone, please give notice.

**Comment by thomasdemoner** [comment]
Design Meeting - Wednesday - 8pm

  - [x] day: Wednesday
   - [x] start_time: 6pm PT
      - [ ] AM
      - [x] PM
   - [x] duration_in_min: 30
   - [x] name_of_meeting: Design Meeting
   - [x] who_must_attend
      - [ ] pm
      - [ ] all_leads
      - [x] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [x] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_should_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [ ] other: please explain
   - [x] who_can_attend
      - [ ] pm
      - [ ] all_leads
      - [ ] design_lead
      - [ ] research_lead
      - [ ] frontend_lead
      - [ ] backend_lead
      - [ ] data_science_lead
      - [ ] design
      - [ ] research
      - [ ] frontend
      - [ ] backend
      - [ ] data_science
      - [x] other: anyone, please give notice.

**Comment by ExperimentsInHonesty** [comment]
I had a text file on my personal drive with this info for this team.  Dumping it here incase we need it later

Date, Start Time, Duration, Name of Meeting, Must Attend, Should, Can Attend
Mon, 6:00 pm, 1 hr, Team meeting on 1st & 3rd Mondays, [PM & All Leads], All, All
Mon, 6:00 pm, 1 hr, PM meeting on alternate Mondays, PM, PM, ,
Tue, 6:00 pm, 1 hr, Research & Design meeting, [Research Lead. Design Lead], [Researchers, Designers], ???
Thu, 6:00 pm, 1 hr, Development Team, [Font End Lead, Back End Lead], [Back end developers, Front end developer], All

**Comment by thomasdemoner** [comment]
> I had a text file on my personal drive with this info for this team. Dumping it here incase we need it later
> 
> Date, Start Time, Duration, Name of Meeting, Must Attend, Should, Can Attend Mon, 6:00 pm, 1 hr, Team meeting on 1st & 3rd Mondays, [PM & All Leads], All, All Mon, 6:00 pm, 1 hr, PM meeting on alternate Mondays, PM, PM, , Tue, 6:00 pm, 1 hr, Research & Design meeting, [Research Lead. Design Lead], [Researchers, Designers], ??? Thu, 6:00 pm, 1 hr, Development Team, [Font End Lead, Back End Lead], [Back end developers, Front end developer], All

These are the ones listed on the project page (https://www.hackforla.org/projects/expunge-assist), which needs updating as well.

**Comment by ExperimentsInHonesty** [comment]
[Update VRMS with correct meeting times](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

**Comment by ExperimentsInHonesty** [comment]
Add update to the wiki page

**Comment by thomasdemoner** [comment]
Just sent vrms update request with the current meetings, listed below in the format required in the request issue.

### List all of your meeting times (PST time ONLY) (Name of project, name of team meeting, day of week, start time am/pm, duration):
- Expunge Assist, PM Meeting, Monday, 3 pm, 1 hour
- Expunge Assist, Dev-Design-PM Collab Meeting, 5 pm, 1 hour
- Expunge Assist, All Hands Meeting, Every 2nd Tuesday, 5 pm, 1 hour
- Expunge Assist, PM-Org Meeting, Thursday, 4 pm, 1 hour
- Expunge Assist, Development Team Meeting, Thursday, 6:00 pm, 1 hour
- Expunge Assist, Research Team Meeting, Friday, 11am, 1 hour

**Comment by ExperimentsInHonesty** [comment]
These are the current meeting times:

- [x] Expunge Assist, PM, Monday, 3 pm, 1 hour
- [x] Expunge Assist, Dev-Design-PM Collab, 5 pm, 1 hour
- [x] Expunge Assist, All Hands, Every 2nd Tuesday, 5 pm, 1 hour
- [x] Expunge Assist, PM-Org, Thursday, 4 pm, 1 hour
- [x] Expunge Assist, Development, Thursday, 6:00 pm, 1 hour
- [x] Expunge Assist, Research, Friday, 11am, 1 hour
