### ISSUE TITLE
Integrate UX team heuristic evaluation into landing page

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#344]
### Overview
Integrate comments from UX research team's heuristic evaluation into landing page

### Action Items
Review UX researchers evaluation into the landing page

### Resources/Instructions
https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A10

**Comment by jamiesiu** [comment]
Daisy confirmed they already incorporated the comments from the old heuristic evaluation. The new design should be tested following similar guidelines. We will close this out for now
