### ISSUE TITLE
Research with volunteers from A New Way of Life

### ISSUE THREAD

**Issue by yumengluo** [hackforla/expunge-assist#360]
### Overview
We plan to establish research relationships with law student volunteers and community volunteers from A New Way of Life 

### Action Items
 
- [ ] Prepare research meeting with volunteers

- [ ] Draft a research plan

### Resources/Instructions
[Research plan](https://docs.google.com/document/d/1KUA5jzhq1nkhqv28WRZlJrXt0x2nj6SrtM_Zj5HaZ4Y/edit#)
 Will receive an email from Natalie in two weeks.

**Comment by ValeriyaMetla** [comment]
@yumengluo this research with volunteers has never happened right? @ExperimentsInHonesty can we close this issue then?
