### ISSUE TITLE
Feedback on Writing/Content Guidelines 

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#364]
### Overview
The Content team has created writing, tone, voice, and style guidelines for writing on the Expunge Assist app. This is so that anyone who writes copy for the app have resources to keep the copy consistent for the user. 

We are looking for any feedback, thoughts, and discussion you may have before we finalize them (they will be updated periodically).

### Action Items
- [ ] Review the guidelines
- [ ] Send any suggestions, thoughts, discussions, etc. to Sam (here or in Slack or in the comments of the document)

### Resources/Instructions
[Guidelines
](https://docs.google.com/document/d/1w8iHLEjgBlkwi6jm7XgLoI0RE3JtmUnJtCq3psks1nI/edit#heading=h.jakpmonkrl8l)

**Comment by Andan-Eddy** [comment]
did we ever give you feedback on this?

**Comment by SamHyler** [comment]
> did we ever give you feedback on this?

Not yet! But I would love feedback from Design on this. 

Actually, I'd be glad to meet with Design soon to talk about this and the Questions for some feedback and input if possible. Maybe in 2 weeks or so?

**Comment by ExperimentsInHonesty** [comment]
@Andan-Eddy is going to make new issues for each person who has not provided feedback and then link to those issues in the top of this issue, so that we can track progress.

**Comment by Andan-Eddy** [comment]
I assigned this is issue to just daisy @daisyyiudesign can you also share this with Cherry to get her feedback

**Comment by jamiesiu** [comment]
Checking with Sam to see if feedback is needed from Design

**Comment by SamHyler** [comment]
Never received feedback from design. Closing this issue because it's super old now and we've moved passed this. Assigned the label back to Design as it was an issue for Design, not for Content.
