### ISSUE TITLE
Review Writing/Content Guidelines

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#366]
### Overview
The Content team has created writing, tone, voice, and style guidelines for writing for the Expunge Assist tool. This is so that anyone who writes copy for the app has a resource and can keep the copy consistent for the tool/user. 

We are looking for any feedback, thoughts, and discussion you may have before we finalize them (they will be updated periodically).

### Action Items
- [ ] Review the guidelines
- [ ] Send any suggestions, thoughts, discussions, etc. to Lori & Sam (here or in Slack or in the comments of the document)

### Resources/Instructions
[Guidelines
](https://docs.google.com/document/d/1w8iHLEjgBlkwi6jm7XgLoI0RE3JtmUnJtCq3psks1nI/edit#heading=h.jakpmonkrl8l)

**Comment by SamHyler** [comment]
@brandohayes  I tagged this one with communications and development, could you add the folks working in development? I tagged communications as well as I know you are working with the go to market plan, and the guidelines overlap with work in the marketing/communications. I'd really like your input and thoughts. Thanks so much!

**Comment by brandohayes** [comment]
@aahvocado @thomasdemoner @bkmorgan3 . Hey Team. Please look at this in your free time and offer any suggestions. Thank you,

**Comment by aahvocado** [comment]
All good points that I support. I'll keep an eye out for these things while working and adding text.

**Comment by bkmorgan3** [comment]
> @aahvocado @thomasdemoner @bkmorgan3 . Hey Team. Please look at this in your free time and offer any suggestions. Thank you,

@brandohayes  It all sounds good to me.

**Comment by SamHyler** [comment]
Thanks everyone! @brandohayes go ahead and tick off the boxes and close the issue whenever you're ready.

**Comment by ExperimentsInHonesty** [comment]
@westphll @SamHyler I responded to your comments in the document, with some info and a request for you to make a new issue for the glossary.  Feel free to close this issue after the comments have been resolved and the issue made.

**Comment by SamHyler** [comment]
Thanks Bonnie, and thanks for sharing the accessibility guides with us, those will be really helpful going forward.
