### ISSUE TITLE
Recruit New Developers

### ISSUE THREAD

**Issue by brandohayes** [hackforla/expunge-assist#378]
### Overview
Two new developers should be recruited to the team to the team assist with the future iteration of the Expunge Assist Project. One should be a developer with experience that can take lead and the other can be anyone who just wants to learn. 

Skills:
React, Material UI, State Management

### Action Items
- [x] Create job requirements
- [x] Post job requirements on https://github.com/hackforla/engineering/projects
- [x] followup and post notes in the comments

### Resources/Instructions
Contact Bonnie or other PMs if assistance is needed on how to create a job req.

[Front End post on engineering open roles](https://github.com/hackforla/engineering/projects/2#card-61082123)

Need to post for lead https://github.com/hackforla/engineering/projects/2#column-17353428

**Comment by ExperimentsInHonesty** [comment]
@thomasdemoner Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@thomasdemoner Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by thomasdemoner** [comment]
1. one dev onboarded, two more intend on joining but missed last meeting.
2. Not enough personal knowledge to create lead dev open role post. Assigned it to the lead dev himself.
3. N/A
4. Two devs remaining new devs should be cleared to go tonight. New lead dev should be in place within a month, depends on Daniel's judgement.

**Comment by thomasdemoner** [comment]
### Lead Dev open role post draft

<img src="https://user-images.githubusercontent.com/78319934/129253133-b41b4aa6-accc-4521-b769-000c1e39a46b.png" />

**Project Name**: Expunge Assist

**Volunteer Opportunity**: Lead Developer. React fluency required, tech lead experience preferred.

Our web application is nearly ready to launch, and we need some assistance working through the final tasks before launch (as well as adding future features). Our application is written in React. We also use TypeScript, but TypeScript experience is not necessary.

**Duration**: Open-ended

**Meeting times**: Mondays at 5pm, Thursdays at 6 pm PST

**Who to communicate your interest to**
 - Slack channel link: [#expunge-assist](https://hackforla.slack.com/archives/CN8NXTPK5)
 - Slack name of person to contact in the channel: Daniel Xiao, Thomas Demoner

[Read more about the project](https://www.hackforla.org/projects/expunge-assist)
[Github Page](https://github.com/hackforla/expunge-assist)

**Comment by thomasdemoner** [comment]
@aahvocado This is a draft for the Lead dev open role posting. I'll bring it up in today's meeting for you to take a look at. It's kind of a copy of the basic front-end open role with some minor edits really.

**Comment by aahvocado** [comment]
@thomasdemoner I have change for the last couple sentences: 

~~Our application is written in React. We also use TypeScript, but TypeScript experience is not necessary.~~ 

to something like 

**Our application is written with Typescript and uses react-router. It's not a problem if you're not fluent in these libraries, we will work with you to make you comfortable with your implementation.**

**Comment by thomasdemoner** [comment]
Ok, thank you. Open role has been posted with the following, slightly altered description (altered for character limits).

"Web app is nearly ready to launch, and we need help working through the final tasks - and someone who is ready to take leadership of the team post-launch as we proceed with incremental iterations. Our application is written with Typescript and uses react-router. It's not a problem if you're not fluent in these libraries, we will work with you to make you comfortable with your implementation."
