### ISSUE TITLE
"continue form" button

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#380]
If the user accidentally clicks on the links (such as the bottom Privacy Policy) it will take them to a separate page. If they don't press Back on their browser they'll return to the home page and then have to click through everything.

**Comment by thomasdemoner** [comment]
would this problem be rendered irrelevant if we opened the redirecting links on new tabs instead? @aahvocado

**Comment by aahvocado** [comment]
Yeah, talked about this in the dev meeting. Is mostly a concern for when user may navigate out of the page accidentally but otherwise this is not a priority.
