### ISSUE TITLE
Replace statement generator as home screen for expungeassit.org with website created by design team 

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#391]
### Overview
The personal statement generator currently acts as home screen for [expungeassit.org ](https://expungeassist.org/) replace that with [website](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A9) created by design team. From the website there will be links to the personal statement generator. 

### Action Items
- [ ] development should build the website in conjunction with the design team
- [ ] install the website as the landing page to [expungeassit.org ](https://expungeassist.org/) and link the personal statement generator from the website.

**Comment by aahvocado** [comment]
Sounds like this is the landing page - handled in other issues.
