### ISSUE TITLE
create landing page

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#397]
## design
https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A9

## description
(details are going to be a little sparse since I have not been consulted with during the process)

- create the landing page in it's own `/page`
- reuse existing components where possible `Buttons`
- extra design (like the orange and yellow lines) and images can be implemented later
- text can be implemented later

**Comment by sydneywalcoff** [comment]
closing as no longer relevant
