### ISSUE TITLE
Make Figma design edits to Partnership, Accomplishments and Meet the team section of landing page. 

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#399]
### Overview
Make [Figma design](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A9) edits to Partnership, Accomplishments and Meet the team section of landing page. 

### Action Items
- [ ] Combine two Partnership sections
- [ ] Change wording to illustrate what Expunge Assist provides for the partner and not what we need from them
- [ ] List accomplishment: "Created process map for a New Way of Life..."
~~- [ ] Replicate [ballotnav.orgs](https://about.ballotnav.org/) "meet the team" design layout (ie. have button link to Expunge Assist's  hackforla project section)~~ (this is referenced in https://github.com/hackforla/expunge-assist/issues/435)

**Comment by Andan-Eddy** [comment]
Daisy is redesign landing page- this section will be changed. Check with Daisy about how this section will be integrated. Mahmoud will follow up on this

**Comment by jamiesiu** [comment]
Closing as this is based on a past iteration of the landing page https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A9 which we are no longer using. Can be re-opened if needed
