### ISSUE TITLE
Create Public Facing Wiki for Usability Testing 

### ISSUE THREAD

**Issue by yumengluo** [hackforla/expunge-assist#401]
### Overview
We need to create a public-facing Wiki so we can store all research-related documents including consent forms for testing with target users. 

### Action Items
- [x] Find a platform to create public-facing repository for usability testing with target users 
- [x] UXR creates issues that would begin the process of assembling a research plan/guide and consent forms for user testing. Please reference it here.
   - [x] Review examples of HfLA projects who have this feature 
   - [x] Review how usability testing documentation (consent forms, research plan, etc.) was assembled within these projects 

### Resources/Instructions 
- [ ] Bonnie provided the following examples in reference to
   - [ ] the process of building the public repository Wiki page
       - [ ] http://www.greenearthos.org/
       - [ ] https://www.mkdocs.org/getting-started/
       - [ ] https://brigade.cloud/
  - [ ] structure and types of documentation including for usability testing 
       - [ ] https://github.com/hackforla/internship/wiki
       - [ ] http://youthjusticenav.org/
          - [ ] https://github.com/hackforla/internship/wiki/Intern-Research-Plans-and-Goals
          - [ ] https://github.com/hackforla/internship/wiki/The-2022-Internship-Program-Process-Overview
```

**Comment by ExperimentsInHonesty** [comment]
@ValeriyaMetla Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ValeriyaMetla** [comment]
@jbsteinhardt I think we can remove #62 from here. This issue is not about reaching out to legal professionals and doesn't have to be dependency for our research plan.

**Comment by ValeriyaMetla** [comment]
@thomasdemoner per our conversation to check with development about it. 1) does development has the capacity to support creating public repository? 2) alternatively, can they provide support to product on how best create it. @jbsteinhardt  @Ndoyle118 per your information. You can also assign someone to this issue to review how other project have done it and what elements they have that we need for our usability testing. Let me know if any clarifications. The idea is that research will create a separate issue to work on the docs but we provide general feedback and clarify out needs and understandings here.

**Comment by ValeriyaMetla** [comment]
Update from @thomasdemoner "Top of mind I was thinking Notion, the note taking app - they have like embed functionality for websites now and a lot of startups are using it for wiki/guide/faq pages. I have to double check what the integration process/limits are, but I feel like that would be an ideal no-code solution for us." @jbsteinhardt @Ndoyle118 I am going to move to to backlog, you can assign someone to this issue to begin assembling list of documents we need to create for target user testing.

**Comment by thomasdemoner** [comment]
https://www.notion.so/

**Comment by kelseylondon** [comment]
Closing this issue. Following guidance from Bonnie and the Internship Project research team, we are using the github wiki as both an internal and public-facing wiki.
