### ISSUE TITLE
Change copy in prototype before the MVP launch 

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#404]
### Overview
Content team has made smaller copy changes to a few screens to update the overall tone of the product before the MVP launch from a congratulatory, joyous tone to an empathetic, supportive tone. 

Changes are written in the google doc below, mockups are in the main figma content writing tab, and Sam is changing the copy in the EA main figma prototypes.

Contact Sam with any questions. 

### Action Items
- [ ] Change copy on prototype screens
- [ ] See comments on Desktop prototype in Figma regarding spacing
- [ ] Additionally, change "Introduce Yourself!" to "Introduce Yourself" (remove exclamation mark) on all frames under "Introduce Yourself" sections in both mobile and desktop prototypes

### Resources/Instructions
Copy is in [this](https://docs.google.com/document/d/12cTlPhxR_nPym6OcsMfnYtsRlVAW7jYH29wHp9Mvg5I/edit) document.

Mockups in Expunge Assist Main Figma under [content tab](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A5).

**Comment by SamHyler** [comment]
Hi @aahvocado  do you need this issue to be separated into different issues for each page?

**Comment by aahvocado** [comment]
Oh great, this was finished earlier.
