### ISSUE TITLE
[PAUSE STUFF] Determine Content accessibility needs 

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#410]
### Overview
Determine accessibility needs and make a plan to implement them. 

Can include for example word choice (A UX example would be: using deceptive design rather than "dark pattern"), writing for screen readers, adding alt text, etc. 

See also Dev issue https://github.com/hackforla/expunge-assist/issues/487

Define Content accessibility goals. This issue follows up on UXR accessibility goals issue #959.  

When looking at this issue and starting again, please review and adapt below. 

### Action Items
- [ ] Initiate this discussion with Design to see how we can proceed together 
- [ ] Determine what accessibility needs users have and the tools needed
- [ ] Determine content accessibility recommendations
- [ ] Update content/writing guidelines with accessibility guidelines
- [ ] Update website and collaborate with any necessary teams

From other issue (now closed)
- [ ] Review accessibility standards and guidelines such as WCAG
- [ ] Brainstorm content accessibility goals in this [document ](https://docs.google.com/document/d/1QWZBCVfy64yKlDhyj2yPWhA1Jn03MDw1kof-hnScCD8/edit?pli=1#heading=h.o4imd8fnkgfn)
- [ ] Identify 3-4 accessibility goals for UXR accessibility research by 7/7

### Resources/Instructions 

From now closed issue:
- [ ] Read the [ADA Compliance Guide](https://www.ada.gov/pcatoolkit/chap5toolkit.htm).
- [ ] [The a11y project](https://www.a11yproject.com/)
- [ ] Issue #959 websites and resources
- [ ] [Web Content Accessibility Guidelines (WCAG) website](https://wcag.com/resource/what-is-wcag/)
- [ ] [W3C Web Accessibility Initiative (WAI)](https://www.w3.org/WAI/roles/writers/) 

See also https://github.com/hackforla/expunge-assist/issues/410

**Comment by aahvocado** [comment]
should link with #487

**Comment by SamHyler** [comment]
https://github.com/hackforla/expunge-assist/issues/967

**Comment by SamHyler** [comment]
Closing as issue is old. Some accessibility work has already happened through other issues. When the time arises, open new issues for specific accessibility features
