### ISSUE TITLE
create Primary landing page section

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#412]
https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A9

![Screen Shot 2022-01-06 at 2 46 04 PM](https://user-images.githubusercontent.com/2266545/148463281-f02e9c84-20e2-42d0-8e3f-fe05b219f7a2.png)

![Screen Shot 2022-01-06 at 2 46 49 PM](https://user-images.githubusercontent.com/2266545/148463275-2a7046f1-6cb7-4540-96e1-1e8c6315f16e.png)

---

Create component containing the top level of the landing page.
- [x] Outer container should be the tangerine orange the whole width but all other content should be wrapped in `utilityClasses.contentContainer` to maintain sizing.
- [x] "View Demo" link should go to `/form/start`
- [x] Follow design of horizontal presentation in desktop and vertical presentation in mobile.
* **Differences from the design**: 
  - [x] padding from all sides should not be that big, keep it similar to the other pages with `spacing(3)` horizontally and bigger vertically
  - [x] use an existing font family

**Comment by aahvocado** [comment]
assigned to @sydneywalcoff

**Comment by sydneywalcoff** [comment]
> padding from all sides should not be that big, keep it similar to the other pages with spacing(3) horizontally and bigger vertically

@aahvocado how much bigger vertically? Do you have an example?
