### ISSUE TITLE
Update Hack-for-LA project profile card

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#429]
### Dependency
Any changes to the project's PRODUCT LEADERSHIP, TECH STACK, INFO and CONTACT LINKS, and/or BRANDING that should be reflected on the project's page on the Hack for LA website.

### Overview
update expunge assist project profile card to show current project information
https://www.hackforla.org/projects/expunge-assist

### Action Items
- [x] Move issue to In Progress and assign yourself or whoever is to be responsible for it
- [x] complete github issue required to update project profile
https://github.com/hackforla/website/issues/new?assignees=&labels=&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D
- [x] Comment below with the changes you've requested
- [x] Make sure the project profile was updated.
- [x] Move back to Icebox

**Comment by thomasdemoner** [comment]
Last request:
https://github.com/hackforla/website/issues/3135#issuecomment-1125484834

**Comment by amejiamesinas** [comment]
### Action Items
- [ ] Move issue to In Progress and assign yourself or whoever is to be responsible for it
- [ ] complete github issue required to update project profile
https://github.com/hackforla/website/issues/new?assignees=&labels=&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D
- [ ] Comment below with the changes you've requested
- [ ] Make sure the project profile was updated.
- [ ] Move back to Icebox
