### ISSUE TITLE
Feedback on Writing/Content Guidelines (from Andan design PM)

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#434]
### Overview
The Content team has created writing, tone, voice, and style guidelines for writing on the Expunge Assist app. This is so that anyone who writes copy for the app have resources to keep the copy consistent for the user. 

We are looking for any feedback, thoughts, and discussion you may have before we finalize them (they will be updated periodically).

### Action Items
- [x] Review the guidelines
- [x] Send any suggestions, thoughts, discussions, etc. to Lori & Sam (here or in Slack or in the comments of the document)

### Resources/Instructions
[Guidelines
](https://docs.google.com/document/d/1w8iHLEjgBlkwi6jm7XgLoI0RE3JtmUnJtCq3psks1nI/edit#heading=h.jakpmonkrl8l)

**Comment by Andan-Eddy** [comment]
@SamHyler I created a new issue just for my review and feedback here- and assigned the old issue just to Daisy

**Comment by Andan-Eddy** [comment]
@SamHyler this is great, full stop. I don't have any recommendations, thank you. My only suggestion is get initial feedback from the design team. But, come back to them (whoever "they") are after the MVP- my guess is they will have thoughts about how to communicate after we interact with some real people. I also this this should probably be an on going conversation, not simply look at this once and move on. 

what do you think

**Comment by SamHyler** [comment]
> @SamHyler this is great, full stop. I don't have any recommendations, thank you. My only suggestion is get initial feedback from the design team. But, come back to them (whoever "they") are after the MVP- my guess is they will have thoughts about how to communicate after we interact with some real people. I also this this should probably be an on going conversation, not simply look at this once and move on.
> 
> what do you think?

Thanks Andan! The document was always intended to be a working guideline to be updated and discussed as needed and as the project develops. I also anticipated the possibility for changes after any kind of user testing. So, agreed! We just needed a starting point and to get the whole team onboard with a cohesive content voice for the product. And gotcha on the assigning issues.
