### ISSUE TITLE
Change "Meet the UX Design and Development Team" section of Landing Page on Figma

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#435]
### Overview
The ["Meet the UX Design and Development Team"](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A9) section of Landing Page on Figma needs to be changed from the current images to a button which will link to [Hack for LA project section](https://www.hackforla.org/projects/expunge-assist). 

### Action Items
- [ ] Replace current images on Figma landing page with a button (that says meet the team)
       - [ ] https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A9
- [ ] Link the (meet the team) button to the Hack for LA project page
       - [ ] https://www.hackforla.org/projects/expunge-assist
- [ ] ie Ballot Nav website
       - [ ] https://about.ballotnav.org/

**Comment by Andan-Eddy** [comment]
Daisy is redesign landing page- this section will be changed. Check with Daisy about how this section will be integrated. Mahmoud will follow up on this

**Comment by jamiesiu** [comment]
Seems like this is outdated based on the current iteration of the landing page. Confirming with team

**Comment by jamiesiu** [comment]
Closing this out as we are not separating the "Meet the Team" section by discipline. Instead, we'll be directing towards the Hack for LA EA website and highlighting the team as a whole.
