### ISSUE TITLE
Change "What We've accomplished so far " section of Landing Page on Figma

### ISSUE THREAD

**Issue by Andan-Eddy** [hackforla/expunge-assist#436]
### Overview
Change "What We've accomplished so far " section of Landing Page on Figma to "We have built a process map for A New Way of Life, a reentry nonprofit for women reentering the public after prison."

### Action Items
- [ ] Change 3 checks in "What We've accomplished so far " section of Landing Page on Figma to 1 check "We have built a process map for A New Way of Life, a reentry nonprofit for women reentering the public after prison."

**Comment by Andan-Eddy** [comment]
Daisy is redesign landing page- this section will be changed. Check with Daisy about how this section will be integrated. Mahmoud will follow up on this

**Comment by jamiesiu** [comment]
Closing as this looks to be out of date and based on older iterations of the landing page. Can be reopened if needed.
