### ISSUE TITLE
Create Interview Guide for Legal Clinic Professionals 

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#441]
### Overview
Create an interview guide for organizational outreach and research.

### Action Items
- [ ] synthesize research questions and adapt into interview questions
- [ ] draft with attention to:
   - [ ] building relationships
   - [ ] being open to the stakeholder not being interested in, or not seeing a place for, our product in their processes
   - [ ] being sensitive to stakeholders' sense of responsibility and protectiveness towards their clients
   - [ ] being sensitive to stakeholders' time
   - [ ] make any asks with all this in mind
- [ ]  Close this issue when complete

```
### Resources
[We need to include here there past interview guides]

**Comment by yumengluo** [comment]
I finished a basic draft of the screener and interview questions. Feel free to edit or comment on it.

**Comment by ValeriyaMetla** [comment]
Old issue that was never developed.
