### ISSUE TITLE
implement html to text rendering

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#446]
There are places in the app that could benefit from underline or other text-decorations. 

![Screen Shot 2022-02-05 at 2 29 02 PM](https://user-images.githubusercontent.com/2266545/152661083-9eb9ac30-1a97-4c42-9901-dfab3b009ead.png)

We can create our own implementation or use a package like https://github.com/html-to-text/node-html-to-text

It should take in something like `<p>This is sort of <b>important</b> so it would be nice to have</p>` to: 
"This is sort of __important__ so it would be nice to have"

**Comment by thomasdemoner** [comment]
Hey @aahvocado, I moved this issue to the brainstorming issue as well. Let me know if you'd like me to mention you in those comments as well btw.
