### ISSUE TITLE
review dependabot alerts

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#461]
See which issues are critical and resolve them if there are. 

https://github.com/hackforla/expunge-assist/security/dependabot?page=2&q=is%3Aopen

**Comment by aahvocado** [comment]
Merged in dependabot alerts but also had to revert a couple while also updated the github action.

**Comment by aahvocado** [comment]
reopened because there's still some outstanding issues

**Comment by aahvocado** [comment]
moving to Icebox

this is a note for someone in the future to possibly look at the Security tab and see if we can use Dependabot to re-attempt to update high priority security vulnerabilities

**Comment by thomasdemoner** [comment]
Hey @aahvocado, is this issue still relevant? And if so are there any Dependencies that would place this issue in the Icebox?

I do see your last comment stating the context for this, but like the other one it's difficult to know what dependencies might be in the way. And the like in the description also does not seem to work...

**Comment by aahvocado** [comment]
Closing. There are still critical dependency issues in the security page and I will work through those slowly.
