### ISSUE TITLE
Onboard & Offboard: UX Researcher 

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#464]
### Dependency
Waiting to have a researcher to on/off-board.

### Overview
We need to have a checklist of items to do when a UX Researcher onboards and offboards so that the process can be consistent and fast.

### Date Updated
(insert date you created this issue and keep updating the date each time the org template change are integrated)
2022-02-14

### Action Items
- [ ] Move In-Progress column when onboarding or offboarding someone. 
- [ ] Check to see if the org template for this process has new steps in it, and if it does, update this  issue and its template with content and add the last date you updated the template below
- [ ] Copy template to comment below
- [ ] Add name of person
- [ ] Check off as done
- [ ] Move back to the Ice Box otherwise.

```
#### Onboard
- [ ] Google Drive
   - [ ] Add to drive as Contributor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Slack Channels
- [ ] Google Calendar Invites  
```
```
#### Offboard
  - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s)
   - [ ] expungeassist@hackforla.org
```

### Resources/Instructions
- 1password.com
- [Expunge Assist Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n?usp=sharing)
- [Expunge Assist Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
- Check public and 2FA at [people page](https://github.com/orgs/hackforla/people)
- [Expunge Assist GitHub Team URL](https://github.com/orgs/hackforla/teams?query=expunge)
   - [base (read)](https://github.com/orgs/hackforla/teams/expunge-assist/members)
   - [write](https://github.com/orgs/hackforla/teams/expunge-assist-write)
   - [maintain](https://github.com/orgs/hackforla/teams/expunge-assist-maintainers)
   - [triage] - no triage team
   - [admin](https://github.com/orgs/hackforla/teams/expunge-assist-admins/members)
- Shortcut for adding a profile to the desktop:  chrome://settings/manageProfile
- Tutorials
  - [Forward emails to team members](https://github.com/hackforla/product-management/wiki/Forward-emails-to-team-members)

[org template](https://raw.githubusercontent.com/hackforla/.github/main/.github/ISSUE_TEMPLATE/onboard---offboard--product.md) updated 2022-02-09

**Comment by ValeriyaMetla** [comment]
#### Onboard Joanna this week
- [ ] Google Drive
   - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Add to email address
   - [ ] expungeassist@hackforla.org

```

**Comment by ValeriyaMetla** [comment]
#### Onboard Nicolas next week 
- [ ] Google Drive
   - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Add to email address
   - [ ] expungeassist@hackforla.org

```

**Comment by ValeriyaMetla** [comment]
#### Offboard @LarisaGav 
  - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s)
   - [ ] expungeassist@hackforla.org

**Comment by ValeriyaMetla** [comment]
#### Onboard Nikita next week 
- [x] Google Drive
   - [x] Add to drive as Editor 
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public and note in roster
  - [x] Check for 2FA and note in roster
- [x] GitHub
     - [x] Add to team Expunge Assist
- [x] Figma
  - [x] invite
  - [x] acceptance
- [ ] Add to email address
   - [ ] expungeassist@hackforla.org

```

**Comment by ValeriyaMetla** [comment]
#### Onboard Alba 06/24  
- [x] Google Drive
   - [x] Add to drive as Editor 
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public and note in roster
  - [x] Check for 2FA and note in roster
- [x] GitHub
     - [x] Add to team Expunge Assist
- [x] Figma
  - [x] invite
  - [ ] acceptance
- [ ] Add to email address
   - [ ] expungeassist@hackforla.org

```

**Comment by ValeriyaMetla** [comment]
#### Offboard @ana-lobos  
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [ ] Figma
  - [ ] remove from team
- [ ] Remove from email address(s)
   - [ ] expungeassist@hackforla.org

**Comment by ValeriyaMetla** [comment]
#### Offboard @albagaral 
- [x] Google Drive
   - [x] demote to viewer
- [x] Roster
  - [x] mark as inactive
- [x] Figma
  - [x] remove from team
- [x] GitHub
     - [x] demote member to read only team and remove from write team
- [ ] Remove from email address(s)
   - [ ] expungeassist@hackforla.org

**Comment by ValeriyaMetla** [comment]
#### Onboard Vyshiali 08/28/22 
- [x] Google Drive
   - [x] Add to drive as Editor 
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public and note in roster
  - [x] Check for 2FA and note in roster
- [x] GitHub
     - [x] Add to team Expunge Assist
- [x] Figma
  - [x] invite
  - [ ] acceptance
- [ ] Add to email address
   - [ ] expungeassist@hackforla.org

```

**Comment by ValeriyaMetla** [comment]
Onboard @kelseylondon 09/05/22
 Google Drive
 Add to drive as Editor
 Roster
 Send link
 Team member adds themselves
 Check for Public and note in roster
 Check for 2FA and note in roster
 GitHub
 Add to team Expunge Assist
 Figma
 invite
 acceptance
 Add to email address
 [expungeassist@hackforla.org](mailto:expungeassist@hackforla.org)

**Comment by ValeriyaMetla** [comment]
#### Onboard @kelseylondon 09/05/22 
- [x] Google Drive
   - [x] Add to drive as Editor 
- [x] Roster
  - [x] Send link
  - [ ] Team member adds themselves
  - [x] Check for Public and note in roster
  - [x] Check for 2FA and note in roster
- [x] GitHub
     - [x] Add to team Expunge Assist
- [x] Figma
  - [x] invite
  - [ ] acceptance
- [ ] Add to email address
   - [ ] expungeassist@hackforla.org

**Comment by ValeriyaMetla** [comment]
#### Onboard @kyle-whitaker 09/08/22 
- [x] Google Drive
   - [x] Add to drive as Editor 
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public and note in roster
  - [x] Check for 2FA and note in roster
- [x] GitHub
     - [x] Add to team Expunge Assist
- [x] Figma
  - [x] invite
  - [ ] acceptance
- [ ] Add to email address
   - [ ] expungeassist@hackforla.org

**Comment by ValeriyaMetla** [comment]
#### Onboard @mchai1218 09/18/22 
- [x] Google Drive
   - [x] Add to drive as Editor 
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public and note in roster
  - [x] Check for 2FA and note in roster
- [x] GitHub
     - [x] Add to team Expunge Assist
- [x] Figma
  - [x] invite
  - [x] acceptance
- [ ] Add to email address
   - [ ] expungeassist@hackforla.org

**Comment by ValeriyaMetla** [comment]
#### Offboard @albagaral 9/18/22
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] Figma
  - [ ] remove from team
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Remove from email address(s)
   - [ ] expungeassist@hackforla.org

**Comment by sheronvirani21** [comment]
Onboard Kevin and Sofia

- [ ] Google Drive
   - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] 

- [ ] invitation

     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
- [ ] Add to email address(s)
   - [ ] expungeassist@hackforla.org
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by amejiamesinas** [comment]
**Onboard Anne
- [ ] Google Drive
    - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
  - [ ] Add to team Expunge Assist
  - [ ] Change membership to maintainer
- [ ] Figma
    - [ ]  invite
    - [ ] acceptance

**Comment by amejiamesinas** [comment]
**Onboard @gzhang5240
- [ ] Google Drive
    - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [x] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
  - [x] Add to team Expunge Assist
  - [ ] Change membership to maintainer
- [ ] Figma
    - [ ]  invite
    - [ ] acceptance

**Comment by amejiamesinas** [comment]
**Onboard @bethbethbeth
- [ ] Google Drive
    - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
  - [ ] Add to team Expunge Assist
  - [ ] Change membership to maintainer
- [ ] Figma
    - [ ]  invite
    - [ ] acceptance

**Comment by amejiamesinas** [comment]
**Onboard Britney
- [ ] Google Drive
    - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
  - [ ] Add to team Expunge Assist
  - [ ] Change membership to maintainer
- [ ] Figma
    - [ ]  invite
    - [ ] acceptance

**Comment by amejiamesinas** [comment]
#### Onboard @saraisabelcf
- [ ] Google Drive
   - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
- [ ] Add to email address(s)
   - [ ] expungeassist@hackforla.org
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by amejiamesinas** [comment]
#### Onboard @sylvia-nam

- [ ] Google Drive
   - [ ] Add to drive as Contributor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Slack Channels
- [ ] Google Calendar Invites

**Comment by amejiamesinas** [comment]
#### Offboard @BethBethBeth, @gzhang5240, @sofialaguna  
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s)
   - [ ] expungeassist@hackforla.org

**Comment by amejiamesinas** [comment]
#### Onboard melissareca

- [x] Google Drive
   - [ ] Add to drive as Contributor 
- [x] Roster
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public and note in roster
  - [x] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Slack Channels
- [ ] Google Calendar Invites

**Comment by amejiamesinas** [comment]
Creating Issue Template that included all steps. Issue template will now be used for on/offboarding. Closing issue since no longer needed.

**Comment by raeraeicky** [comment]
#### Onboard Prakriti Dumaru
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
      - [ ] Add to drive as Contributor 
- [ ] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
     - [ ] Send link
     - [ ] Team member adds themselves
     - [ ] Check for Public organization visibility and note in roster
     - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [ ] Add to [read vault](https://github.com/orgs/hackforla/teams/expunge-assist/members)
- [ ] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
     - [ ] invite
     - [ ] acceptance
- [ ] Slack Channels
     - [ ] confirm in team channel
     - [ ] confirm in research channel
- [ ] Google Calendar Invites  
- [ ] Wiki share
- [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Team/_edit)
- [ ] Help Identify First Issue w/ Team
- [ ] Open a ticket with the [website team to update our project card](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) to add a person to all-time contributors / current team lead if applicable.

**Comment by raeraeicky** [comment]
#### Onboard Nikita Adhikari
[nikitaadhikari11@gmail.com](mailto:nikitaadhikari11@gmail.com) GH: NikitaAdhikari113
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
     - [ ] Add to drive as Contributor 
- [ ] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
     - [ ] Send link
     - [ ] Team member adds themselves
     - [ ] Check for Public organization visibility and note in roster
     - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [ ] Add to [read vault](https://github.com/orgs/hackforla/teams/expunge-assist/members)
- [ ] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
     - [ ] invite
     - [ ] acceptance
- [ ] Slack Channels
     - [ ] confirm in team channel
     - [ ] confirm in research channel
- [ ] Google Calendar Invites  
- [ ] Wiki share
- [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Team/_edit)
- [ ] Help Identify First Issue w/ Team
- [ ] Open a ticket with the [website team to update our project card](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) to add a person to all-time contributors / current team lead if applicable.

**Comment by raeraeicky** [comment]
#### Offboard Sylvia Nam
  - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s)
   - [ ] expungeassist@hackforla.org

**Comment by raeraeicky** [comment]
#### Offboard Sara Castro
  - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] Help them delete the desktop shortcut to email address if they made one.
- [ ] Remove from email address(s)
   - [ ] expungeassist@hackforla.org

**Comment by raeraeicky** [comment]
#### Onboard Namitha Murali
namitha.murali23@gmail.com
namithamurali23

- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
     - [ ] Add to drive as Contributor 
- [ ] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
     - [ ] Send link
     - [ ] Team member adds themselves
     - [ ] Check for Public organization visibility and note in roster
     - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [ ] Add to [read vault](https://github.com/orgs/hackforla/teams/expunge-assist/members)
- [ ] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
     - [ ] invite
     - [ ] acceptance
- [ ] Slack Channels
     - [ ] confirm in team channel
     - [ ] confirm in research channel
- [ ] Google Calendar Invites  
- [ ] Wiki share
- [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Team/_edit)
- [ ] Help Identify First Issue w/ Team
- [ ] Open a ticket with the [website team to update our project card](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) to add a person to all-time contributors / current team lead if applicable.

**Comment by defnotbert** [comment]
#### Onboard Sarah Jackson
- [x] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
     - [x] Add to drive as Contributor 
- [x] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
     - [x] Send link
     - [ ] Team member adds themselves
     - [ ] Check for Public organization visibility and note in roster
     - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [x] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [ ] Add to [read vault](https://github.com/orgs/hackforla/teams/expunge-assist/members)
- [ ] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
     - [ ] invite
     - [ ] acceptance
- [ ] Slack Channels
     - [ ] confirm in team channel
     - [ ] confirm in research channel
- [ ] Google Calendar Invites  
- [ ] Wiki share
- [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Team/_edit)
- [ ] Help Identify First Issue w/ Team
- [ ] Open a ticket with the [website team to update our project card](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) to add a person to all-time contributors / current team lead if applicable.
