### ISSUE TITLE
Review of expungeassist.org for strategy

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#472]
### Overview
Content (Sam) did a quick test of expungeassist.org by entering fictional information to see what kind of letter it might produce. The product is not finished so note that there are missing parts (conclusion, introduction, etc.). 

This issue is for the PMs to review the letter produced so far, evaluate the quality of the product in regards to needs of the project at the MVP stage, and strategize about any necessary changes.

Action items are the result of the discussion. 

 
### Action Items
- [x] PMs review attached screens
- [ ] #512
- [x] PMs Discuss and decide on any strategy or plan as necessary (or not) and when
- [x] Sam makes a separate issue to fix obvious grammatical/spelling issues with Development (https://github.com/hackforla/expunge-assist/issues/479)
- [x] #485

### Resources/Instructions

See [this doc](https://docs.google.com/document/d/1gnw7YABICyxOo-HZTiQVzcVLvBgO4GU1WgxBCcLeK0M/edit#). 
There are two new content audits in [this folder](https://drive.google.com/drive/folders/1Y-sUXVs2zcEu7NsqyxNynJLlpCxyQ_XO), done after the demo mvp was more complete.

**Comment by SamHyler** [comment]
PMs, can you help me with the labels and anything else? I hope this helps clarify from yesterday. Let me know if not!

**Comment by SamHyler** [comment]
> Hey Sam. I added the labels that I felt was necessary. The only one that I was hesitant on wast he dependency one as none of the current dependency ones fit in my opinion. If you want, I can do a quick write up and give you my feedback on the images or we can have a quick call so that we all can discuss our thoughts. Your call?

Brandon - either works! I have time either way. Thank you for adding the labels and for any feedback! I'll send you a slack message.

**Comment by SamHyler** [comment]
Some other issues when I checked all boxes: Only gives option for 1 child, and field "how long have you been a parent" is really asking "how old is your child?" Since the outcome says "My child, X, is X years old." The difference matters not only for accuracy in asking but also since people might have been a parent before that child, lost a child earlier, or another situation. Could bring up trauma or misrepresent the situation for the user.

**Comment by brandohayes** [comment]
PM's met with Sam today and reviewed the screen shots. We agreed that the issues definitely need to be changed and altered however we may not make the MVP date if we focus heavily on the content changes. We will discuss this with Dev during the team meeting tomorrow and formulate a better plan on when and how to get this completed.

**Comment by Andan-Eddy** [comment]
I took part in PM review on 2.21.2022
