### ISSUE TITLE
Small content changes to letter generator

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#479]
### Overview
Here are two small content changes to the MVP letter generator. Other larger content changes are being discussed. 

### Action Items
- [x] Change spelling of "believe" in involvement/job/unemployed ("I **believe** that having my record cleared would help me find a job and be more involved in my community").
- [x] Make punctuation consistent for user entered fields. Either a period is added for the user at the end or not. Alt. a better solution to detect and add (or not) punctuation based on user input. Example: "Goals" A period is not automatically entered for the user in the first field, but a period is entered for the user in the second field causing a potential double period.

**Comment by SamHyler** [comment]
@aahvocado here are the two small things we talked about earlier. Feel free to (re)assign this within Development. I probably got some of the labels wrong as well, sorry for that.

**Comment by aahvocado** [comment]
Consistency ruling for the period will now be as follows: if user can type multiple sentences we will not insert a period for them.
