### ISSUE TITLE
Usability testing: Pre-Test Questions

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#480]
### Overview
Create pre-test questions for usability testing.  This is to focus on their use of technology, and specific questions for legal professionals about creating declaration letter. 
### Action Items
- [x] create questions for legal clinic professionals 
- [x] Review task list with team 
   - [x] Make changes requested
- [x]  Remove Dependency from #444
- [x]  Close this issue when complete

### Working Draft 
Go to the Working Draft, find the section for screener and your name assigned, make changes: #442

**Comment by yumengluo** [comment]
Added and edited a few questions on the pre-test questions.

**Comment by ValeriyaMetla** [comment]
@yumengluo please see my comments in the research plan, last revisions on pre-test quessitons so I can close this issue
