### ISSUE TITLE
review accessibility of app

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#487]
DEPENDENCY: Have the product (MVP) ready for release to do the actual review, with all the elements that will be included. 

I noticed that when pressing Tab to cycle through Radio options, it would skip the others. This will be fixed but we need to make sure the rest of the app is also a11y compliant.

Things like screen readers, vision impairment, motor impairment, etc.

**Comment by sydneywalcoff** [comment]
Being handled in issue #1060.
