### ISSUE TITLE
Update Team Wiki / Product Manager Wiki Pages

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#502]
### Overview
We need to do basic housekeeping of the Wiki page  (who are the PMs, link to onboarding and offboarding issue).

### Action Items
- [x] [Take inventory of existing EA Wiki pages](https://docs.google.com/spreadsheets/d/1b54NUoUmTDQSme3V3bVVmLfAudP7NPuFhtv06RWzoqQ/edit#gid=0) / research what other projects do well
- [x] Update Joining the Team page 
   - [x] Document current onboarding process (link to onboarding & offboarding issue)
   - [ ] Add onboarding items across teams (Research, Development, Design, Content, etc.)
- [x] Update The Team page (add your team members)
- [x] [Update Repo Readme.md](https://github.com/hackforla/expunge-assist)
- [x] Update Resources page (make sure all links are current, anything is missing?)
- [x] Clarify role title preference - Web developer vs frontend - on wiki
 
### Resources/Instructions
[Doc for inventory of all Wiki pages ](https://docs.google.com/spreadsheets/d/1b54NUoUmTDQSme3V3bVVmLfAudP7NPuFhtv06RWzoqQ/edit#gid=0) 
https://github.com/hackforla/expunge-assist/wiki/Product-Manager-and-Owner
https://github.com/hackforla/expunge-assist/wiki/Joining-the-Team - Additionally as PM's, we will update the wider team org wiki pages e.g. https://github.com/hackforla/expunge-assist/wiki/Glossary

https://github.com/hackforla/expunge-assist/projects/1?card_filter_query=label%3A%22feature%3A+wiki%22 related Wiki issues
https://github.com/hackforla/internship/wiki/Volunteer-Overview Internship Project - Good example reference

**Comment by ValeriyaMetla** [comment]
I added the team members, please double check for each team. 
I also worked on joining the team page (still need to better incorporate GitHub onboarding process)
PMs please add your meeting times.

**Comment by jamiesiu** [comment]
To support sweeping wiki update efforts with https://github.com/hackforla/expunge-assist/issues/723, all EA disciplines including Product Management are looking to update their respective wiki pages to ensure potential visitors to wiki pages get a fair / updated representation of team and our process (e.g. no draft, template pages)

**Comment by jamiesiu** [comment]
Going thru inventory of existing pages. Kelsey / UXR open to helping. Noting that many of our onboarding / project start pages and common files are out of date. Contributing guide for Dev (https://github.com/hackforla/expunge-assist/blob/main/products/statement-generator/CONTRIBUTING.md) is nested within a diff path outside wiki and should perhaps be hosted in wiki section

**Comment by jamiesiu** [comment]
- removed draft header messages on pages
- deleted pages for data scientist / other volunteer that were not being used 
- removed majority of duplicative information in repo front page, direct viewers to wiki pages

**Comment by jamiesiu** [comment]
* Updated Product Manager/Owner page
* further slight edits and adjustments for typos 
* updated team roster
