### ISSUE TITLE
Update Wiki for Content

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#505]
### Overview
Update wiki with information from and about the content team. This issue is primarily to document the work the Content has done thus far to help future team members orient and understand the history and trajectory. 

NOTE: this document/wiki needs to be updated continuously (every month-3months or by phase) by the content team as work progresses

### Action Items
- [x] Gather information about Content work June 2021 -present in one document
- [x] Create a clear timeline with the overview of the Content process
- [x] Add important issues to document
- [x] Handover to PMs for adding to wiki

### Resources/Instructions
This [document](https://docs.google.com/document/d/1W2zFZxBvFfzLaPlv51LEzQx3J_0fCiy_XlBYjN59IUA/edit).

**Comment by SamHyler** [comment]
outline documentation/timeline created, need to add links to docs and github issues. Pending further info of how and where it should be added.

**Comment by SamHyler** [comment]
I've created a draft of this documentation. I know this has been on the back burner for a while, grateful if a PM could have a look when you have time and let me know what needs to be added or changed, and if there is a structure to get it ready for Github/Wiki. Also, would it be important to link any specific issues from Github? @jamiesiu @ValeriyaMetla

**Comment by ValeriyaMetla** [comment]
@SamHyler thank you! We will check the issues structure around Wiki to see if anything could be linked to the issue. Also, did the development (Dan) made a doc about how to work with Wiki page? I remember there was some guidance from him on Slack.

**Comment by SamHyler** [comment]
I've updated the document. To your questions @Val: Dan created a resource for updating content using code [here](https://github.com/hackforla/expunge-assist/wiki/Updating-Content). I've added it to the doc.

**Comment by jamiesiu** [comment]
The instructions that Dan provided are for updating the EA website text. Since this is on the GH wiki, it can be updated similar to updating a GH issue/ticket text using the markdown formatting. Made the change here https://github.com/hackforla/expunge-assist/wiki/Content-Writer . Let us know if anything needs further updating @SamHyler . Otherwise, we can close this out

**Comment by SamHyler** [comment]
Thank you so much @jamiesiu ! I will close it. I wonder what the best practice for updating it would be? How can we set a reminder to check in and update it every month-3months (is this a good time frame)?

**Comment by jamiesiu** [comment]
No problem! That's a good question. For this type of documentation, I would suggest quarterly is a good balance of time vs the energy it would take to collect info and update it again. We could do recurring google calendar reminders for that frequency and a GitHub issue with a dependency of a date 3 months for now.
