### ISSUE TITLE
Internal User Research Plan & Guide 

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#507]
Overview
The team will conduct internal usability testing with HfLA volunteers. 

Details
This version is missing a lot of features, so we will only test it within the organization. 

Action Items
- [x] Create document for internal testing 
- [x] Develop
   - [x]  research plan
   - [x]  task guide 
   - [x]  materials for testing (Clandly, recruitment message, template for note)
- [x] Review with Org (Bonnie)
   - [x] Make changes requested
   - [x] Get Org Signoff
- [x] Close this issue when complete

Final Draft:
[Internal Testing Research Plan](https://docs.google.com/document/d/11PQAi72WbArX6w_YrJxAhgWizsLDexIQKbQ6NWD8kxE/edit#)
[Internal Testing Moderator Guide](https://docs.google.com/document/d/1STbiyliXovuQ6H-fi-_LJp-3YcTae6uY4I67r62W2Ac/edit#heading=h.z5z09tesesye)
[Internal Testing Notetaking Template](https://docs.google.com/document/d/1BHVxs-5f-Ew3MFl8_zE_DS0s578_IObe/edit#heading=h.ag0hygdfx7n1)
[Calendly link](https://calendly.com/expungeassist-ux/30min?month=2022-04)
[Session Tracker](https://docs.google.com/spreadsheets/d/1bO0xvQ1JAiKCBKOboarJqNXskUO_wstOiuDrNeTHAnE/edit#gid=0)
[User Responses for Analysis_Excel](https://docs.google.com/spreadsheets/d/1l1jnJ1fqDOo-KGTfPqTLweypDDoxHkeToxN4Px1AVac/edit#gid=0)

**Comment by ValeriyaMetla** [comment]
@ana-lobos please attach the doument for internal testing to the issue

**Comment by ValeriyaMetla** [comment]
@rhiannab and @Ndoyle118 feel free to work on internal usability when the doc is created

**Comment by Ndoyle118** [comment]
> I've edited and updated a bulk of this document for formatting and content. If anyone is available to review and/or accept changes, please let me know.

I can take a look!

**Comment by ValeriyaMetla** [comment]
@rhiannab and @Ndoyle118 I assigned you to this issue to start working on the internal testing guide. 
@yumengluo can you help out with this?

**Comment by yumengluo** [comment]
I left some comments on the doc.

**Comment by ana-lobos** [comment]
Recruitment message (copy/paste to Slack to see animated emojis):

Website launch - help needed :mario_luigi_dance:

Expunge Assist is launching a website to help justice-impacted individuals clear their records. Can you spare 30 minutes for a usability test on Zoom?  :party_blob:

Who: You! No past criminal record needed to participate :eyes: We will provide you with all you need to test the website :ok_hand:

How: Sign up [here](https://calendly.com/expungeassist-ux/30min?month=2022-04&date=2022-04-24) :gratitude-thank-you:

**Comment by w0ahth3re** [comment]
Bonnie suggested https://support.google.com/a/users/answer/9308875?hl=en is an alternative to Calendly if needed

**Comment by ExperimentsInHonesty** [comment]
In the intro
We will ask you at the end of the interview how public you want your answers to be made. The level of disclosure will be completely in your control because we want you to answer freely. You can also completely opt-out of any of your interview data being used at any point

At the end
![image](https://user-images.githubusercontent.com/37763229/163494487-7459b933-37d2-4b80-9d5a-ca53f435d507.png)

**Comment by ValeriyaMetla** [comment]
The recruitment message was slightly modified. Here is the final version. @ExperimentsInHonesty please use this to circulate. 

**Recruitment message (copy/paste to Slack to see animated emojis):**

:mario_luigi_dance: Website launch - help needed 
Expunge Assist is launching a website to help justice-impacted individuals clear their records. Can you spare 30 minutes for a usability test on Zoom? :party_blob:
Who: You! No past criminal record needed to participate :eyes: We will provide you with all you need to test the website :ok_hand:
How: Sign up through Calendly :gratitude-thank-you:

**Comment by ValeriyaMetla** [comment]
The research plan and guide was approved by Bonnie. The internal testing was completed on the 04/29/22.
