### ISSUE TITLE
Discover typical/common format for a letter to a judge [usability testing]

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#512]
### Overview
What does a letter to a judge look like? What are some examples? Which ones are well received by the court system and what would be '(un)acceptable?'

Content + UXR collaboration. Perhaps UXR connection with potential partners could help to find real examples of letters (we can always exclude personal information/anonymize them)

### Action Items
- [x] Find examples of actual (real) letters that were accepted/helped in court cases 
- [x] Analyze and extrapolate the important elements of successful letters
- [x] Distill recommendations for letter formatting that can be used to create the next version of the Expunge Assist letter generator
- [ ] Find ways to add letter examples to the website (collab with Design) 

### Resources/Instructions

- Google [doc](https://docs.google.com/document/d/1Ym5bKhG38DKMa0kO7MSGd72wac0scL4KDPQ2rAF-cFo/edit#heading=h.rijmxkeinmy4) on samples of declarations, links, and other resources
- Letters can be submitted as a separate document or its content can be included in the Declaration form [MC-030](https://www.courts.ca.gov/documents/mc030.pdf) as well as MC-031.

**Comment by SamHyler** [comment]
let's prioritize this for the post-MVP version of the letter generator

**Comment by SamHyler** [comment]
@jbsteinhardt this issue is for UXR/Content collab when we're ready to take it up again.

**Comment by SamHyler** [comment]
Unsure if we are still able to do this. Will raise again with new UXR team

**Comment by sylvia-nam** [comment]
@SamHyler @emmathrash Here's the most recent version of the [document](https://docs.google.com/document/d/1Ym5bKhG38DKMa0kO7MSGd72wac0scL4KDPQ2rAF-cFo/edit#heading=h.rijmxkeinmy4) for UXR x Content x Design collaboration needs

**Comment by sylvia-nam** [comment]
@SamHyler @emmathrash Here's the most recent version of the [document](https://docs.google.com/document/d/1Ym5bKhG38DKMa0kO7MSGd72wac0scL4KDPQ2rAF-cFo/edit#heading=h.rijmxkeinmy4) for UXR x Content x Design collaboration opps

**Comment by sylvia-nam** [comment]
One comment from Bonnie in her review of the EA site was that the sample letters on the EA landing page are too similar (all from vets, specifically). Instead what is needed is variation.

**Comment by SamHyler** [comment]
Is this issue done and can be closed? @sylvia-nam ? We might consider creating an issue to take results further @anitadesigns @jyehllow @emmathrash ? So this doesn't get lost in the shuffle?

**Comment by sylvia-nam** [comment]
@SamHyler I wouldn't close until there is discussion with Design and actionable next steps. 
The current site has an image of 1 letter that is fully visible and 2 that are obscured. Worth discussion: 1) Is this image selection a best practice? What's the point of samples that you can't read for ex. 2) Are these letters fictional or real?Transparency is important, given V&T exercise, etc. 3) Why is it on the landing page? Is it a shorthand about product benefits? If so can we discuss placement?

**Comment by anitadesigns** [comment]
@sylvia-nam @SamHyler are these the images of the letters in reference? 

![Image](https://github.com/user-attachments/assets/b00b1dbe-325e-4bd3-85f4-3e5d495c41fb)

**Comment by SamHyler** [comment]
I believe those are what @sylvia-nam  is referencing, @anitadesigns. However the issue is about the format for a letter to a judge that exists in the legal system and with legal aid clinics, not what our product looks like. This issue is about discovery research outside out product to inform choices about our product in a broad sense.

**Comment by anitadesigns** [comment]
Considering the background of this issue, I am open to closing this issue as well

**Comment by SamHyler** [comment]
Thanks Anita, closing issue.
