### ISSUE TITLE
Rewrite landing page text

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#522]
### Overview
Update landing page text (and one page text), specifically this sentence:

"Expunge Assist aims to help people in California with criminal records accomplish record clearance, expungement, or a reduction and subsequently a second chance as a part of society."

This sentence also appears on the one page, and should be updated wherever it appears.

The issue is with the sentiment of "second chance."

### Action Items
- [x] Rewrite text

### Resources/Instructions
Add google doc here

**Comment by cynphonic** [comment]
[Quote rewrite](https://docs.google.com/document/d/12Tz1a8NjLPsgfKrBhYXeLBWV7mLGHMYP81KQYUmktEQ/edit)

For landing page, quote rewrite
