### ISSUE TITLE
Before you begin for MVP

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#523]
### Overview
Rewrite before you begin for MVP launch. This will be a compromised version for the launch, and a more robust version will be written for the next version of the product. 

### Action Items
- [x] Check existing version and version written for post-MVP launch and pull most important bits
- [x] "Rewrite before you begin "page

### Resources/Instructions
Rewrite is found in [this]([Before you begin](https://docs.google.com/document/d/1nu8zX3MJAKIvlfkv2rveEFM4WvYKTffrbVDy7ixCzsg/edit#heading=h.oajagfk44ihz)) google doc.

**Comment by cynphonic** [comment]
[Before you begin](https://docs.google.com/document/d/1nu8zX3MJAKIvlfkv2rveEFM4WvYKTffrbVDy7ixCzsg/edit#heading=h.oajagfk44ihz)

**Comment by SamHyler** [comment]
@cynphonic made a first draft but we didn't finish before internal user testing. Putting a hold on this issue until we get feedback from testing and will finish based on that feedback for the next version of the product.

**Comment by SamHyler** [comment]
Content made progress and collaboration with Design on the landing page, but didn't finish before usability testing. Therefore we will update the landing page now based on results from testing. Closing and will reopen a new issue later.

**Comment by SamHyler** [comment]
Closing the issue and will open a new issue for this page when it's time to create a new draft.
