### ISSUE TITLE
Another update to "advice for a successful declaration letter"

### ISSUE THREAD

**Issue by cynphonic** [hackforla/expunge-assist#532]
### Overview
Update the copy on the 'advice for a successful personal statement' page to create consistent and clear instructions for users to complete their letter writing tasks. We would like to make a small change

### Action Items

- [x] Update copy on existing "advice for a successful declaration letter"
- [x] Decide between removing or keeping punctuation after numerical lists
- [x] Add in quotations for examples
- [x]  Change "do not" to "don't" for consistency
- [x] Remove punctuation in bullet lists
- [x] Mockup in Figma

### Resources/Instructions
Related to Issue [#488](https://github.com/hackforla/expunge-assist/issues/488)
[Document with copy changes](https://docs.google.com/document/d/13iCW24CSVEZZOgxfFp4qMms7tv-PR-Oje6gygNcAGow/edit)

**Comment by SamHyler** [comment]
hey @cynphonic  could you check off the boxes here? Is this issue done?

**Comment by SamHyler** [comment]
@jamiesiu  this was before IUT 1, so milestone was wrong. Not sure if I gave it the right one...
