### ISSUE TITLE
Another update to "advice for a successful declaration letter"

### ISSUE THREAD

**Issue by cynphonic** [hackforla/expunge-assist#533]
### Overview
Update the copy on the 'advice for a successful personal statement' page to create consistent and clear instructions for users to complete their letter writing tasks. We would like to make a small change

### Action Items
- [ ] Change "do not us profanity" to "don't use profranity" for consistency in first bullet point
- [ ] Change expunge my record because I need a new job to "expunge my record because I need a new job" (add in quotation marks)
- [ ] Change I want to expunge my record because I want to apply for jobs. to “I want to expunge my record because I want to apply for jobs.” (add in quotation marks)
- [ ] Remove punctuation after bullet points

### Resources/Instructions
Related to Issue [#488](https://github.com/hackforla/expunge-assist/issues/488)
[Document with copy changes](https://docs.google.com/document/d/13iCW24CSVEZZOgxfFp4qMms7tv-PR-Oje6gygNcAGow/edit)

**Comment by aahvocado** [comment]
@cynphonic Does this look right?
![Screen Shot 2022-04-07 at 6 10 46 PM](https://user-images.githubusercontent.com/2266545/162343738-278cb89b-4aea-4a80-b9fd-d6f78a0ff19c.png)
