### ISSUE TITLE
Request to do content check in 2 google forms

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#542]
### Dependency
- [x] #331 
- [ ] #332 

### Overview
Content received a request to look over the content in two google forms. 

These are the related issues: https://github.com/hackforla/expunge-assist/issues/332  and https://github.com/hackforla/expunge-assist/issues/331

More information needed about the goals, purpose, and how to make changes to complete the task. 

### Action Items
- [ ] Look over text 
- [ ] Strategize and make any changes
- [ ] ?
- [ ] Request login to make changes?

### Resources/Instructions

The google forms are here

https://docs.google.com/forms/d/e/1FAIpQLSeMQTeWMGsKozC1al2jR857aEBAV3UwX7v4m3b3zOxibggswg/viewform

https://docs.google.com/forms/d/e/1FAIpQLScyfAr9d7I4yCpsj-k1VgYkkYlZipdxlAEdl7oMA7rVG3g4Jw/viewform

**Comment by SamHyler** [comment]
@thomasdemoner got this request from you via a slack thread. When you have time to clarify, we can get started on this issue.

**Comment by anitadesigns** [comment]
@SamHyler close?

**Comment by SamHyler** [comment]
Issue was not clarified in over a year, figure it is not relevant any longer. Closing.
