### ISSUE TITLE
Onboard & Offboard: UX / UI Designer

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#543]
### Dependency 
Waiting to have a UX/UI Designer to on/off-board.

### Overview
We need to have a checklist of items to do when a UX / UI Designer onboards and offboards so that the process can be consistent and fast.

### Date Updated
(insert date you created this issue and keep updating the date each time the org template change are integrated)
2022-04-20

### Action Items
- [ ] Check to see if the org template for this process has new steps in it, and if it does, update this  issue and its template with content and add the last date you updated the template below
- [ ] Copy template to comment below
- [ ] Add name of person
- [ ] Check off as done

```
#### Onboard
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [ ] Add to drive as Contributor
- [ ] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public organization visibility and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [ ] Add to read vault
- [ ] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [ ] Wiki share
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
- [ ] Help Identify First Issue w/ Team

```
```
#### Offboard
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] demote to view access
- [ ] Wiki / HFLA website team roster Update
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
  - [ ] [Update HFLA Website "Current Team" as needed](https://www.hackforla.org/projects/expunge-assist.html)
- [ ] Google Calendar
  - [ ] removes from sync invites

```

### Resources/Instructions
- 1password.com access is managed by Bonnie
- [Expunge Assist Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n?usp=sharing)
- [Expunge Assist Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
- Check public organization visibility and 2FA at [people page](https://github.com/orgs/hackforla/people). Can toggle your personal settings at this page with your username highlighted. 
- [Expunge Assist GitHub Team URL](https://github.com/orgs/hackforla/teams?query=expunge)
   - [base (read)](https://github.com/orgs/hackforla/teams/expunge-assist/members)
   - [write](https://github.com/orgs/hackforla/teams/expunge-assist-write)
   - [maintain](https://github.com/orgs/hackforla/teams/expunge-assist-maintainers)
   - [triage] - no triage team
   - [admin](https://github.com/orgs/hackforla/teams/expunge-assist-admins/members)
- Shortcut for adding a profile to the desktop:  chrome://settings/manageProfile
- Tutorials
  - [Forward emails to team members](https://github.com/hackforla/product-management/wiki/Forward-emails-to-team-members)

[org template](https://raw.githubusercontent.com/hackforla/.github/main/.github/ISSUE_TEMPLATE/onboard---offboard--product.md) updated 2022-02-09

Reference for parity
* https://github.com/hackforla/expunge-assist/issues/456
* https://github.com/hackforla/expunge-assist/issues/464

**Comment by jamiesiu** [comment]
#### Onboarding for Serena Sanders (by Daisy)
- [ ] Google Drive
   - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
- [ ] Add to email address(s)
   - [ ] expungeassist@hackforla.org
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by jamiesiu** [comment]
#### Onboard with Anita Morales @anitadesigns 
- [ ] Google Drive
   - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
- [ ] Add to email address(s)
   - [ ] expungeassist@hackforla.org
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by jamiesiu** [comment]
#### Onboard Sam C.
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] Google Drive
   - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist write vault
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs

**Comment by jamiesiu** [comment]
#### Onboard Sarah Ahmed
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] Google Drive
   - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist write vault
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs

**Comment by jamiesiu** [comment]
#### Onboard Snigdha Behara
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] Google Drive
   - [ ] Add to drive as Editor 
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist write vault
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs 

(Below primarily for Product/Leads)
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
- [ ] Add to email address(s)
   - [ ] expungeassist@hackforla.org
- [ ] Train how to 
   - [ ] login to team account
   - [ ] setup chrome shortcut for adding to desktop
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite

**Comment by jamiesiu** [comment]
#### Onboard David Lee
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public organization visibility and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist write vault
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [ ] Wiki share

**Comment by jamiesiu** [comment]
#### Onboard Phuong (Phu)
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public organization visibility and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist write vault
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [ ] Wiki share
- [ ] Help Identify First Issue w/ Team

**Comment by jamiesiu** [comment]
Removed several alumni members from the Github EA write vault as they are no longer active and would not require edit access.

**Comment by jamiesiu** [comment]
#### Onboard Justin Yeh
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public organization visibility and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist write vault
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [ ] Wiki share
- [ ] Help Identify First Issue w/ Team

**Comment by jccchurch** [comment]
#### Onboard Michelle Bui
- [x] Design / PM Walkthrough
   - [x] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [x] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [x] Add to drive as Contributor
- [ ] [Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
  - [x] Send link
  - [ ] Team member adds themselves
  - [x] Check for Public organization visibility and note in roster
- [x] GitHub
     - [x] Add to team Expunge Assist write vault
     - [x] Add to read vault
- [x] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
  - [x] invite
  - [ ] acceptance
- [x] Slack 
  - [x] confirm in team channel
  - [x] confirm in design/content channel
- [x] Google Calendar
  - [x] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [x] Wiki share
  - [x] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
- [ ] Help Identify First Issue w/ Team

**Comment by jccchurch** [comment]
#### Onboard Elizabeth Brown
- [x] Design / PM Walkthrough
   - [x] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [x] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [x] Add to drive as Contributor
- [ ] [Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
  - [x] Send link
  - [ ] Team member adds themselves
  - [x] Check for Public organization visibility and note in roster
- [x] GitHub
     - [x] Add to team Expunge Assist write vault
     - [x] Add to read vault
- [x] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
  - [x] invite
  - [ ] acceptance
- [x] Slack 
  - [x] confirm in team channel
  - [x] confirm in design/content channel
- [x] Google Calendar
  - [x] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [x] Wiki share
  - [x] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
- [ ] Help Identify First Issue w/ Team

**Comment by amejiamesinas** [comment]
### Offboard Phuong, Serena, & David Lee
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] demote to view access
- [ ] Wiki / HFLA website team roster Update
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
  - [ ] [Update HFLA Website "Current Team" as needed](https://www.hackforla.org/projects/expunge-assist.html)
- [ ] Google Calendar
  - [ ] removes from sync invites

**Comment by anitadesigns** [comment]
#### Onboard Amanda Castro-Caballero
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [ ] Add to drive as Contributor
- [ ] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public organization visibility and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [ ] Add to read vault
- [ ] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [ ] Wiki share
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
- [ ] Help Identify First Issue w/ Team

**Comment by amejiamesinas** [comment]
#### Onboard @adammitch3ll
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [ ] Add to drive as Contributor
- [ ] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public organization visibility and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [ ] Add to read vault
- [ ] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [ ] Wiki share
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
- [ ] Help Identify First Issue w/ Team

**Comment by amejiamesinas** [comment]
#### Onboard @amandacaballero
- [x] Design / PM Walkthrough
   - [x] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [x] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [x] Add to drive as Contributor
- [x] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
  - [x] Send link
  - [x] Team member adds themselves
  - [x] Check for Public organization visibility and note in roster
- [x] GitHub
     - [x] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [x] Add to read vault
- [x] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
  - [x] invite
  - [ ] acceptance
- [x] Slack 
  - [x] confirm in team channel
  - [x] confirm in design/content channel
- [x] Google Calendar
  - [x] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [ ] Wiki share
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
- [ ] Help Identify First Issue w/ Team

**Comment by anitadesigns** [comment]
### Offboard Adam Mitchell

- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [ ] Add to drive as Contributor
- [ ] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public organization visibility and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [ ] Add to read vault
- [ ] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [ ] Wiki share
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
- [ ] Help Identify First Issue w/ Team

**Comment by anitadesigns** [comment]
#### Offboard Elizabeth Brown
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] demote to view access
- [ ] Wiki / HFLA website team roster Update
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
  - [ ] [Update HFLA Website "Current Team" as needed](https://www.hackforla.org/projects/expunge-assist.html)
- [ ] Google Calendar
  - [ ] removes from sync invites

**Comment by anitadesigns** [comment]
#### Offboard Michelle Bui
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] demote to view access
- [ ] Wiki / HFLA website team roster Update
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
  - [ ] [Update HFLA Website "Current Team" as needed](https://www.hackforla.org/projects/expunge-assist.html)
- [ ] Google Calendar
  - [ ] removes from sync invites

**Comment by anitadesigns** [comment]
#### Onboard Ellynna Ruan 
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [ ] Add to drive as Contributor
- [ ] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public organization visibility and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [ ] Add to read vault
- [ ] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [ ] Wiki share
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
- [ ] Help Identify First Issue w/ Team

**Comment by anitadesigns** [comment]
#### Onboard Christina Campbell
- [ ] Design / PM Walkthrough
   - [ ] Team share / demo of work in progress e.g. Design System, Figma, current iterations 
- [ ] [Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n)
   - [ ] Add to drive as Contributor
- [ ] [Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public organization visibility and note in roster
- [ ] GitHub
     - [ ] Add to team Expunge Assist [write vault](https://github.com/orgs/hackforla/teams/expunge-assist-write)
     - [ ] Add to read vault
- [ ] [Figma team invite](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
  - [ ] invite
  - [ ] acceptance
- [ ] Slack 
  - [ ] confirm in team channel
  - [ ] confirm in design/content channel
- [ ] Google Calendar
  - [ ] send invites to syncs 
- [ ] Additional documentation 
  - [ ] e.g. Share latest Usability Testing Results
- [ ] Wiki share
  - [ ] [Update Team Roster Wiki](https://github.com/hackforla/expunge-assist/wiki/The-Team)
- [ ] Help Identify First Issue w/ Team

**Comment by CBx3000** [comment]
Hey @anitadesigns  ! I was going through the GitHub onboarding /off boarding issues I was tagged in and I don't see the Github user names for the following people on the Team Roster . I’m trying demote / give them Github access :

Christina Campbell
Ellynna Ruan
Elizabeth Brown
Michelle Bui

I also wasn’t able to demote two of the designers to a viewer in the EA Google Drive : Elizabeth Brown and Michelle Bui .

**Comment by anitadesigns** [comment]
hey @CBx3000 found the GitHub user names! I attached them below:

Christina Campbell: ChrisCamp201
Ellynna Ruan: eruan8888
Elizabeth Brown: ermbrown
Michelle Bui: mbui31

**Comment by anitadesigns** [comment]
We are creating entirely new issues to onboard and offboard. Dev is creating templates for us to use

**Comment by mariaweissman** [comment]
Transitioned into using Issue template

**Comment by mariaweissman** [comment]
> > > [@mariaweissman](https://github.com/mariaweissman) [@shraddhasaraf](https://github.com/shraddhasaraf) for all other teams, we use this issue for getting new volunteers access, and then they do self-onboarding in a separate issue. is there a reason this is being done differently for design?
> > 
> > 
> > [@raeraeicky](https://github.com/raeraeicky) I think the teams have mostly transitioned to using issue templates at different points instead of this (so two different issues instead of a comment on this + another pre-work issue for self-onboarding). You use the template for onboarding logistics. Then, they "self-onboard" by being assigned "Pre-work: Design"
> > Anita's comment from Aug 2024 here: [#543 (comment)](https://github.com/hackforla/expunge-assist/issues/543#issuecomment-2308951627)
> > After clicking "new Issue" these pop up:
> > Issue 1 - to onboard the person ![Image](https://github.com/user-attachments/assets/718d155c-4512-4cf6-8ee6-479e9c49bc70)
> > Issue 2 - to get them used to the different processes ("Self-onboarding") ![Image](https://github.com/user-attachments/assets/3ebeb454-bdda-405f-9260-d9ba86e04bd5)
> 
> I think we're saying a similar thing about the two separate issues, but is this creating a new issue to onboard/offboard every new designer, instead of keeping it in the comments of one issue like every other team is using?

@raeraeicky that's my understanding of what design has wanted to do, based on anita's above comment from August 2024 "We are creating entirely new issues to onboard and offboard. Dev is creating templates for us to use". @sydneywalcoff do you have any more info on teams onboarding/ offboarding via a comment on one ongoing issue in the "start here" column vs. using a template to make a new issue? it looks like [dev also switched to a template in 2024](https://github.com/hackforla/expunge-assist/issues/749#issuecomment-1986425849)?
