### ISSUE TITLE
Create recommendations for improvements to the EA Design System

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#551]
### Dependency
- #544 

### Overview
Create recommendations for improvements to the EA Design System. These will be valuable for feedback discussions with the team and informing implementation of changes. 

### Action Items
- [x] Review gaps and opportunities identified during [diff analysis step](https://github.com/hackforla/expunge-assist/issues/544) 
- [x] Define recommended changes (in writing)
- [x] Share with Design & Content team for feedback

### Resources/Instructions
* Refer to the diff analysis results listed in Figma. Currently at https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A2 
* Prioritization of recommendations will likely be influenced by internal usability testing results from the UX Research team.

**Comment by anitadesigns** [comment]
Information and status of this issue were shared and expanded on #750 . Closing this issue as the Design team is working on auditing and improving our design system.
