### ISSUE TITLE
Create Content/Writing Guidelines page in Figma 

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#557]
### Overview
The Content/Writing Guidelines exist now in a Google Doc on the shared drive. The idea is to transfer this information into Figma and create it in an accessible way across teams. 

Housing the guidelines in Figma makes it more visible and accessible to all who write on the product.

### Action Items
- [x] Create a separate page and create a template in Figma to house the guidelines
- [x] Transfer information from the Google Doc
- [ ] Design to be easy to read and digest in a Figma format rather than the existing text heavy Google Doc format
- [x] Decide where to keep the source of truth (perhaps it should be Figma)
- [ ] Communicate and disseminate information about guidelines to the whole team (possible present at an All-Teams meeting) 

### Resources/Instructions
[Figma page Content Guidelines
](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A19)

[Writing/Content Guidelines on google drive](https://docs.google.com/document/d/1w8iHLEjgBlkwi6jm7XgLoI0RE3JtmUnJtCq3psks1nI/edit?usp=drive_web&ouid=107153008429615125872)

**Comment by SamHyler** [comment]
Finished transferring information except for the chart. Needs that and a second look for design elements before putting into ready for review.

**Comment by SamHyler** [comment]
Everything is in Figma now, needs to be designified

**Comment by SamHyler** [comment]
Could very much use a second pair of eyes on this @ Design team and @cynphonic. 

Everything is in Figma since June 5th, just needs a more useful format.

**Comment by ValeriyaMetla** [comment]
@SamHyler can you put the links to the doc and Figma page. @jamiesiu not sure if you had a chance to review this but seems like we need design team feedback. I will review after links are attached:) Thank you Sam!

**Comment by SamHyler** [comment]
> @SamHyler can you put the links to the doc and Figma page. @jamiesiu not sure if you had a chance to review this but seems like we need design team feedback. I will review after links are attached:) Thank you Sam!

Yes of course, sorry for that! It's ready @jamiesiu @ValeriyaMetla

**Comment by SamHyler** [comment]
adding @RenaNicole and @anitadesigns  for review

**Comment by SamHyler** [comment]
Has been done a long time ago, closing
