### ISSUE TITLE
Cosmetic changes re: info links and Nav bar, based on feedback

### ISSUE THREAD

**Issue by thomasdemoner** [hackforla/expunge-assist#571]
### Overview
Cosmetic changes based on internal feedback that we should test. 

### Action Items
Address issues with small links in the footer that were hard to find, and the nav bar that people looked for for information.

- [ ] Make Nav bar under the logo header.
- [ ] Move About Us and FAQ links from the footer to the Nav bar and increase font size.

**Comment by thomasdemoner** [comment]
@jamiesiu
Just a reminder, we should have Content update the FAQ page to address and link to the About Us, Privacy Policy, and Terms of Use pages from within itself - if it doesn't already.

**Comment by jamiesiu** [comment]
thanks for reminder @thomasdemoner . will check with the Content team
