### ISSUE TITLE
Update header & footer with bigger fonts and new navigation links

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#573]
### Overview
Update header & footer with bigger fonts and new navigation links

### Action Items
- [x] Update header and footer font size
- [x] Update location of links so users can locate information more easily
- [ ] As needed, further update header and footer design to be more visible

### Resources/Instructions
According to the [Internal Usability Testing Report](https://docs.google.com/document/d/1N0u7c1RwbxglQpLk_lIgbhDnAenMhCwNPazcNHI9aJI/views), several users had trouble finding information on the expungement process. 
Update to be made at Figma design section - [June 1 Landing Page](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A23) created by Serena

**Comment by aahvocado** [comment]
Attached a screenshot to #577

**Comment by anitadesigns** [comment]
Creating a footer for mobile and handing off to Dev

**Comment by anitadesigns** [comment]
Presenting to Design for approval
