### ISSUE TITLE
Create Zoom Background for Expunge Assist Project

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#575]
### Overview
Create Zoom Background for Expunge Assist Project

### Action Items
- [ ] Get example from Bonnie
- [x] Create Zoom Background using our logo

### Resources/Instructions
[Expunge Assist Logos & Assets](https://drive.google.com/drive/u/0/folders/1Eu2kVpimmJK9Lptkbs3tpxSMgGfj35tT)

**Comment by jamiesiu** [comment]
@ExperimentsInHonesty could you provide an example and further clarity around what we should be doing for this?

**Comment by jamiesiu** [comment]
@RenaNicole will take a look and see what they can come up with

**Comment by jamiesiu** [comment]
@RenaNicole 

Examples from Bonnie 
* https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?node-id=2%3A19. taken from a charity event. You can notice from the screenshots that the speaker has a dynamic-looking type background that draws your attention to the speaker and has their project name in the corner. Perhaps we can do similar with a purple background? 
* [TDM Calculator project sample background](https://drive.google.com/file/d/16aNtApSem_NmGORgHeZn3ZULSeZBIjFu/view)

**Comment by mbui31** [comment]
@anitadesigns @jccchurch Not sure if the direction/goals/vision of this project has changed but I created some mockups in Figma & will tag you for fb!
