### ISSUE TITLE
Include simple explanation of how private data will be used for EA Website

### ISSUE THREAD

**Issue by ValeriyaMetla** [hackforla/expunge-assist#579]
### Dependency
- [ ] #62 

### Overview
The usability testing showed that users struggled with finding a simple explanation of how their data will be used, whether the progress will be saved, etc. There is a need to create a simple explanation of how private data will be used to ensure legitimacy, transparency, and improve the overall experience for users. 

### Action Items
- [x] strategize where a brief explanation of the privacy policy will live on the website (possibly Q&A, landing page, or before you begin)
- [x] we need to agree on key things about our privacy protections and how we can translate it into simple language 
- [x] write a super brief explanation somewhere in simple language about how the info will be used

**Comment by SamHyler** [comment]
Design and Content are currently iterating a small blurb regarding privacy on the landing page, forthcoming

**Comment by SamHyler** [comment]
This [issue](https://github.com/hackforla/expunge-assist/issues/621) addresses what's listed here to some degree. Have we acomplished what's needed for this issue for now? It's the "committed to data safety" section on the landing page.  @ValeriyaMetla @jamiesiu

**Comment by jamiesiu** [comment]
This looks to be captured by #658 and #231 in essence, so can be closed as a duplicate. #658 can be revised to help refine the Privacy Policy update from Product

**Comment by SamHyler** [comment]
> This looks to be captured by #658 and #231 in essence, so can be closed as a duplicate. #658 can be revised to help refine the Privacy Policy update from Product

Interesting, there are a lot of overlap but there are a bit different threads going on. I'd say we covered this in our collab with design on the landing page. HOWEVER, I'm not sure we got that part about being able to save progress. Something for the before you begin page have added a note.

**Comment by SamHyler** [comment]
Closing this issue with the note that we will add how to save progress/that they cannot on the before you begin page. The other part has been put on the landing page, screenshot example of a current in progress iteration (Content side for this piece is finished)
<img width="744" alt="Screenshot 2022-09-17 at 00 05 27" src="https://user-images.githubusercontent.com/87077650/190810678-2ae52a64-df56-4689-b16f-88d53790f0e1.png">

**Comment by jamiesiu** [comment]
Cool that distinction and added information about the Save Progress piece helps
