### ISSUE TITLE
Create GitHub How-To doc for Wiki

### ISSUE THREAD

**Issue by jbsteinhardt** [hackforla/expunge-assist#580]
### Overview
Create a document that explains how to use GitHub as a member of the Expunge Assist, for new members to reference. 

### Action Items:
- [x] Create draft of the instructions that include information on
   - [x] how to manage GitHub Project Board
   - [x] how to write a good issue 
   - [x] how to create agenda for team meeting 
- [x] Review with PM
- [x] Review with Org. (Bonnie)
- [x] Upload document to onboaridng section of EA Wiki page

### Resources/Instructions
[GitHub HOW-TO](https://docs.google.com/document/d/1KuNrH_yKli4gvjdSF7DkPi0GtUArh2axYMJip6LlPFA/edit)

**Comment by ValeriyaMetla** [comment]
@jbsteinhardt and @Ndoyle118 as we already have [HfLA Guide] (https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit#heading=h.nl3p4nf4eqb4), @ExperimentsInHonesty proposed to identify what is missing in the guide and we can add to it from EA How-To doc. And leave there anything that is specific for the project, like feature labels.

**Comment by ValeriyaMetla** [comment]
After reviewing the How-To Doc it seems like yes, there are some extra details and basic instructions to navigate GitHub to accomplish all these tasks - create an issue, create an agenda, and manage Kanban Board. We can give it to Guide team if they feel the need to incorporate any of that. I would add 3 docs on our Wiki in the Onboarding section, HfLA Kanban Guide, Geeting the most out of GitHUb Issues page, and our How-To (for practical steps). Perhaps, we can remove all that could be found in other guides, but I would keep it. As not all team members will go over 20 page guide, but How To Doc provides quick overview of everything that is needed to successfully manage GitHub

**Comment by ValeriyaMetla** [comment]
Uploaded three documents on Wiki (see previous comment).
