### ISSUE TITLE
Update on Prop 47 + Nov 4, 2022 deadline

### ISSUE THREAD

**Issue by jbsteinhardt** [hackforla/expunge-assist#581]
### Overview
Update the EA Team on the details of the [November 4th deadline](https://www.courts.ca.gov/42537.htm) and it's relevance to the project. Is this really the last call for the reduction of felonies (for possession + low-level theft) to misdemeanors under Prop 47? 

### Action Items
- [x] Read relevant online material
- [x] Possibly call a county court to verify the details
- [x] Present finding and discuss with the team how it effects product launch

### Resources/Instructions
https://www.courts.ca.gov/42537.htm

**Comment by ValeriyaMetla** [comment]
@jbsteinhardt and @Thomas-Pietruszewski please provide outcomes of the research in the comment, and I will close the issue then. If we don't include the outcomes, future teams won't be able to know how this issue was resolved. Thank you!

**Comment by ValeriyaMetla** [comment]
Thank you @jbsteinhardt! I am closing the issue as it seems no next steps are needed.
