### ISSUE TITLE
Address letter process for users [from usability testing]

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#588]
### Overview
Users wonder what the letter writing process they are about to start looks like - how long would it take, what does it look like, etc? Users need some overview/peek under the hood/preview to feel secure going forward.

### Action Items
- [ ] brainstorm solutions
- [ ] Create checklist of solutions here. 
- [ ] For example: Address letter process somewhere upfront to the user: how many questions, what type of question (long form, short answer, check boxes), or give a 'peek under the hood'/preview of some kind. Give users an indication of what they are about to start.
- [ ] Suggestion: create a visual (collaborate with Design) that shows the process upfront with relevant indicators that gives the user a sense of what they are about to do in a realistic way (rather than for example, saying it will take "20 minutes" which is impossible on a subjective task like this one)

**Comment by SamHyler** [comment]
We discussed this in Content / Design some time ago and Design decided this needed to be tabled for the next iteration due to work load.

**Comment by anitadesigns** [comment]
I think we can close this issue too as we will be testing our landing page soon! @SamHyler

**Comment by SamHyler** [comment]
@anitadesigns yes, we sorta kinda addressed this one with Landing page iterations and a bit in the onboarding flow. It's possible we would want to reopen again and make further iterations.

**Comment by SamHyler** [comment]
Closing as I agree!
