### ISSUE TITLE
Review content in pop-ups [from usability testing]

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#590]
### Overview
Users noted that: illustrations in pop-ups should match content, that the font size on the “Welcome” pop-up was very small., there was too much text on some of the pop-ups.

### Action Items
- [ ] Collaborate with Design to iterate new pop-ups
- [ ] Collaborate with Dev and Design regarding decisions about how pop-up content will be displayed
- [ ] Consider creating A/B test with different content to help make the pop-ups more widely appreciated
- [ ] Summarize content on text using fewer words or review content to make changes

**Comment by ValeriyaMetla** [comment]
@SamHyler I don't think we need dependency here. Do you mean that it's not urgent? Then, we just keep it in backlog with low priority label. If you meant, something else explain it in the comment, we can change it so it is more clear.

**Comment by SamHyler** [comment]
> @SamHyler I don't think we need dependency here. Do you mean that it's not urgent? Then, we just keep it in backlog with low priority label. If you meant, something else explain it in the comment, we can change it so it is more clear.

I mean that it's not an issue we can resolve solely in content. If we make changes, it will affect Design and Dev in more than just changing the words. So I'll fix the dependency after we figure out our task priority with Design (Tuesday we'll do the exercise). Perhaps a joint issue is better suited, not sure now

**Comment by SamHyler** [comment]
I put 1 point for now, if we do A/B testing and depending on collab decisions it would be a larger size

**Comment by SamHyler** [comment]
should also revise the double message text: keep going and take a break

**Comment by SamHyler** [comment]
this has been addressed in a small way. Some of the content needs a small adjustement, but otherwise this is not planned now.
