### ISSUE TITLE
Improve Visibility and Accessibility of Privacy Information

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#605]
### Overview
Per user feedback from internal usability testing, privacy information is hard to find. Make it visible and accessible. 

### Action Items
- [x] Evaluate current privacy policy information flow
- [x] Develop recommendations / proposed (e.g. suggested making a link or button on LP, increasing size of buttons)
   - [x] Implement changes in Design system 
   - [x] Reflect changes in wireframes
- [ ] Implement with Development Team / Create GH Issue

### Resources/Instructions
[EA: Internal Usability Pilot Results: Issue Tracker](https://docs.google.com/spreadsheets/d/1NfqYUQKl7GRz1-r-vWI0kBWa-mgkXagCDAz9wMAa6Bc/edit#gid=0)

### Additional Context
"When tasked specifically to find information on personal information and privacy, four out of seven users were not able to locate the privacy policy link.
These users scrolled through the “FAQ” but didn’t find it there, then the “Terms of Use.” (""But it’s still not clear how my information will be used...”)
One user found the information but was dissatisfied with the process; two found it satisfactorily. 
One user explained that the difficulty was due to the link being “small and almost invisible.”
The two who felt satisfied went to “Privacy Policy” immediately. (“I would go to privacy policy - I think that would be covered here.”) "

**Comment by anitadesigns** [comment]
Created a design for this within LP. Will be completed once the LP design is finalized and sent to DEV. Linked to https://github.com/hackforla/expunge-assist/issues/624
