### ISSUE TITLE
Resize short form input fields to reduce confusion 

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#606]
### Overview
Per user feedback from internal usability testing, there was confusion about what to write in some fields due to the form field size. Resize these to make it easier to understand. 

### Action Items
- [x] Identify short form fields that created confusion and need to be updated
- [x] Determine and develop solution (proper size/resize)
- [x] Implement change with Development Team / Create GH Issue

### Resources/Instructions
[EA: Internal Usability Pilot Results: Issue Tracker](https://docs.google.com/spreadsheets/d/1NfqYUQKl7GRz1-r-vWI0kBWa-mgkXagCDAz9wMAa6Bc/edit#gid=0)

### Additional Context
"One user entered a full sentence into the “school name” prompt. They noted that if the form field was shorter they would have known to only enter a name."

**Comment by anitadesigns** [comment]
Design team finalized the size for short form field and updating designs. Will send to Dev once completed

**Comment by jamiesiu** [comment]
Need to confirm Mobile version of this change and that it applies wherever this is needed

**Comment by anitadesigns** [comment]
Design is complete and handed over to Dev
