### ISSUE TITLE
Competitive / Comparative Analysis

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#612]
### Overview
Update our comparative / competitive analysis to understand if we should make or buy solution(s)/tool(s) to fulfill our user's need and project goals. 

### Action Items
- [ ] Review past competitive/comparative analysis documentation and port over to template form
- [ ] Update analysis based on current project status and team direction/resourcing

### Working Document 
[EA Competitive Analysis](https://docs.google.com/spreadsheets/d/1ALYQgzgwY7Gxm0kLJTK6FzsAWJjUJsJ1iYYikOPEXFI/edit#gid=1259306930)

### Resources/Instructions
[HfLA Guide](https://docs.google.com/document/d/12D--k82V3hMyue8bFJEFTz1Q4_OHSwt0B9e-RJTPOPc/edit#heading=h.c8tc614ce3iu)
[OLD 2021 Template](https://docs.google.com/spreadsheets/d/19hhNCR856myUpH3NSw35Q2pKWVZLg1Xar0bH7kRhFJo/edit#gid=1259306930)
[NEW TEMPLATE](https://github.com/hackforla/product-management/issues/342)
### Past Research
#356 
[2021-03 Record Clearance PSG Report](https://drive.google.com/file/d/13BQa_5pf-BWakmKN0ve7aa0ZHH6J3xfm/view?pli=1)

**Comment by ValeriyaMetla** [comment]
@jamiesiu @thomasdemoner I added HfLA Guide. I will move it to the backlog.

**Comment by jamiesiu** [comment]
Expanded on some of the various dimensions/components that were listed as rows in the analysis doc. Maybe too granular but wanted to dig into them and understand the parts a bit more as I'm seeing these come up with Design/Content. It's helpful so far to think through them even with just the first example for comparison with [ULearn Personal Statement Creator](https://ulearn.education/personal-statement/)

**Comment by ValeriyaMetla** [comment]
@jamiesiu @thomasdemoner I am putting it in the backlog for now. If someone want to keep working on it, assign yourself and move in progress. If i have time before I leave at the end of September, I will try to finalize.

**Comment by jccchurch** [comment]
Closed this issue out - it's now combined into:
 https://github.com/hackforla/expunge-assist/issues/960
