### ISSUE TITLE
Ensure key information on the expungement process is visible and easily located on the Landing Page

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#613]
### Overview
Ensure key information on the expungement process is visible and can be easily located from the landing page.

### Dependency
UXR work in #616 

### Action Items
- [x] Gather information from UXR on User Journey via #616 
- [x] Develop design to illustrate EA process and where it fits in
- [x] Create dev issue to implement

### Resources/Instructions
[EA: Internal Usability Pilot Results: Issue Tracker](https://docs.google.com/spreadsheets/d/1NfqYUQKl7GRz1-r-vWI0kBWa-mgkXagCDAz9wMAa6Bc/edit#gid=0)

### Context 
"When tasked specifically to find information on the expungement process, two users could not find this information and three found it, but felt it was hard to locate. 
Two scrolled to the bottom immediately and clicked on “FAQ.” 
Three users initially looked at the “What is Expunge Assist?” section for this information. 
One user thought the “FAQ” link at the bottom was ""really small.” They were looking for an “info tab.”
One user expected the “FAQ” link to be at the top, while another user kept looking for a dropdown menu to find information before starting.
When tasked specifically to find information on personal information and privacy, "

**Comment by jamiesiu** [comment]
Given the User Journey (and where EA fits in the flow) is dependent on UXR, we will lower this issue in priority as we have alternative means to display and make key information available to users.

**Comment by anitadesigns** [comment]
@SamHyler I think we can close this issue as we worked on it already and will undergo testing

**Comment by SamHyler** [comment]
@anitadesigns  yes!
