### ISSUE TITLE
Evaluate different grid widths for website (borders header footer / centered cards / text fields) for better viewability and consistency

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#614]
### Overview
Evaluate different grid widths for website (borders header footer / centered cards / text fields) for better viewability and consistency

### Action Items
- [x] Assess how widths differ across various parts of website and across different designs (Mobile vs Desktop)
- [x] Understand impact with Partner teams for any changes we would make (e.g. impact to Content for text fields, flow)
- [x] Develop recommendations for improvement and consistency
- [ ] Create GH Issue for Dev Implementation

### Resources/Instructions
[Expunge Assist LG Flow Sample Intro Page](https://expungeassist.org/#/./form/intro)
- E.g. note how the widths differ for the header/footer/completion status banner vs the form input field. 

### Context
On the website, grids tend to extend to border. But when gets to cards/letter form fields, it's more centered. Is this for responsiveness on mobile? why not aligned to outer grid? We want to research this further

**Comment by anitadesigns** [comment]
@RenaNicole is making an issue for Dev to implement sweeping changes for 56px for Desktop. 

Will talk to Dev regarding sweeping changes for content containers for LG pages (633px) and other pages (1040px)

**Comment by anitadesigns** [comment]
Over the 2023 break, we worked on the grid and implemented it on our designs. It now is saved in our Figma style library and wireframes are updated with new grid version
