### ISSUE TITLE
Implement visual design in Content Guidelines

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#620]
### Overview
The Content Team requested the Design Team to improve the Content/Writing Guidelines on Figma to make it easier to read and to consume 

### Action Items
- [ ] Review Content/Writing Guidelines on Figma
- [ ] Brainstorm designs to implement 
- [ ] Implement designs
- [ ] Present to Content Team for feedback 

### Resources/Instructions
[Content/Writing Guidelines Figma page](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A19)

**Comment by anitadesigns** [comment]
@SamHyler since Content is currently working on this, can we close this issue?

**Comment by SamHyler** [comment]
@possibly, but let's hold off for another two weeks. I think we may need some assistance, but we might do some quick n dirty research to find out :D.
