### ISSUE TITLE
Add copy to Privacy/ Information Security Section

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#621]
### Overview
To address user concerns about data privacy, Design Team included a new section on the landing page to assure that user information would be kept secure. This section needs copy

### Action Items
- [x] Review the new landing page wireframe 
- [x] Create copy for section 
- [x] Iterate in Content
- [x] Handoff copy to design/ write copy in the section of wireframe 

### Resources/Instructions
[Landing page wireframe on Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A23)

**Comment by SamHyler** [comment]
Have created a first draft, all copy is living entirely in Figma now (source of truth)

**Comment by SamHyler** [comment]
final copy has been finalized for second round of user testing, source of truth is directly in figma.

**Comment by SamHyler** [comment]
@anitadesigns @RenaNicole I assume the copy will be handed over to dev as a package when the landing page is finalized?
