### ISSUE TITLE
Re-arrange content on the landing page 

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#624]
### Overview
Per our Content & Design Team Sync Meeting on July 22, 2022, we decided to re-arrange the content on the landing page. 

### Action Items
- [x] Move Letter Generator below hero header 
- [x] Merge the “What is Expunge Assist?” and “Who We Are” sections and have a button below that directs users to the About Us page 
- [x] Present to Content for Feedback and review
- [x] Include visual design 
   - [x] re-arrange/ select illustrations
   - [x] make button for FAQ section
   - [x] adjust Privacy section
- [x] Create a mobile design of page
- [ ] Create GitHub Issue for Dev to update website

**Comment by anitadesigns** [comment]
This is dependent on this issue https://github.com/hackforla/expunge-assist/issues/642

**Comment by anitadesigns** [comment]
https://github.com/hackforla/expunge-assist/issues/636 is an extension of this issue

**Comment by jamiesiu** [comment]
(Anita) Create mobile version by Mon 10/3 sync w/ Dev. 
(David) Figure out options for what Illustrations to add (screenshot of last page w/ letter download, image next to "what is EA". Discuss by Wed 10/5 Design meeting

**Comment by anitadesigns** [comment]
Going to create a draft of this issue and then will close

**Comment by anitadesigns** [comment]
Update: Found that @RenaNicole created a draft for the issue. Final details for the page are being updated and will be ready for the hand off soon. Since the information has been rearranged and just waiting for illustrations, going to mark as complete and close. Issue #704 will be handed over to Dev soon
