### ISSUE TITLE
Pop-up minor changes

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#628]
### Overview
The pop-ups used to be webpages, and were designed as such. When they became pop-ups, the copy stayed the same. Consider changing the button copy to something more appropriate.

Buttons are not in figma, but next buttons appear on the webpage.

### Action Items
- [x] Change button copy (next) to something else (Change them to "LET'S CONTINUE")
- [x] Collab with design on updating the prototype in figma
- [x] Update in Figma
- [x] Hand over to dev https://github.com/hackforla/expunge-assist/issues/646
- [x] Only the welcome page is a page, the rest have become pop-ups. Should this be changed or kept? Discuss and make changes

**Comment by SamHyler** [comment]
Change buttons on the pop-ups to "LET'S CONTINUE"

**Comment by SamHyler** [comment]
Consider moving the button to the right side on the pop-ups @RenaNicole @anitadesigns (for ex https://expungeassist.org/#/./form/involvement)

**Comment by SamHyler** [comment]
Design is updating the Mobile, Desktop, and Design system in figma with this button change. Sam is creating an issue to hand over the copy to Dev.

**Comment by SamHyler** [comment]
Welcome page stays as a page for now. No changes to that button copy for now.

**Comment by SamHyler** [comment]
Content is done on this issue, has been handed over to dev. Design will create a button on the Figma prototype (last thing to do before issue can be closed)

**Comment by SamHyler** [comment]
@anitadesigns  can you close this issue when it's finished?

**Comment by anitadesigns** [comment]
Yes! marking the issue as closed. @deaglelee14 completed the issue
