### ISSUE TITLE
Add "Completed" Progress Bar to "Previewing final letter" page

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#635]
### Overview
The ["Preview final letter"](https://expungeassist.org/#/./form/finalize/preview) page does not have a progress bar; whereas other pages in the Letter Generator form do. Other pages within the Letter Generator contain a title above the progress bar that reflects their progress within the form. We would like to add a completed progress bar on the "Previewing final letter" page on mobile and desktop to show that the user has finished completing the form. 

### Action Items
- [ ] Add a light purple (Hex #f7ebff) rectangle  (height: 120px) with a radius of 64 on the bottom right corner below the menu bar 
- [ ] Replace the title of the progress bar with "Completed" 
- [ ] Below the word "Completed", add a dark purple (Hex #9903FF) rectangle (height:8px) with a radius of 4 on all four corners

### Desktop
![Screen Shot 2022-08-08 at 4 41 18 PM](https://user-images.githubusercontent.com/105686896/183542233-124d78a3-bf25-45a0-8639-898fce91c816.png)

### Mobile
![Screen Shot 2022-08-08 at 4 43 19 PM](https://user-images.githubusercontent.com/105686896/183542357-b1c818f8-5282-4ea6-a0b4-9ded49f49452.png)

**Note:** The mobile version of the progress bar extends full width of the screen

### Resources/Instructions
For further reference, feel free to look at our design in [Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=0%3A1) or reach out to Anita (@anitadesigns )

**Comment by thomasdemoner** [comment]
Thanks for making the issue and assigning me! Looks great, you did it perfectly.

I'm gonna go ahead and move it to In Progress and assign @aahvocado to delegate it.
