### ISSUE TITLE
Create wireframe for LP with FAQ accordion expanded

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#636]
### Overview
As an extension of https://github.com/hackforla/expunge-assist/issues/624, we need to display what the FAQ accordion would look like when the user clicks on a question. 

### Action Items
- [x] Design an expanded accordion for FAQ questions 
- [x] Create mobile version 
- [x] Implement in LP to hand off to Dev

**Comment by jamiesiu** [comment]
Part of this is waiting on UXR to confirm which questions are important to include. In meantime, Anita is going to grab LP mobile widths from Dev and work on the mobile version design with placeholder text

**Comment by anitadesigns** [comment]
May need to adjust font size for desktop. Seeking feedback from Design
