### ISSUE TITLE
Create design with activated buttons for  last page of LG

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#638]
### Overview
As an extension of https://github.com/hackforla/expunge-assist/issues/608, we need to design how the last page of the letter generator would look like when the user would click the box and activate the download button options

### Action Items
- [x] Add check mark to box 
- [x] Change color of buttons to Electric violet
- [x] Create mobile version for page 
- [x] Present to Design and Content for review
- [x] Present to Dev for Review 
- [x] Create issue for Dev to implement

**Comment by jamiesiu** [comment]
decide by EOW on button layout

**Comment by anitadesigns** [comment]
Created desktop version. Working on button placement before designing mobile

**Comment by anitadesigns** [comment]
Continuing to have buttons as is and have it go under UT. Added a design component (blue box) to separate text from the download agreement. Awaiting feedback/approval from Content and Design

**Comment by anitadesigns** [comment]
Handed off to Dev. #659
