### ISSUE TITLE
Update Desktop and Mobile wireframes on Figma

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#641]
### Overview
There are inconsistencies between desktop, mobile, and expungeassist.org. In the previous release, the EA team had the final designs on the mobile wireframes on Figma, but did not update the desktop. As we gain new Designers on the team, we need to update the wireframes to reflect the current website. 

### Action Items
- [x] Update Desktop wireframes 
   - [x] Reference live website, previous mobile wireframes, and previous desktop wireframes to create new wireframes 
   - [x] Share with Content to get approval 
   
- [x] Update mobile wireframes 
    - [x] Component adjustments for consistency 
       - [x] Establish mobile breakpoint and frame to use (reference material.io and Dev)
       - [x] Establish content width (reference material.io and Dev)
       - [x] #806 
       - [x] #804 
       - [x] #802
       - [x] #805 
       - [x] #803
    - [x] Review that adjustments were reflected in mobile wireframes 
    - [x] Create mobile wireframes of remaining flows
       - [x] #813 
       - [x] Step 2d-  Involvement: Education 
       - [x] #814
       - [x] #815
       - [x] #816
       - [x] #817
    
### Note
- Content and Dev team notified the Design team that the mobile wireframes are the most up-to-date designs, but may still have inconsistencies.

**Comment by jamiesiu** [comment]
moving to in progress as work is being done by co-leads towards this

**Comment by anitadesigns** [comment]
Updating the issue by removing the pages that need to be updated and posting them in this comment for reference :

- [x] Update Pages
   - [x] Desktop
      - [x] Landing Page
         - [x] Landing page with accordion expanded
      - [x] Privacy Policy
      - [x] Terms of Service 
      - [x] About Us
      - [x] FAQ
      - [x] Letter Generator
         - [x] Welcome
         - [x] Before you begin
         - [x] Advice 
         - [x] Introduce yourself flow
         - [x] Introduce yourself edit 
         - [x] Pop-Up thank. you (followed by introduce yourself edit)
         - [x] Involvement flow
         - [x] Involvement page with sections selected 
         - [x] Employment flow
         - [x] Employment edit 
         - [x] Unemployment flow
         - [x] Unemployment edit
         - [x] Self-improvement flow
         - [x] Self-improvement edit 
         - [x] Education flow
         - [x] Education edit
         - [x] Parenting flow
         - [x] Parenting edit
         - [x] Community service flow
         - [x] Community service edit 
         - [x] Something else flow
         - [x] Something else edit
         - [x] Future goals flow
         - [x] Future goals edit
         - [x] Well done pop-up
         - [x] Why flow
         - [x] Why edit
         - [x] Almost done pop-up
         - [x] Editing final letter (split by sections)
         - [x] Previewing final letter 
            - [x] Previewing final letter with buttons activated
   - [ ] Mobile
 - [x] Landing Page
         - [ ] Landing page with accordion expanded
      - [x] Privacy Policy
      - [x] Terms of Service 
      - [x] About Us (Serena)
      - [x] FAQ
      - [ ] Letter Generator
         - [x] Welcome (Serena)
         - [x] Before you begin
         - [x] Advice 
         - [x] Introduce yourself flow (Serena)
         - [x] Introduce yourself edit 
         - [ ] Pop-Up thank. you (followed by introduce yourself edit)
         - [x] Involvement flow
         - [ ] Involvement page with sections selected 
         - [x] Employment flow
         - [x] Employment edit 
         - [x] Unemployment flow
         - [x] Unemployment edit
         - [x] Self-improvement flow
         - [x] Self-improvement edit 
         - [x] Education flow
         - [x] Education edit
         - [x] Parenting flow
         - [x] Parenting edit
         - [ ] Community service flow
         - [x] Community service edit 
         - [x] Something else flow
         - [x] Something else edit
         - [ ] Future goals flow
         - [x] Future goals edit
         - [ ] Well done pop-up
         - [ ] Why flow
         - [x] Why edit
         - [ ] Almost done pop-up
         - [ ] Editing final letter (split by sections) (Anita)
         - [x] Previewing final letter 
            - [x] Previewing final letter with buttons activated
            
We are working on a new way to display, create, and connect issues to improve team workflow. Adjusted the issue to reflect upcoming changes
