### ISSUE TITLE
Include a "demo" of LG on landing page

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#643]
### Dependency
Assess after IUT2 if this is still needed or existing information provided is sufficient for users. 

### Overview
The Internal usability testing showed that participants had difficulty finding information on the expungement process and how the letter generator fit into the process. The Design and Content team is collaborating on creating a visual to illustrate this information on the landing page. Thus far, we have discussed creating a demo or a look into how the tool works. 

### Action Items
- [x] Brainstorm different options to present "demo" of LG 
- [x] Finalize option and execute 
- [x] Adjust design to reflect 
- [x] Adjust copy (if needed)
- [x] Present to Dev for feedback 
- [x] Create issue to Dev to implement 

### Resources/Instructions
[Internal Usability Testing results](https://docs.google.com/spreadsheets/d/1NfqYUQKl7GRz1-r-vWI0kBWa-mgkXagCDAz9wMAa6Bc/edit#gid=0)

**Comment by jamiesiu** [comment]
Content and Design deferred this a few weeks back. We saw that copy Content had written actually fulfilled the need of including an animation or demo and decided to just add screenshots instead of a demo. We wanted to test out this decision in IUT2 and re-visit the demo if the results show that our design contained an information gap regarding the letter generator.

**Comment by anitadesigns** [comment]
I feel like we executed this on the landing page by providing the steps users would take when using the LG and providing examples of the final downloaded letter

I suggest we close . thoughts? @SamHyler

**Comment by SamHyler** [comment]
Yes, we did a lighter version of our original thought. We can close  - though might be good to revisit or ask UXR to test if our "light" version meets the user's needs. @anitadesigns

**Comment by anitadesigns** [comment]
Agreed! @jccchurch can we close this and then re-open/ make a new issue depending on the usability results on the landing page?
