### ISSUE TITLE
Change copy on pop-up buttons

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#646]
### Overview
Replace button copy for pop-ups before internal usability testing 2. 

### Action Items
- [ ] Change copy from NEXT or whatever it says now on ALL pop-up screens to "LET'S CONTINUE" 
   - [ ] Button (see pictures for reference)
      - [ ] Color: #9903FF (Electric Violet)
      - [ ] 40 px height x 173 px width
      - [ ] Top and bottom padding: 8
      - [ ] Side padding: 16
      - [ ] Padding between "CONTINUE" and arrow: 8

- [ ] Do not change the button copy on the Welcome page

### Top and Bottom padding
![Screen Shot 2022-08-11 at 11 13 24 PM](https://user-images.githubusercontent.com/105686896/184295248-80605f35-20d6-4223-9566-c5da5aada31c.png)

### Side Padding

![Screen Shot 2022-08-11 at 11 14 51 PM](https://user-images.githubusercontent.com/105686896/184295435-3ad6e87d-2ad1-4164-83bd-797f1cb95f2e.png)

### Padding between "CONTINUE" and arrow
![Screen Shot 2022-08-11 at 11 15 32 PM](https://user-images.githubusercontent.com/105686896/184295649-5f5be608-d058-496e-95f6-072ab2c8085e.png)

### Resources/Instructions
See this [issue](https://github.com/hackforla/expunge-assist/issues/628)

**Comment by SamHyler** [comment]
@thomasdemoner  Not sure how to assign folks right now, can you assign the right person and unassign yourself?  There will be more issues coming for Dev, trying to get them out so I don't forget. Hope the micro task is not a bother.

**Comment by thomasdemoner** [comment]
Sounds good!

This probably is a case where it'd be easier for Design to test and confirm the changes on Figma before Dev moves forward with it - because it seems like it'd change the dimensions of the button and that's something Design should approve - so I'm tagging @jamiesiu here for the "good to go" before I move it to In Progress and assign it!

Appreciate the issue! Micro task is definitely not a bother, if anything the more broken down the task is, the more helpful it is for us.

**Comment by anitadesigns** [comment]
@thomasdemoner The design team gives the green light! Just added Design details to the issue for Dev. Let us know if there are any questions

**Comment by SamHyler** [comment]
Thanks @thomasdemoner ! I'll keep that in mind when sending over issues coming up.

**Comment by thomasdemoner** [comment]
@anitadesigns thanks for the update, your additions to this issue were fantastic! hey @aahvocado, we've got a new issue to tackle!

**Comment by aahvocado** [comment]
Asked in Slack if the button padding changes are affecting all buttons.
