### ISSUE TITLE
Update copy on Privacy Policy

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#648]
### Overview
Update the privacy policy by exchanging the word SOFTWARE for WEBSITE. 

Content has updated the copy in Figma on both Website and Mobile versions. https://github.com/hackforla/expunge-assist/issues/647

### Action Items
- [ ] Replace the word SOFTWARE with WEBSITE on the Privacy policy page (there are three instances)

Full text should read: 

THE WEBSITE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. 

IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE WEBSITE OR THE USE OR OTHER DEALINGS IN THE WEBSITE.

ALL SESSION DATA IS KEPT PRIVATE AND PERSONAL INFORMATION IS CONFIDENTIAL.

**Comment by ValeriyaMetla** [comment]
I think it's a good quick fix. But eventually, we need to have a standard privacy policy before we begin testing with users. It's issue #231 @thomasdemoner check if any feedback from the development side. I am moving this to in-progress tasks

**Comment by aahvocado** [comment]
Hm, I've made the change. Were you supposed to do more work on this @thomasdemoner or can I close it out?

**Comment by SamHyler** [comment]
> #231

thanks Val, and good point. Thanks for the issue reminder. 

@aahvocado if these small changes are done, you can close. We have https://github.com/hackforla/expunge-assist/issues/231 open for any bigger changes that need to be made down the line.
