### ISSUE TITLE
Google Drive Migration EA

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#649]
### Overview
Work with past EA volunteers to migrate old google drive files from the old legacy drive to the newer current drive. 

(Duplicate Tracker for EA Project Board to ensure we continue progress on it. Original ticket exists within a separate Google Drive migration repo)

### Resources/Instructions
https://github.com/hackforla/google-drive-migration/issues/8
https://docs.google.com/spreadsheets/d/1fDAsxzCvkwf7CHYaEszKCWCIF_wm-ow9fxZyTxdlaJ8/edit#gid=309222957

**Comment by ValeriyaMetla** [comment]
@jamiesiu I sorted everything that was still not sorted before and updated Excel. There are only 3 contacts who didn't c change permissions, I send a follow-up email to all three today 9/18. I will unassign myself, just keep an eye on email and update the 3 remained contacts when is all done.
