### ISSUE TITLE
Update the UI/UX Designer Wiki Page for EA so that new volunteers can learn how we work and how they can start contributing. 

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#650]
### Dependency
- [ ] #1183 

### Overview
The Wiki page for joining as a UI/UX Designer needs to be updated so that new volunteers can learn how we work and how they can start contributing. 

### Action Items
- [x] Review current Wiki pages and identify gaps
- [x] How to use Expunge Assist Figma 
- [x] Add a current link to the personas & user stories board
- [x] Update Project Management link to a list of design issues
- [x] Develop draft recommendations (suggested using separate Google Doc)
- [x] Share with team for feedback. Revise and implement feedback
- [x] Repeat as needed
- [x] Finalize and Update into GH Wiki page

### Resources/Instructions
[EA Wiki - Join the Team Page](https://github.com/hackforla/expunge-assist/wiki/Joining-the-Team)
[EA Wiki - UI/UX Designer Page](https://github.com/hackforla/expunge-assist/wiki/UI-UX-Designer)
[HFLA Website Team Wiki example](https://github.com/hackforla/website/wiki/UI-UX-Designer)
[Internship Team Wiki example (different style)](https://github.com/hackforla/internship/wiki/Role:-Design)
[Civic Tech Jobs Team Wiki - done via GH Pages](https://hackforla.github.io/CivicTechJobs/joining-the-team/uiux-designer/)
[VMRS Team Wiki](https://github.com/hackforla/VRMS/wiki/Join-the-Team)
[Home Unite Us Team Wiki](https://github.com/hackforla/HomeUniteUs/wiki/UI-UX-Designer)

**Comment by jamiesiu** [comment]
To support sweeping wiki update efforts with https://github.com/hackforla/expunge-assist/issues/723, all EA disciplines are looking to update their respective wiki pages to ensure potential visitors to wiki pages get a fair / updated representation of our team and our process (e.g. no draft or template pages). No need to be perfect, but making a good enough effort of what we can do

**Comment by anitadesigns** [comment]
Updated the Wiki to contatin important information for new UX Designers. Currently working on a Figma guide on how folks can navigate EA's Figma workspace. This will be located in Figma. Moving the issue to "Prioritized Backlog" until we have a chance to resume working on this again

**Comment by sydneywalcoff** [comment]
@anitadesigns since this now has a dependency, I moved this to the icebox and cleared all the completed action items to be checked again once the dependency is complete.
