### ISSUE TITLE
Prospecting Survey for Legal Professionals

### ISSUE THREAD

**Issue by jbsteinhardt** [hackforla/expunge-assist#652]
### Overview
This survey originated as a Content need from IUT 1 and [this issue](https://github.com/hackforla/expunge-assist/issues/603), and is meant to serve a few goals: 1) get contact info from legal professionals whose clients write letters in their applications for record clearance for potential partnership 2) clarify terminology around how legal professionals refer to the letter. It should be short. We will disseminate it in CA for Wave 1. Other states and mediums for outreach will be included after the pilot survey aimed for September 2022.  

### Action Items
- [x] Finalize survey instrument and convert in Google Form 
- [x] Finalize survey dissemination methods & which online sites we're posting on
- [x] Finalize Database for Outreach #445 
- [x] Finalize Outreach Protocol #431 

### Working Documents
[Survey Draft](https://docs.google.com/document/d/146NHcN7LRTe-zZ_2Mde0wQkQQLaaCMiUsbd3huQWjzo/edit#)
[Step-by-step instructions for posting/sending the survey](https://docs.google.com/document/d/1Vsd8QOTsFK9iNvZjFK0ymHvM653577_hvEAI84X0yXw/edit)

**Comment by yumengluo** [comment]
Reviewed the draft. It looks pretty good!

**Comment by ValeriyaMetla** [comment]
@jbsteinhardt please attach Google Form here when completed. I will assign it to you and @yumengluo

**Comment by ValeriyaMetla** [comment]
@jbsteinhardt @Ndoyle118 can you attach issue about searching for ways to dissemminate. If it's in the same database, please specify it. Also, please attach google form as discussed. Aftee google form is attached and survey is finalized we can move this issue to Ice Box with dependencies on 3 issues specified (database, protocol, ways to disseminbate)
