### ISSUE TITLE
Add a question to the FAQ

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#657]
### Overview
After Design/Content sync, we decided to not add an extra page to the website that includes a user journey now, and push that task to the tasks after this upcoming IUT2. In the meantime, we can add a question on FAQ that addresses"Why does the deceleration letter matter to me/ expungement process/ in getting my record cleared?" - something along these lines, to help the user in words rather than a user journey visual. For now. 

Adding to high prio items to be done before IUT 2.

### Action Items

- [ ] add a question on FAQ ( "Why does the deceleration letter matter to me/ expungement process/ in getting my record cleared?")
- [ ] Choose where in the flow of FAQ questions it should fit
- [ ] Discuss in Content and Design 
- [ ] Add to all relevant spaces on Figma
- [ ] Hand over to Dev

**Comment by SamHyler** [comment]
Moved to W3 priority due to time. 
 @kyle-whitaker  see changed labels from high to medium and milestones (learning purposes)

**Comment by anitadesigns** [comment]
@SamHyler I feel like this question was already answered in our FAQ and this issue can be closed. Here is the section where this question is answered in the FAQ
![Screen Shot 2023-04-04 at 10 03 12 PM](https://user-images.githubusercontent.com/105686896/229985683-277646d0-cbbd-410c-912b-ccc6abef53d5.png)

**Comment by SamHyler** [comment]
> @SamHyler I feel like this question was already answered in our FAQ and this issue can be closed. Here is the section where this question is answered in the FAQ ![Screen Shot 2023-04-04 at 10 03 12 PM](https://user-images.githubusercontent.com/105686896/229985683-277646d0-cbbd-410c-912b-ccc6abef53d5.png)

I understand your thought process, but I would say yes and no. This FAQ question doesn't address what we were trying to target exactly, but somewhat tangentally. I'm thinking we should review the FAQs overall coming up soon as they became fairly wordy and information has changed. I'm unsure if we should close as "won't do" but thinking perhaps instead I'll add this as a note for a future FAQ review.
