### ISSUE TITLE
Update last page of Letter Generator 

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#659]
### Overview
Dev and Design decided to merge the last two pages of the letter generator onto one page and add information on how users can further edit their final declaration letter that is generated. 

### Action Items
- [ ] remove https://expungeassist.org/#/./form/download page 
- [ ] Update spacing between the progress bar and "Previewing final statement"
   - [ ] desktop: 96 px 
   - [ ] mobile: 40 px
- [ ] Update  content container width of box that show letter 
   - [ ] desktop: 633 px 
   - [ ] mobile: 328 px 
- [ ] Add blue information box below letter box 
   - [ ] dimensions : 108px height x 636px width (desktop) ; 204 px height x 328px width (mobile)
- [ ] Add blue "i" alert icon to the left inside blue box 
- [ ] Add header to the right of icon (8px spacing between icon and header) 
   - [ ] Copy: Review your completed declaration letter
- [ ] Add paragraph below header and icon 
   - [ ] Copy: If you want to make edits after downloading your completed letter, you can edit it with a text editor such as 
                     Microsoft Word, Google Docs, or Pages.
- [ ] Add download agreement
   - [ ] Add dark purple  (#25003F) inactive check box 24px x 24 px box 
   - [ ] Add copy (8px spacing between the inactive box and copy) : By checking this box you take full responsibility in this 
          personal statement, and release all association with Hack for LA. We recommend that you have a lawyer  or a legal 
          clinic review this letter before you submit your application.
- [ ] Add inactive buttons 
   - [ ] 56px spacing between buttons and download agreement 
   - [ ] 24 px spacing between each button 
   - [ ] button dimensions: 
      - [ ] desktop: 40px height x 225px width 
      - [ ] Mobile: 44px height x 225px width 
   - [ ] Order of buttons:
      - [ ] Pdf
         - [ ] Add download icon
         - [ ] Copy: DOWNLOAD .PDF
       - [ ] Clipboard
         - [ ] Add copy icon
         - [ ] Copy: COPY TO CLIPBOARD
       - [ ] TXT
         - [ ] Add download icon
         - [ ] Copy: DOWNLOAD .TXT
       - [ ] Email
         - [ ] Add mail icon
         - [ ] Copy: SEND IN AN EMAIL            
       - [ ] Word doc
         - [ ] Add Word doc  icon
         - [ ] Copy: DOWNLOAD WORD DOC         
- [ ] Add back button 
   - [ ] dimensions: 
      - [ ] desktop: 40 px height x 101 px width 
      - [ ] mobile: 44px height x 101 px width 
   - [ ] Add arrow icon
   - [ ] 8px padding between arrow icon and copy 
   - [ ] Add copy: BACK
- [ ] Add return home button 
   - [ ] dimensions:
      - [ ] desktop: 40px height x 162 px width 
      - [ ] mobile: 44px height x 162 px width 
   - [ ] Add drop shadow
   - [ ] Copy: RETURN HOME

### Resources/Instructions
Feel free to see the design under [" Design Hand-offs" on Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=2%3A38) labeled "Issue #659. Ask @anitadesigns for any questions

**Comment by aahvocado** [comment]
I'm not sure I understand why we wanted the change to the space between the header and the content. I'm pushing back on it for now and will bring it up at the next meeting so I can get the rationale. If it is desired I can implement it properly as a sweeping change.

Here is what it looks like with 96px margin on my screen:

![Screen Shot 2022-09-25 at 10 06 44 AM](https://user-images.githubusercontent.com/2266545/192156039-6cab9af4-b794-4a4d-bbb1-68059dae5b6b.png)

**Comment by aahvocado** [comment]
Leaving some notes about things that I also have to push back and not do in this issue:
* `Download Word Doc` button. This doesn't exist yet and I don't remember having the conversation to have this implemented.
* Button style change. I'll do this in a separate issue because there seems to be a lot of changes and looks like it should affect the entire application
