### ISSUE TITLE
header and footer layout get broken in mobile view

### ISSUE THREAD

**Issue by aahvocado** [hackforla/expunge-assist#662]
Header:
![Screen Shot 2022-08-29 at 9 21 19 AM](https://user-images.githubusercontent.com/2266545/187248129-808f8419-7cd6-4ef9-b64f-ff7fc39c66d5.png)

Footer:
![Screen Shot 2022-08-29 at 9 21 26 AM](https://user-images.githubusercontent.com/2266545/187248127-169aafa1-7bc4-456e-9a61-17dd12f242fb.png)

---
Most likely this needs Design treatment first.

**Comment by anitadesigns** [comment]
Design created for footer and ticket was made: https://github.com/hackforla/expunge-assist/issues/672
