### ISSUE TITLE
Improve parenting flow

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#665]
### Overview
The current flow regarding parenting questions on the letter generator is not inclusive for users who have more than one child. In collaboration with the Content Team, the Design team will work on a new flow for the parenting questions

### Action Items
- [x] Brainstorm ideas
- [x] Create lo-fi wireframes
- [x] Present to Dev for feedback 
- [x] Present to Content 
- [x] Create high-fidelity mobile and desktop wireframes 
- [x] Create issue to hand off to Dev

**Comment by jamiesiu** [comment]
Aiming to finish by end of next week ~10/7.

**Comment by jamiesiu** [comment]
Pretty much done design-wise. Content taking final look and will hand off to Dev
