### ISSUE TITLE
Organize Information for Public Wiki

### ISSUE THREAD

**Issue by Thomas-Pietruszewski** [hackforla/expunge-assist#667]
### Overview
We need to identify what information we want to include in the public facing wiki and where that info can be found on google drive. 

### Action Items
Identify what to include in the public facing wiki.

Organize google drive links where that information can be found.

**Comment by Thomas-Pietruszewski** [comment]
Below is a link to a document where we can find what information to include in the wiki. 

https://docs.google.com/document/d/1boh-I-SNxV-B5sVDIOxqPHYcwjf4bteMuvvO4vlK-U0/edit

**Comment by kelseylondon** [comment]
Closing this issue because we have a number of more recent issues related to the public facing wiki including: 
#723 
#774
