### ISSUE TITLE
Identify Places to Disseminate User Terminology Survey 

### ISSUE THREAD

**Issue by Ndoyle118** [hackforla/expunge-assist#669]
### Overview
We need to develop a list of online places to distribute the [User Terminology survey (Issue: #603)](https://github.com/hackforla/expunge-assist/issues/603). We are looking for any online forums which would be relevant for/used by individuals who are applying for expungement/have applied for expungement in the past/or are otherwise personally involved in the expungement process. This can include online forums such as relevant Facebook Groups, Subreddits, Meetup Groups, etc. 

For each online forum, we will need to identify an administrator or moderator who can be contacted to explain who we are, what the purpose of the survey is, and can grant permission to distribute the survey in the forum, either by sharing it ourselves, or having an administrator share the survey on our behalf.

### Action Items

- [x] Develop list of potential online forums/newsletters/groups where the user terminology survey could be distributed 
- [ ] Identify moderators and/or admin for each online forum/newsletter/group

### Relevant Issues
https://github.com/hackforla/expunge-assist/issues/603

### Resources/Instructions
[Database for disseminating User Survey](https://docs.google.com/spreadsheets/d/16tzlMCkiSJwGWihdQTCP9k3eYi_TevYFMo3_xYBgyjU/edit#gid=0)

**Comment by SamHyler** [comment]
This should probably be reviewed/closed @kelseylondon @yumengluo
