### ISSUE TITLE
New FAQ Question

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#676]
### Overview
A new FAQ question has been written from this [issue](https://github.com/hackforla/expunge-assist/issues/656). Will appear on the FAQs and on the landing page. 

Information about where it is on the landing page and in the order of FAQs communicated in Figma.

### Action Items
- [ ] Add new FAQ text to landing page
- [x] Add new FAQ text to FAQ section (See Design handover space for location)
- [x] There is an extra space between sentences in the first Q, please redo that one. (Between "reduced. Expungement")

### Resources/Instructions
(See Design handoff space](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=7156%3A74656)

**Comment by AilinLuca** [comment]
What does "Add new FAQ text to landing page" mean? I don't see it in the Figma wireframe and I don't see FAQs on the landing page.

**Comment by AilinLuca** [comment]
Should we move the FAQ text out of the JSON file and put it directly into the page? I think the numbering in translation.json makes updating the FAQ text more difficult.

**Comment by SamHyler** [comment]
> What does "Add new FAQ text to landing page" mean? I don't see it in the Figma wireframe and I don't see FAQs on the landing page.

Hi! There are three FAQ questions at the bottom of the landing page. This issue is referring to the copy for the FAQ question being added in both places. It's the one related to concerns around law enforcement. Let me know if you have questions, always quicker to ping me on Slack

**Comment by sydneywalcoff** [comment]
Since most of this task was completed, I moved the remaining task to a new issue(#927)
