### ISSUE TITLE
Update Advice page

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#677]
### Overview
Update advice page from https://github.com/hackforla/expunge-assist/issues/591, both for visual design and content. 

Iterations on the Design side are not finished, will update issue when ready to be worked on. 

### Action Items
- [x] Update content on Advice page
- [x] Add "x" icon"
- [x] Add "check" icon 
- [x] Add boxes around the "do" and "don't" examples under each advice 

### Resources/Instructions
See handover (when finalized) in Design hand off space on [Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=4524%3A34430)

**Comment by SamHyler** [comment]
This is ready to go from Content side.

**Comment by sydneywalcoff** [comment]
@aahvocado I've got this!

**Comment by anitadesigns** [comment]
@sydneywalcoff yes! it is good to go?
