### ISSUE TITLE
Desktop LG Pop-Up Illustrations Update

### ISSUE THREAD

**Issue by deaglelee14** [hackforla/expunge-assist#682]
### Overview
To reflect the IUT #1 issue of the illustrations not being representative of diverse age groups and genders, I have sourced new illustrations for the Desktop Letter Generator Pop-Ups.

### Action Items

- [x] Replace current Desktop Pop-Up illustrations on with new illustrations

### Resources/Instructions
The updated illustrations (in SVG and Component form) are located in the "Design Hand-Offs" page linked [here](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=5358%3A49631)

**Comment by anitadesigns** [comment]
Added to IUT2 milestone but can be pushed to W3 if needed
