### ISSUE TITLE
Update HfLA/CfA relationship - About Page

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#684]
### Overview
For IUT2, Design and Content were working on improving the About Us page. We went over the information architecture of the website and found that there were sections on the original About Us page that worked better on the LP. We wanted to include more information about the team and project goals on the About Us page. Due to time, the Design team decided to further work on this page for IUT3. 

Now that the team is preparing to Launch for potential partners and updates to Hack for LA have happened, the team is prioritizing updating the About Us page with updated information and page format. 

### Action Items

- [x] #1049
- [x] #1051

### Resources

Section on current About Us page
<img width="512" alt="Screenshot 2023-08-04 at 21 21 41" src="https://github.com/hackforla/expunge-assist/assets/87077650/bda34c3a-3cea-4b84-9386-3e823be06458">

**Comment by anitadesigns** [comment]
Code for America announced the dissolution of the Brigades program that HackforLA was part of. Our About Us page contained information about this relationship, but this will need to be updated once we gain clarity on our next steps as an org. 

I motion to move this issue for a future milestone once we gain more clarity of our stance @SamHyler

**Comment by SamHyler** [comment]
@anitadesigns agreed. I added a content task, a content label (so we don't forget), and changed the milestone. There's two milestones, so it can either be a content or design one for Wx+ development. I decided to make it a design issue, created a new content one for the text specific, and connected the two. Do you think Wx+ is the right milestone, or should they be W3 (the one coming up post IUT2?)

**Comment by anitadesigns** [comment]
Since we created an issue with more updated information on the About Us page that has insight from IUT2. Decided to close this issue and reference it in the new issue

**Comment by anitadesigns** [comment]
PMs this needs the Content/Design milestone

**Comment by anitadesigns** [comment]
Previous Github Overview was the following:

**Comment by sydneywalcoff** [comment]
replaced 'parent' language in issue title with `main issue` label

**Comment by SamHyler** [comment]
Content is finished. In process of being checked by Design, soon to handover to Dev

**Comment by SamHyler** [comment]
Content is finished. Content will be under the master pages and in the Content SOT copydoc. Design has OKed handover without check on padding. Handing over to Dev on [Design handover space in Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-38&mode=design).
