### ISSUE TITLE
Add accordions to FAQ page

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#686]
### Overview
As an extension to Issue #630 and work done in IUT2, we would like to add accordions to the FAQ page for each question. The LP currently has this design for the FAQ section. We would like to replicate that for consistency. 

### Action Items
- [ ] Add accordion for desktop 
- [ ] add accordions for mobile 
- [ ] Present to Dev
- [ ] Create issue for Dev

### Resources/Instructions
 Landing page and "Faq" on Figma

**Comment by anitadesigns** [comment]
We need to redo the FAQ page. Going to talk to Content regarding working on this while we wait for Landing page usability results before closing

**Comment by anitadesigns** [comment]
expanding this issue to a redesign for a page.

**Comment by SamHyler** [comment]
Corresponding content FAQ issue is here https://github.com/hackforla/expunge-assist/issues/957
