### ISSUE TITLE
Create email for Website

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#687]
### Overview
In IUT1 the EA team had decided to present a way for users to contact us if they had any questions, concerns, or would like to share feedback. The team had used "[info@expungeassist.org](mailto:info@expungeassist.org)" as a filler, but this email still needs to be created. 

### Action Items
- [ ] Follow up with Bonnie regarding the email being integrated into our main EA email.
- [ ] Provide team with update 

### Context
Currently we have our email address with the project as [expungeassist@hackforla.org](mailto:expungeassist@hackforla.org). We were hoping to create an expunge assist specific address like [info@expungeassist.org](mailto:info@expungeassist.org) but we don't know if this is possible with our existing Google tools and what we have available as volunteers. This is so we can filter out questions/inquiries from users of the site versus ppl who contact our normal email address

**Comment by jamiesiu** [comment]
Scratch notes from a past Oct sync with Bonnie
- how to host email while 
- DNS
- instruction set when website hosted in github but email hosted in gsuite
- @reach out to Dev Ops team on Bonnie behalf  
	- wednesday 6pm 
	- what are instructions for this
		- domain registered in google domains 
		- want to use with secondary domain to handle the email 
	- if too slow, ask one of the developers on team to work on it. 
	- hard to use Gsuite
	- video some place maybe for these 
		- Google help files not helpful 

- challenge is can't alias with [info@hackforla.org](mailto:info@hackforla.org)
- secondary domain
- other option is [expungeassist+info@hackforla.org](mailto:expungeassist+info@hackforla.org)

**Comment by jamiesiu** [comment]
Reaching out in #ops Slack channel to see if they have suggestions on how to proceed. https://hackforla.slack.com/archives/CV7QGL66B/p1678326109107939

**Comment by jamiesiu** [comment]
@chelseybeck thanks for offering the #ops support. please let us know if you need more information regarding the request

**Comment by chelseybeck** [comment]
@jccchurch & @jamiesiu has this been created yet?

**Comment by anitadesigns** [comment]
@chelseybeck not yet!

**Comment by mariaweissman** [comment]
Update: we discussed that expungeassist@hackforla.org is the email address that needs to be used moving forward, and the info@expungeassist.org as a filler will be changed to expungeassist@hackforla.org on the website. @sydneywalcoff
