### ISSUE TITLE
Create option to download letter a a Word doc

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#690]
### Overview
IUT results shared that participants wanted the option to download the declaration letter as a Word doc.

Note: the current frames under the design hand off space do not have the final UI styles. Please use what we currently have on our website in regard to button padding, color, style, etc 

### Action Items
- [ ] Add a new button on the last page of the letter generator page
   - [ ] disabled 
   - [ ] activated 
- [ ] add copy 
- [ ] add icon 
- [ ] Rename and re-arrange order of the buttons as the following:
   - DOWNLOAD .DOCX
   - DOWNLOAD .PDF
   - DOWNLOAD .TXT
   - SEND IN AN EMAIL
   - COPY TO CLIPBOARD

### Resources/Instructions
Feel free to reference [issue 690](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=10000-102028&t=GfwDj2VWcv7B6vhP-4) under "Design handoff" on figma for design

**Comment by SamHyler** [comment]
I created an issue for content to keep track of tasks. https://github.com/hackforla/expunge-assist/issues/690

**Comment by SamHyler** [comment]
Content approves adding a WORD download option, deciding as follows: 

Choosing to do .extensions for all. 

The order of the buttons would be:
DOWNLOAD .DOCX
DOWNLOAD .PDF 
DOWNLOAD .TXT
SEND IN AN EMAIL
COPY TO CLIPBOARD 


Needs to be written on Master Desktop, WIP Mobile, and anywhere else relevant (IUT 2 iterations archive?) and checked off with Design before closing issue.

**Comment by anitadesigns** [comment]
Design is currently working on adjusting padding and preparing annotations for the design handoff on Figma. 

Few questions arose that we would like to discuss with Dev regarding responsive design and padding.

**Comment by anitadesigns** [comment]
@sydneywalcoff Issue is ready to be assigned and worked on!
