### ISSUE TITLE
Something else flow

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#698]
### Overview
From this [issue](https://github.com/hackforla/expunge-assist/issues/597). 
Adding this flow. This is the only new flow for this iteration.

### Action Items
- [x] Add "something else" to the "Involvement" page where the user can select the list of categories (this is part of Issue #701 )
- [x] Create new web pages for Something else flow which includes the Preview page 
- [x] Add copy to "Something else" flow (see Figma handover space for details)
- [x] Add menu/header
- [x] Add progress bar with 16px bottom padding
- [x] Add the first question with a short input field
- [x] Add gray text inside the short input field
- [x] Add a second question with a long input field 
- [x] Add back and next buttons 
- [x] Link the "Back" button to the previous Involvement category the user selected. If no other category was selected, the back button would direct the user to the [Involvement page](https://expungeassist.org/#/./form/involvement)
- [x] Next button should be disabled by default. Once the user completes both questions, the next button should turn bright purple. 
- [x] Link the next button to the something else preview page (this is for when the users complete responding to the questions) 
- [x] On the preview page, link the "next" button should direct the users to ["Future goals" page with pop-up](https://expungeassist.org/#/./form/goals)
- [x] On the preview page, the "back" button should direct them back to the Something else page with their responses

### Resources/Instructions
[Design hand off space](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=6483%3A67759)

**Comment by sydneywalcoff** [comment]
@aahvocado I'll take a stab at this.
