### ISSUE TITLE
Update Parenting Flow

### ISSUE THREAD

**Issue by RenaNicole** [hackforla/expunge-assist#702]
### Overview
Simplify and update questions on the involvement Parenting form. Simplified to only include relevant information about the user and value user privacy if they do not wish to share child's information. If you have any questions or concerns please message @RenaNicole / Serena Sanders on Slack.

[View Figma designs here](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=6516%3A73060)
### Action Items

- [x] Replace the first question with "How many children do you have?"
- [x] The input field for the first question should only allow numbers to be entered
- [x] The width of the input field for the first questions is 144 px. 
- [x] Change the generated text from "child" to "children" when the response for the first question is more than 1
- [x] Second question remains the same
- [x] The "Next" button becomes activated once both questions are answered

**Comment by aahvocado** [comment]
@SamHyler 
It's not clear but I'm going to use `I have 2 children.` and `I have a child.` as the two possible texts, does that sound alright?

**Comment by SamHyler** [comment]
> @SamHyler It's not clear but I'm going to use `I have 2 children.` and `I have a child.` as the two possible texts, does that sound alright?

Sorry for the messy handover! Are you asking about the autotext for the parenting flow? There are two separate autotext formats based on the grammar change here. Those I put in two screens stacked on top of each other here: https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=6574%3A70338
