### ISSUE TITLE
Update About Us Page

### ISSUE THREAD

**Issue by RenaNicole** [hackforla/expunge-assist#703]
Updated copy on the About Us page that gives more information on our connection to Hack For LA and Code For America.

- [x] "Meet The Team" button under the Who We Are paragraph hyperlinks to Expunge Assist's Hack For LA page: 
https://www.hackforla.org/projects/expunge-assist
- [x] "Hack For LA" hyperlinks to Hack For LA's homepage : https://www.hackforla.org/
- [x] "Code For America" hyperlinks to Code For America's homepage : https://codeforamerica.org/
- [x] "*Source" hyperlinks to : https://codeforamerica.org/programs/criminal-justice/automatic-record-clearance/
- [x] "Contact Us" button under Partner With Us opens a new email addressed to the Expunge Assist email

https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=6774%3A70735&t=i0KDbDZtKYpjCH2I-4

**Comment by troymathis** [comment]
**Changes I made**
---
- Added buttons and hyperlinks with correct redirect to those links
- Added english locale for entire page
- styles added for entire page (buttons, links, ul)

**Notes**
Styles not to precise liking, did the best I can
