### ISSUE TITLE
Update Landing Page

### ISSUE THREAD

**Issue by RenaNicole** [hackforla/expunge-assist#704]
### Overview
The landing page underwent re-design to resolve participant pain points from IUT1 regarding finding important information on the letter generator tool and expungement process. 

### Action Items
- [ ] Add EA Device illustration to the left of "What is Expunge Assist" section and move the copy to the right of the page
- [ ] Add Semi-bold style to "What is Expunge Assist?" header
- [ ] Change copy below "What is Expunge Assist?"
- [ ] Add a button with copy "About Us" and link it to the [About Us page](https://expungeassist.org/#/./about-us)
- [ ] Add "Making letter writing less intimidating" copy as a header with semi-bold style -- center align 
- [ ] Add screenshot illustration to left of the page 
- [ ] add tool description copy to the right of the screen shot illustration 
- [ ] Add "How it works" header- semi bold with paragraph copy below 
- [ ] Add steps illustration to the right of "How it works" copy 
- [ ] Add "A complete letter" header -semi bold style and center align 
- [ ] Add sentence below 
- [ ] Add the image of the three letters below 
- [ ] Add recommendation copy below illustrations of 3 letters
- [ ] Add "Committed to data safety" header- semi bold , left align 
- [ ] Add paragraph copy below 
- [ ] Add "View privacy policy" button and link to the [Privacy policy page](https://expungeassist.org/#/./privacy-policy)
- [ ] Add secure laptop illustration to the right of copy 
- [ ] Add "Frequently asked questions" header - semi bold , left aligned 
- [ ] Add three accordions with three different questions 
- [ ] Add" Read our FAQ" button and link to [FAQ page](https://expungeassist.org/#/./faq)
- [ ] Add light purple box below 
- [ ] Add "Partnership opportunities" header, semi bold , center align 
- [ ] Add copy below 
- [ ] Add a "contact us" button that opens their email app on the computer 
- [ ] Delete previous partnership opportunities header and copy, Meet the team and illustrations

### Resources/Instructions
- [Design hand off space](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=6917%3A72320)
- Illustrations/SVG are found in the design handoff space

**Comment by anitadesigns** [comment]
Sent Dev SVG files of the images found in the landing page. Let us know if there is anything Design can provide to help with the file size
