### ISSUE TITLE
Create step-by-step guide for disseminating Terminology Survey

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#708]
### Overview
The[ Terminology survey and research plan](https://github.com/hackforla/expunge-assist/issues/603) is finished. Now we need to create a step-by-step guide for researchers to follow when posting the survey and gathering responses.
 
### Action Items
- [x] Create a step-by-step guide
- [x] Include blurbs and other relevant information
- [x] Discuss in Research

### Resources/Instructions
[Step-by-step guide](https://docs.google.com/document/d/1WOHNkJzBITELsmMlPY0Pokzt_afSyxvIcHsMeSfGkgA/edit)
[Terminology Survey and research plan](https://docs.google.com/document/d/1JC6JdBPgpxp-bGquuWEKq6gRQ32DB9eFKDPNcyd9Lkc/edit#)

**Comment by SamHyler** [comment]
Step guide is created, waiting for more information from the database and other sources to finalize

**Comment by kelseylondon** [comment]
Hey @SamHyler - it's been months, so no worries if you don't remember, but do you know what info you were waiting for from the "database and other sources"? It would be great to finalize this soon.

**Comment by SamHyler** [comment]
> Hey @SamHyler - it's been months, so no worries if you don't remember, but do you know what info you were waiting for from the "database and other sources"? It would be great to finalize this soon.

Yes @kelseylondon . If you open the step guide, I left a comment in the margin. Either the database is the wrong one, wasn't created or completed when I left this comment. Maybe it's done now and that information can be plugged into the step by step guide. At the time I remember I didn't have all the necessary info to complete - and it was just waiting on other's tasks. Then the surveys got tabeled and this issue with it. 

Let me know if you need more info, hope it helps!
