### ISSUE TITLE
[HOLDSweeping copy change for header in all Preview pages in LG

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#716]
### Action Items
- [ ] Change copy headers on the Editing final letter page: https://expungeassist.org/#/./form/finalize

**Comment by jamiesiu** [comment]
@SamHyler @anitadesigns checking in on the draft status for this issue - did we need to confirm additional info in order to finalize it? didn't know what we'd like to specifically change copy-wise for the headers

**Comment by SamHyler** [comment]
I don't think we needed to confirm additional info, it probably just never got checked off the list.

**Comment by tglaz** [comment]
@jamiesiu @SamHyler - perhaps i am missing something, but should there be anything under `Resources/Instructions` section here? I can't seem to tell from this issue what the new header copy should be.

**Comment by SamHyler** [comment]
reviewing with @anitadesigns  currently, will get back to you all!

**Comment by SamHyler** [comment]
@sydneywalcoff I think we found that the changes needed are already addressed elsewhere? @anitadesigns am I remembering right? And/or that we would double check after all the updates are live to see if this one was needed in the end. It relates to small changes to the words on a few sections, so the fix would be fast if needed.
