### ISSUE TITLE
EA: Dev / Design Sync Meeting Agenda

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#717]
## This issue tracks the running agenda for our weekly Dev / Design / Product Sync

```
# [Date] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] 
- [ ] 
- [ ] 

### FYI / Announcements
- [ ] 

### Notes from Meeting
- [ ] 
- [ ] 
- [ ] 

### Action Follow-up
- [ ] Review previous action items
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2022.10.17]  Dev / Design Sync Notes
### Attendees
- 
### Recurring items: 
- [ ] Balance / Team Health Sustainability Check 
- [ ] Review previous action items outstanding
- [ ] Review Project Board / GH Issues [Design](https://github.com/hackforla/expunge-assist/projects/1?card_filter_query=label%3A%22role%3A+design%22) / [Dev](https://github.com/hackforla/expunge-assist/projects/1?card_filter_query=label%3A%22role%3A+development%22) / [Content](https://github.com/hackforla/expunge-assist/projects/1?card_filter_query=label%3A%22role%3A+ux+content+writing%22)
- [ ] Blockers Support / Help Needed
- [ ] Progress Share / Feedback Requests
- [ ] Design <> Content / Dev / Research / Product Alignment
- [ ] Set Weekly Goals 
### New Meeting Items
- [ ]
### FYI / Announcements
-  
### Notes from Meeting
- 
### Weekly Goals
- 
### Action Follow-up
- [ ] 
### Items for next weeks agenda
- [ ]

**Comment by jamiesiu** [comment]
# [2022.10.24] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
     - [ ] Review previous action items outstanding 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] 
- [ ] 
- [ ] 

### FYI / Announcements
-  
 
### Notes from Meeting
- [ ] 
    - 
- [ ] 
    - 
- [ ] 
    - 

### Action Follow-up
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2022.11.14] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
     - [ ] Review previous action items outstanding 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] 
- [ ] 
- [ ] 

### FYI / Announcements
-  
 
### Notes from Meeting
- [ ] 
    - 
- [ ] 
    - 
- [ ] 
    - 

### Action Follow-up
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2022.11.21] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
     - [ ] Review previous action items outstanding 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] 
- [ ] 
- [ ] 

### FYI / Announcements
-  
 
### Notes from Meeting
- [ ] 
    - 
- [ ] 
    - 
- [ ] 
    - 

### Action Follow-up
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2022.11.28] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
     - [ ] Review previous action items outstanding 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] 
- [ ] 
- [ ] 

### FYI / Announcements
-  
 
### Notes from Meeting
- [ ] 
    - 
- [ ] 
    - 
- [ ] 
    - 

### Action Follow-up
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2022.12.05] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
     - [ ] Review previous action items outstanding 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] 
- [ ] 
- [ ] 

### FYI / Announcements
-  
 
### Notes from Meeting
- [ ] 
    - 
- [ ] 
    - 
- [ ] 
    - 

### Action Follow-up
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2022.12.12] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ]  Check-in on IUT2 implementation - how's it going? any questions / help needed. How much is left? Any idea on timing? 
- [ ] 
- [ ] 

### FYI / Announcements
-  
 
### Notes from Meeting
- [ ] 
    - 
- [ ] 
    - 
- [ ] 
    - 

### Action Follow-up
- [ ] Review previous action items
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2023.01.02] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ]  Restart recruiting new Developers to join the team
- [ ] 
- [ ] 

### FYI / Announcements
-  
 
### Notes from Meeting
- [ ] 
    - 
- [ ] 
    - 
- [ ] 
    - 

### Action Follow-up
- [ ] Review previous action items
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2023.01.23] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] IUT2 Progress Check-In 
- [ ] Design Requests for Dev (if any)
- [ ] Dev Team Recruiting
- [ ] 

### FYI / Announcements
- [ ] Next week is team planning / first week of month. All discipline syncs cancelled (including Mon/Thur dev syncs)
- [ ] Jamie Siu out 1/27 Friday to 2/3 Friday
- [ ] James Shin out 1/30 Monday to 1/31 Tuesday
- [ ] Tracy N out two weeks for personal time / self care

### Notes from Meeting
- [ ] 
- [ ] 
- [ ] 

### Action Follow-up
- [ ] Review previous action items
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2023.02.13] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] 
- [ ] 
- [ ] 

### FYI / Announcements
- [ ] 

### Notes from Meeting
- [ ] 
- [ ] 
- [ ] 

### Action Follow-up
- [ ] Review previous action items
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2023.03.06] Agenda and Notes
### Attendees
- [ ] Thomas PM
- [ ] Lexie
- [ ] Sydney
- [ ] Tom G
- [ ] Anita
- [ ] Serena
- [ ] Raman
- [ ] Ailin C
- [ ] Troy
- [ ] Royal
- [ ] Tracy
- [ ] Phu
- [ ] Justin
- [ ] Alexis
- [ ] Jamie

### Recurring items: 
- [ ] Accountability and Support Check 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] 
- [ ] 
- [ ] 

### FYI / Announcements
- [ ] 

### Notes from Meeting
- [ ] 
- [ ] 
- [ ] 

### Action Follow-up
- [ ] Review previous action items
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jamiesiu** [comment]
# [2023.03.13] Agenda and Notes
### Attendees
- [ ] Thomas PM
- [ ] Lexie
- [ ] Sydney
- [ ] Tom G
- [ ] Anita
- [ ] Serena
- [ ] Raman
- [ ] Ailin C
- [ ] Troy
- [ ] Royal
- [ ] Tracy
- [ ] Phu
- [ ] Justin
- [ ] Alexis
- [ ] Jamie

### Recurring items: 
- [ ] Accountability and Support Check 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] 
- [ ] 
- [ ] 

### FYI / Announcements
- [ ] 

### Notes from Meeting
- [ ] 
- [ ] 
- [ ] 

### Action Follow-up
- [ ] Review previous action items
- [ ] @ 
- [ ] @ 

### Items for next weeks agenda
- [ ] 
- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by jccchurch** [comment]
# [2023.05.08] Agenda and Notes
### Attendees
- [x] Thomas PM
- [x] Sydney
- [ ] Tom G
- [ ] Anita
- [x] Raman
- [ ] Ailin C
- [ ] Troy
- [ ] Royal
- [ ] Tracy
- [x] Phu
- [ ] Justin
- [x] Alexis
- [x] Julia
- [ ] Analicia 
- [ ] Lane

### Recurring items: 
- [ ] Accountability and Support Check 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] 
- [ ] 
- [ ] 

### FYI / Announcements
- [ ] 

### Notes from Meeting

- [ ] 
- [ ] 
- [ ] 

### Action Follow-up
- [ ] Review previous action items

### Items for next weeks agenda

- [ ] Carry over to next week anything we didn't get covered this week
   - [ ] Make next weeks agenda

**Comment by lmitch10** [comment]
# [2023.05.08] Agenda and Notes
### Attendees
- [ ] Thomas PM
- [ ] Sydney
- [ ] Tom G
- [ ] Anita
- [ ] Raman
- [ ] Ailin C
- [ ] Troy
- [ ] Phu
- [ ] Justin
- [ ] Alexis
- [ ] Julia
- [ ] Analicia 
- [ ] Lane
- [ ] Liz
- [ ] Michelle

### Recurring items: 
- [ ] Accountability and Support Check 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] Julia phasing out of the program
- [ ] Finding new Content PM and Design PM 
- [ ] Dev onboarding

### FYI / Announcements
- [ ] 

### Notes from Meeting




### Items for next weeks agenda
- [ ] Establish facilitator & notetaker rotation 
- [ ] Make next weeks agenda

**Comment by amejiamesinas** [comment]
# [2023.10.12] Agenda and Notes
### Attendees
- 

### Recurring items: 
- [ ] Accountability and Support Check 
- [ ] Blockers Support / Help Needed 
- [ ] Progress Share / Feedback Requests 

### New Meeting Items 
- [ ] Roadmapping
- [ ] Accessibility 
- [ ] Milestones and Role Issue Tags 
- [ ] 
- [ ] 
- [ ] 


### FYI / Announcements
- [ ] 

### Notes from Meeting




### Items for next weeks agenda
- [ ] Establish facilitator & notetaker rotation 
- [ ] Improving cross collab on Github using issues: Create issues for each team vs handing one issue from team to team
- [ ] Make next weeks agenda

**Comment by sydneywalcoff** [comment]
Since this meeting has been cancelled. I'm going to close this issue.
