### ISSUE TITLE
UXR handover from Content/Design

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#719]
### Overview
Coordinate feedback issues and focus areas from Content and Design 
### Action Items
- [x] Gather most important areas needing feedback
- [x] Add to Slide deck
UPDATES
- [x] Transfer info from affinity mapping into slide deck and organize
- [x] Add links to github issues the areas address from IUT 1 
- [x] Add appropriate images and arrows to add visual element 
- [ ] Hand over to UXR

### Resources/Instructions
[Slide deck for UXR](https://docs.google.com/presentation/d/15wcgqSastcWfsZJDfgrAbIIDou44cb2TrWCDLWFhWAY/edit#slide=id.p)

**Comment by anitadesigns** [comment]
Reviewing slides one more time before handing over

**Comment by anitadesigns** [comment]
Scheduled presentation with UXR for 1/27. @SamHyler @RenaNicole would it be okay to close this?

**Comment by SamHyler** [comment]
> Scheduled presentation with UXR for 1/27. @SamHyler @RenaNicole would it be okay to close this?

Yes! Closing issue as handover will happen this week.
