### ISSUE TITLE
[Feature] User can download final PDF or get emailed

### ISSUE THREAD

**Issue by alexchoiweb** [hackforla/expunge-assist#72]

**Comment by cayd** [comment]
Adding myself to look into the emailing side of this

**Comment by ggrrettcchhenn** [comment]
Currently the user can download a PDF of their final statement (thank you @alexchoiweb), but we will hold off on adding the functionality to email themselves the final statement until after we connect with the expungement clinic staff in the next few weeks.

The Research team will gather more information about the expungement clinic attorneys' process and assess what output would be most helpful. Once we have more information about that, we will bring this issue back up to make sure that the user is getting their statement in a helpful (& ideally editable) format.

**Comment by aahvocado** [comment]
Archiving this because it will be covered by https://github.com/hackforla/expunge-assist/issues/262
