### ISSUE TITLE
[From IUT 1] Add spell check copy to Advice page

### ISSUE THREAD

**Issue by kyle-whitaker** [hackforla/expunge-assist#721]
### Overview
Until there is a decision about creating a spell check solution for the user to check their letter, Content discussed linking to a free online spell checker on the Advice page and recommending that the user check their spelling before downloading their letter.

### Action Items
- [ ] Find good free spell check tool
- [ ] Add new copy and link to Advice page

### Resources/Instructions
Figma

**Comment by SamHyler** [comment]
Unsure if we will do this, or if we will go with grammerly or redirect somewhere else (or not at all).

**Comment by SamHyler** [comment]
privacy was a concern with grammerly. there may be other solutions. The spelling/grammar problem persists and will need a solution eventually. Putting as low prio as not for launch prep for now.

**Comment by SamHyler** [comment]
Added to https://github.com/hackforla/expunge-assist/issues/982 for consideration in the redesign of the Advice page. Re-open if needed on a different page/area of the site, otherwise closing as unplanned.
