### ISSUE TITLE
Gather functionality issues on website and create a list for Dev

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#739]
### Overview
On November 7th, Dev published design updates to the [Expunge Assist website](https://expungeassist.org/#/./). Design and Content need to go through the website and ensure there are no usability or inconsistency errors from the design changes we handed over. We want to present this to Dev on Monday, November 14, 2022.

### Action Items
- [x] Audit the website for inconsistencies or functionality issues 
- [x] Create a Github issue for Dev to fix 
- [x] Add issue to the list below

### List with Issues for Dev linked
- #741
- #740
- #742
- #743
- #744
- https://github.com/hackforla/expunge-assist/issues/745
- #737 
- Make ":" consistent on final preview page (i.e. "Previewing: blah blah" for all and not a mix of that and "Previewing blahblah"). I do not know what the original was. #752 
- See comment on this issue: Content has been entered incorrectly (Unemployment vs Unemployed) https://github.com/hackforla/expunge-assist/issues/699

**Comment by SamHyler** [comment]
Note to self: Previewing blah blah is listed as "Previewing: blah blah" AND "Previewing blah blah" in different spaces. Should be consistent

**Comment by anitadesigns** [comment]
@SamHyler Since we are starting to integrate QA process with Dev, I say we can close this issue since we would not need to use it anymore and would review issues that we created and Dev completed to ensure all changes are added before officially closing and the issue. We could comment on each issue changes that we were not integrated for Dev to fix

**Comment by SamHyler** [comment]
@anitadesigns Agreed!
