### ISSUE TITLE
Fix Completed Progress bar on last page of LG

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#744]
### Overview
The progress bar on the [last page of the letter generator] (https://expungeassist.org/#/./form/finalize/preview)is right-aligned and not fully filled in. Since this page is to represent a complete or final step of the LG, the progress bar should be completely filled in. 

<img width="1430" alt="Screen Shot 2022-11-10 at 11 54 27 AM" src="https://user-images.githubusercontent.com/105686896/201193133-ac43bb02-7372-471d-a442-86f7f51559d7.png">

### Action Items
- [ ] update the progress bar to be completely filled in 

### Resources/Instructions
Please see the [design handoff space page](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?node-id=7144%3A74353) on Figma to reference design details

**Comment by AilinLuca** [comment]
Has already been resolved. See screenshots. 
<img width="1722" alt="Screen Shot 2023-03-21 at 10 54 48 PM" src="https://user-images.githubusercontent.com/33815456/226790187-e5d90d6b-828f-43a4-b229-ad9aa26632cc.png">
