### ISSUE TITLE
Onboard / Offboard: Dev

### ISSUE THREAD

**Issue by thomasdemoner** [hackforla/expunge-assist#749]
### Dependency 
Waiting to have a Developer to on/off-board.

### Overview
Checklist for complete developer onboarding / offboarding process

### Action Items
- [ ] Move In-Progress column when onboarding or offboarding someone.
- [ ] 

### Date Updated
(insert date you created this issue and keep updating the date each time the org template change are integrated)
2022-02-10

### Action Items
- [ ] Check to see if the org template for this process has new steps in it, and if it does, update this  issue and its template with content and add the last date you updated the template below
- [ ] Copy template to comment below
- [ ] Add name of person
- [ ] Check off as done

```
#### Onboard
- [ ] Request google account email / GH Username
- [ ] Google Calendar meeting invites
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
- [ ] GitHub
     - [ ] Add to team write team
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Share link to wiki / contributing doc, PR guidelines


For Leads/PM
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
```
```
#### Offboard
  - [ ] 1password setup
    - [ ] remove from team vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault
- [ ] Google Drive
   - [ ] demote to viewer
- [ ] Roster
  - [ ] mark as inactive
- [ ] GitHub
     - [ ] demote member to read only team and remove from write team
- [ ] Figma
  - [ ] remove from team
- [ ] Go over the person's assigned Github issues and Close or Reassign them
```

### Resources/Instructions
- 1password.com
- [Expunge Assist Google Drive](https://drive.google.com/drive/folders/1qR-5gm7a-3h-Zm6Tu8IxDQ6yL488kf1n?usp=sharing)
- [Expunge Assist Team Roster](https://docs.google.com/spreadsheets/d/12sAwYiQJP4fmEONF6-oUVYFVupTwSkci/edit)
- Check public and 2FA at [people page](https://github.com/orgs/hackforla/people)
- [Expunge Assist GitHub Team URL](https://github.com/orgs/hackforla/teams?query=expunge)
   - [base (read)](https://github.com/orgs/hackforla/teams/expunge-assist/members)
   - [write](https://github.com/orgs/hackforla/teams/expunge-assist-write/members)
   - [maintain](https://github.com/orgs/hackforla/teams/expunge-assist-maintainers)
   - [admin](https://github.com/orgs/hackforla/teams/expunge-assist-admins/members)
- [Figma Members page](https://www.figma.com/files/team/957045401738666965/Expunge-Assist's-team/members?fuid=1085745174581545626)
- Shortcut for adding a profile to the desktop:  chrome://settings/manageProfile
- Tutorials
  - [Forward emails to team members](https://github.com/hackforla/product-management/wiki/Forward-emails-to-team-members)

[org template](https://raw.githubusercontent.com/hackforla/.github/main/.github/ISSUE_TEMPLATE/onboard---offboard--product.md) updated 2022-02-09

**Comment by thomasdemoner** [comment]
#### Onboard - Davide
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team write team
        - [ ] Change membership to maintainer
     - [ ] Add to read vault
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault

**Comment by jamiesiu** [comment]
#### Onboard Royal Bai
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team write team
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault

**Comment by jamiesiu** [comment]
#### Onboard Tracy N
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
  - [ ] Check for 2FA and note in roster
- [ ] GitHub
     - [ ] Add to team write team
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault

**Comment by jamiesiu** [comment]
#### Onboard Phillip Sanchez
- [ ] Request email address / GH username for permissions
- [ ] Google Calendar meeting invites
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
- [ ] GitHub
     - [ ] Add to team write team
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Share link to wiki / contributing doc, PR guidelines


For Leads/PM
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] Expunge-Assist
       - [ ] Zoom vault

**Comment by thomasdemoner** [comment]
#### Onboard Tom G
- [ ] Request google account email / GH Username
- [ ] Google Calendar meeting invites
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
- [ ] GitHub
     - [ ] Add to team write team
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Share link to wiki / contributing doc, PR guidelines

**Comment by thomasdemoner** [comment]
#### Onboard Raman Kala @ramankala
- [ ] Request google account email / GH Username
- [ ] Google Calendar meeting invites
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
- [ ] GitHub
     - [ ] Add to team write team
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Share link to wiki / contributing doc, PR guidelines

**Comment by thomasdemoner** [comment]
#### Onboard
- [ ] Request google account email / GH Username
- [ ] Google Calendar meeting invites
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
- [ ] GitHub
     - [ ] Add to team write team
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Share link to wiki / contributing doc, PR guidelines

**Comment by thomasdemoner** [comment]
#### Onboard Troy
- [ ] Request google account email / GH Username
- [ ] Google Calendar meeting invites
- [ ] Google Drive
   - [ ] Add to drive as Contributor
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public and note in roster
- [ ] GitHub
     - [ ] Add to team write team
     - [ ] Add to read vault
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] Share link to wiki / contributing doc, PR guidelines

**Comment by sydneywalcoff** [comment]
replaced with Issue template by #1206
