### ISSUE TITLE
Update final preview page with ":" 

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#752]
### Overview
Just a small adjustment for consistency. There are ":" colons on some headlines and not on others on the Final preview page.
This page: https://expungeassist.org/#/./form/finalize

### Action Items
- [ ] Add a colon " : " on each headline in the appropriate place on the Final preview page. For example, this headline is live and correct: "Previewing Involvement: Unemployed". Please update all to match.

**Comment by jamiesiu** [comment]
@SamHyler wanted to check in regarding the draft status for this issue. Did we need additional info in order to finalize it?

**Comment by SamHyler** [comment]
Thank you Jamie, simply got overwhelmed by Github and forgot to finish this one. I finalized it. 

> @SamHyler wanted to check in regarding the draft status for this issue. Did we need additional info in order to finalize it?
