### ISSUE TITLE
[PAUSE STUFF] Update Content timeline for documentation purposes

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#756]
### Overview
Content lead needs to update the content timeline for the most recent developments (IUT 2) and put it in an appropriate folder in Google Drive (i.e. move it from the wiki which is now going to be an external resource)
### Action Items
- [x] Update timeline with IUT 2
- [x] Put in appropriate folder in Content Google Drive, link where appropriate

### Resources/Instructions
[Content timeline in Google Drive](https://docs.google.com/document/d/1W2zFZxBvFfzLaPlv51LEzQx3J_0fCiy_XlBYjN59IUA/edit#heading=h.ass02svzyll7)

**Comment by SamHyler** [comment]
Removed the timeline from the Wiki, it's how once again housed in the google drive in this original document. https://docs.google.com/document/d/1W2zFZxBvFfzLaPlv51LEzQx3J_0fCiy_XlBYjN59IUA/edit#heading=h.ass02svzyll7

Will update timeline shortly, updated Wiki first.

**Comment by SamHyler** [comment]
@kyle-whitaker @jamiesiu @jamesshin27  would you check the doc to see if there's something I should be adding ?

**Comment by SamHyler** [comment]
@jamiesiu @jamesshin27  I added some milestone information in the document and made some notes.

**Comment by kyle-whitaker** [comment]
> 

@SamHyler Gave it a look and made a few minor adjustments, but content looks good. Fixed page break.

**Comment by SamHyler** [comment]
> > 
> 
> @SamHyler Gave it a look and made a few minor adjustments, but content looks good. Fixed page break.

Thank you @kyle-whitaker ! Please tell me how you fixed the page break issue - it was driving me mad.

**Comment by kyle-whitaker** [comment]
> > > 
> > 
> > 
> > @SamHyler Gave it a look and made a few minor adjustments, but content looks good. Fixed page break.
> 
> Thank you @kyle-whitaker ! Please tell me how you fixed the page break issue - it was driving me mad.

@SamHyler It was some kind of heading issue, so I just reformatted that section of text to "Normal" and that did it.

**Comment by SamHyler** [comment]
Have updated with comments from Jamie, Kyle, and Alexis (newest Content member). Added a key to identify common terms and milestones. Up to date as of Feb 2023. Future content designers, please update as necessary!
