### ISSUE TITLE
New Year Check-in with Research Team Members

### ISSUE THREAD

**Issue by yumengluo** [hackforla/expunge-assist#771]
### Overview
Check-in with every team member's capacity and expectations

### Action Items

- [x] Create a spreadsheet including the average time per week, if they’re going to be away/busy so that they know if in the next few months, particular UXR skills they want to develop) 
- [x] check-in with every team member 
### Resources/Instructions
 [Check-in spreadsheet](https://docs.google.com/spreadsheets/d/1tfIgJIxaCMSV2RlG2Rf5aquUi3mE1vKIakHSmDsaw0k/edit#gid=0)

**Comment by kelseylondon** [comment]
@yumengluo - I can't access the spreadsheet. Would you please expand editing permissions and move it into a folder on the Expunge Assist Drive?

**Comment by yumengluo** [comment]
Strange. I created it in the Expunge Assist folder. I will take a look Sent from my iPhoneOn Jan 13, 2023, at 11:37 AM, kelseylondon ***@***.***> wrote:﻿
@yumengluo - I can't access the spreadsheet. Would you please expand editing permissions and move it into a folder on the Expunge Assist Drive?

**Comment by yumengluo** [comment]
@kelseylondon I fixed it. It is in the expunge assist google drive now.
