### ISSUE TITLE
Set up GHA to close issue automatically

### ISSUE THREAD

**Issue by jamesshin27** [hackforla/expunge-assist#776]
### Overview
Currently, the issues need to be closed manually. We want to set up GHA (GitHub Actions) so that the linked issue gets closed automatically once PR is merged.

### Action Items
Set up GHA so the linked issue is closed automatically.

### Resources/Instructions
The Website project team has a way to close out Issues automatically.

**Comment by sydneywalcoff** [comment]
Closing as we can do this without a GHA. Improvement of process has fixed this.
