### ISSUE TITLE
Update Research Wiki: UX Researcher page - "What is UX Research?"

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#777]
### Overview
The wiki is transforming into both an internal and public facing wiki, and new pages need to be created to document our research processes and outputs. We need to update the "UX Researcher" page to provide information to potential volunteers about the role of UX researchers. 

### Action Items

- [x] Review example from Content team: [Content Writer](https://github.com/hackforla/expunge-assist/wiki/Content-Writer)
- [x] Update section titled "What is UX Research"
    - [x] Go to the [UX Researcher wiki page](https://github.com/hackforla/expunge-assist/wiki/UX-Researcher) and click "edit"
    - [x] Under the heading "What is UX Research", write a brief description of the role of a UX researcher. 
    - [x] Click "save page"
- [x] Request peer review:
    - [x] Ask a team member to review the section "What is UX Research"
    - [x] Assign that team member to this issue
    - [x] Leave a comment on this issue tagging that team member and asking for feedback
- [x] Peer reviewer:
    - [x] Read the section "What is UX research?"
    - [x] Provide feedback by:
        - [x] Editing the wiki page (see instructions above). Please explain your changes in the field "edit message" before pressing "save page" _and/or_
        - [x] Writing suggestions as a comment to the issue.
- [x] Make suggested changes (or explain why you're not making a suggested change in the comments to this issue). 
- [x] Close issue. 
     
### Resources/Instructions
- [The current "UX Researcher" wiki page is here ](https://github.com/hackforla/expunge-assist/wiki/Researcher)
- [The example "Content Writer" page is here ](https://github.com/hackforla/expunge-assist/wiki/Content-Writer)
- [Github/Wiki Video Tutorial](https://drive.google.com/drive/u/0/folders/1IGHX-b8aDYGh1zRsYuV_XpHiFFjzbkyh)
- [Scaffolding of Research Wiki Pages](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?node-id=0%3A1&t=lypj29BG7rOOOuhm-1)

### Related issues
- #774
- #714
- #723 
- #473 
- #401

**Comment by dmeyers1348** [comment]
@SamHyler I edited some grammar and added another sentence to further describe the goal of UX Research. Let me know if you have questions, otherwise we can close the issue when you're ready

**Comment by SamHyler** [comment]
I think this can be closed ? @amejiamesinas @sofialaguna

**Comment by sylvia-nam** [comment]
I made additions to the page to clarify some of the language on UX research in general and UX research in civic tech in particular. I also noted reordered the description of the methods used for UXR for EA based on a hierarchy of methods
