### ISSUE TITLE
Update Research Wiki: UX Researcher page - "UX Research for Expunge Assist"

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#778]
### Overview
The wiki is transforming into both an internal and public facing wiki, and new pages need to be created to document our research processes and outputs. We need to update the "UX Researcher" page to provide information to potential volunteers and partners about the Expunge Assist research team. 

### Action Items

- [x] Review example from Content team: [Content Writer](https://github.com/hackforla/expunge-assist/wiki/Content-Writer)
- [x] Update section titled "UX Research for Expunge Assist"
    - [x] Go to the [UX Researcher wiki page](https://github.com/hackforla/expunge-assist/wiki/UX-Researcher) and click "edit"
    - [x] Under the heading "UX Research for Expunge Assist", write a brief description of the role of the Research Team for Expunge Assist. 
    - [x] Click "save page"
- [x] Request peer review:
    - [x] Ask a team member to review the section "UX Research for Expunge Assist"
    - [x] Assign that team member to this issue
    - [x] Leave a comment on this issue tagging that team member and asking for feedback
- [x] Peer reviewer:
    - [x] Read the section "UX Research for Expunge Assist"
    - [x] Provide feedback by:
        - [x] Editing the wiki page (see instructions above). Please explain your changes in the field "edit message" before pressing "save page" _and/or_
        - [x] Writing suggestions as a comment to the issue.
- [ ] Make suggested changes (or explain why you're not making a suggested change in the comments to this issue). 
- [ ] Close issue. 
     
### Resources/Instructions
-[Edited page for this issue is here](https://github.com/hackforla/expunge-assist/wiki/UX-Researcher)

- [The current "UX Researcher" wiki page is here ](https://github.com/hackforla/expunge-assist/wiki/Researcher) -- this page is now dead/defunct and has been replaced with the same link as above
- [The example "Content Writer" page is here ](https://github.com/hackforla/expunge-assist/wiki/Content-Writer)

### Related issues
- #777
- #774
- #714

**Comment by SamHyler** [comment]
Make a quick draft, also updated the broken/dead link on this page so that it links to the UXR page https://github.com/hackforla/expunge-assist/wiki/Joining-the-Team

**Comment by dmeyers1348** [comment]
@SamHyler I added a sentence on our target user groups. If you're set with this, feel free to close this issue!

**Comment by SamHyler** [comment]
@dmeyers1348 I added the right wiki page to the resources section. Thanks for the added sentence!
