### ISSUE TITLE
Update Research Wiki: UX Researcher page - "Joining the team"

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#779]
### Overview
The wiki is transforming into both an internal and public facing wiki, and new pages need to be created to document our research processes and outputs. We need to update the "UX Researcher" page to provide information to potential volunteers about how to join the team.

### Action Items

- [x] Review example from Content team: [Content Writer](https://github.com/hackforla/expunge-assist/wiki/Content-Writer)
- [x] Update section titled "Joining the Research Team"
    - [x] Go to the [UX Researcher wiki page](https://github.com/hackforla/expunge-assist/wiki/UX-Researcher) and click "edit"
    - [x] Under the heading "Joining the Research Team", write a sentence explaining how to join the team (see example from Content above)
    - [x] Click "save page"
- [x] Request peer review:
    - [x] Ask a team member to review the section "Joining the Research Team"
    - [x] Assign that team member to this issue
    - [x] Leave a comment on this issue tagging that team member and asking for feedback
- [ ] Peer reviewer:
    - [x] Read the section "Joining the Research Team"
    - [x] Provide feedback by:
        - [ ] Editing the wiki page (see instructions above). Please explain your changes in the field "edit message" before pressing "save page" _and/or_
        - [x] Writing suggestions as a comment to the issue.
- [x] Make suggested changes (or explain why you're not making a suggested change in the comments to this issue). 
- [x] Close issue. 

### Resources/Instructions
- [The current "UX Researcher" wiki page is here ](https://github.com/hackforla/expunge-assist/wiki/Researcher)
- [The example "Content Writer" page is here ](https://github.com/hackforla/expunge-assist/wiki/Content-Writer)

### Related issues
- #777
- #774
- #714
-  #723

**Comment by yumengluo** [comment]
It looks good. I did not make any changes.
