### ISSUE TITLE
Research into Automation Tools or Productivity Tools

### ISSUE THREAD

**Issue by j100892** [hackforla/expunge-assist#78]
**Gilles is also on this ticket**

### Overview
Pro Bono Attorneys working in expungement clinics or criminal justice related issues may need a whole host of digital tools to help their work. 

### Action Items
Research (Primary or Secondary) is needed and a summary of possible opportunties for design and dev work  

### Resources/Instructions

Here are some possible avenues we can contact to gain more information and do some early discovery/uncover pain points: 

1. https://www.laclj.org/
2. https://safeandjust.org/about-us/our-team/
3. https://pbtraining.org/volunteer/expungement-clinic/

Or going through different legal aid clinics on this list here:

**https://libguides.law.ucla.edu/c.php?g=459742&p=3151654**

Please summarize the findings, notes or conversations in a Google Doc and share that file inside our record clearance Google Drive.

**Comment by yumengluo** [comment]
This research is duplicated with another new discovery research.
