### ISSUE TITLE
Review Desktop Edit Final Letter (FIGMA)  [PAUSE STUFF etc.]

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#787]
### Overview
Edit final letter screen is now finalized by design. Needs to be reviewed and checked off by content. 
### Action Items

- [x] Review section
- [x] Edit any language 
- [x] Let any team members know of changes where relevant
- [ ] Finalize in Content & Design

### Resources/Instructions
See the Desktop page on figma

**Comment by kyle-whitaker** [comment]
Reviewed, removed "Previewing" language from headings to match live site. Gave gold star.
