### ISSUE TITLE
Update Research Wiki: Discovery Research, Phase 2

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#789]
### Overview
The wiki is transforming into both an internal and public facing wiki, and new pages need to be created to document our research processes and outputs. We need to update the page about our Stakeholder Interviews to provide new volunteers and potential partners with information about our past research.

### Action Items

- [x] Review example from Internship Project: [Research Plan 6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [x] Locate necessary information and files on our [Research Timeline](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Research-Plans-and-Goals)
   - [x] Research Plan
   - [x] Relevant docs & links
- [x] Go to the [Discovery Research Phase 2 wiki page](https://github.com/hackforla/expunge-assist/wiki/Discovery-Research-Phase-2) and click "edit"
- [x] Update section titled "Summary of Research"
    - [x] Under the subheading "Research Questions", write out key research questions using bullets (_note_: the research plan for Stakeholder interviews did not phrase these as questions but you can extrapolate from the text in the "Goals & Key Questions" section)
    - [x] Under the subheading "Purpose", write out the purpose/goals of this research 
    - [x] Under the subheading "Methods", provide a 1-2 sentence summary of methods.
- [x] Update section titled "Current Status"
    - [x] Write "complete", "ongoing", or "future research"
- [x] Update section titled "Assets"
    - [x] Create appropriate subheadings for the project documents (use h3 to generate markdown for subheadings) - such as "Research Plan", "Interview Guide", "Meeting Notes"
    - [x] Add links to each asset under the appropriate subheading
- [x] Click "save page"
- [x] Request peer review:
    - [x] Ask a team member to review this page
    - [x] Assign that team member to this issue
    - [x] Leave a comment on this issue tagging that team member and asking for feedback
- [x] Peer reviewer:
    - [x] Read the page
    - [x] Click on all links to make sure they work
    - [x] Provide feedback by:
        - [x] Editing the wiki page (see instructions above). Please explain your changes in the field "edit message" before pressing "save page" _and/or_
        - [x] Writing suggestions as a comment to the issue.
- [x] Make suggested changes (or explain why you're not making a suggested change in the comments to this issue). 
- [x] Close issue. 
     
### Resources/Instructions
- [Project Background: Stakeholder Interviews wiki page](https://github.com/hackforla/expunge-assist/wiki/Project-Background:-Stakeholder-Interviews)
- [Research Timeline](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Research-Plans-and-Goals)
- [Example from Internship Project: Research Plan 6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [Github/Wiki Video Tutorial](https://drive.google.com/drive/u/0/folders/1IGHX-b8aDYGh1zRsYuV_XpHiFFjzbkyh)
- [Scaffolding of Research Wiki Pages](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?node-id=0%3A1&t=lypj29BG7rOOOuhm-1)

### Related issues
- #774
- #714
- #723 
- #473 
- #401

**Comment by kelseylondon** [comment]
Changed the name of the page and the title in the Research Timeline to better reflect that this was considered Phase 2 of the Research Discovery process.

**Comment by dmeyers1348** [comment]
One note for Peer Reviewer: I could not locate the Research Plan for this project. The Research Questions were created based on the Goals & Key Questions section.

**Comment by yumengluo** [comment]
I do not recall there was a research plan for this research.
