### ISSUE TITLE
Update Research Wiki: Discovery Research Phase 1

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#790]
### Overview
The wiki is transforming into both an internal and public facing wiki, and new pages need to be created to document our research processes and outputs. We need to update the page about our Literature Reviews to provide new volunteers and potential partners with information about our past research.

### Action Items

- [x] Review example from Internship Project: [Research Plan 6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [x] Locate necessary information and files on our [Research Timeline](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Research-Plans-and-Goals)
   - [x] [Past Research Overview](https://docs.google.com/document/d/1OpvE--lSkKukhbim7EYUCSsAUQ92msCxoH8gs-kt8Hg/edit) (this is an account of several types of past research, including - but not limited to - lit reviews)
   - [x] [Review of Code for America's Research on Rights and Record Clearance ](https://docs.google.com/document/d/1g-w-LobHuRTeKutA7cAQoQKGmWb2C_W6EeUqjKU3zC0/edit#heading=h.aoqes017iz2b)
   - [x] [Review of Code for America's data on user personas/people seeking expungement ](https://docs.google.com/document/d/1YJByabmc-PAhvM2khlwy4jrzJFGoYIXmn4NgniQRvhg/edit)(first part of document)
- [x] Go to the [Discovery Research Phase 1 wiki page](https://github.com/hackforla/expunge-assist/wiki/Discovery-Research---Phase-1) and click "edit"
- [x] Update section titled "Summary of Research"
    - [x] Under the subheading "Research Questions", write out key research questions using bullets (_note_: there do not appear to be clearly stated research questions - can we extrapolate from the available documentation?)
    - [x] Under the subheading "Purpose", write out the purpose/goals of this research 
    - [x] Under the subheading "Methods", provide a 1-2 sentence summary of methods.
- [x] Update section titled "Current Status"
    - [x] Write "complete", "ongoing", or "future research"
- [x] Update section titled "Assets"
    - [x] Create appropriate subheadings for the project documents (use h3 to generate markdown for subheadings) - such as "Research Plan", "Interview Guide", "Meeting Notes"
    - [x] Add links to each asset under the appropriate subheading
- [x] Click "save page"
- [x] Request peer review:
    - [x] Ask a team member to review this page
    - [x] Assign that team member to this issue
    - [x] Leave a comment on this issue tagging that team member and asking for feedback
- [x] Peer reviewer:
    - [x] Read the page
    - [x] Click on all links to make sure they work
    - [x] Provide feedback by:
        - [x] Editing the wiki page (see instructions above). Please explain your changes in the field "edit message" before pressing "save page" _and/or_
        - [x] Writing suggestions as a comment to the issue.
- [x] Make suggested changes (or explain why you're not making a suggested change in the comments to this issue). 
- [x] Close issue. 
     
### Resources/Instructions
- [Project Background: Literature Reviews wiki page](https://github.com/hackforla/expunge-assist/wiki/Project-Background:-Literature-Reviews)
- [Example from Internship Project: Research Plan 6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [Research Timeline](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Research-Plans-and-Goals)
- [Past Research Overview](https://docs.google.com/document/d/1OpvE--lSkKukhbim7EYUCSsAUQ92msCxoH8gs-kt8Hg/edit) (this is an account of several types of past research, including - but not limited to - lit reviews)
- [Review of Code for America's Research on Rights and Record Clearance ](https://docs.google.com/document/d/1g-w-LobHuRTeKutA7cAQoQKGmWb2C_W6EeUqjKU3zC0/edit#heading=h.aoqes017iz2b)
- [Review of Code for America's data on user personas/people seeking expungement ](https://docs.google.com/document/d/1YJByabmc-PAhvM2khlwy4jrzJFGoYIXmn4NgniQRvhg/edit)(first part of document)

### Related issues
- #774
- #714
- #723 
- #473 
- #401

**Comment by kelseylondon** [comment]
Changed page name from "Literature Reviews" to "Discovery Research" to better reflect the range of methods used. Updated our Research Timeline page to do the same.

**Comment by dmeyers1348** [comment]
@kelseylondon or @yumengluo - it looks like the link to "Record Clearance Event Personas" is incorrect, and is bringing me to the same page as "Interviews with Participants at Legal Clinics". I can't seem to locate the actual link to the personas, any chance either one of you could locate that link?

**Comment by yumengluo** [comment]
@dmeyers1348 Here is the correct link to the persona research: https://drive.google.com/drive/u/0/folders/12-1yK0UMW_XH1Q6sTtlXmq0LjVu7E_Tr

**Comment by yumengluo** [comment]
I corrected the link to the "Record Clearance Event Personas"
