### ISSUE TITLE
Update Research Wiki: RP2 - Terminology Survey

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/expunge-assist#793]
### Overview
The wiki is transforming into both an internal and public facing wiki, and new pages need to be created to document our research processes and outputs. We need to update the page about RP2 to provide new volunteers and potential partners with information about our ongoing research.

### Action Items

- [x] Review example from Internship Project: [Research Plan 6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [x] Locate necessary information and files on our [Research Timeline](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Research-Plans-and-Goals)
   - [x] Research Plan
   - [x] Relevant docs & links
- [x] Go to the [RP2 wiki page](https://github.com/hackforla/expunge-assist/wiki/Research-Plan-2:-Terminology-Survey) and click "edit"
- [x] Update section titled "Summary of Research"
    - [x] Under the subheading "Research Questions", write out key research questions using bullets 
    - [x] Under the subheading "Purpose", write out the purpose/goals of this research 
    - [x] Under the subheading "Methods", provide a 1-2 sentence summary of methods.
- [x] Update section titled "Current Status"
    - [x] Write "complete", "ongoing", or "future research"
- [x] Update section titled "Assets"
    - [x] Add link to Research Plan 
    - [x] Add link to survey's [Google Drive folder](https://drive.google.com/drive/folders/1klixLDeB1wu1c3r56eTR9i0qlkDb9Dly)
- [x] Update section titled "Relevant Issues"
    - [x] Using bullet points, add links to the github issues listed in [Research Timeline](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Research-Plans-and-Goals)
- [x] Click "save page"
- [x] Request peer review:
    - [x] Ask a team member to review this page
    - [x] Assign that team member to this issue
    - [x] Leave a comment on this issue tagging that team member and asking for feedback
- [x] Peer reviewer:
    - [x] Read the page
    - [x] Click on all links to make sure they work
    - [x] Provide feedback by:
        - [x] Editing the wiki page (see instructions above). Please explain your changes in the field "edit message" before pressing "save page" _and/or_
        - [x] Writing suggestions as a comment to the issue.
- [x] Make suggested changes (or explain why you're not making a suggested change in the comments to this issue). 
- [ ] Close issue. 
     
### Resources/Instructions
- [RP1 wiki page](https://github.com/hackforla/expunge-assist/wiki/Research-Plan-1:-Information-Gathering-Survey)
- [Research Timeline](https://github.com/hackforla/expunge-assist/wiki/Expunge-Assist-Research-Plans-and-Goals)
- [Example from Internship Project: Research Plan 6](https://github.com/hackforla/internship/wiki/Research-Plan-6:-Intern-Intake-Interviews)
- [RP 2 Google Drive folder](https://drive.google.com/drive/folders/1klixLDeB1wu1c3r56eTR9i0qlkDb9Dly)
- [Github/Wiki Video Tutorial](https://drive.google.com/drive/u/0/folders/1IGHX-b8aDYGh1zRsYuV_XpHiFFjzbkyh)
- [Scaffolding of Research Wiki Pages](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?node-id=0%3A1&t=lypj29BG7rOOOuhm-1)

### Related issues
- #774
- #714
- #723 
- #473 
- #401

**Comment by yumengluo** [comment]
follow up with Sheron.

**Comment by yumengluo** [comment]
@sheronvirani21  Could you add Caroline to the project GitHub and assign this task to her?

**Comment by kelseylondon** [comment]
@yumengluo - would you be willing to peer-review this page?

**Comment by yumengluo** [comment]
Hi, I have reviewed everything on the page. It looks great! No changes need to be made.
