### ISSUE TITLE
Grammarly API assisted letter writing exploration

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#818]
### Overview
Explore further the implications of using AI-assisted tooling and/or Grammarly API in letter-writing process

### Action Items
- [ ] clarify privacy / data security concerns 
- [ ] understand from UXR/perspective of target user if this would be viable or usable
- [ ] clarify budgeting/account level needs - if using a tool, how would this be funded by the org? 
- [ ] clarify technical feasibility and costs of implementation
- [ ] clarify UX Content writing use cases and impact

### Resources/Instructions
https://developer.grammarly.com/plans - free tier available

**Comment by jamiesiu** [comment]
@sofialaguna shared they will reach out with the UXR team regarding user personas and how they might relate to use of (or ability to use) AI in letter writing

**Comment by jamiesiu** [comment]
https://www.theguardian.com/commentisfree/2020/sep/08/robot-wrote-this-article-gpt-3

**Comment by jamiesiu** [comment]
look further into ChatGPT API & data security

**Comment by mariaweissman** [comment]
Conclusion was reached to not use AI assistance. If wanting to explore in the future, can reopen or open a new issue.
