### ISSUE TITLE
[Audit Colors] in About Us page

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#826]
### Overview
Extension of #823 . Audit mobile and desktop wireframes under "Design System Audit" on Figma. 

### Action Items
- [x] Select each individual "atom" on a wireframe 
- [x] Draw an arrow to each "atom" and type out the HEX code or Color style being used
   - [x] If "atom" is not using a color style, use a yellow (HEX # #F6841B) arrow and note the HEX code being used 
- [x] Note any inconsistencies to share with the team
- [x] Close issue

### Resources/Instructions
Ask @anitadesigns or @RenaNicole if you have any questions

**Comment by lexramos01** [comment]
Completed audit color for About Us page (mobile and desktop wireframe). Note: I noticed a few atoms had the color "Black", but this color is not listed in the Color Styles.

**Comment by anitadesigns** [comment]
Hexcodes were pulled but missing other metadata. Need to be re-done to keep consistency

**Comment by mbui31** [comment]
Waiting on updates from Dev before auditing live website

**Comment by mbui31** [comment]
@anitadesigns "Completed. Ready for Review"
