### ISSUE TITLE
[Audit Colors] in Onboarding flow in LG

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#830]
### Overview
Extension of #823 . Audit mobile and desktop wireframes under "Design System Audit" on Figma. 

### Action Items
- [x] Select each individual "atom" on a wireframe 
- [x] Draw an arrow to each "atom" and type out the HEX code or Color style being used
   - [x] If "atom" is not using a color style, use a yellow (HEX # #F6841B) arrow and note the HEX code being used 
- [x] Note any inconsistencies to share with the team
- [x] Close issue

### Resources/Instructions
- Includes "Welcome", "Before you begin", "Advice" pages
- Ask @anitadesigns or @RenaNicole if you have any questions

**Comment by mbui31** [comment]
@phuonguvan feel free to take a stab at this one!
