### ISSUE TITLE
[Audit Colors] in "Education" flow in LG

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#835]
### Overview
Extension of #823 . Audit mobile and desktop wireframes under "Design System Audit" on Figma. 

### Action Items
- [x] Select each individual "atom" on a wireframe 
- [x] Draw an arrow to each "atom" and type out the HEX code or Color style being used
   - [x] If "atom" is not using a color style, use a yellow (HEX # #F6841B) arrow and note the HEX code being used 
- [ ] Note any inconsistencies to share with the team
- [ ] Close issue

### Resources/Instructions
Ask @anitadesigns or @RenaNicole if you have any questions

**Comment by jyehllow** [comment]
Needs auditing for live website section!

**Comment by phuonguvan** [comment]
@anitadesigns Completed. Ready for Review
