### ISSUE TITLE
[Audit Colors] in "Community service" flow in LG

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#837]
### Overview
Extension of #823 . Audit mobile and desktop wireframes under "Design System Audit" on Figma. This issue is split into two parts: Auditing Mobile/Desktop wireframes and Auditing screenshot of page on expungeassist.org

#### Auditing Mobile/Desktop wireframes 
- [x] Select each individual "atom" on a wireframe 
- [x] Assess what Hex code and color style is being used
- [x] Add metadata (color swap, location, style being used, Hex code, opacity )
           ***Example:***
         <img width="250" alt="Screen Shot 2023-04-26 at 9 01 03 PM" src="https://user-images.githubusercontent.com/105686896/234757040-203bbb37-ded9-47ea-912b-55f7130f3b6a.png">
- [x] Use AutoFlow plugin to draw an arrow to each "atom" and element's color metadata
   - [x] If "atom" is not using a color style, use the Orange (color style saved in Figma library) arrow and note the HEX code being used 
   - [x] If an old color style is being used, change the text sharing location and color style to red (use color style saved in Figma library)
- [x] Note any inconsistencies to share with the team

#### Auditing screenshot of page on expungeassist.org
- [x] Use Google Chrome's "inspect" tool to view website's code
- [x] Assess what Hex code and .jss component is being used 
- [x] Add metadata on screenshot in Figma (color swap, location, hex code, .jss rule)
- [x] Draw an arrow from element to metadata on Figma 

#### Next steps
- [x] Comment in this issue "Completed. Ready for Review" and tag "@anitadesigns". Add any other information that is important to share in the comments
- [x] Unassign yourself and assign "@anitadesigns " to issue
- [x] Move issue from "In Progress" to "Ready for Review" on the project board

### Resources/Instructions
Reach out to @anitadesigns if you have any questions. 

You can find access to the space to audit this page under the "Design System Audit" in Figma

**Comment by anitadesigns** [comment]
The majority of the elements on the mobile and desktop wireframes were already audited in other issues. We decided to skip auditing the mobile and desktop wireframes. The live website still needs to be audited

**Comment by phuonguvan** [comment]
@anitadesigns Completed. Ready for Review
