### ISSUE TITLE
Create LinkedIn Post for Terminology Surveys Dissemination

### ISSUE THREAD

**Issue by yumengluo** [hackforla/expunge-assist#860]
### Overview
In order to disseminate our terminology surveys on LinkedIn, we will need to create a LinkedIn for our surveys and Bonnie will help us to post it on Hack for LA's LinkedIn official account.  

### Action Items

- [x] Go to Hack for LA's LinkedIn account and learn from past posts. 

- [x] Create a survey dissemination LinkedIn post for Hack for LA's official LinkedIn account (Bonnie suggested that the format and content of the post should be consistent with the past posts )
- [x] Ask Bonnie to review the LinkedIn post, get feedback from her, and post it on the Hack for LA's LinkedIn post. 

### Resources/Instructions
 [Hack for LA LinkedIn](https://www.linkedin.com/company/hack-for-la/)
[Linkedin Post in this doc
](https://docs.google.com/document/d/13meTVbiY69lrrCpf0alsleNYQbXS1JvfKKYRt49MvZ4/edit)

**Comment by SamHyler** [comment]
Reviewed HfLA's LinkedIn. There is only 1 post by HfLA.

**Comment by SamHyler** [comment]
draft created

**Comment by SamHyler** [comment]
Incorporated feedback left on the LinkedIn document. Did not have enough information to create the draft and did not receive answers to the questions I left in the comments. Primarily: 1. Target audience for the LinkedIn post (One or both groups? One or both surveys?) 2. Which survey(s) to post. I was asked to create one post, should there be two posts? 3. Deadline for respondents to answer the survey.

Will discuss at Friday meeting and finalize.

**Comment by SamHyler** [comment]
Survey updated with 2 options. Ready for review.

**Comment by ExperimentsInHonesty** [comment]
I will happily post option 2.  Just let me know which link goes with which text by linking it in the text.  And then fill out the [reach Bonnie form ](https://docs.google.com/forms/d/e/1FAIpQLSedtewZ75lHmwAcCOnpL9AJZIF6d-Gv84i8tl_yF4lzHGQj5g/viewform) again.

I will still have to proof the survey forms.  But as long as they are properly branded, and you have addressed how to store the PII, etc. then it should be fine.  If there is a separate issue for the forms, please let me know.

**Comment by yumengluo** [comment]
https://docs.google.com/document/d/13meTVbiY69lrrCpf0alsleNYQbXS1JvfKKYRt49MvZ4/edit?pli=1
The post is updated with the link in the text.

**Comment by SamHyler** [comment]
@amejiamesinas  here's the issue for the surveys!

**Comment by amejiamesinas** [comment]
Posted by Bonnie in linkedin: https://www.linkedin.com/posts/bonnieawolfe_expunge-assist-terminology-survey-for-legal-activity-7131402871455027200-fPGq

**Comment by amejiamesinas** [comment]
This is what was posted:
Are you a member of the legal community with experience in the process of clearing a criminal record?

Could you help us learn about common legal terms by spending 2 minutes on our Expunge Assist Terminology Survey for Legal Professionals survey and/or sharing it with your network?

Your responses are completely anonymous.

Expunge Assist is a volunteer-led project by Hack for LA, a project of Civic Tech Structure, Inc. a 501(c)(3) non-profit civic tech organization.

Expunge Assist is focused on creating technology-based solutions for justice-impacted individuals seeking to expunge their criminal records and to facilitate cooperation with legal clinics working in this space.

This project is currently seeking insight on legal terminology used by various groups in the community.

Thank you!
https://docs.google.com/forms/d/e/1FAIpQLSe6K3E1wzYzsohzVM9KslgBbciiw3uFJY6qxr7mQARQ5DBwww/viewform

**Comment by amejiamesinas** [comment]
@SamHyler @RongAnn  This is the issues for the surveys that have been approved by Bonnie. We can re-share in LinkedIn. And I will post in slack. This [Google Doc](https://docs.google.com/document/d/13meTVbiY69lrrCpf0alsleNYQbXS1JvfKKYRt49MvZ4/edit) contains our blurb and links to each survey!
