### ISSUE TITLE
Finalize the survey for legal professionals

### ISSUE THREAD

**Issue by yumengluo** [hackforla/expunge-assist#861]
### Overview
We have received approval to carry out the Terminology Survey, originally developed in Summer/Fall 2022. During the week of Feb. 17th- Feb. 24, the research team reviewed the survey and provided feedback on the original survey. Now, we will need to finalize this survey and the corresponding Google form based on the feedback we collected from team members. 

### Action Items
- [x] Review and Edit the survey introduction and each question based on the feedback from the team
- [x] Finalize the survey for legal professionals on Google Doc and Google Form. 

### Resources/Instructions
[Survey Google Doc-legal professionals](https://docs.google.com/document/d/146NHcN7LRTe-zZ_2Mde0wQkQQLaaCMiUsbd3huQWjzo/edit#heading=h.fn6lpkttz3p7)
[Google form-legal professionals](https://docs.google.com/forms/d/1D-sv63VENV_mutBHWKuxC5P33pGAmDoYZapdZIC9fnw/viewform?edit_requested=true)
[Feedback from Github comments](https://github.com/hackforla/expunge-assist/issues/847)

**Comment by sofialaguna** [comment]
@amejiamesinas and I finalized the Google form based on all comments made through Github and the Google Doc. We edited the Google doc to reflect the changes we made.

**Comment by yumengluo** [comment]
The survey was sent to 15 groups or organizations' admins on March 15th, 2023.
