### ISSUE TITLE
Finalize the survey for justice-impacted individuals 

### ISSUE THREAD

**Issue by yumengluo** [hackforla/expunge-assist#862]
### Overview
We have received approval to carry out the Terminology Survey, originally developed in Summer/Fall 2022. During the week of Feb. 17th- Feb. 24, the research team reviewed the survey and provided feedback on the original survey. Now, we will need to finalize this survey and the corresponding Google form based on the feedback we collected from team members. 

### Action Items
- [x] Review and Edit the survey introduction and each question based on the feedback from the team
- [x] Finalize the survey for Justice-impacted Individuals on Google Doc and Google Form. 

### Resources/Instructions
 [Google form](https://docs.google.com/forms/d/1Trxv6ejnOhTu7y-ddLTNjUzySt_45Rq8agNhY3GQQL0/viewform?edit_requested=true)
[Google doc](https://docs.google.com/document/d/1JC6JdBPgpxp-bGquuWEKq6gRQ32DB9eFKDPNcyd9Lkc/edit)
[Feedback from Github comments](https://github.com/hackforla/expunge-assist/issues/849)

**Comment by kevinmoutoucarpin** [comment]
Completed
