### ISSUE TITLE
Update EA Project One Sheet 

### ISSUE THREAD

**Issue by jamiesiu** [hackforla/expunge-assist#868]
### Overview
Update EA Project One Sheet so that it is current and can be shared with external viewers (such as potential donors) and prospective new volunteers. 

### Action Items

- [x] Review existing [project one sheet](https://docs.google.com/document/d/1X7dcsM9pOQ5I3r0NI--WSFFbkSeVXF2cB9ZLeUFVlIg/edit)
- [x] Make revisions
- [x] Share with PM / team for feedback and additional edits as needed
    -   [x]  Send draft to Bonnie
    -   [x]   Revisions
- [x] Update One Page link on EA Wiki (https://github.com/hackforla/expunge-assist/wiki) 
- [x] Add to https://www.hackforla.org/projects/ Overview
- [x] Add to HfLA [repo](https://github.com/hackforla/product-management/tree/master/project-one-sheets)

### Resources/Instructions
[Hack for LA guide for One Sheets](https://github.com/hackforla/product-management/issues/74)

**Comment by ExperimentsInHonesty** [comment]
Hi PMs @jamiesiu @jamiesiu @thomasdemoner @sheronvirani21 
And issue assignee @alexulven 

I approved your recent change to the website to remove an outdated version of the one sheet (called overview on the site).  But this is a requirement for being a project of hack for la and is not optional.

I have changed the status on this issue to priority: high and I would like to see a new draft in the next 7 days. 

Thanks,

Bonnie

**Comment by jamiesiu** [comment]
@ExperimentsInHonesty thanks for flagging and highlighting the importance of this. We've recently had some shuffles with our team, been busy with work, and didn't get to it as expected. We'll get this over to you for review as soon as possible

**Comment by sylvia-nam** [comment]
Here's a working [draft](https://docs.google.com/document/d/1qBwcyfkfK_LFOBYhxwW90SzCK7xxG7M5l8kePZ-5MoA/edit). To discuss in the PM and leads meeting [today](https://github.com/hackforla/expunge-assist/issues/432#issuecomment-1964254555).

**Comment by ExperimentsInHonesty** [comment]
I have added some comments to your document: [Expunge Assist Project One Sheet 2024-3-1 version](https://docs.google.com/document/d/1qBwcyfkfK_LFOBYhxwW90SzCK7xxG7M5l8kePZ-5MoA/edit).  Please fill out the [reach bonnie form](https://docs.google.com/forms/d/e/1FAIpQLSedtewZ75lHmwAcCOnpL9AJZIF6d-Gv84i8tl_yF4lzHGQj5g/viewform) again when you are ready for me to re-review.  I will be unavailable from the March 8-18.

**Comment by sylvia-nam** [comment]
Here's the latest [version](https://docs.google.com/document/d/1SVgk4vH02oH7kUVbphKebrWMQNOMtzkIkpcksnHAULo/edit) which incorporates @ExperimentsInHonesty's comments and revisions.

**Comment by ExperimentsInHonesty** [comment]
@sylvia-nam Hopefully you can be at the meeting we have scheduled for 2024-03-22 1-2 pm to discuss your comments on the doc which I don't understand.

**Comment by ExperimentsInHonesty** [comment]
Also we will need to reduce the amount of info on the one sheet because the formatting has too little white space.

**Comment by sylvia-nam** [comment]
@ExperimentsInHonesty I plan to be there. I have another version of the One Sheet for you to review specifically geared towards potential community partners. It's not formatted according to HfLA One Sheet guidelines however. I will finish today or tomorrow and link here when the draft is ready.

**Comment by sylvia-nam** [comment]
@ExperimentsInHonesty here's a [One Sheet draft](https://docs.google.com/document/d/1B0jkFn4kGlXUP11KXeUZ_-1dNCuSwSkAPbJ51vftG9U/edit) geared specifically to potential partners.

It reflects social justice oriented communications strategy: it is geared toward a specific audience (potential partners) with the most important information on top, and headers organized and written with that audience in mind.

**Comment by sylvia-nam** [comment]
@ExperimentsInHonesty Here are the two One Sheets for your feedback:
1) [One Sheet for Wiki](https://docs.google.com/document/d/1SVgk4vH02oH7kUVbphKebrWMQNOMtzkIkpcksnHAULo/edit)
2) [One Sheet for Partners](https://docs.google.com/document/d/1B0jkFn4kGlXUP11KXeUZ_-1dNCuSwSkAPbJ51vftG9U/edit)

They incorporate all of your comments from today's meeting.
For the Wiki One Sheet: I moved the most important info about EA to the top of the page (like the Civic Tech Jobs One Sheet). There's also more white space and a little less text.

For the Partnership One Sheet: I modified the content under Partnership Opportunities subheader to indicate that the partnership and tool are pro bono. It doesn't fully capture that the partnership is also free or fee-free, but it's getting there.

**Comment by sylvia-nam** [comment]
@ExperimentsInHonesty Here's the [revised One Sheet](https://docs.google.com/document/d/1SVgk4vH02oH7kUVbphKebrWMQNOMtzkIkpcksnHAULo/edit) based on your feedback during the 4/19 Org-PM meeting. 
- There is no sub-header called Purpose. Instead that information is included in the top-of-the-fold section. 
- I removed other redundancies

**Comment by sylvia-nam** [comment]
https://github.com/hackforla/expunge-assist/issues/379#issuecomment-2113932818:

> Bonnie's corrections
> - Bonnie fixed HfLA logo (earlier version too blurry)
> - Changed email address
> - Ok with text in footer though no other teams do it
> - Use international standard for dates Year-Mo-Day
> - Revise so there isn't so much text
> - Spacing is 1.15
> - Turn into PDF, add to https://github.com/hackforla/product-management/tree/master/project-one-sheets, then add ticket to website team to add to HfLA website with URL

**Comment by sylvia-nam** [comment]
Sent ticket request with PDF of One Sheet.

Revised One Sheet for Wiki [here](https://docs.google.com/document/d/1PYlYrrgBJW2OFtQJ5SfZYLbAYPEO_Brj0dAkTJ2OnM8/edit).
Revised One Sheet for partners [here](https://docs.google.com/document/d/16w0dZH4qohXmuMkeqarq9Pnre-MkR76I-Ft6SJZJVtQ/edit).

**Comment by amejiamesinas** [comment]
Submitted.

**Comment by sylvia-nam** [comment]
Complete
