### ISSUE TITLE
Letter Generator BUG: Selecting an Involvement option adds it to a stack when clicking back

### ISSUE THREAD

**Issue by ramankala** [hackforla/expunge-assist#870]
### Overview
When selecting any option on the [Involvement Page](https://expungeassist.org/#/./form/involvement), going forward and back, then deselecting that option in favour for another, repeating the flow of going forward and back creates a bug such that going back redirects users to the previously selected options.

#### Example

For this example, 'Parenting' was selected, although this works with any of the options. Click Next.
![image](https://user-images.githubusercontent.com/45212806/223357106-acd73bba-c1f7-4d09-a871-2bc98df9c9e8.png)

Click Back.
![image](https://user-images.githubusercontent.com/45212806/223357319-8bd88a9c-b7e2-464a-b85c-2a3731c5fbd4.png)

Deselect 'Parenting' and select any other option, 'Recovery' was selected for example. Click Next.
![image](https://user-images.githubusercontent.com/45212806/223357595-a81a88c8-cb93-4bc9-8c86-776625ddce3c.png)

Click Back.
![image](https://user-images.githubusercontent.com/45212806/223357862-ce2cafb4-d4d8-4da3-9a8a-2573411e9967.png)

Page redirects user to 'Parenting' page instead of the Involvement Page.
![image](https://user-images.githubusercontent.com/45212806/223357990-8dce2f6f-6b8b-4909-8250-43b155fe29fe.png)

NOTE: Repeating this process by deselecting 'Recovery' and selecting another option, then going through the flow of going back, the page redirects users through all previously selected options in the stack.

Click Next.
![image](https://user-images.githubusercontent.com/45212806/223360004-0e3097fd-b532-401b-9249-e7719d80d5f7.png)
Click Back.
![image](https://user-images.githubusercontent.com/45212806/223359460-7ea06372-42c7-4049-9b6f-34556b4ab3b0.png)
Click Back.
![image](https://user-images.githubusercontent.com/45212806/223359539-52aa19f9-5293-4b64-8f96-49d9f48f462d.png)
Click Back.
![image](https://user-images.githubusercontent.com/45212806/223359610-cf180a17-5f93-44dc-a2c0-092afc066df1.png)

Clicking Back cycles through the stack before reaching the Involvement Page.

### Action Items
- Clicking back should redirect users to /#/./form/involvement.

**Comment by jamiesiu** [comment]
@sydneywalcoff this is the bug that was mentioned today at All-Team's
