### ISSUE TITLE
IUT 1 Feedback cleanup

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#883]
### Overview
Review medium and low priority tasks and organize/assign/mark as won't do. 
Exercise on Figjam
### Action Items

- [x] Review medium and low priority tasks from IUT 1 Feedback (summer 2022) 
- [x] Organize, create and add to a Figjam board between Design and Content
- [x] Review Github issues together at a meeting and make priorities
- [x] Finalize

### Resources/Instructions
[Figjam board](https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB)

**Comment by SamHyler** [comment]
I've now gone through on Github and Figjam @anitadesigns

**Comment by anitadesigns** [comment]
closing this as complete.
