### ISSUE TITLE
Brainstorming Research Goals: Internal Landing Page Usability Test

### ISSUE THREAD

**Issue by yumengluo** [hackforla/expunge-assist#892]
### Overview
We are planning to conduct a second round of internal usability testing and specifically focus on the landing page. In this brainstorming session, we try to achieve two goals.

1. What are the goals of the test? What do we hope to achieve by conducting this test? 
2. Identify the key research questions that the test should aim to answer. What do we want to learn about the landing page? What are the specific areas of focus?

### Action Items
- [x] Please jot down any research goals you want to achieve from this internal usability test of the landing page on the FigJam board before the March 31st team meeting.[FigJam Page](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?node-id=948-1642&t=kqHwwqhp8GV2OSln-0)
- [x] Please report your progress in the comment section. If completed, comment: complete. If you have any questions, feel free to DM research leads or report the blockers that you have in the comment section. If you do not have time to do it this week, please comment: no time to do this task this week. 

### Resources/Instructions
 [Previous test and the research plan google doc](https://github.com/hackforla/expunge-assist/issues/880)

**Comment by amejiamesinas** [comment]
complete

**Comment by sofialaguna** [comment]
Complete

**Comment by SamHyler** [comment]
not done, had to dig to find this issue during the current meeting when we started the in meeting task (had not seen this before). Please communicate with me via slack or at meetings about tasks, I don't know that I should check for tasks on Github otherwise. Thanks!
