### ISSUE TITLE
EPIC: Update HfLA/CfA information across EA website 

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#902]
### Overview
HfLA and CfA have changed their relationship. HfLA is now a project underneath  the nonprofit "Civic tech structure." EA is a project under HfLA. This information must be reflected on the About Us page, FAQs and the LP. All these texts should be coordinated.

### Action Items
- [x] #1285
- [x] #684 
- [x] #1052 
- [x] #1058 

### Resources/Instructions

news about the change https://statescoop.com/code-for-america-local-brigades-ending/
Our new nonprofit is https://www.civictechstructure.org
https://socialimpact.github.com/insights/merl-center-move/
Bonnie's advice video https://drive.google.com/drive/folders/1TGl0s76LtxqIJcNPtwmg_4F2rE0tLtol 
[Revised Figma frames](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2%3A45&mode=design&t=RsrNQ5dPybJSAitU-1)

**Comment by SamHyler** [comment]
still needs to be addressed, keeping open

**Comment by SamHyler** [comment]
Can and should be done in collab with this issue, About us page https://github.com/hackforla/expunge-assist/issues/965. as updates should appear on both pages

**Comment by sydneywalcoff** [comment]
replacing the 'grandparent' language in the title with an `epic` label to assist in sorting the project board.

**Comment by SamHyler** [comment]
Created modular copy for LP, About, and FAQ regarding this relationship change. Commenting in the EPIC as all 3 mains and all 3 requests linked here have the same result from Content

This is the quick fix version for stakeholder review, we have more that we wold like to prioritize in a later milestone.

Notes:
Corrected typo regarding EA as a nonprofit and updated relationship that changed regarding Code for America (CfA). .
Written as modular copy across the 3 pages 
Discussed the need to use the word FREE from IUT 2 and discussed the difference between free and freely, decided on free as freely has other connotations 
Decided to use TOOL and not SERVICE as service has implications of user support

**Comment by SamHyler** [comment]
Content is finished. Content will be under the master pages and in the Content SOT copydoc. Design has OKed handover without check on padding. Handing over to Dev on [Design handover space in Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-38&mode=design).

**Comment by SamHyler** [comment]
<img width="797" alt="Screenshot 2024-05-03 at 22 29 49" src="https://github.com/hackforla/expunge-assist/assets/87077650/464b8b2b-3d45-44f7-a150-b3ab7eb316f0">
This is modular copy across 3 pages. Screenshot of one of them, copy should be the same. Updating SOT copydoc and Master pager next

**Comment by sydneywalcoff** [comment]
<img width="874" alt="Screenshot 2024-06-03 at 7 09 42 PM" src="https://github.com/hackforla/expunge-assist/assets/75542938/d686d688-d783-46bd-8884-7905113d81a4">
