### ISSUE TITLE
[Updating Content Guidelines] Reviewing product principles

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#906]
### Overview
The product principles were taken from a Design guide that was incomplete and fairly old (also has not been actively used by the team in 2 years). The product principles could be updated to better reflect the tone and voice we want to use with our users. 

Review in a team meeting and then tasks will be worked out/assigned. 

This issue is being worked on in collaboration with ongoing foundations work in Design (i.e. colors) and with the branding work. 

### Action Items

- [x] Look at Voice and Tone keywords/product principles together and rework them
- [x] Create a figjam board with a brainstorming space for the whole EA team https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?type=whiteboard&node-id=2348-6046&t=2fMOoCWkVrOrAmdA-4
- [x] Categorize the feedback received
- [x] Narrow down and brainstorm new terms at a team meeting
- [x] Choose 3-5 new product principles
- [x] Present and discuss in Design 
- [x] Present and discuss with branding/greater team

### Resources/Instructions
Content guidelines in Figma https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-19&mode=design
There was a proposal to create a cloze test with the whole EA team. We created a different kind of exercise for the whole EA team instead to gather their feedback and get some "stuff" to brainstorm and work with in finding our voice and tone.      

FigJam board where we are working on the exercises https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?type=whiteboard&node-id=2348-6046&t=nZG8DdDrclFeBoxE-4

Product principles were created before June 2021, there was a cloze test here https://docs.google.com/forms/d/10EZg9P9kPhbLMtLR3zgjPsUOfAQO_h_puyo5zQuBXdo/edit  and design principles were put into a document here. The Content Guidelines used these as the product principles, but it is now time to update them.

**Comment by SamHyler** [comment]
We are working on narrowing down the terms in the meetings right now, as it's helpful to talk them out rather than work individually. Looking forward to connecting with branding work

**Comment by emmathrash** [comment]
We've landed on 3 product principles and have presented them to Design in the Friday Sync. Next would be to present and discuss them with branding.

**Comment by SamHyler** [comment]
Closing as complete. They need to be presented to and discussed with branding, and added to the Content Guidelines, but are otherwise done.
