### ISSUE TITLE
Experience letter request for Bonnie to review and approve

### ISSUE THREAD

**Issue by mchai1218** [hackforla/expunge-assist#916]
### Overview
This issue is created for Bonnie @bonniewolfe  to review and approve Minqi Chai's experience letter request, who used to be EA's UX Research Lead. Minqi is now working as a Senior UXR in a tech consulting firm on OPT, and she has won this year's H1B (U.S. work visa) lottery. In preparing for the **H1B visa filing**, her company's HR and lawyer asked her to submit experience letters from any company/organization where she worked in the realm of UX. More specifically, an experience letter provided by Hack for LA as proof of her UX experience will increase the opportunity for USCIS (U.S. Citizenship and Immigration Services) to directly approve her work visa application.

Please note that this experience letter is different from a letter of recommendation. It mainly focuses on the person's job duties and tools used during the work. Therefore, Minqi has provided a full draft for Bonnie's convenience. 

### Why important
It’s not easy to go through the whole H1B lottery thing; As she transitioned from academia, the lack of UX-related experience letters will severely affect the chance for USCIS to approve her H1B work visa application. This means that she'll have to leave her job and be deported after OPT expires this year.

### Action Items
- [ ] Review the HcLA LoR template filled out by Minqi - [URL](https://docs.google.com/document/d/1VDYBX_2G2WKXkRDN6miqQAgRE4zcPLFI90uBcIhcvmY/edit?usp=sharing)
- [ ] Review the experience letter initial full draft provided by Minqi: [URL](https://www.dropbox.com/s/1vo5a2rdd1np6bu/HcLA%20Experience%20letter.docx?dl=0)
- [ ] Approve her letter request
- [ ] Provide an experience letter with Bonnie's signature (If Bonnie is not available, other executive's signature shall work as well), and ideally, HcLA letterhead/logo
- [ ] Contact her by replying to this ticket, Slack, or a scheduled meeting. Email: minqichai@gmail.com

**Comment by mchai1218** [comment]
@bonniewolfe @ExperimentsInHonesty  Thank you for getting back to me! To clarify, I did follow the protocol and submitted the "reach Bonnie form" on Monday, April 24. In my survey response, I chose urgent needs to get prioritized. Have you received that survey response? If not, I can resubmit it. This is very important to my visa status. Thank you!!

**Comment by mchai1218** [comment]
@ExperimentsInHonesty Thank you for your response!! Sure, the reason why I include the paragraph is to meet the H1B _specialty occupation_ requirement by USCIS. In particular, a specialty occupation is one that requires the application of a body of highly specialized knowledge and the attainment of at least a bachelor's degree or its equivalent. If USCIS thinks my case fails to meet the specialty occupation (say, my current UXR job position does not require a bachelor's degree or its equivalent), then my H1B petition will be rejected. 

Again, thank you so much for your help!! Let me know if you have more questions.

**Comment by ExperimentsInHonesty** [comment]
@mchai1218 You can download the pdf from this link https://drive.google.com/file/d/1KKgrkcaghHov2-FCDMWZaDoe84lNBOuH/view?usp=sharing  

I revised the paragraph that you proposed to make it clear you had a high level of qualification.

**Comment by mchai1218** [comment]
@ExperimentsInHonesty Thank you!!
