### ISSUE TITLE
Design pop-up for last page of LG

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#924]
### Overview
The last page of the letter generator is missing a pop-up to prevent users from losing their letters. 

@RenaNicole had previously [worked on this pop-up](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=9734-104138&t=b7IFaCDcD3K5gRc2-4) but the team had to place this task on hold due to team bandwidth. Now that we have an expanded our team's bandwidth, we would like to have this pop-up completed and tested for IUT2.

### Action Items
- [x] Discuss with Content whether this is necessary 
- [x] Review previous design and alter 
- [x] Create mobile and desktop wireframes for this page that has a pop-up 
- [x] Tag @anitadesigns to review 
- [x] Hand over to Content 
- [x] In collaboration with Content create an issue for Dev to implement this design 
- [x] Prepare design handoff for Dev and link to issue 
- [x] Present to Dev
- [x] Close issue

### Resources/Instructions
Work on this issue under the "Error Prevention pop-up" page on Figma 

Ask @anitadesigns if you have any questions

More background to this issue can be found #640

**Comment by anitadesigns** [comment]
Talked more about this issue with the team. Visit [Content + Design](https://github.com/hackforla/expunge-assist/issues/618#issuecomment-1537512976) sync meeting notes here for more info.

**Comment by ermbrown** [comment]
Dimensions

Website: 400 X 250

Mobile: 303 X 406

**Comment by ermbrown** [comment]
Completed. Ready for review.

**Comment by anitadesigns** [comment]
Added notes and re-assigning for improvements.
