### ISSUE TITLE
Update Landing Page FAQ

### ISSUE THREAD

**Issue by sydneywalcoff** [hackforla/expunge-assist#927]
### Overview
#676 - PR missed updating the copy on the landing page.

### Action Items

- [ ] replace copy in FAQ accordian dropdown shown below with copy from FAQ page
<img width="953" alt="Screen Shot 2023-05-11 at 6 50 35 PM" src="https://github.com/hackforla/expunge-assist/assets/75542938/b770fea9-68b8-49b8-80df-4af31c2f386c">

Screenshot of [FAQ page](https://expungeassist.org/#/./faq) copy;
<img width="577" alt="Screen Shot 2023-05-11 at 6 51 14 PM" src="https://github.com/hackforla/expunge-assist/assets/75542938/b61ca6f5-acb3-4e95-899e-4f9bff1f319d">

**Comment by anitadesigns** [comment]
@sydneywalcoff Double checking with Content on whether the difference in the answer is intentional. I added "hold" label until hearing back . @SamHyler Will need to update the LP wireframes if the copy should match both on LP and FAQ Page

**Comment by SamHyler** [comment]
Thanks for spotting the error. I don't know where it came from. Let's go with the longer version everywhere, FAQ/Landing page. I'll work with Anita to fix the wireframes in Figma.
