### ISSUE TITLE
Ask for Peer Reviewer to Review screener, and assign them to this issue

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/expunge-assist#935]
### Overview
Now that the Participant Recruitment Criteria & Screener Guide has been developed, we each need to peer review the document in order to begin recruiting participants. 

### Action Items
Please peer review the [Participant Screener](https://docs.google.com/document/d/16ef3l-nvjreV5o-ddnroEjRVSsXZLdZgoCMKIXoAJIc/edit)

- Please check for grammar, spelling, and overall writing of screener, as well as any other elements to look out for based on feedback
- Peer Reviewer to write any comments in screener or as a comment in the google doc. 

Please complete this task before our next meeting on 5/19.
Once you have peer reviewed the screener, please comment DONE.
If you are unable to review before our meeting, please comment, unable to review.

**Comment by SamHyler** [comment]
done

**Comment by sofialaguna** [comment]
done
