### ISSUE TITLE
Peer Review Success Metrics

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/expunge-assist#936]
### Overview
In preparation for IUT2 we have finalized our Research Objectives and Research Questions. We have also developed our Research Metrics. Our task is to provide a team peer review of the Research Metrics to move forward with IUT 2. 
 
### Action Items
Please provide a peer review of [Research Metrics](https://docs.google.com/document/d/1TUHVwXvQBEeQc5t57RGdNmQUH_QVoZd1orBMeEloSOk/edit?pli=1#)
- Please be sure to add edits as comments or suggestions in the google doc. 
- Please check for grammar, spelling, and overall writing of screener, as well as any other elements to look out for based on group discussion

Please complete this task before our next meeting on 5/19.
Once you have peer reviewed the research metrics, please comment DONE.
If you are unable to review before our meeting, please comment, unable to review.

**Comment by SamHyler** [comment]
done

**Comment by amejiamesinas** [comment]
@amejiamesinas to update procedure once calendly, session tracker, and zoom are finalized.
