### ISSUE TITLE
IUT2: Post Google Form Screener to Slack channel to begin recruitment

### ISSUE THREAD

**Issue by dmeyers1348** [hackforla/expunge-assist#939]
### Overview
The purpose of this issue is to create a post for the general Hack for LA Slack channel to recruit participants for IUT2.

### Action Items
- [x] Draft post for general Hack for LA Slack channel, with link to Google Form Screener
- [x] Post recruitment message to Slack channel
- [x] Close issue once complete

### Resources/Instructions
[IUT2 Google Drive folder](https://drive.google.com/drive/folders/194Hxh87eo1KPs1r2wQe_nt2GbDH7LOvS)

**Comment by amejiamesinas** [comment]
Will close once re-posted, later this week.
