### ISSUE TITLE
Usability Sessions Recruitment Script

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/expunge-assist#953]
### Overview
Upon reviewing our screener survey, and selecting our prospective research participants. We will need to email all prospective participants to schedule their usability research session. 

### Action Items
Review the [Recruitment Script](https://docs.google.com/document/d/1s_Vv7s2m2wacPGbP8Iq44uN_DPzSxTZ85LWxFl9_3zw/edit)
And add any edits/suggestions for changes. 
Please comment "DONE" once reviewed. Please complete by 6/5/2023

**Comment by RongAnn** [comment]
DONE

**Comment by kevinmoutoucarpin** [comment]
Done

**Comment by sofialaguna** [comment]
Done
