### ISSUE TITLE
Re-designing FAQ page

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#956]
### Overview
[IUT1](https://docs.google.com/spreadsheets/d/1NfqYUQKl7GRz1-r-vWI0kBWa-mgkXagCDAz9wMAa6Bc/edit?pli=1#gid=0) results shared that participants were overwhelmed with the information provided on the FAQ page. The Design and Content team decided to add accordions ( #646) to the FAQ page as a simple MVP due to limited bandwidth. Now that our Dev team is growing, we would like to revisit and collaborate together to re-design the FAQ page. 
 
### Action Items
- [X] Review [Internal Usability Test results](https://docs.google.com/spreadsheets/d/1NfqYUQKl7GRz1-r-vWI0kBWa-mgkXagCDAz9wMAa6Bc/edit?pli=1#gid=0) and note FAQ page pain points
- [X] Review Landing page wireframes and current FAQ page wireframes
- [X] Communicate with Content on pain points they are tackling 
- [X] Perform a competitive analysis of 3 competitors' FAQ pages 
- [X] Review user personas, pain points, and Content needs to brainstorm solutions 
- [X] Create lo-fi wireframes of solutions 
- [x] Present to team (Design, Content, Dev) for feedback 
- [x] Create hi-fi wireframes 
- [X] Prepare for Design handoff to Dev
- [X] Assign @anitadesigns to issue and move to "Ready for Review" 
- [x] Close issue 

### Resources/Instructions
[List of competitors](https://docs.google.com/document/d/1I__-d0yHV2xLJEKzVZUlln58XrBCFUN9mdx2nHDtBwM/edit)
[Figma workspace for FAQ page](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=10561-103299&t=eF45sx3hZt7Lpzts-4)

**Comment by SamHyler** [comment]
Corresponding content issue https://github.com/hackforla/expunge-assist/issues/957

**Comment by mbui31** [comment]
created some designs/prototypes; will share for feedback during design/content sync

**Comment by mbui31** [comment]
https://www.freepik.com/free-vector/characters-people-chatting-through-smartphones_3226068.htm#query=people%20chatting&position=11&from_view=search&track=ais#position=11&query=people%20chatting

using this image to create a user-friendly intro to the FAQ page

**Comment by mbui31** [comment]
![EA FAQ image](https://github.com/hackforla/expunge-assist/assets/129242827/6c75f0bb-0b93-41e7-bc0c-323e83aa4c85)

Converted image from png --> svg using Adobe Express

**Comment by mbui31** [comment]
![undraw_sharing_knowledge_03vp (1)](https://github.com/hackforla/expunge-assist/assets/129242827/f395d175-7884-4faa-af94-a3e4f8e294d6)

**Comment by mbui31** [comment]
Used this image because it was more inclusive and edited to be more EA branding

**Comment by mbui31** [comment]
@anitadesigns @jyehllow high-fi wireframes are done and ready to be reviewed!

**Comment by mbui31** [comment]
Vector image was taken from: https://undraw.co/search (search: knowledge sharing)
