### ISSUE TITLE
UXR: User Persona and Journey Mapping Audit

### ISSUE THREAD

**Issue by dmeyers1348** [hackforla/expunge-assist#958]
### Overview
The following research questions will guide this research:
- Who is our target user?
- What is the user journey?

The goal of this project is to review existing research and make edits or updates as needed. 

The three main deliverables are:
- Demographic profile of the general population of users we would be targeting (Time: 5-10 hours)
- 2-3 hypothetical personas (Time: 10 hours)
- User journey for the personas (maybe organized by county) (Time: 15 hours)

### Action Items
**Review of Demographic Research on Justice-Impacted Individuals**
- [ ] Review demographic research on justice-impacted individuals in California
  - [ ] See this [Product Demo Google Slides](https://docs.google.com/presentation/d/1WzvnMc6cTzoxKBo3DLqd9-ENex3mXjQZBMHSUXM7yxU/edit#slide=id.g20a56e2c0ec_0_70) for Bonnie, with some info on the population of target users
  - [ ] Look up other demographic info on these target users (e.g., gender, race/ethnicity, education level, age, etc.)
- [ ] Create a document or brief Google Slides with this demographic information laid out, include all information sources
- [ ] Share with team on 6/30, gather feedback, and make edits

**Review of Past Research and Draft User Personas**
- [ ] Review previous research on user personas and journey maps
  - [ ]  [User Personas (from Code for America)](https://drive.google.com/drive/folders/1-clMH5uWSFPRDtqebGp8loWEzf-KK5X8)
  - [ ] [Existing folder on user personas](https://drive.google.com/drive/folders/12-1yK0UMW_XH1Q6sTtlXmq0LjVu7E_Tr?usp=drive_link)
  - [ ] [CJ Resources](https://docs.google.com/document/d/17k8gBUH8cRhd3lNtdab5C5lFOWaZOPLAXOUy3a3-mt8/edit?usp=sharing)
  - [ ] [Previous User Journey Map](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-34&t=vlgwxJGsn0C1owUD-0)
- [ ] See [here](https://maze.co/guides/user-personas/building-personas/) for steps on how to create user personas and templates
- [ ] Feel free to use Figjam to brainstorm ideas within your team
- [ ] Based on previous research and our current website, draft 2-3 hypothetical user personas. Deliver draft ideas to team on 7/7
- [ ] After 7/7 meeting, make edits/updates to personas

 **Journey Mapping**
- [ ] Create journey maps for each user persona 
  - [ ] See this [Figma](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-34&t=CqBlePrbBzMbgJcI-0) for an example of user journey
  - [ ] See [this Nielsen Norman Group ](https://www.nngroup.com/articles/journey-mapping-101/)step-by-step guide on journey mapping
  - [ ] Feel free to use Figjam/Figma to build updated journey maps
- [ ] Deliver draft ideas to team on 7/14
- [ ] After 7/14 meeting, make edits/updates to journey maps
- [ ] Close issue once complete

### Resources/Instructions
- Save all documentation to this [Google Folder](https://drive.google.com/drive/folders/1K2im1aDEgZ4A6kToNawcOm7jQhGikqbr)
- [EA Research Planning 2023](https://docs.google.com/document/d/1jvAC_zPS-oRRPO1ip0rFCp4e3QagaBtmiuUVUCl5Sj8/edit?pli=1)
- Can also reference #616 for previous work

**Comment by RongAnn** [comment]
Hi, for those who would like to check out our file on we currently work on demographic info:   https://docs.google.com/document/d/1V-gnlL2zhquYKyeeoQyMz5vf9EBp3mhb5ITbAR5Hvzk/edit                                                            And you can find our whole google drive                            https://drive.google.com/drive/folders/1K2im1aDEgZ4A6kToNawcOm7jQhGikqbr

**Comment by dmeyers1348** [comment]
Adding:
**Review of Demographic Research on Individuals with Expunged Records**
- [ ] Review demographic research on those who have expunged records in California
- [ ]  Look up demographic info on these target users (e.g., gender, race/ethnicity, education level, age, etc.)
- [ ]  Create a document or brief Google Slides with this demographic information laid out, include all information sources
- [ ]  Share with team, gather feedback, and make edits

**Comment by RongAnn** [comment]
> Hi, for those who would like to check out our file on we currently work on demographic info: https://docs.google.com/document/d/1V-gnlL2zhquYKyeeoQyMz5vf9EBp3mhb5ITbAR5Hvzk/edit                                       And you can find our whole google drive https://drive.google.com/drive/folders/1K2im1aDEgZ4A6kToNawcOm7jQhGikqbr

**Comment by RongAnn** [comment]
> Hi, for those who would like to check out our file on what we currently work on demographic info: [Demographic information](https://docs.google.com/document/d/1V-gnlL2zhquYKyeeoQyMz5vf9EBp3mhb5ITbAR5Hvzk/edit) And you can find our whole google drive here [Google drive](https://drive.google.com/drive/folders/1K2im1aDEgZ4A6kToNawcOm7jQhGikqbr)

ht

**Comment by RongAnn** [comment]
> Adding: **Review of Demographic Research on Individuals with Expunged Records**
> 
> * [ ]  Review demographic research on those who have expunged records in California:- how many, what motivated them, what was process like, did some people have advantages because of SES, race class etc.
> * [ ]   Look up demographic info on these target users (e.g., gender, race/ethnicity, education level, age, etc.)
> * [ ]   Create a document or brief Google Slides with this demographic information laid out, include all information sources
> * [ ]   Share with team, gather feedback, and make edits

**Comment by dmeyers1348** [comment]
[User Persona Figma link](https://www.figma.com/file/Bgy3wQLh1S0K0J4ihxOcHd/EA-User-Persona-Journey-Map-July-2023?type=design&node-id=0-1&mode=design&t=zb7zlkPbue9c2D7b-0)
