### ISSUE TITLE
UXR: Accessibility Research

### ISSUE THREAD

**Issue by dmeyers1348** [hackforla/expunge-assist#959]
### Overview
The following research questions will guide this project:
- Is our site accessible? 
- What are our accessibility goals? 

The goal of this project is to collaborate with the content and design team to define our accessibility goals. With these established goals, we can test the current EA website to assess accessibility.  

There are two deliverables to present to the team:
- Identify accessibility goals (Time: 5 hours)
- Create timeline for testing (can be a heuristic analysis) for team to implement (Time: 5 hours)

### Action Items
**Identify Accessibility Goals**
- [ ] Collaborate with Design and Content teams
  - [ ] FYI: Design & Content weekly meetings are Fridays at 9:30AM PST
- [ ] Review websites and resources to determine accessibility goals
  - [ ] [Inclusive Design](https://www.nngroup.com/articles/inclusive-design/)
  - [ ] [Best Practices](https://userway.org/blog/6-best-practices-in-accessibility-web-design/)
  - [ ] [US gov info](https://www.usa.gov/accessibility-policy)
  - [ ] [Accessibility from Google](https://support.google.com/sites/answer/7529116?hl=en)
  - [ ] [For testing](https://developer.android.com/guide/topics/ui/accessibility/testing)
- [ ] Review current [EA website](https://expungeassist.org/#/./)
- [ ] Identify accessibility goals and best practices 
  
**Consider testing for accessibility**
  - [ ] Use Google Docs or Sheets to create a timeline for heuristic analysis / accessibility research
  - [ ] Create notetaking template to use for conducting heuristic analysis, based on accessibility goals
  
**Heuristic Analysis**
- [x] Review [Heuristic Analysis Workbook Sheet from Nielsen & Norman](https://media.nngroup.com/media/articles/attachments/Heuristic_Evaluation_Workbook_1_Fillable.pdf) and [Web Accessibility Checklist](https://cdn2.hubspot.net/hubfs/153358/Web%20Accessibility%20Quick%20Checklist%20for%20Designers.pdf?utm_referrer=https%3A%2F%2Fwww.deque.com%2F)
- [x] @tntalcott will create [FigJam template following the Nielsen & Norman workbook](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?type=whiteboard&node-id=1670-2433&t=WAqPpw1Kyi3q7j3R-4)
- [x] Accessibility research team will conduct analysis on FigJam
- [x] Accessibility research team will meet on 8/17/23 at 1PM to discuss findings and next steps
- [x] Team will update [FigJam](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?type=whiteboard&node-id=1670-2433&t=WAqPpw1Kyi3q7j3R-4) with major themes/patterns from heuristic analysis and add into large sticky notes on right side
- [x] @britneyveal will use [Lighthouse Tool](https://developer.chrome.com/docs/lighthouse/overview/) to evaluate site's accessibility
- [x] Team will meet on 8/24/23 at 1 PM PST to discuss major themes/patterns from analysis, Lighthouse accessibility audit, and discuss next steps for reporting insights to other teams

### Resources/Instructions
- Save all documentation in this [Google Folder](https://drive.google.com/drive/folders/19jO4Kcyoat_3AiHWhkQhILHYPXioG1eq)
- [EA Research Planning](https://docs.google.com/document/d/1jvAC_zPS-oRRPO1ip0rFCp4e3QagaBtmiuUVUCl5Sj8/edit?pli=1)

Content issue https://github.com/hackforla/expunge-assist/issues/967

**Comment by jccchurch** [comment]
Added to the research folder - summary of some accessibility & inclusivity research. 

Outlining: 
- [ ] The POUR 4 Web Accessibility Principles 
- [ ] 6 Key WCAG Criteria for Designers
- [ ] Accessibility vs Inclusive Design
- [ ] Microsoft 3 key Inclusive Design Principles

https://docs.google.com/document/d/1EiWOWjA0AStdlAHwF2gOO6B4R49zJ5FycJdd4eSjfzk/edit?usp=sharing

**Comment by amejiamesinas** [comment]
Team met on 8/24 to discuss Lighthouse Tool and [FigJam Board](https://www.figma.com/file/A1B5JqXHdov0KrRcLTyp9Q/Research-Team-Documentation-Planning?type=whiteboard&node-id=1670-2433&t=WAqPpw1Kyi3q7j3R-4) with major themes/patterns from heuristic analysis. 

Findings to be shared at upcoming content/design collaboration meeting.
