### ISSUE TITLE
UXR: Competitive Analysis

### ISSUE THREAD

**Issue by dmeyers1348** [hackforla/expunge-assist#960]
### Overview
The following research questions will guide this project:
- Who are our competitors? What can we learn from them?

The goals of this project are to:
- Collaborate with the design team to complete a competitive analysis
- Research team to conduct competitive analysis on mission statement and privacy policies across competitors

There are three key deliverables for this project:
- Complete competitive analysis in collaboration with Design team (Time: 10 hours)
- Identify needs for privacy EA statement (Time: 5-10 hours)
- Assess mission statement pages on competitor sites (Time: 5-10 hours)

### Action Items
**Competitive Analysis**
- [ ] Review working [Figma](https://www.figma.com/file/Crqy17T5GSG4cbRxF1XamO/EA-COMP-ANALYSIS?type=whiteboard&node-id=0-1&t=UsIuAQu6SLzUrNqo-0) document of competitor list and assessments
  - [ ] Is there anything missing? Collaborate with Content & Design team to identify any further competitors or notes on features
  - [ ] FYI: Design & Content meetings are at 9:30am PST on Fridays
- [ ] Research team to focus on:
**Privacy EA Statement**
- [ ] Update Figjam board based on findings on privacy statement across competitors
- [ ] Deliver draft ideas of privacy statements to meeting 6/30
- [ ] Make edits/updates after meeting 6/30
**Mission statement**
- [ ] Update Figjam board based on findings on mission statement pages across competitors
- [ ] Deliver draft ideas of privacy statements to meeting 6/30
- [ ] Make edits/updates after meeting 6/30

### Resources/Instructions
- [EA Research Planning](https://docs.google.com/document/d/1jvAC_zPS-oRRPO1ip0rFCp4e3QagaBtmiuUVUCl5Sj8/edit?pli=1)

**Comment by jccchurch** [comment]
**Key deliverables for design team:** 
- [ ] UI & Branding Analysis: What works & what isn't working?
- [ ] Key Features Analysis: What are competitors offering? How does that compare to EA's LG?

**Action Items**
- [ ] Design team to focus on:
- [ ] Update FigJam board with findings/insights for 6/30 meeting 
- [ ] Make edits/updates after meeting 6/30
- [ ] **Accessibility** - how are competitors addressing accessibility principles (if at all)? 

**Final Deliverable for Bonnie/Record**
- [ ] PMs will condense findings into the official EA Comp Analysis template
