### ISSUE TITLE
"Before you begin" hyperlinks + minor design update 

### ISSUE THREAD

**Issue by lexramos01** [hackforla/expunge-assist#962]
### Overview
Content / Design reconciled a hyperlinking question from Dev in this issue [here.](https://github.com/hackforla/expunge-assist/issues/932#issue-1710127363) The hyperlinks on the "Before you begin" page is now ready for Dev to be updated.

Please refer to Issue 962 in this [Dev Handover space](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=10739%3A112003&t=JFzXfKekw4yZXp0T-1
) on Figma linked here for changes to the page: 

### Action Items
- [x] Update copy for first paragraph starting with "Be sure you are eligible..."
- [x] On mobile, fix padding between header and paragraph to 8px 
- [x] On mobile, change header weights from bold to "regular"
- [x] For first bullet, change font style from italic to regular
- [x] On mobile, change main heading "Before You Begin" to 24px size 
- [x] On mobile, update other headers to 20px

### Resources/Instructions
Dev left a question for us on this issue: https://github.com/hackforla/expunge-assist/pull/912
Content worked to reconcile this question: https://github.com/hackforla/expunge-assist/issues/944
More background to this issue can be found: https://github.com/hackforla/expunge-assist/issues/694

**Comment by awellsbiz** [comment]
Hey Team,

Available: 8/12/23 from  12pm-4pm
The issue should be completed by 8/12/23 1pm
