### ISSUE TITLE
Fix About Us page, small issues 

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#965]
### Overview
The About us page has a few bugs that need to be fixed.

1. "source" is written in a unconventional way. Fix and update to match the actual source.
2. Correct "500,000 records were cleared in Utah..." to "350,000 records were cleared in Utah..." to match source.
3. "Black and BIPOC people" on the About us page is repetitive. Fix this sentence to be accurate. 
4. Fix sentence: "144,000 eligible marijuana records for clearance (reduced or dismissed) in California" should be: "In California, 227,650 marijuana convictions eligible for record clearance. 94% of those convictions cleared between 2019 and 2023."  Cite DoJ [source](https://oag.ca.gov/system/files/media/ab1706-q4-report.pdf).

Can be done in collaboration with this issue on the About Us page (either way, should collab between whoever is doing these two issues): https://github.com/hackforla/expunge-assist/issues/902 

5. "Contact" us is misspelled on the About us page (right before the button at the bottom). Fix!
<img width="665" alt="Screenshot 2023-08-30 at 12 44 25" src="https://github.com/hackforla/expunge-assist/assets/87077650/05ad6944-5418-44cb-911b-3c731ebfda43">

"About us" is written in title case "About Us" in both the header and the nav bar. This was not in the SOT. Fix.
<img width="665" alt="Screenshot 2023-08-30 at 12 44 04" src="https://github.com/hackforla/expunge-assist/assets/87077650/a600eac4-5f2a-4f66-9a20-deac05022935">

6. 27 Feb: From discussion with Design: There is availability and and OK to move forward with redesigning the About page beyond the small fixes. That is, the About page should be Designed on par with for example the LP and the FAQ pages. 
Tasks are listed in the comments of this issue (at the bottom)

### Action Items

- [ ] Check off these boxes as they are done and document progress and updates in the comments below 
- [ ] Establish collaboration with Design and Content (should be minimal necessary to fix the errors addressed in this issue)
- [ ] Compare the live version to the IUT 2 iterations 
- [ ] Iterate solutions
- [ ] Feedback in Content and Design
- [ ] Iterate further
- [ ] Tag Sam and Anita and move to ready for review column 
- [ ] Handover to dev
- [ ] Update desktop and mobile wireframes on master pages in Figma

### Resources/Instructions
<img width="531" alt="Screenshot 2023-06-24 at 18 19 22" src="https://github.com/hackforla/expunge-assist/assets/87077650/50928044-6cc6-4e95-8fde-aef26969bcd5">

Figma IUT 2 archive and live site 

[Revised Figma frames (WIP)](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2%3A45&mode=design&t=RsrNQ5dPybJSAitU-1)

**Comment by SamHyler** [comment]
Can/should be done in conjunction with this issue, updating HfLA information on the LP and About us page. https://github.com/hackforla/expunge-assist/issues/902

**Comment by sydneywalcoff** [comment]
> Can/should be done in conjunction with this issue, updating HfLA information on the LP and About us page. #902

@SamHyler is there any reason we're combining these? I think we might be able to update these separately

**Comment by SamHyler** [comment]
@sydneywalcoff This issue is part of that grandparent cluster! I separated it out because this is a small fix for the Content team, and can be done for.ex. by a brand new member without needing to be too involved in lots of background info/work or collabs (to fix the errors addressed in the issue)

**Comment by SamHyler** [comment]
https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=2-45&mode=design a start has been made on this page. The next person working on this can begin there and iterate further

**Comment by SamHyler** [comment]
6. 27 Feb: From discussion with Design: There is availability and and OK to move forward with redesigning the About page beyond the small fixes. That is, the About page should be Designed on par with for example the LP and the FAQ pages. 
Tasks: 
-Identify areas that need improvement and make a list of tasks to do. Suggest some solutions through iterations(Content meetings, Design/Content syncs, Slack, etc. are available to bounce your ideas and iterations when you're ready for feedback, just reach out to any of us!)
-Work with Design, passing iterations and ideas back and forth to create a new page including potentially new information hierarchy, new/removing content.
- Note the areas of improvement list in this github issue (either in the task list below or in the comment section 
- and communicate this with the Design partner and the Content team through the process

**Comment by emmathrash** [comment]
Update: This issue has been reverted back to small fixes only for stakeholder 1 milestone as they are issues that Bonnie has specified to need fixing. The redesign will have it's own issue as a part of the stakeholder 2 milestone. This is to solve the competing priorities for stakeholder 1.

**Comment by cherylcline** [comment]
I made the small fixes and tagged Dev (Onwubu)
