### ISSUE TITLE
Competitor Analysis - Dev

### ISSUE THREAD

**Issue by lmitch10** [hackforla/expunge-assist#966]
### Overview
For the EA Comp Analysis project, Lane and Sydney are assigned to fill out the sections under Technology to better understand what our competitors are using. 

### Action Items
Finish Competitor Analysis 3-5 

### Resources/Instructions
Below is the link to the figma: 
https://www.figma.com/file/Crqy17T5GSG4cbRxF1XamO/EA-COMP-ANALYSIS?type=whiteboard&node-id=0-1&t=2okGLeytU7llJNVu-0

**Comment by sydneywalcoff** [comment]
@lmitch10 are we good to close this?
