### ISSUE TITLE
Content accessibility goals

### ISSUE THREAD

**Issue by audrey-ma** [hackforla/expunge-assist#967]
### Overview
Define Content accessibility goals. This issue follows up on UXR accessibility goals issue #959.  

### Action Items
- [ ] Review accessibility standards and guidelines such as WCAG
- [ ] Brainstorm content accessibility goals in this [document ](https://docs.google.com/document/d/1QWZBCVfy64yKlDhyj2yPWhA1Jn03MDw1kof-hnScCD8/edit?pli=1#heading=h.o4imd8fnkgfn)
- [ ] Identify 3-4 accessibility goals for UXR accessibility research by 7/7

### Resources/Instructions
- [ ] Read the [ADA Compliance Guide](https://www.ada.gov/pcatoolkit/chap5toolkit.htm).
- [ ] [The a11y project](https://www.a11yproject.com/)
- [ ] Issue #959 websites and resources
- [ ] [Web Content Accessibility Guidelines (WCAG) website](https://wcag.com/resource/what-is-wcag/)
- [ ] [W3C Web Accessibility Initiative (WAI)](https://www.w3.org/WAI/roles/writers/) 

See also https://github.com/hackforla/expunge-assist/issues/410

**Comment by SamHyler** [comment]
Copied over info to this issue, to blend two similar issues. Otherwise, this issue was started and not gone through with, so closing as unplanned.
