### ISSUE TITLE
Run Personal Generator by Attorney 

### ISSUE THREAD

**Issue by j100892** [hackforla/expunge-assist#98]
### Overview
Michael from [(https://www.qiu-qiulaw.com/)] has agreed to go through our personal statement generator designs and copy and see if he can dig through the California Law to see if our generator won't cause any legal issues. 

### Action Items
E-mail him with the designs ASAP.

**Comment by SamHyler** [comment]
This appears to be a very old issue, should it be closed?

**Comment by SamHyler** [comment]
closing this issue as the person who created it is no longer here to take care of it
