### ISSUE TITLE
Improving visuals and language on LP: Letter examples, LG sneakpeak, Making letter writing, and how it works sections

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#980]
### Overview
A few participants in an internal usability test for the landing page and feedback from Bonnie found that the images were difficult to read or contained redundant information. 

**Letter Generator Image:**
- All three images of the letter examples shared that they were all veterans 
- Some of the text in the letter was black and the rest was purple. 
- There were concerns that these were real letters that were being shared 

*These images need to be fixed on the wireframes and handed over to Dev for updates.*
![image](https://github.com/hackforla/expunge-assist/assets/105686896/f67f1403-272e-4cba-901d-4decc4ef37f2)

**Letter Generator Sneak Peak image:**
- Image was too blurry to see 
![image](https://github.com/hackforla/expunge-assist/assets/105686896/70023192-2cb1-4e24-85e8-9971ed32f61d)

**Letter Generator Making letter writing less intimidating/How it works sections** 
- "Targeted question prompts" and "question prompts" was confusing language. Replace with plain language, keep consistent throughout.
<img width="681" alt="Screenshot 2023-08-04 at 21 08 31" src="https://github.com/hackforla/expunge-assist/assets/87077650/cf6b04e7-d746-46cf-a011-bc35944b3f7b">
<img width="681" alt="Screenshot 2023-08-04 at 21 08 43" src="https://github.com/hackforla/expunge-assist/assets/87077650/27cfadea-2398-4d2c-954c-da911e8fd3a5">

### Action Items
**Letter Generator Image:**
- [x] Remove sentence about being an US Veteran from 2 out of the 3 letters
- [x] Replace names with Jane Doe or John Doe 
- [x] Change the font color to the text on the letter to "black"
- [x] Updates these changes in the mobile and desktop wireframes in the master section on Figma 
- [x] Hand over to Dev 

**Letter Generator Sneak Peak image:**
- [x] Reach out to Dev and see what is needed to improve picture quality 

**Letter Generator Making letter writing less intimidating/How it works sections** 
- [x] "Targeted question prompts" and "question prompts" was confusing language. Replace with plain language, keep consistent throughout.

### Resources/Instructions
You can find these images on the LP wireframes under the Master section in Figma
- [Desktop](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=8543-106427&mode=design&t=cAEWwHwaUT6qmrOx-4)
- [Mobile](https://www.figma.com/file/hYqRxmBVtJbDv9DJXV6nra/Expunge-Assist-Main-Figma?type=design&node-id=10591-103990&mode=design&t=cAEWwHwaUT6qmrOx-4)

**Comment by sydneywalcoff** [comment]
Hi Design! 

I dug into the site and found the issues with both images.

For the letter _generator_ example, the issue is actually that it's a screen shot lol. If ya'll rebuild it, it would be much clearer.

For the letter examples, the rendered size (the size it's displayed on the screen) for desktop sizes is larger than the intrinsic size of the image. Basically, we are stretching the image so it gets a little blurry.
<img width="424" alt="Screen Shot 2023-10-02 at 7 07 16 PM" src="https://github.com/hackforla/expunge-assist/assets/75542938/15448ec7-4c04-42d0-9353-53671599c68a">

**Comment by emmathrash** [comment]
Update: Content has updated letters to all be different from one another. Design used SVG for mobile version from original desktop image, updated font color to black and inserted new content into letters. Content updated "targeted question prompts" into simpler statement. Ready to be peer reviewed.

**Comment by anitadesigns** [comment]
@emmathrash @ermbrown safe to say that we can close this issue? looks like it was handed over to Dev
