### ISSUE TITLE
Develop a detailed User Flow of the letter generator 

### ISSUE THREAD

**Issue by anitadesigns** [hackforla/expunge-assist#984]
### Overview
The team is missing a detailed user flow of the LG. This would help us with user interactions and a consistent design 

### Action Items
- [x] Examine current website 
- [x] Build user flow 
- [x] Share with team

**Comment by mbui31** [comment]
@jccchurch @anitadesigns took a stab at the user flow and you can find it in the FigJam. Would love your feedback and we can discuss it live on Wed as well.

**Comment by mbui31** [comment]
@anitadesigns can you add the feature? thank you!

**Comment by anitadesigns** [comment]
This just needs team feedback before closing
