### ISSUE TITLE
FAQ card sort study

### ISSUE THREAD

**Issue by audrey-ma** [hackforla/expunge-assist#985]
### Overview
As part of issue #957. Conduct a card sort study to determine categories and category headers for questions on the Frequently Asked Questions (FAQ) page. 

### Action Items
- [x] Create an open card sort study for FAQ questions from the latest update using Optimal Workshop.
- [x] Post it in Hack for LA general and Expunge Assist general slack channels.
- [x] Participants will sort questions into categories that make the most sense to them and label the categories.
- [x] Close study and analyze results.
- [x] Collaborate to finalize headers for the FAQ page questions.

### Resources/Instructions
[Link to launched card sort study](https://8wujnojk.optimalworkshop.com/optimalsort/eafaq)
Log in to Optimal Workshop using Expunge Assist email and credentials. Reach out to PM or assignees for credentials.

**Comment by amejiamesinas** [comment]
Posted link to card sort in the #general slack channel and EA channel.

**Comment by amejiamesinas** [comment]
Task complete. Further testing will be incorporated into IUT 3.
