### ISSUE TITLE
Popup, remove "take a break"

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#989]
### Overview
"Take a break" on one of the popups now conflicts with the other messaging in the LP. Remove this sentence. 

### Action Items

- [x] Check off these boxes as they are done and document progress and updates in the comments below 
- [x] Establish collaboration between Content and Design 
- [x] Find the popup in figma that has the "take a break" text and remove it
- [x] Should be a simple issue, work with Design on padding etc. to prep for handover 
- [x] Present at Content and Design meetings and syncs for team feedback
- [x] Iterate further if necessary (unlikely for this issue)
- [x] Tag Sam and Anita and move to ready for review column when completed 
- [x] Handover to Dev
- [x] Update mobile and desktop wireframes on Figma master pages

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by anitadesigns** [comment]
Getting back to the groove of EA things and came across this Issue. Is this issue ready for Design to review?

**Comment by emmathrash** [comment]
@anitadesigns hey, yes! It was a simple case of removing text but design can review any spacing changes that were made.

**Comment by anitadesigns** [comment]
Thanks Emma! Once we finish that, we will give you the green light to hand it over to Dev!

**Comment by anitadesigns** [comment]
@emmathrash Wireframe is ready to be handed off to Dev! 

Design is working on adjusting all pop-ups/modal styles, but shouldn't impact the pop up attached to this issue. I spoke to Sydney and she shared that we can make two different issues for Dev: 

1. Updating copy to this pop-up (high priority)
2. Updating visual design to all pop-ups (low priority)
