### ISSUE TITLE
Before page small fixes

### ISSUE THREAD

**Issue by SamHyler** [hackforla/expunge-assist#990]
### Overview
The Before page needs small updates, based on Bonnie's review in July 2023

**Advice 1:**
We don't need to tell folks that they must read the TT and PP before proceeding. It can be removed from the Before page

**Advice 2:**
If they reload the page (for example their computer freezes), they will lose all their work. Give them this warning/information gently. 

### Action Items
Check off these boxes as they are done and document progress and updates in the comments below 

#### Week 1: Plan
- [x] Establish collaboration with Design and Content
- [x] Review the current EA website
- [x] Plan out approach and needs 
   - [x] Any research needed? If so reach out to UXR
- [ ] Content: Remove TT and PP advice

#### Week 2: Discover
- [x] Explore and research workshops 
- [x] Share with team for feedback 
- [x] Schedule workshop 

#### Week 3: Research
- [x] Conduct HMW workshop 
- [x] Gather Insights from the workshop 

#### Week 4: Design
- [x] Develop lo-fi wireframes/hi fi wireframes based on insights 
- [x] Add Copy
- [x] Present in Content and Design syncs for team feedback
- [x] For any further questions, tag leads in Figma and reach out via Slack 

#### Week 5: Iterate
- [x] Iterate wireframes and prepare for review
- [x] Tag Sam and Anita and move to "ready for review" column when done for review

#### Week 6: Develop
- [ ] Prepare Handover to Dev
- [ ] Present to Dev
- [ ] Update mobile and desktop wireframes on master pages in Figma
- [ ] Close Issue

**Comment by emmathrash** [comment]
I've started a new page on Figma for this page, and have removed the TT and PP. Waiting on design collab for confirmation and to start iteration on advice 2

**Comment by emmathrash** [comment]
Issue Update: Content received feedback from team and decided on final iteration for text, including an extra heading asking the  user to check that they have enough time for the task, design is now using this to update the page using a visual cue as well.

**Comment by anitadesigns** [comment]
Hey @ermbrown can this issue be closed as complete?
