### ISSUE TITLE
Content Terminology Research

### ISSUE THREAD

**Issue by sofialaguna** [hackforla/expunge-assist#999]
### Overview
We are conducting research to evaluate the terminology used on the Expunge Assist website related to 3 key terms. 

Content request for this issue is for research into three specific terms and their nuances, including contextual information. The information will be used by content together with plain language, trauma informed, and conscious language principles to iterate the best terminology for our user, and it should be legally correct. Those terms are in the research plan linked in the action items, and more briefly here:

1. What do we call the process (expungement, record clearance, something else) 
2. What do we call the user (justice-impacted individual, people/folks with criminal records, something else)
3. What do we call the thing they write (declaration, personal statement, letter, etc.)

### Action Items

- [x] Initial meeting for terminology research is on Thursday, 8/24/23 at 12PM PST
- [x] Audit EA site for 3 key terminology [Figjam Board](https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?type=whiteboard&node-id=2414-6109&t=sXYnWUTmjGjiSAww-4)
- [x] Audit competitor sites from competitor analysis and other related sites for terminology they use
- [x] Create research plan - Each team member is assigned to develop a section in the [research plan](https://docs.google.com/document/d/1wUEHdlHmgzRiB-bLBmLKqXjSwAEYYisDIlc1jSdvjA8/edit#heading=h.vwpf15jx8xv). Please complete by 10/13. 
- [x] Originally marked low priority, given the need to understand expungement in CA, desk research = foundational research. Sylvia: use this [document](https://docs.google.com/document/d/1D19tbPqQkFzHYF2GemsZDDdMjbUM6jh6E6ArYWS-WIo/edit) to replace Sam's memo
- [x] Pull this issue out of the icebox and handover to Content together with results https://github.com/hackforla/expunge-assist/issues/478  Edit: This was originally written as a "Note to Sam" (by Sam) and was about connecting these 3 key terms to the glossary work later when the glossary issues were ready to be worked on. These three terms will be part of a larger glossary. Deliverable is the 3 key terms for this issue and not the glossary.

### Resources/Instructions

Deliverable is the 3 key terms and relevant research to assist in understanding, reasoning, and using them.

- [Previous issue focused on research of terminology](https://github.com/hackforla/expunge-assist/issues/894) using surveys with legal professionals and justice-involved individuals
- [Figma Chart for Audit](https://www.figma.com/file/SRsM0BvWhtmFwpg23bKTLB/EA-Collaboration-(Design%2FContent)?type=whiteboard&node-id=2414-6109&t=2VHxyE98dg4QJjI7-4)
- [Terminology Research Plan Sept 2023](https://docs.google.com/document/d/1wUEHdlHmgzRiB-bLBmLKqXjSwAEYYisDIlc1jSdvjA8/edit#heading=h.vwpf15jx8xv)
- [Desk Research Plan](https://docs.google.com/document/d/19ns4CWAz3ZwMLjtwGtWwxM5CTjccHfhzl4I3A5duqQo/edit)
- [Create LinkedIn Post for Terminology Surveys](https://github.com/hackforla/expunge-assist/issues/860)

**Comment by SamHyler** [comment]
content should look at this issue after this one is done https://github.com/hackforla/expunge-assist/issues/478

**Comment by SamHyler** [comment]
Notes from second meeting: 

Huge thanks everyone! Here’s the notes and plan from today:
Meet next week to check in. Tasks for that meeting:
1. Sam will start the research plan (RP) and have a plan for peer review
2. Everyone finish their sections on the FigJam board
3. Everyone consider if they have a contact to interview
4. Bring the user personas to the meeting and begin thinking about who we would want to talk to and why, and if our existing contacts fit the criteria
Today we discussed creating a short research plan. In the plan we can define the 3 questions we are seeking answers to (already in the Figjam more informally written).
Methods we will use now:
1. Audit (done - ish) our site and competitors/context analysis
2. Work with personas to build criteria for who we will interview
3. By gathering who we already know, interview key persons who are subject matter experts (20 min, anonymous interviews, possibly 1 person interviewing 1 person notetaking, varies by person) . Discussing if we need to interview more than these people
4. Sending out the existing interviews internally to HfLA
We will also need to discuss and write in the RP our analysis methods and deliverables.
Did I miss anything?

**Comment by sylvia-nam** [comment]
Here is the updated [glossary](https://docs.google.com/document/d/1D19tbPqQkFzHYF2GemsZDDdMjbUM6jh6E6ArYWS-WIo/edit)

**Comment by SamHyler** [comment]
Edited issue for accuracy and clarity

**Comment by sylvia-nam** [comment]
@SamHyler Since the issue was closed, can you create a new issue with the requested deliverable?

**Comment by amejiamesinas** [comment]
@sylvia-nam @SamHyler  I reopened issue, so no need for a new issue. We can continue to work from here.

**Comment by sylvia-nam** [comment]
@SamHyler Can you specify what you mean by the deliverable? I am doing a slide deck and presentation for Friday. The UXR glossary contains the terms you note with the exception of what to call the user.

**Comment by amejiamesinas** [comment]
@sylvia-nam yes, this is my understanding of the deliverable

**Comment by sylvia-nam** [comment]
Comments from @SamHyler on Google doc: 
Thanks Sylvia, I appreciate your work and knowledge in expungement, it will help EA a lot. I addressed both old glossary docs for Content and am reviewing and updating the glossary issue for the Stakeholder 2 milestone as I get a chance to look at it all. Will get back to you there soon for crossfunctional discussions.

For now, it could be helpful if we can separate the glossary work from other ongoing work. A glossary should read as Term - definition - explanation/similar terms/etc. In list form, something like the original doc, with a clear header/overview section, with any contextual or other research materials that help explain nuances and so forth in another relevant section, and including a reference section to document for future teams. The glossary has a very specific functional need for Dev and Content to create tool tips at a later stage. More about that when we get to discussions about the glossary issue.

The to-do, research and strategy, interview phase type sections in this document can be better placed in another document to assist with clarity in this document, as they don't pertain to a glossary, but rather research strategy and other tasks. But from reading this, and our discussions, I know there is ongoing research into expungement processes, and legal information, and also a need to disseminate that research to the teams. I think you are already working on that and have a separate issue for it. It could be helpful to separate that work from the glossary work for legibility. I'm seeing a lot of good information in this doc around expungement and laws, so my suggestion is that expungement foundational research and clarity/team education should be step 1, and is a separate github issue (likely the one you've already created), that will be the basis to inform the glossary and other potential initiatives. Much of this document seems to belong better to the 1214 issue you've created in UXR here: [https://github.com/hackforla/expunge-assist/issues/1214](https://www.google.com/url?q=https://github.com/hackforla/expunge-assist/issues/1214&sa=D&source=docs&ust=1713885749380814&usg=AOvVaw0jiUAq1qCZwKeiRW0nOxAk).

**Comment by sylvia-nam** [comment]
@amejiamesinas @SamHyler The next steps should be to clarify roles and the direction of the what and how of the ask. The UXR glossary was originally tied to this issue, and was 1 of 4 docs.

**Comment by SamHyler** [comment]
> Comments from @SamHyler on Google doc: Thanks Sylvia, I appreciate your work and knowledge in expungement, it will help EA a lot. I addressed both old glossary docs for Content and am reviewing and updating the glossary issue for the Stakeholder 2 milestone as I get a chance to look at it all. Will get back to you there soon for crossfunctional discussions.
> 
> For now, it could be helpful if we can separate the glossary work from other ongoing work. A glossary should read as Term - definition - explanation/similar terms/etc. In list form, something like the original doc, with a clear header/overview section, with any contextual or other research materials that help explain nuances and so forth in another relevant section, and including a reference section to document for future teams. The glossary has a very specific functional need for Dev and Content to create tool tips at a later stage. More about that when we get to discussions about the glossary issue.
> 
> The to-do, research and strategy, interview phase type sections in this document can be better placed in another document to assist with clarity in this document, as they don't pertain to a glossary, but rather research strategy and other tasks. But from reading this, and our discussions, I know there is ongoing research into expungement processes, and legal information, and also a need to disseminate that research to the teams. I think you are already working on that and have a separate issue for it. It could be helpful to separate that work from the glossary work for legibility. I'm seeing a lot of good information in this doc around expungement and laws, so my suggestion is that expungement foundational research and clarity/team education should be step 1, and is a separate github issue (likely the one you've already created), that will be the basis to inform the glossary and other potential initiatives. Much of this document seems to belong better to the 1214 issue you've created in UXR here: [https://github.com/hackforla/expunge-assist/issues/1214](https://www.google.com/url?q=https://github.com/hackforla/expunge-assist/issues/1214&sa=D&source=docs&ust=1713885749380814&usg=AOvVaw0jiUAq1qCZwKeiRW0nOxAk).

Yes, these (above) are my comments on the [UXR glossary](https://docs.google.com/document/d/1D19tbPqQkFzHYF2GemsZDDdMjbUM6jh6E6ArYWS-WIo/edit#heading=h.n5tb1h4qmf0f) which is one part of issues [478](https://github.com/hackforla/expunge-assist/issues/478) and [409](https://github.com/hackforla/expunge-assist/issues/409).

@sylvia-nam Yes, the glossary work is part of the next steps after this issue, and those next steps are in other issues (main, epic). There will be other work from here as well, Content will be implementing the results across the site by updating the terminology used and noting which terms will be used/why/etc. in our Content Guidelines to create and maintain consistency.

**Comment by sylvia-nam** [comment]
#@sylvia-nam The deliverable would be a response to the questions, goals, and background in the research plan that the UXR team created together in the Fall linked above. All 3 terms were chosen in response to results from IUT 1 and 2 and goals for stakeholder 1. So deliverable here relates to the 3 key terms.

The glossary is a deliverable for the glossary collab issue(s), currently under review to create clarity, we will discuss soon. These 3 terms will be part of future glossary.

Deliverable formats are for UXR to decide, but happy to work across the teams with you over time if you want to learn together about what processes for delivering research results has the most impact in UX and for the product. I think it would be fun and interesting in Design and Content as well to learn about and develop handover practices together.@SamHyler here's the draft of the slide deck that answers

Here's the [draft](https://docs.google.com/presentation/d/1sJgFQiAtwdWQxRvjT3Kx-rBy2cbx7m-J_FKp2oHN39A/edit#slide=id.g2ce3e6fb87e_0_20) of the slide deck I am presenting to Open Sync on Friday

**Comment by sylvia-nam** [comment]
Refer to #1353 for next steps

**Comment by sylvia-nam** [comment]
Two deliverables: 1) UXR glossary, 2) slide deck.
